### ISSUE TITLE
Android: Minor cosmetic issue: Paging indicator is not aligned correctly

### ISSUE THREAD

**Issue by shnaz** [alexrainman/CarouselView#10]
Hey @alexrainman, again thanks for a stable plugin.

I just noticed that the PagingIndicator is not correclty centered. It seems a bit off to the left..

Device & OS:
4.4.2, Nexus 5 in Xamarin Android Player.
I am using Xamarin Android Player to test on

![image](https://cloud.githubusercontent.com/assets/6933856/17077876/c2afa618-50e1-11e6-9519-f0cfb5b7a547.png)

**Comment by alexrainman** [comment]
Lets fix that too!

**Comment by alexrainman** [comment]
I found a solution for controls HeightRequest issue, expect version 2 in couple of days :)

**Comment by alexrainman** [comment]
Maybe there's something wrong in your emulator. It looks in the center for me.

**Comment by alexrainman** [comment]
Fixed!

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
