### ISSUE TITLE
iOS: Default constructor not found for type System.Array

### ISSUE THREAD

**Issue by Hasanajouz** [alexrainman/CarouselView#100]
when i am using:
<x:Array Type="{x:Type DataTemplate}">
in iOS it is throwing this exception
"System.MissingMethodException: Default constructor not found for type System.Array"

While in android it is working perfect?
any idea,
Thanks.

**Comment by alexrainman** [comment]
Do it from code behind. I couldn't figure it out from XAML

```
myCarousel.ItemsSource = new List<DataTemplate>()
{
	new DataTemplate(() => { return new PhotoUrl(); }),
	new DataTemplate(() => { return new Bio(); }),
	new DataTemplate(() => { return new ContactInfo(); })
};

myCarousel.BindingContext = new Person()
{
	PhotoUrl = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAefAAAAJDJkNGNiOTU4LWI4ZTQtNDY5My1hZWJhLTE3ZGQ5Y2I1MzRmMQ.jpg",
	Bio = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.",
	ContactInfo = "alexrainman1975@gmail.com"
};
```

**Comment by Hasanajouz** [comment]
i am testing it without item source for now.
this is example and it will not work in iOS:
<controls:CarouselViewControl.ItemsSource>
           <x:Array Type="{x:Type DataTemplate}">
                    <DataTemplate>
					    <StackLayout BackgroundColor="White" Padding="12">
                            <Image Source="{Binding PhotoUrl}" Aspect="AspectFill"/>
						</StackLayout>
                    </DataTemplate>
                    <DataTemplate>
					    <StackLayout BackgroundColor="White" Padding="12">
                            <Label Text="{Binding Bio}"/>
						</StackLayout>
                    </DataTemplate>
                    <DataTemplate>
                        <StackLayout BackgroundColor="White" Padding="12">
                            <Label Text="{Binding ContactInfo}"/>
						</StackLayout>
                    </DataTemplate>
           </x:Array>

**Comment by alexrainman** [comment]
What i said is that i don know how to make it work from XAML as ItemsSource is IEnumerable now :)

**Comment by Hasanajouz** [comment]
Thanks I saw new demo and new documentation

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by dalesmckay** [comment]
I managed to define the list in XAML by doing the following:

**Define a custom list in my own namespace:**
```csharp
namespace MyNamespace
{
	using System;
	using System.Collections.Generic;
	using Xamarin.Forms;

	public class CarouselPageTemplateList : List<DataTemplate>
	{
		public CarouselPageTemplateList() : base() {}
		public CarouselPageTemplateList(IEnumerable<DataTemplate> collection) : base(collection) {}
		public CarouselPageTemplateList(int capacity) : base(capacity) {}
	}
}
```

**Add a reference to my namespace in the XAML file:**
```xml
xmlns:local="clr-namespace:MyNamespace;assembly=MyAssembly"
xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
```

**Define the list as a resource in the XAML file:**
```xml
<ContentPage.Resources>
	<ResourceDictionary>
		<local:CarouselPageTemplateList x:Key="CarouselPages">
			<DataTemplate>
				<StackLayout BackgroundColor="Red" Padding="12">
					<Label Text="Page 1" />
				</StackLayout>
			</DataTemplate>

			<DataTemplate>
				<StackLayout BackgroundColor="White" Padding="12">
					<Label Text="Page 2" />
				</StackLayout>
			</DataTemplate>

			<DataTemplate>
				<StackLayout BackgroundColor="Blue" Padding="12">
					<Label Text="Page 3" />
				</StackLayout>
			</DataTemplate>
		</local:CarouselPageTemplateList>
	</ResourceDictionary>
</ContentPage.Resources>
```

**Consume the list in the XAML file:**
```xml
<cv:CarouselViewControl ItemsSource="{Binding Source={x:StaticResource CarouselPages}}" />
```


Hope this helps.
(BTW: Fantastic component!)

**Comment by dpalat** [comment]
@dalesmckay Good answers! awesome!, please @alexrainman can you mention this approach in the README.md file or in the DEMO projects.
