### ISSUE TITLE
Images rotation on Android.

### ISSUE THREAD

**Issue by ziomagic** [alexrainman/CarouselView#101]
Hello.
I have some issues with orientation change on Android. When I am using CarouselView like this:

```
<controls:CarouselViewControl
    x:Name="CarouselView"
		Orientation="Horizontal"
		Position="{Binding Position}"
		InterPageSpacing="10"
		ItemsSource="{Binding Path=LoadedImages}"
		VerticalOptions="FillAndExpand"
		HorizontalOptions="FillAndExpand">
		<controls:CarouselViewControl.ItemTemplate>
			<DataTemplate>
				<StackLayout
					IsClippedToBounds="true"
          BackgroundColor="Red"
					HorizontalOptions="FillAndExpand"
					VerticalOptions="FillAndExpand">
					<StackLayout.GestureRecognizers>
						<PinchGestureRecognizer
							PinchUpdated="OnPinchUpdated" />
					</StackLayout.GestureRecognizers>
          <Image
            HorizontalOptions="CenterAndExpand"
            VerticalOptions="CenterAndExpand"
            Aspect="AspectFit"
            Source="{Binding .}">
          </Image>       
        </StackLayout>
			</DataTemplate>
		</controls:CarouselViewControl.ItemTemplate>
	</controls:CarouselViewControl>
```

Image size will stay the same after rotation, even if parent is still filling carousel view correctly.
Here is an example of loaded image, and the same image after rotation.
![good](https://cloud.githubusercontent.com/assets/3288789/25134922/28971d88-2451-11e7-93b8-d654194a621d.png)
![bad](https://cloud.githubusercontent.com/assets/3288789/25134923/2897524e-2451-11e7-9461-eb5c9c998a7d.png)

This problem occurs only on Android. IOS is working good. Also, Image will be fixed when CarouselView will slide at next 2 positions ahead, and then back to my image.

**Comment by alexrainman** [comment]
I think your problem is in the image itself, try this:

```
<Image
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand"
            Aspect="AspectFill"
            Source="{Binding .}">
```

**Comment by ziomagic** [comment]
Thank you for a fast response. I just tried every LayoutOption, and my image size is still the same :/

**Comment by alexrainman** [comment]
Can you share a demo?

**Comment by ziomagic** [comment]
Unfortunately I can't (This is not my app, I am just working on it). But today i checked, and when I am removing Image parent (StackLayout in this case) image will resize just good.. This is still a problem for me, becouse I need StackLayout as a parent.

**Comment by alexrainman** [comment]
I think thats the case.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by wauterm** [comment]
I had the exact same problem as ziomagic, I worked around it by resetting the carousel height after a rotation.

`public View()
        {
            InitializeComponent();
            photoCarousel.SizeChanged += PhotoCarousel_SizeChanged;     
        }

        private void PhotoCarousel_SizeChanged(object sender, System.EventArgs e)
        {
            var normalHeight = photoCarousel.Height;
            photoCarousel.HeightRequest = 60;
            photoCarousel.HeightRequest = normalHeight;
        }`
