### ISSUE TITLE
Same Images in Carousel not possible?

### ISSUE THREAD

**Issue by McFlemchSoda** [alexrainman/CarouselView#104]
Hi, 
I was using your carousel package and when I add multiple identical images to it, it looks like it binds the position to the image? I get an infinite loop if I add 2 of the same images and the position indicator does not change. It works fine if all images are different. 

Hope that makes any sense and you can fix it.

**Comment by alexrainman** [comment]
The carousel doesn't care about the content of its children. Position is not bind in any way to the children content. Saying that, no matter if you use same image or different ones, it doesn't makes a difference for the control.

Its known that in Xamarin Android images are not handled in the right way, so i advice you to use FFImageLoading.

Please, review your code, you must be doing something wrong.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
