### ISSUE TITLE
Not working with Latest Xamarin.Forms pre release 2.3.5.233-pre1

### ISSUE THREAD

**Issue by abdu292** [alexrainman/CarouselView#107]
It appears that this control is not working with the latest Xamarin.Forms pre release. App just goes to break mode with a generic exception "unhandled exception".

I want to use this Xamarin.Forms release to leverage the fast renderers and others, but along with this CarouselView control.

Any workaround?

**Comment by alexrainman** [comment]
No idea. I have to run some tests. Anyway the control will be part of 2.3.5 pre release soon.

**Comment by abdu292** [comment]
Okay. Let me know when you get a chance to do the tests. I reverted the Xamarin.Forms version to the latest stable.

And, wow great to know this control is going to be part of Xamarin.Forms. This really works!!!
Just curious, 
1) I know Xamarin team was creating another control (was pre for long time), will that be go away or are you merging the code with that?
2) Do you know (high-level) if the new pre-release with this control will be available in a couple of weeks?

**Comment by alexrainman** [comment]
This control will replace the one they were building. The PR is ready so it should be merged and available as pre-release soon.

**Comment by alexrainman** [comment]
And no, no merging with their control. They are pulling mine.

**Comment by abdu292** [comment]
Wow! can't wait seeing it. Thanks for your great contributions!

**Comment by hardcodet** [comment]
I've been struggling so badly with Xamarin's control - can't wait for the replacement. Thanks for the work you put in, Alex! Quick question: Is the version here API compatible with Xamarin's current control (same property names / types), or would I have to adjust it?

**Comment by alexrainman** [comment]
@abdu292 i updated the project and the demo to latest pre-release and everything works as expected.

**Comment by abdu292** [comment]
Thanks a bunch for the info. I'm on vacation for a week. I'll try this as soon I have access to my computer.
Also curious to see this to be part of Xamarin Forms sooner.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by abdu292** [comment]
@alexrainman hey, definitely I can do that. Is this info still valid? Should I be able to go ahead and nominate?

Apologies, I was on a long vacation and was busy all these days.

Also, do you know if this control is already part of Xamarin.Forms yet or any scheduled date?
(Sorry I did not read any of the recent release notes)
