### ISSUE TITLE
App crash after sometimes. memory leak?

### ISSUE THREAD

**Issue by csyong87** [alexrainman/CarouselView#109]
The carousel view is working fine for start. but the app will crashed after 5-10 mins. I am using timer for auto increase the position for archive screen saver feel as below:

I am suspecting memory leak.... any idea?

[test.txt](https://github.com/alexrainman/CarouselView/files/954531/test.txt)

**Comment by alexrainman** [comment]
If you are using the control with images, you have to use FFImageLoading plugin.

**Comment by alexrainman** [comment]
Use this repo as example: https://github.com/alexrainman/TabbedCarouselView

**Comment by csyong87** [comment]
alex, thanks for your prompt reply! could you able provide me sample with StreamImageSource? which get from byte array.

**Comment by alexrainman** [comment]
First, you have to use FFImageLoading instead of XF Image. Then you set source from stream same as you do with XF Image.

**Comment by csyong87** [comment]
thanks bro... everything work fine now!!

**Comment by alexrainman** [comment]
Great!

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by csyong87** [comment]
please get me your email address for the nomination

**Comment by alexrainman** [comment]
alexrainman1975@gmail.com

**Comment by csyong87** [comment]
done

**Comment by alexrainman** [comment]
Thanks

**Comment by csyong87** [comment]
sorry to disturb you alexrainman, its still crashed for ipad mini 1 in iOS 9.3.5. any idea??

**Comment by alexrainman** [comment]
StackTrace? Demo project?

**Comment by csyong87** [comment]
its only happen on device. not able to capture the stack trace so far

**Comment by alexrainman** [comment]
Debug mode? Release mode? How do you know its the carousel?

**Comment by csyong87** [comment]
its crash from carousel page. I have create a screen saver page

**Comment by alexrainman** [comment]
I don't have a way to know what's going on my friend unless you can provide a demo project or StackTrace :(

**Comment by csyong87** [comment]
Another issue i had is The app will crashed if i swipe the carousel view quickly. Error as below:
FYI, I am using timer for auto increase the position for screen saver feel.

NSInternalInconsistencyException
No view controller managing visible view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x7f889e444760; frame = (0 0; 1024 768); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x60800582b840>>
