### ISSUE TITLE
Spacing between items

### ISSUE THREAD

**Issue by shnaz** [alexrainman/CarouselView#11]
Hey @alexrainman. I have a enhancement request. 
I want a gap/spacing between my items in carouselview, just like in iOS gallery app or facebook gallery etc. 
I can probably solve it by adding left/right padding in my itemtemplate, but then my image wouldnt fill the whole screen. 

What do you think?

Thanks again for remarkable plugin. 

Because right now my items seems like they are attached/appended to each other. The following screenshots is of the iOS Photos app:

![image](https://cloud.githubusercontent.com/assets/6933856/17085350/fd96fd0e-51d5-11e6-8138-db3d09a85e52.png)
![image](https://cloud.githubusercontent.com/assets/6933856/17085351/fda25cda-51d5-11e6-8c99-734a5ee116bd.png)

**Comment by alexrainman** [comment]
This will be quite complicated. You may solve it adding Left/Right spaces using Margin property.

**Comment by alexrainman** [comment]
As each page may be exactly the size of the parent native pager control :)

**Comment by shnaz** [comment]
As it seems, UIPageViewController and PageViewer has built-in functionality, haven't checked UWP's FlipView yet. 

iOS UIPageViewController:
<img width="719" alt="screen shot 2016-07-24 at 23 17 25" src="https://cloud.githubusercontent.com/assets/6933856/17086541/4584e62a-51f5-11e6-9445-1d81fa7952ec.png">


Android ViewPager:
<img width="506" alt="screen shot 2016-07-24 at 23 18 12" src="https://cloud.githubusercontent.com/assets/6933856/17086540/42f4862c-51f5-11e6-962e-dd1bc4b8d292.png">

**Comment by alexrainman** [comment]
Interesting. Let me try that.

**Comment by shnaz** [comment]
Sounds great. And plz do tell if I can be of assistance of some kind.

**Comment by alexrainman** [comment]
Try yo find out how to do the same in UWP FlipView.

**Comment by shnaz** [comment]
FlipView doesnt have native support for spacing between items.

**Comment by alexrainman** [comment]
Bad news :(

**Comment by shnaz** [comment]
@alexrainman not nessicarly. Just like you have platform specific features like Bounce and Arrows feature, this should also fall under that category.

**Comment by alexrainman** [comment]
Thats what i was thinking :)

**Comment by alexrainman** [comment]
Umm i will test margin property in FlipView. As i am reading, it may work.

**Comment by alexrainman** [comment]
https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.frameworkelement.margin

or

https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.control.padding

**Comment by alexrainman** [comment]
Later today my friend :)

**Comment by alexrainman** [comment]
Added to Android an iOS but not supported in UWP.

**Comment by shnaz** [comment]
Superb! when will it be released? :)

**Comment by alexrainman** [comment]
Released in version 2.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
