### ISSUE TITLE
[UWP] FlipView inherits background color from default XAML style

### ISSUE THREAD

**Issue by mattrichnz** [alexrainman/CarouselView#110]
On UWP, FlipView native control has background colour inherited from the default XAML style.

This means the FlipView has default background color of "#19000000" even if the CarouselView BackgroundColor is Transparent.

[FlipView Default Style](https://msdn.microsoft.com/library/9db798b1-06b7-40e3-add2-c89676b2bfdb)

```
<!-- Default style for Windows.UI.Xaml.Controls.FlipView -->
<Style TargetType="FlipView">
<Setter Property="Background" Value="{ThemeResource SystemControlPageBackgroundListLowBrush}" />
```

**Comment by alexrainman** [comment]
There's a property named InterPageSpacingColor that does exactly that: play with control background color. I am going to deprecate that property and use BackgroundColor instead to set control background, including FlipView.

**Comment by mattrichnz** [comment]
Ah great. Have TODO'd it in our code for as have fixed it by overriding the default style in App.xaml. Will keep an eye out for this fix in the future and will remove our workaround.

Thanks for the quick reply! Look forward to seeing this in XF core.

**Comment by alexrainman** [comment]
Can you share that code with me? I am trying to implement that in the control.

**Comment by mattrichnz** [comment]
All I did was place the following in App.xaml on the UWP project.
You could probably use an AP if you needed more control.

```
<!-- Default style for FlipView.  -->
<!-- Note: This style is used by the CarouselView.FormsPlugin. -->
<!-- TODO: Remove when https://github.com/alexrainman/CarouselView/issues/110 is fixed. -->
<Style TargetType="FlipView">
    <Setter Property="Background" Value="Transparent" />
</Style>
```

**Comment by alexrainman** [comment]
How you do that programmatically? Let's say:

```
flipView.Style.Background = ...
```

**Comment by alexrainman** [comment]
I figure it out :)

```
flipView.Background = (SolidColorBrush)converter.Convert(Element.BackgroundColor, null, null, null);
```

**Comment by mattrichnz** [comment]
Great! Sorry for the late reply!

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by abdu292** [comment]
Just was wondering if this is addressed. I can still see the control background is different unless I override the style in the UWP App.xaml file as mentioned above. I am using latest version 4.1.2. 
Am I missing something?

**Comment by alexrainman** [comment]
4.1.2 is not the latest version.

**Comment by abdu292** [comment]
Apologies. I was on the "Installed" Nuget tab. The latest version 4.4.2 works well. Thanks!

**Comment by abdu292** [comment]
@alexrainman Oh, I lost the transparency on Android. "Interpage...BackgroundColor" also doesn't seem to be available in this new version. Could you be of help?

**Comment by abdu292** [comment]
Sorry again,Working well now.  It was all about temp files. Deleting bin/obj did the trick. Thanks!
