### ISSUE TITLE
Animation speed between positions

### ISSUE THREAD

**Issue by djcparker** [alexrainman/CarouselView#111]
Is there a way to set the animation speed between positions?

My example is this: I have three views (positions 0,1,2).
Swiping is really nice between them all
On position 2, if they tap a value, it programatically sets the position to 0 and it changes to that view.

except it is too fast, the users have said it feels like it jumps rather than scrolls smoothly.

I hope that makes sense!

thanks 
Dave

**Comment by alexrainman** [comment]
I will think about this.

**Comment by alexrainman** [comment]
I have to find the way to do this for all the platforms supported.I don't know if i am going to be able to do it before the plugin PR is accepted into Xamarin.Forms.Core

**Comment by djcparker** [comment]
No worries, it is not a showstopper... Thanks for the hard work!
