### ISSUE TITLE
Does IsSwipingEnabled only work on Android?

### ISSUE THREAD

**Issue by lidi** [alexrainman/CarouselView#112]
_Before I begin a huge thank you for such an amazing library!!!_

## Platform

 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
iOS 9.3.5 on device
iOS 10.3 simulator

## Version of Library
4.2.0

## Version of Xamarin forms
2.3.4.231

## Expected Behaviour
Setting IsSwipingEnabled to false should disable swiping on iOS

## Actual Behaviour
Setting IsSwipingEnabled to false does not disable swiping on iOS (note: it does work on Android though).

To reproduce:
Run [the demo app](https://github.com/alexrainman/CarouselView/tree/master/Demo) on iOS and set [IsSwipingEnabled](https://github.com/alexrainman/CarouselView/blob/master/Demo/Pages/MainPage.xaml#L25) to false

**Comment by alexrainman** [comment]
Confirmed. Next update.

**Comment by xitasoappdev** [comment]
I debugged it and found out that the value is correctly set initially, but setting the `GetPreviousViewController` delegate method (CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs, Line 247) seems to reset this property on the underlying UIScrollView.

**Comment by alexrainman** [comment]
I already fixed this. Releasing the fix soon.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
