### ISSUE TITLE
ItemsSource_CollectionChanged() listener never gets removed from INotifyCollectionChanged

### ISSUE THREAD

**Issue by JoshaMunnik** [alexrainman/CarouselView#113]
I've created some code that during debug builds will wrap the page content with an AbsoluteLayer (if it is not already using an AbsoluteLayer) and adds some debug buttons on top.

Apparently this recreates view renderers. Everything worked fine until I started adding items to the ObservableCollection linked to ItemSource property. This would cause an exception.

It turns out the ItemsSource_CollectionChanged listener method of the previous CarouselViewRenderer instance still gets called. The method references the Element property which no longer has a value (it is null), causing the exception.

**Comment by alexrainman** [comment]
I think this a Xamarin.Forms issue where renderer is called even when Element is null. I will checking if Element is null everywhere now.

**Comment by JoshaMunnik** [comment]
I'm not sure how event handlers work exactly in c#, but the problem might be that a listener is added to the ItemSource's  CollectionChanged (line 52). This listener is still active, even though the rest of the ViewRenderer is not. The old instance probably also does not get garbage collected because the ItemsSource_CollectionChanged method is still referenced by the CollectionChanged event (since the instance contained by the ItemSource does not get recreated). So when an event gets invoked, the ItemSource_CollectionChanged method of the non active ViewRenderer will also be called.

A check sounds sufficient though, thanks again for the quick reply.

**Comment by JoshaMunnik** [comment]
Just noticed there is a Dispose method :) I could not test, but the bug probably can also be solved by removing the CollectionChanged listener at the Dispose method.

**Comment by alexrainman** [comment]
Thats exactly the fix i am adding :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
