### ISSUE TITLE
Layout issues on iOS within TabbedPage and NavigationPage

### ISSUE THREAD

**Issue by rkorsak** [alexrainman/CarouselView#114]
I have a CarouselViewControl containing a ScrollView and StackLayout, with the CarouselViewControl itself also inside of a StackLayout (this is with Forms v2.3.4.231).

Ex:
```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:CarouseList" xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions" x:Class="CarouseList.CarouseListPage">
  <StackLayout Spacing="0">
    <cv:CarouselViewControl x:Name="carousel" HorizontalOptions="Fill" VerticalOptions="FillAndExpand">
      <cv:CarouselViewControl.ItemTemplate>
        <DataTemplate>
          <ScrollView>
            <StackLayout>
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Aqua" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Green" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Maroon" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Silver" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Yellow" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Black" />
            </StackLayout>
          </ScrollView>
        </DataTemplate>
      </cv:CarouselViewControl.ItemTemplate>
    </cv:CarouselViewControl>
    <Label Text="More Stuff Here" HorizontalOptions="Center" />
  </StackLayout>
</ContentPage>
```

When this is used as the MainPage, everything works as expected:
![normal-scrolling](https://cloud.githubusercontent.com/assets/771197/25593999/f9eae334-2e8c-11e7-865f-5fd3f5a14660.gif)

But when I wrap it in both a TabbedPage and NavigationPage (which my real app uses), the layout breaks:
![with-navtabs](https://cloud.githubusercontent.com/assets/771197/25594043/1b7d2ce6-2e8d-11e7-90e6-a878665ba039.gif)

Notice that the "More Stuff Here" label doesn't show at all, and the positions of elements in the StackLayout are broken.  Hopefully there is a workaround or simple fix, as I'm loving the control otherwise.

**Comment by alexrainman** [comment]
Why you have ScrollView inside the Carousel control? The carousel has its own scrollview.

**Comment by rkorsak** [comment]
Ah, I wasn't aware of that.  I was using another CarouselView before and am adapting the code to yours.  Taking out the ScrollView doesn't seem to entirely fix my issue, however.  The label at the bottom is still missing and the view does not scroll.

New layout:
```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:CarouseList" xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions" x:Class="CarouseList.CarouseListPage">
  <StackLayout Spacing="0">
    <cv:CarouselViewControl x:Name="carousel" HorizontalOptions="Fill" VerticalOptions="FillAndExpand">
      <cv:CarouselViewControl.ItemTemplate>
        <DataTemplate>
          <StackLayout>
            <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Aqua" />
            <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Green" />
            <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Maroon" />
            <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Silver" />
            <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Yellow" />
            <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Black" />
          </StackLayout>
        </DataTemplate>
      </cv:CarouselViewControl.ItemTemplate>
    </cv:CarouselViewControl>
    <Label Text="More Stuff Here" HorizontalOptions="Center" />
  </StackLayout>
</ContentPage>
```

New behavior:
![without-scroll](https://cloud.githubusercontent.com/assets/771197/25594452/a27ed658-2e8e-11e7-8c20-77eba8b6dc5e.gif)

**Comment by rkorsak** [comment]
For what it's worth, I don't have this issue if I use only a NavigationPage or a TabbedPage.  It's only the two together that seem to cause problems.

**Comment by alexrainman** [comment]
I don't think its related to the carousel.

**Comment by alexrainman** [comment]
Anyway i advice you to not add scrollview inside the Carousel.

**Comment by alexrainman** [comment]
And, i believe you have to embed one of the children of the tabbed page inside a NavigationPage to make it works.

**Comment by alexrainman** [comment]
Something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:TabbedPageWithNavigationPage;assembly=TabbedPageWithNavigationPage" x:Class="TabbedPageWithNavigationPage.MainPage">
	<local:TodayPage />
	<NavigationPage Title="Schedule" Icon="schedule.png">
		<x:Arguments>
			<local:SchedulePage />
		</x:Arguments>
	</NavigationPage>
	<local:SettingsPage />
</TabbedPage>
```

Then you can globally access to that navigation instance.

**Comment by rkorsak** [comment]
Yes, that's what I'm doing for this example:
```
            var tabbedPage = new TabbedPage();
            tabbedPage.Children.Add(new NavigationPage(new CarouseListPage { Title = "Carousel" }) { Title = "Carousel" });
            MainPage = tabbedPage;
```

The real app uses this approach extensively with no issues.  Until today I was using the (soon to be replaced) [Xamarin.Forms CarouselView](https://github.com/xamarin/Xamarin.Forms.CarouselView) control.  Because of some other minor issues, I decided to try swapping it with yours and encountered this problem.  The exact same layout and navigation setup does not have this problem when using that control.

**Comment by rkorsak** [comment]
For comparison, this is the same layout with the other CarouselView control (note that this does need a ScrollView to work):
```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:CarouseList" xmlns:cv="clr-namespace:Xamarin.Forms;assembly=Xamarin.Forms.CarouselView" x:Class="CarouseList.CarouseListPage">
  <StackLayout Spacing="0">
    <cv:CarouselView x:Name="carousel" HorizontalOptions="Fill" VerticalOptions="FillAndExpand">
      <cv:CarouselView.ItemTemplate>
        <DataTemplate>
          <ScrollView>
            <StackLayout>
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Aqua" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Green" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Maroon" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Silver" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Yellow" />
              <BoxView HorizontalOptions="Fill" HeightRequest="200" Margin="10" BackgroundColor="Black" />
            </StackLayout>
          </ScrollView>
        </DataTemplate>
      </cv:CarouselView.ItemTemplate>
    </cv:CarouselView>
    <Label Text="More Stuff Here" HorizontalOptions="Center" />
  </StackLayout>
</ContentPage>
```
And it renders correctly:
![other-carousel](https://cloud.githubusercontent.com/assets/771197/25595365/87318c98-2e92-11e7-8a53-c0ca72cd5bfd.gif)

**Comment by alexrainman** [comment]
My bad, you need a ScrollView in the ItemTemplate. But you don't need StackLayout wrapping the carousel.

**Comment by alexrainman** [comment]
I tried your configuration and it works. I picker one of the examples i have in my demo:

```
<?xml version="1.0" encoding="UTF-8"?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
		xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
		x:Class="Demo.MyTabbedPage"
		xmlns:controls="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions">

	<NavigationPage>
		<x:Arguments>
			<ContentPage Title="First">
				<controls:CarouselViewControl x:Name="myCarousel"
		                                      HorizontalOptions="FillAndExpand"
		                                      VerticalOptions="FillAndExpand"
		                                      AnimateTransition="true"
		                                      IndicatorsShape="Circle"
		                                      InterPageSpacing="10"
		                                      BackgroundColor="Red"
		                                      Orientation="Horizontal"
		                                      ShowIndicators="true"/>
			</ContentPage>
		</x:Arguments>
	</NavigationPage>

	<ContentPage Title="Second">
		<Label Text="Second tab" />
	</ContentPage>

	<ContentPage Title="Third">
		<Label Text="Third tab" />
	</ContentPage>

	<ContentPage Title="Four">
		<Label Text="Third tab" />
	</ContentPage>

	
</TabbedPage>
```

**Comment by alexrainman** [comment]
I faced this issue before when i was testing the Carousel on screen rotation. I had a StackLayout wrapping the Carousel. I noticed the StackLayout doesn't resize in the right way. It works if i use a Grid.

**Comment by rkorsak** [comment]
The Grid does seem to improve things!  I'm still seeing one bit of odd behavior.
New layout (the CarouselView is bound to two objects, and I'm using numbers to make the scrolling more obvious):
```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:CarouseList" xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions" x:Class="CarouseList.CarouseListPage">
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="*" />
      <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <cv:CarouselViewControl Grid.Row="0" x:Name="carousel" HorizontalOptions="Fill" VerticalOptions="Fill">
      <cv:CarouselViewControl.ItemTemplate>
        <DataTemplate>
          <ScrollView>
            <StackLayout Spacing="20" BackgroundColor="White">
              <Label Text="{Binding Title}" FontSize="40" HorizontalOptions="Center" />
              <Label Text="1" FontSize="40" HorizontalOptions="Center" />
              <Label Text="2" FontSize="40" HorizontalOptions="Center" />
              <Label Text="3" FontSize="40" HorizontalOptions="Center" />
              <Label Text="4" FontSize="40" HorizontalOptions="Center" />
              <Label Text="5" FontSize="40" HorizontalOptions="Center" />
              <Label Text="6" FontSize="40" HorizontalOptions="Center" />
              <Label Text="7" FontSize="40" HorizontalOptions="Center" />
              <Label Text="8" FontSize="40" HorizontalOptions="Center" />
              <Label Text="9" FontSize="40" HorizontalOptions="Center" />
              <Label Text="10" FontSize="40" HorizontalOptions="Center" />
            </StackLayout>
          </ScrollView>
        </DataTemplate>
      </cv:CarouselViewControl.ItemTemplate>
    </cv:CarouselViewControl>
    <Label Text="More stuff here" HorizontalOptions="Center" Grid.Row="1" />
  </Grid>
</ContentPage>
```

You can see what appears to be a duplicate of View 1 being rendered behind the scrollview on both views:
![with-grid](https://cloud.githubusercontent.com/assets/771197/25596191/059876d4-2e96-11e7-9aad-bbabdceb88eb.gif)

**Comment by rkorsak** [comment]
I should note that the above behavior does not happen unless I'm using the TabbedPage and NavigationPage combination.

**Comment by alexrainman** [comment]
Again, this is not related to the Carousel.

**Comment by rkorsak** [comment]
Are you saying this is a bug in Xamarin.Forms or my code?  I'm trying to present the simplest possible example for this scenario, and when I keep everything the same but use a different Carousel control, the problem goes away.  If it's not a bug in your CarouselView, it must at least be a  bug in Xamarin.Forms that affects your view and not others.

By the way, you have to be the most responsive dev I've ever encountered with regard to bug reports.  Thank you.

**Comment by alexrainman** [comment]
I care about what i share with the community :)

This control is on the way to be part of Xamarin.Forms core so it has to be as stable as possible.

**Comment by alexrainman** [comment]
Well, wrapping the whole thing in a StackLayout breaks the thing :(

**Comment by alexrainman** [comment]
And grid shows like duplicate in background. Really weird. I think this is Xamarin.Forms going nuts with this layout :)

**Comment by rkorsak** [comment]
At least the Grid solution will probably work for my app.

I figured out that the duplicated views only occur if you don't give the CarouselView a BackgroundColor.  I messed around with your Demo app and took out the BackgroundColor on the MainPage example, and noticed the same duplicated view effect when pulling to the far left or right.  It's an easy enough workaround for me, of course, but I figured I'd let you know.

**Comment by alexrainman** [comment]
But you see the duplicate effect on my demo? MainPage? With no changes just removing background color?

**Comment by rkorsak** [comment]
I also wrapped the MainPage in a NavigationPage inside a TabbedPage, as per the other examples.  Should have mentioned that ;).

**Comment by alexrainman** [comment]
Ah :)

**Comment by alexrainman** [comment]
I don't have a solution for you other that using a grid :)

**Comment by rkorsak** [comment]
I'll test out the Grid (which I probably should have just been using anyway - the view kind of evolved into its current state).  Thanks again!

**Comment by alexrainman** [comment]
GL :)

**Comment by rkorsak** [comment]
Hey, that did it!  Now my view doesn't look insane, and doesn't exhibit the bugs I was encountering with the other CarouselView.  Now I'll stop spamming you.  Cheers.

**Comment by alexrainman** [comment]
Just published an update :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
