### ISSUE TITLE
Rotation bug (iOS)

### ISSUE THREAD

**Issue by lassana** [alexrainman/CarouselView#115]
I came across very odd bug.

Steps to reproduce:
1. Clone the original repo (ddc6fb1).
2. Remove `BackgroundColor` property from `myCarousel` (MainPage.xaml) and the line `BackgroundColor = Color.White;` (MyFirstView.xaml.cs).
3. Run `Demo.iOS` (device in the portrait mode).
4. Rotate the device to landscape mode.

Result:
![screencast](https://cloud.githubusercontent.com/assets/2004960/25710801/05b293f4-30f6-11e7-8f08-5b9e9b21079a.gif)

It occurs on iOS 10.3 Simulator (I didn't test on a real device). Any ideas how to fix it?

**Comment by alexrainman** [comment]
Interesting. Lemme fix that.

**Comment by alexrainman** [comment]
Found the fix :) this is so weird. It seems that calling Xamarin.Forms SetNativecontrol() doesn't remove the previous one from the UI if exists :)

**Comment by lassana** [comment]
Wow, you're faster than light! 🙂 Thank you

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by lassana** [comment]
Done 🙃

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
