### ISSUE TITLE
Empty layout on iOS

### ISSUE THREAD

**Issue by BurningAXE** [alexrainman/CarouselView#117]
I have a test project that uses the CarouselView to display a number of columns each of which consists of a ListView with tasks. It works fine on Android and Windows but I get a blank screen on iOS (see screenshots). I'm attaching the XAML + ViewModel and Model files. Let me know if you need something else to help reproduce the issue.
![screen shot 2017-05-05 at 10 52 08](https://cloud.githubusercontent.com/assets/5779978/25742251/51c88cca-3197-11e7-8ff4-024d09681f8e.png)
![simulator screen shot 5may 2017 10 43 28](https://cloud.githubusercontent.com/assets/5779978/25742261/57dcdb48-3197-11e7-9394-10dcf9ff5c42.png)
[CarouselViewIssueCodeFiles.zip](https://github.com/alexrainman/CarouselView/files/978761/CarouselViewIssueCodeFiles.zip)

**Comment by alexrainman** [comment]
You are missing the MainPage code behind.

**Comment by alexrainman** [comment]
Its not blank for me on iOS :)

<img width="374" alt="screen shot 2017-05-05 at 7 16 47 am" src="https://cloud.githubusercontent.com/assets/3793554/25745073/da637020-3162-11e7-8f40-1bd6054daf32.png">

**Comment by BurningAXE** [comment]
Hm, that's weird! Anyway, sorry for the trouble!

**Comment by BurningAXE** [comment]
Hey, can you send me a zip of the working project with my files? I am out of ideas on debugging this!

**Comment by alexrainman** [comment]
I have to put it together again. I deleted it :)

**Comment by BurningAXE** [comment]
I would be grateful! I don't know what else to try.

**Comment by alexrainman** [comment]
I just updated the repo. Your code is included in a page named ColumnPage. Run it as App main page.

**Comment by BurningAXE** [comment]
Thanks!

**Comment by BurningAXE** [comment]
Just FYI - the problem was that I was missing the init call in the AppDelegate. I don't know why I didn't pay attention to this in the usage instructions! And obviously Android can work without it!
