### ISSUE TITLE
iOS layout while invisible is problematic

### ISSUE THREAD

**Issue by sehd** [alexrainman/CarouselView#118]
I have placed one of these inside a horizontal stack layout it's the middle item and two chevrons on two sides. This stack is invisible and the list is empty. As items gets added to the list carousel view populates with that item and stack layout becomes visible.

The issue is that carousel view which has horizontal option of fill and expand will get more space than available and pushes the right chevron out of the view.

If it's visible from start this does not happen.

**Comment by alexrainman** [comment]
If you use a Grid instead you will solve the problem.

```
<Grid RowSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="60" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="60" />
        </Grid.ColumnDefinitions>
</Grid>
```

This is not the control itself. You can blame horizontal StackLayout.

**Comment by sehd** [comment]
I used Grid. It now displays in the designated area on page but inside the CarouselView I have a frame which still renders in the larger area as before. So it means that the correct size of the CarouselView is not propagated correctly to it's children or since it's unknown when invisible CarouselView allows it's children to be rendered in whatever space they want.

**Comment by sehd** [comment]
For anyone else who might be interested, the problem solved by making the frame not the root element of the ItemTemplate in CarouselView. I placed the frame inside the grid and the layout is now fixed.

**Comment by alexrainman** [comment]
Can you share a xaml example?
