### ISSUE TITLE
F# Compilation breaks.

### ISSUE THREAD

**Issue by SpiegelSoft** [alexrainman/CarouselView#119]
I added the plugin to my F# project, and the compilation broke, because F# does not allow circular dependencies.

There is a demo project at https://github.com/SpiegelSoft/XamarinForms.Reactive.FSharp/tree/carouselview-demo

If I have time, I'll make the relevant pull request.

**Comment by alexrainman** [comment]
Circular dependencies?

**Comment by SpiegelSoft** [comment]
No, that's not right -- you use 'and' in the Resources file. I'll dig into this a bit more.

**Comment by alexrainman** [comment]
?
