### ISSUE TITLE
IllegalStateException on Android

### ISSUE THREAD

**Issue by SamuelDebruyn** [alexrainman/CarouselView#12]
`The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 5, found: 0 Pager id: mybundleidremoved:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class md5fa3be16b83ce3acd3be83265686c14de.CarouselViewRenderer_PageAdapter`

This happens when my page dissappears and the itemssource has no items left.

**Comment by alexrainman** [comment]
Can you elaborate a little more?

**Comment by SamuelDebruyn** [comment]
It seems like the Android renderer doesn't call `viewPager.Adapter.NotifyDataSetChanged();` when the amount of items in the `ItemsSource` changes.
What I'd recommend to fix (I'll do a PR in an hour or so):

1. Check if the `ItemsSource` implements `INotifyCollectionChanged `.
2. If it does, subscribe to the `CollectionChanged` event.
3. When the event is called, call `viewPager.Adapter.NotifyDataSetChanged();` in the renderer.

**Comment by alexrainman** [comment]
In the plugin, im always calling NotifyDataSetChanged when any changes happen. The problem seems to be that you are deleting all the items and ViewPager needs at least one, and when pop back, something weird happens. I will review it.

**Comment by alexrainman** [comment]
If you take a look at the code you will confirm that it does :)

**Comment by alexrainman** [comment]
It seems you are deleting the Items from ItemsSource directly. Instead, use what the Carousel API offers:

```
carousel.RemovePage(position);
```

This will remove the page and the item from the source. Anyway, i will implement your advice and make the ItemsSource and observable collection if it's not already.

Thanks

**Comment by alexrainman** [comment]
For now the control core supports ObservableCollections but don't support INotifyCollectionChanged event. Anyway, you can use it CollectionChanged in your own code for your own business logic. If you want to remove/add elements to carousel, use the provided API.

**Comment by alexrainman** [comment]
As all the native components behave different on each platform and, took me a while to make them work in the same way, that's way i am handling removing/adding pages at core level because sometimes you need to remove the item from the source after removing the UI object and that wont be the case if i use CollectionChanged event, where the item will be always removed from the collection before the UI object. Anyway, i will do my round of testing. I believe if i do this change it will mean a huge change in the control that will brake previous version people are using already. Thanks

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
