### ISSUE TITLE
Strange behavior with sequence on re-bind

### ISSUE THREAD

**Issue by fenix2222** [alexrainman/CarouselView#120]
I am using CarouselView with data binding. My ItemsSource is bound to ObservableCollection<MyItem> and Position is bound to integer Position property. Everything works fine on first load. i.e. if I have "Item1", "Item2" and "Item3" in my collection, they show up in the right sequence. Then when I change the collection in my view model by clearing collection and then adding new items I get carousel showing old items. In particular, if I delete "Item1", "Item2" and "Item3" and add "Item4", "Item5" and "Item6", then my view model has an updated collection, but carousel is showing "Item5", "Item6" and "Item1"??? Not, it ignored first new "Item4" and appended old item "Item1" that was removed.

Here is my code:

XAML
```
<controls:CarouselViewControl Orientation="Horizontal" InterPageSpacing="0" 
						Position="{Binding Position}" ItemsSource="{Binding ServiceProviders}" 
						VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
			<controls:CarouselViewControl.ItemTemplate>
```
ViewModel

```
this.Position = 0;
				await Task.Delay(200);
				for (var i = this.ServiceProviders.Count - 1; i >= 0; i--)
				{
					await Task.Delay(100);
					this.ServiceProviders.Remove(this.ServiceProviders[i]);
				}

				foreach (var result in results?.Value ?? new List<ServiceProviderSearchResultV1>())
				{
					this.ServiceProviders.Add(result);
				}
```

```
private ObservableCollection<ServiceProviderSearchResultV1> serviceProviders =
			new ObservableCollection<ServiceProviderSearchResultV1>();
		public ObservableCollection<ServiceProviderSearchResultV1> ServiceProviders
		{
			get
			{
				return this.serviceProviders;
			}
			set
			{
				if (this.serviceProviders != value)
				{
					this.serviceProviders = value;
					this.NotifyOfPropertyChange(() => this.ServiceProviders);
				}
			}
		}
```

I don't understand how it gets items taht are deleted. It is like it is shifted by one.

**Comment by alexrainman** [comment]
You are right. ObservableCollection CollectionChanged.Clear is not implemented.

**Comment by fenix2222** [comment]
But I am not using clear, I am doing for loop with remove

**Comment by alexrainman** [comment]
Thats exactly the problem :)

**Comment by alexrainman** [comment]
Can you try this?

```
while (list.Count > 0)
{
     list.RemoveAt(list.Count - 1);
}
```

**Comment by fenix2222** [comment]
Thanks, I will try this. In fact, can I just use normal list, not the observable collection?

**Comment by alexrainman** [comment]
You can but your wont be able to add and remove from the list. Only setting ItemsSource will refresh the UI.

I am implementing ObservableCollection Clear, Move and Replace actions.

**Comment by fenix2222** [comment]
Thought so. I hope RemoveAt will fix it for me. What is an ETA on clear? Also, when is xamarin adding your carousel?

**Comment by alexrainman** [comment]
ETA tomorrow. Carousel in Xamarin core? Dont know yet. PR is on idle state.

**Comment by fenix2222** [comment]
Unfortunately, RemoveAt is doing the same as my previous code. 

First load I have

**ServiceProviders collection:** "Provider1", "Provider2", "Provider3", 
**Carousel**: "Provider1", "Provider2", "Provider3"

User clicks search, I use you code snippet with "while" and "remove at"
**ServiceProviders collection**: "Provider4", "Provider5", "Provider6", 
**Carousel**: "Provider5", "Provider6", "Provider1"

out of sync

**Comment by alexrainman** [comment]
If you need to Clear the list and start adding new elements, try this:

```
myCarousel.ItemsSource = new ObservableCollection<object>();
myCarousel.ItemsSource.Add(obj);
```

**Comment by fenix2222** [comment]
I can't do it. Because all my code is in viewmodel and I am binding to an observable collection

**Comment by alexrainman** [comment]
Not a problem. Assign the new collection in your VM.

**Comment by alexrainman** [comment]
All CollectionChanged Actions implemented. Will release soon.

**Comment by johnnysbug** [comment]
Hey @alexrainman, do you have an ETA for when the new CollectionChanged actions will be released? I'm running into the same problem, and resetting the ItemsSource to a new ObservableCollection doesn't seem to resolve the issue for me, since bindings in the child views no longer update afterwards.

**Comment by alexrainman** [comment]
In a couple of days. I have to finish UWP implementation.

**Comment by johnnysbug** [comment]
Great work, btw. Looking forward to when your PR gets merged into Xamarin Forms core.

**Comment by alexrainman** [comment]
Im looking forward to it also. I dont have time to maintain this repo anymore :(

**Comment by alexrainman** [comment]
Done.

**Comment by hameedibrahim** [comment]
public ObservableCollection<FlipperGetters> flipperGetters;
flipperGetters = new ObservableCollection<FlipperGetters>();
flipperGetters.Clear()
carousel.ItemsSource = flipperGetters; 

After clearing and adding the carousel.ItemsSource is getting arrayondexoutofbound exception how to sove this problem. if i remove(flipperGetters.Clear()) it is working fine.
