### ISSUE TITLE
GC causing performance issues

### ISSUE THREAD

**Issue by thewindev** [alexrainman/CarouselView#121]
I'm using the CarouselView to load some pages that contain lists of devices, and I noticed that the GC is doing a major sweep when I navigate to some pages.
For example. let's say I have 4 pages, and the carousel starts from page 1. When I navigate to pages 2->3->4, everything is ok. Then I navigate to page 3, still loads fine, but when I go back to page 2 the GC starts and it does a delay of 2-3 seconds, on a Galaxy S7.
What I found is that the second page is removed from memory when I get to page 4, so when I navigate back it loads again and that's when the GC starts. Maybe this is done because of virtualization? Because if this is the reason I would like to disable it, but I can't find a way. In WPF I would just replace the virtualizing stack panel with a normal one, but in Xamarin I couldn't find anything.
Also, I tried the carousel from Xamarin.Forms(they have a separate nuget package) and it works fine, no GC triggered.
On iOS it works slightly better but I can still see a delay.
Do you have any ideas why this is happening? Or maybe you can tell me how to disable virtualization?

**Comment by alexrainman** [comment]
@thewindev this normally happens when you are using images in the carousel. Are you?

**Comment by thewindev** [comment]
Yes, I'm using images for icons(Font Awesome) and I'm using Iconize to load them like this:
`<iconize:IconImage
                        HorizontalOptions="Start"
                        Icon="fa-lightbulb-o"
                        IsVisible="{Binding IsIconVisible}"
                        Style="{DynamicResource DeviceIconStyle}"
                        WidthRequest="20" />`

In one page I also hav some images(5-6 maximum) and I'm using FFImageLoading like this:
` <ffimageloading:CachedImage
                            Aspect="AspectFill"
                            DownsampleHeight="150"
                            DownsampleUseDipUnits="false"
                            ErrorPlaceholder="logo.png"
                            HeightRequest="150"
                            LoadingPlaceholder="intro.png"
                            Source="{Binding Image}" />`
I'll try later to see if I can reproduce this with a sample of my project and attach a link to it here;

**Comment by alexrainman** [comment]
Can you provide a reproduction project?

**Comment by xamarindevelopervietnam** [comment]
@thewindev I think you need set DownsampleToViewSize = "True" for ffimageloading:CachedImage

**Comment by alexrainman** [comment]
Did @thewindev advice solved your problem?

**Comment by alexrainman** [comment]
Otherwise, please provide a demo project.

**Comment by alexrainman** [comment]
@thewindev i think this is related to https://github.com/alexrainman/CarouselView/issues/125 and i am releasing a fix for it.
