### ISSUE TITLE
Swiping between pages on iOS is very slow with a bound CarouselView with template selector

### ISSUE THREAD

**Issue by tomasz23** [alexrainman/CarouselView#124]
Hi

I have an app that tries to bind the Carousel view with template selectors used to display either listview or textbox based screen. I find that textview based screens appear much faster than listview ones. The swiping from screen to screen can take more than 2 seconds on listviews with 10 items (on older gen device). The listview has a label and an fixed small image.

The problem is less visible on newer/faster devices/generation. I tried iPod 5th generation and iPod 6th generation. The performance difference is very large between the two devices.

I tried to remove the labels in listview to see how performance would improve - marginal may be 20% speed gain when only an image is presented without text label.

Having said that I have an older version that is Xamarin iOS native and it performs very fast on both iPods doing similar thing to CarouselView.

How can I improve performance with bound listviews as right now the app is barely usable due to large lag when swiping between screens on 5th gen iPods?

**Comment by alexrainman** [comment]
I believe this problem is not associated with the CarouselView itself but with the listview.

Are you using RecycleElement option in the ListView?

Are you using a library to get better performance with images? Like Fresco or FFImageLoading?

**Comment by tomasz23** [comment]
Yes I am using RecycleElement and the image is local image which is used like a tick so if you select row the image will change the image to another small local image.

**Comment by alexrainman** [comment]
Umm theres no reason for it to be slow then ...

**Comment by alexrainman** [comment]
Can you share a demo project?

**Comment by tomasz23** [comment]
I have implemented a custom renderer for the ListView and the performance went through the roof. This seems to support what you said earlier. Wish that Xamarin would make ListView faster it is used pretty much in most apps but still has so many performance problems.

**Comment by alexrainman** [comment]
Excellent. Can you share that custom renderer?

**Comment by tomasz23** [comment]
Unfortunately, I must say no - I am a contractor and this is client's code, so I don't have any authority over it. I will see if I write my own app which will utilise the same principle I could then share that code.

**Comment by Ruddy2007** [comment]
@tomasz23 Any change on this? I have also ran into this issue and would love to get my hands on the custom renderer you have created!
