### ISSUE TITLE
Significant Memory Leak for iOS when using custom layout for page content

### ISSUE THREAD

**Issue by johnnysbug** [alexrainman/CarouselView#125]
This appears to only be be an issue when more than two pages are added to the CarouselView.

Steps to repro:

1. Restore Nuget packages making sure not to overwrite FodyWeavers.xml file.
2. Run iOS project.
3. Tap 'Add Page' until you have at least three pages.
4. Swipe to navigate from page 1 through to page 3, then swipe back to return to page 1.
5. Repeat step 4 a few times. (_app output shows as you navigate that the items source for each page appears to change which seems like it is creating new instances of the layout at certain points_)
6. Tap 'Shrink'. This walks through each page and updates the height on each label causing a child measure invalidated event to occur for each page. Notice in the output that there are more unique ids than there are pages. The first page seems to have the most copies of the layout.

The more you navigate through the pages, the more unique copies of individual pages build up. Oddly, if you only have two pages, this isn't an issue at all.

[CarouselViewTest.zip](https://github.com/alexrainman/CarouselView/files/1003044/CarouselViewTest.zip)

**Comment by alexrainman** [comment]
I will take a look at your demo, but theres something you should know: the iOS version of the plugin render only one page at the time. Maybe you are creating the issue yourself?

**Comment by johnnysbug** [comment]
Here's a simpler example. This example is not using a custom layout and just using a stacklayout in each page added.

Follow the steps above to see the same results.

Here's some sample app output showing that after tapping "shrink", it receives events from eight instances of StackLayout even though there are only three pages.

```
LayoutChildren for MyStackLayout [8ee837a5-358c-489a-af80-943c3519fae7]
LayoutChildren for MyStackLayout [4e6ec851-abb2-4740-999a-71f9aaf77e74]
LayoutChildren for MyStackLayout [dbe3d30a-6ea6-480c-9c49-05c033e12efc]
LayoutChildren for MyStackLayout [bc23e564-9ab0-4ba3-931e-e613c8014bfe]
LayoutChildren for MyStackLayout [b4e98b82-016f-408b-b7ee-5299937479e1]
LayoutChildren for MyStackLayout [939b4af3-ff07-43a4-9e38-f0e87feeb189]
LayoutChildren for MyStackLayout [9aed5897-1c2e-453a-a6d3-01ddffb97bec]
LayoutChildren for MyStackLayout [0899b5e2-c26a-44dc-9c1c-4838b260d731]
```

[CarouselViewTest 2.zip](https://github.com/alexrainman/CarouselView/files/1004815/CarouselViewTest.2.zip)

**Comment by alexrainman** [comment]
Will take a look later.

**Comment by alexrainman** [comment]
I am using your demo. I cant find anything wrong with it. If you clean your Application Output window and start adding pages and calling Shrink, LayoutChildren is called a maximum of 3 times as the UIPageViewController renders a maximum of 3 pages at the time (virtualization).

**Comment by johnnysbug** [comment]
After you add the pages, how many times did you navigate back and forth between the pages? That's the key as I've noted in step 4. The output I posted was after I cleared the console window before calling shrink.

**Comment by johnnysbug** [comment]
I even tried updated to your most recent version 4.2.5. Still a major leak.

Here's a video I posted showing exactly what I described: https://youtu.be/1EtRYO2Aji0

**Comment by alexrainman** [comment]
I think i have a way to correct that but i have to run some tests.

**Comment by alexrainman** [comment]
Dispose is being call in the ViewControllers that are not used anymore by the PageController, but the Xamarin.Forms View is not being collected and i don't know how to solve it.

**Comment by johnnysbug** [comment]
I was noticing the same thing when doing some tests using your source locally. I even tried to grab the underlying renderer and call SetElement passing in null, but they still seem to hang around.

**Comment by alexrainman** [comment]
It seems to be a Xamarin issue. I dont know how to fix it :(

**Comment by alexrainman** [comment]
I tried overriding Dispose in the ViewContainer controller but it doesn't works neither.

The thing is that pageController.ViewControllers always have only one but actually more than one has been rendered because virtualization (page controller render the next and prev page ahead of time), but i don't know where those pages are located before they become the current visible controller.

They are collected and Dispose is called, but the Xamarin.Forms View hand around in memory. Where? No freaking idea :)

**Comment by alexrainman** [comment]
There is a string reference somewhere that is keeping the alive. I tried setting Parent to null but no luck :(

**Comment by johnnysbug** [comment]
I think I figured out a way to stop the leak. I'm not sure how it will behave with tons of pages, but if your renderer keeps a dictionary like this:
`Dictionary<object, ViewContainer> _pages = new Dictionary<object, ViewContainer>();`

And in your `CreateViewController` method, after you get the `bindingContext`, do this:

```
if (_pages.ContainsKey(bindingContext))
{
	return _pages[bindingContext];
}
```

Then at the bottom of that method:
```
var viewController = new ViewContainer();
viewController.Tag = bindingContext;
viewController.View = nativeConverted;
_pages[bindingContext] = viewController;
return viewController;
```

It'll reuse any stored ViewContainers tied to each requested bindingContext.

In my sample project, when I tapped Shrink, it only output three LayoutChildren calls, even after navigating a ton of times. What do you think?

By the way, I'm not sure what you tried in your dispose implementation, but I know when I was looking at XF ListViewRenderer implementation, they walk the ViewController's subviews and call dispose on each of those.

**Comment by alexrainman** [comment]
If we are doing this, we don't need a dictionary as ViewContainer has a Tag property object that contains the bindingContext, so it will be just a list of controllers.

Lemme try disposing all the subviews.

**Comment by alexrainman** [comment]
Can you point me where you saw that code?

**Comment by johnnysbug** [comment]
The dictionary allows you to track all of them, though. The inverse currently doesn't really give you a way to track or re-use. I've noticed the ViewContainer start to build up in the UIPageViewController's ChildrenViewController collection, and eventually go into the either, leaving the Forms view orphaned.

**Comment by alexrainman** [comment]
HA, good catch. Disposing all the Subviews work 👍

**Comment by johnnysbug** [comment]
The dispose stuff is here: https://github.com/xamarin/Xamarin.Forms/blob/e6d5186c8acbf37b877c7ca3c77a378352a3743d/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L124

**Comment by johnnysbug** [comment]
Awesome!

**Comment by alexrainman** [comment]
This is what i did, but i am going to implement it as them:

```
InvokeOnMainThread( () => {
	foreach (var view in View.Subviews)
	{
		view.Dispose();
	}

	View.Dispose();
	View = null;
});
```

**Comment by alexrainman** [comment]
I need to run it on UI thread or we get a crash.

**Comment by johnnysbug** [comment]
I noticed that, too when I was trying it the other day. I never got to the point of disposing the child view though, until I thought of it today. When I noticed there didn't appear to be any magic happening in the ListViewRenderer, I figured something wasn't being disposed.

**Comment by alexrainman** [comment]
I ended up with this:

```
InvokeOnMainThread( () => {
	foreach (var view in View.Subviews)
	{
		view.RemoveFromSuperview();
		view.Dispose();
	}

	View.RemoveFromSuperview();
	View.Dispose();
	View = null;
});
```

Problem solved. Thanks a lot!

**Comment by johnnysbug** [comment]
I was thinking about this this morning. The reason why you need to run on the main thread is because that dispose pass is happening on the finalizer thread. I also realized during my previous tests that the dispose never seemed to be called with `disposing` equal to true, which I am assuming you aren't checking. 

I found this regarding this same scenario: https://forums.xamarin.com/discussion/1134/how-do-i-clean-up-in-dispose-if-i-cant-call-uikit-from-another-thread

One issue that you might want to watch out for is the finalizer pass doesn't have a guarantee of what order objects are disposed, hence the boolean that gets passed in. Might be something to think about. 

Another approach as mentioned in that post is to override WillMoveToSuperview and if the superview is null call dispose there. Problem is I couldn't figure out how to cast the native view on the vRenderer object to a uiview wrapper in order to override that method.

Anyway, just some thoughts.

**Comment by alexrainman** [comment]
You are right, disposing is always false :(

And, there's not way to override WillMoveToSuperView o each subview as it's a group method.

**Comment by alexrainman** [comment]
I don't think there will be any problem in the way we are doing the disposing as dispose is being called because of virtualization.

**Comment by johnnysbug** [comment]
I updated this morning and am seeing a significant improvement on my app. Although in some situations, I am still still extra pages left over, but it doesn't seem to affect performance. I think we are good for now though.

I might revisit this later, because I have another idea from something I read earlier in the week about UIPageViewControllers in Xamarin. I'll send you a PR if I can pull off what I'm thinking of if it works.

**Comment by alexrainman** [comment]
Can you share that read with me?

**Comment by johnnysbug** [comment]
It's basically this:

> At the end of FinishedAnimating I ended up adding the following:

> //Cleanup non adjacent controllers
> var childControllers = ChildViewControllers;
> foreach (BaseMediaItemController childController in childControllers)
> if (childController.Index < (CurrentIndex - 1) || childController.Index > (CurrentIndex + 1))
> childController.Dispose ();

Essentially, it forces the non-adjacent controllers to dispose which may also cause the newly updated dispose method to pass true keeping you from needing to run the dispose on the finalizer thread. I haven't tested it though.

**Comment by johnnysbug** [comment]
For reference:
https://forums.xamarin.com/discussion/40619/proper-way-to-dispose-cleanup-memory-in-a-uipageviewcontroller

https://stackoverflow.com/a/30168817/224963

**Comment by alexrainman** [comment]
K will take a look later and see if i can implement it. Thanks a lot

**Comment by alexrainman** [comment]
This implementation rocks :)

**Comment by alexrainman** [comment]
As the control is dynamic and we can add/remove/clear ItemsSource which will end up refreshing the UI, i added a method called CleanupChildViewControllers which i call ad the end of DidFinishAnimating but also after calling SetViewControllers:

```
void CleanupChildViewControllers()
{
	//Cleanup non adjacent controllers
	var childControllers = pageController.ChildViewControllers;
	foreach (var childController in childControllers)
	{
		var index = Element.ItemsSource.GetList().IndexOf(((ViewContainer)childController).Tag);
		if (index< (Element.Position - 1) || index > (Element.Position + 1))
			childController.Dispose();
	}
}
```

Also, i checking if disposing is true now and i don't need to run the code in the finalizer thread.

I think now we have a solid solution here :)

**Comment by alexrainman** [comment]
Something i noticed is that pageController.ChildViewControllers keeps all the rendered ViewControllers when you navigate back and fort in the carousel, no matter if you call dispose.

**Comment by johnnysbug** [comment]
Awesome!

I've noticed the ChildViewControllers retention as well, but after a while they start falling off randomly.

**Comment by alexrainman** [comment]
Yeah, i noticed too! Awesome. Will release an update and also include this on the the active PR for Xamarin.Forms.

Thanks a lot!

**Comment by johnnysbug** [comment]
Anytime, man! Glad I could help solidify this!

**Comment by alexrainman** [comment]
The implementation is causing crashes on fast scrolling https://github.com/alexrainman/CarouselView/issues/134

**Comment by johnnysbug** [comment]
This might shed some light:
https://stackoverflow.com/questions/14220289/removing-a-view-controller-from-uipageviewcontroller

**Comment by alexrainman** [comment]
Which part of it? HA

**Comment by johnnysbug** [comment]
Does that mean the leaks will come back? Currently, I don't have any crashes using the version prior to you removing the memory leak fixes. I'll test to see if the leaks return when you release the next update. If anything, I'll make sure to target the version where the views are disposed.

**Comment by johnnysbug** [comment]
I may fork and implement a custom version for my app that uses the logic I mentioned in this [comment](https://github.com/alexrainman/CarouselView/issues/125#issuecomment-302826044) above.

**Comment by alexrainman** [comment]
After revisiting this, i believe there are not leaks. Its just the way UIPageViewController handle/caches/dispose pages using ChildViewControllers array.

**Comment by alexrainman** [comment]
You should do that if that solves your issue.

**Comment by johnnysbug** [comment]
Have you tried running it against the demos I previously posted? If it still works, I won't need to customize. :)

**Comment by johnnysbug** [comment]
I'd hate to diverge.

**Comment by alexrainman** [comment]
I will teat with your demos.

**Comment by alexrainman** [comment]
This is the only fix that works:

The problem:

To facilitate smooth swiping, UIPageViewController keeps a ghost copy of the pages in a collection named ChildViewControllers. This collection is handled internally by UIPageViewController to keep a maximun of 3 items, but when a custom view is used from Xamarin.Forms side, the views hang in memory and are not collected no matter if internally the UIViewController is disposed by UIPageViewController.

Fix explained:

Some code has been added to GetPreviousViewController and GetNextViewController to return a child controller of exists in ChildViewController. Also Dispose has been implemented in ViewContainer to release the custom views. Dispose is called in the finalizer thread (UI) so the code to release the views from memory has been wrapped in InvokeOnMainThread.

Releasing a new version.
