### ISSUE TITLE
DataTemplate pages not showing up in CarouselViewControl

### ISSUE THREAD

**Issue by DanielSmith1239** [alexrainman/CarouselView#126]
I created a carousel view and I am attempting to set up the DataTemplate pages. All I am getting right now is just six blank white pages. 
Here is the code that configures the carousel view:
````
carouselView.ItemsSource = new ObservableCollection<String> { "hi", "my", "name", "is", "dani", "smith"};
carouselView.ItemTemplate = new DataTemplate(typeof(SiddurCarouselView));
carouselView.InterPageSpacing = 10;
carouselView.IndicatorsTintColor = Color.LightSteelBlue;
carouselView.ShowIndicators = true;
carouselView.Orientation = CarouselViewOrientation.Horizontal;
````

Here is my code for the SiddurCarouselView:
````
using System;
using System.Collections.Generic;
using Xamarin.Forms;

namespace YidKit
{
	public partial class SiddurCarouselView : ContentView
	{
		public SiddurCarouselView()
		{
		}
	}
}
````

````
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="YidKit.SiddurCarouselView">
	<ContentView.Content>
		<StackLayout HorizontalOptions = "FillAndExpand"
			VerticalOptions = "FillAndExpand"
			BackgroundColor = "Lime">
			<Label Text = "{Binding text}"/>
		</StackLayout>
	</ContentView.Content>
</ContentView>
````

And all I'm getting is just six empty white pages. Any tips? Thanks in advance.

**Comment by johnnysbug** [comment]
@DanielSmith1239 It doesn't look like you are calling `InitializeComponent();` in your `SiddurCarouselView` constructor.

**Comment by DanielSmith1239** [comment]
That got the page to show up, but the binding isn't working properly. Could you help me with getting that set up?

**Comment by DanielSmith1239** [comment]
Thanks, that fixed it. Would I be able set a variable in the SiddurCarouselView instead of using Binding? I need to display local HTML files using WebViews, and I would like to just pass the file path to the SiddurCarouselView and then it will take care of getting and displaying the file.

**Comment by alexrainman** [comment]
Yes, you can use variables.

**Comment by DanielSmith1239** [comment]
How do I use variables instead of the binding properties?

**Comment by DanielSmith1239** [comment]
Can you please help ASAP I am in a rush to complete this project. I would really appreciate it.

**Comment by alexrainman** [comment]
Where do you want to use variables?

**Comment by DanielSmith1239** [comment]
I would like to have the CarouselView pass the current ItemSource to the SiddurCarouselView as a variable and not as a bound value. I would like to process the data in the SiddurCarouselView's code, not just have it display something.

**Comment by alexrainman** [comment]
Whats is SiddurCarouselView?

**Comment by DanielSmith1239** [comment]
It is my item template.
`carouselView.ItemTemplate = new DataTemplate(typeof(SiddurCarouselView));`

**Comment by alexrainman** [comment]
Ah got it. The carousel is already passing the source as binding context. Just dont do any bindings. 

Instead override BindingContextChanged and do your stuff there.

Also to do some processing youncan bind to the original values and use converters to get what you need from them.
