### ISSUE TITLE
(UWP) CarouselViewControl will not work if DataTemplate has WebView with a Source

### ISSUE THREAD

**Issue by GuyMicciche** [alexrainman/CarouselView#128]
PLEASE HELP ME. Your control is awesome, but I am getting an error. Page will not launch. WebViews will not work. It gives me a debugger error. Can you help me?

This will not work in UWP:

`
<cv:CarouselViewControl

                    ItemsSource="{Binding Pages}"
                    ShowIndicators="true"
                    ShowArrows="True"
                    VerticalOptions="FillAndExpand" 
                    HorizontalOptions="FillAndExpand">
                    <cv:CarouselViewControl.ItemTemplate>
                        <DataTemplate>
                                             <WebView Source="http://xamarin.com/"/>
                        </DataTemplate>
                    </cv:CarouselViewControl.ItemTemplate>
                </cv:CarouselViewControl>
`

**Comment by alexrainman** [comment]
This is a known issue https://github.com/alexrainman/CarouselView/issues/127

**Comment by GuyMicciche** [comment]
Oh I see. Well, I am not wrapping the CarouselViewControl inside a DataTemplate or a ControlTemplate. My issue is specific to WebView. In my code above, if replace the WebView with a Label, it works as expected. If add a WebView WITHOUT the Source property, it also works. But once I add the Source property, the page fails to render and will not attach to the debugger.

Basically, I want a CarouselViewControl with WebView as the ItemTemplate. It works in Android, but not working in UWP. The Xamarin.Forms.CarouselView renders with WebView, maybe you can take a look at that code. I would, but I don't have much time available. I am not using Xamarin's CarouselView, because it is way too slow on Android, and because yours is better ;) 

Like I said, WebView as the ItemTemplate works in Android, but not in UWP. Anything I can help, or a work around, let me know. Thanks for your help!

**Comment by GuyMicciche** [comment]
Nevermind. I found out I was having Memory issues, loading too much html data into 365 different pages of the CarouselView. 

It does work with Xamarin's, but it's sooo slow. I reduced the page count to about 30, and it works.

Thanks!

Guy

**Comment by FruitAndAShape** [comment]
I'm getting an absolute mess on Android with WebViews.
