### ISSUE TITLE
Vertical CarouselView

### ISSUE THREAD

**Issue by DVieira7** [alexrainman/CarouselView#13]
does vertical carousel view will be released at any point or it will be just horizontal?

**Comment by alexrainman** [comment]
None of the platform specific controls have that functionality by defauly. It will need to be custom stuff. I have 2 more things in my roadmap for the current implementation and then i will take a look as i have time. I wont say no :)

**Comment by DVieira7** [comment]
ye i know because i had to create custom renders to do a carouselview for both ios and android a few months back, i just say this repo and decided to give it a try because it doesnt use custom renderers. good work so far :)

**Comment by alexrainman** [comment]
I have a pending fix for the page indicators and provide support for CollectionChanges callback. After that i will give vertical swiping a try. Thanks

**Comment by alexrainman** [comment]
This is on the way. iOS is an easy task. Android? I need to implement a Vertical ViewPager from scratch and test it. I will need to manage Page indicators and move them to the side when orientation is vertical.

**Comment by alexrainman** [comment]
Android and iOS are ready. Working on UWP now :)

**Comment by alexrainman** [comment]
Done :)

**Comment by DVieira7** [comment]
wow great job

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
