### ISSUE TITLE
Ability to change the position of the indicators

### ISSUE THREAD

**Issue by SuperJMN** [alexrainman/CarouselView#131]
I would like to align them to the right. Is it possible with the current version?

![captura](https://cloud.githubusercontent.com/assets/3109851/26391749/491e7afe-4064-11e7-80c4-1fa2d498db05.PNG)

Thanks!

**Comment by alexrainman** [comment]
This is something i have in my TODO list. I faced some issues under iOS.

**Comment by SuperJMN** [comment]
OK, if you have problems I can give you the control I have just created: "PageIndicator". It's the control that contains the circles and it's working without custom renderers.

**Comment by alexrainman** [comment]
Indicators are implemented in platform specific code and using another way will require a lot of refactoring, but i am not against it. Please share and i will evaluate the amount of work required.

Thanks

**Comment by alexrainman** [comment]
Can you provide the "PageIndicator" control? I want to run some test. The thing is UIPageControl is really slow when the number of pages is high. In these cases ShowIndicators should be set to false but i want to avoid the users facing that issue where the carousel takes like 10s to load and behaves clunky. Also UIPageControl cannot be aligned to the sides :(

**Comment by SuperJMN** [comment]
Sorry for the delay! I have uploaded everything to GitHub for your convenience. Please, take a look: https://github.com/SuperJMN/PageIndicatorDots-XamarinForms
