### ISSUE TITLE
There is no SelectedItem property

### ISSUE THREAD

**Issue by SuperJMN** [alexrainman/CarouselView#132]
I expected a SelectedItem property to bind it in TwoWay mode to my ViewModel.

I consider it essential to know which item is currently shown.

I hope it's easy to get this! :) Thanks in advance.

**Comment by alexrainman** [comment]
You have Position property. You can easy get SelectedItem using:

```
ItemsSource[position]
```

**Comment by SuperJMN** [comment]
I would like to have both, like most of the components in XAML 😊

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Alex Rainman<mailto:notifications@github.com>
Enviado: miércoles, 24 de mayo de 2017 19:32
Para: alexrainman/CarouselView<mailto:CarouselView@noreply.github.com>
CC: José Manuel Nieto<mailto:superjmn@outlook.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [alexrainman/CarouselView] There is no SelectedItem property (#132)


You have Position property. You can easy get SelectedItem using:

ItemsSource[position]

**Comment by alexrainman** [comment]
As getting the SelectedItem is easy using Position and ItemsSource, i have not plans to include that property for now as other important issues need to be solved first.

Anyway, thanks for the suggestion.
