### ISSUE TITLE
How can I add events for detecting scroll movement/direction on the iOS CarouselViewRenderer?

### ISSUE THREAD

**Issue by twentytwokhz** [alexrainman/CarouselView#133]
Is there a way to override some base CarouselViewRenderer event in order to access the UIScrollViewer Scrolled event?

**Comment by alexrainman** [comment]
You can use PositionSelected Event to detect scroll direction. Keep a track of the previous position and compare with the current one selected.

Anyway i will think about how to implement Scrolled event that send direction as EventArgs.

**Comment by modplug** [comment]
What about adding scroll progress to those event args? Could be useful for timing animations with the scroll amount
