### ISSUE TITLE
Version 4.2.7 - Fast scrolling is causing crash

### ISSUE THREAD

**Issue by ziomagic** [alexrainman/CarouselView#134]
Hello.
I updated my lib to version 4.2.7 today, and I am getting IOS Crash, when fast scrolling back and forth. I checked, and Version 4.2.6 is working fine.

Error message:
 Assertion failure in -[UIPageViewController queuingScrollView:didCommitManualScroll:toRevealView:concealView:direction:animated:canComplete:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UIPageViewController.m:1981

**Comment by twentytwokhz** [comment]
I can confirm it happened to me too

**Comment by alexrainman** [comment]
Maybe because of the code i added to handle Memory Leaks. I am disposing ChildViewControllers outside of the previous and next to the current one visible.

**Comment by alexrainman** [comment]
Going back to 4.2.6 in next release.

**Comment by b099l3** [comment]
Think this might be an iOS bug [stackoverflow] as it is still happening on v4.4.6 (https://stackoverflow.com/questions/25740245/assertion-failure-in-uipageviewcontroller)
