### ISSUE TITLE
Android: NullReferenceException

### ISSUE THREAD

**Issue by mcpummec** [alexrainman/CarouselView#139]
Hi,
while working fine on iOS, CarouselView causes a NullReferenceException on Android:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at CarouselView.FormsPlugin.Android.FormsToNativeDroid.ConvertFormsToNative (Xamarin.Forms.View view, Xamarin.Forms.Rectangle size) [0x00046] in <78f2e2234165408294ce634a82101454>:0 
   at CarouselView.FormsPlugin.Android.CarouselViewRenderer+PageAdapter.InstantiateItem (Android.Views.ViewGroup container, System.Int32 position) [0x000aa] in <78f2e2234165408294ce634a82101454>:0 
   at Android.Support.V4.View.PagerAdapter.n_InstantiateItem_Landroid_view_ViewGroup_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_container, System.Int32 position) [0x00011] in <27c17fe440cf491ba8255bcefade6e02>:0 
   at (wrapper dynamic-method) System.Object:7613faef-e6df-4e72-949c-70e9ffe163ff (intptr,intptr,intptr,int)`

To me, this issue seems to be related to [https://bugzilla.xamarin.com/show_bug.cgi?id=47911#c4](url).

Currently, CarouselView is added in xaml:

`<controls:CarouselViewControl Orientation="Horizontal" InterPageSpacing="10" Position="0" PageIndicators="True" ItemsSource="{Binding Images}" x:Name="CarouselImages" IsVisible="false" Grid.Row="0" Grid.Column="0" Grid.RowSpan="3" Grid.ColumnSpan="3" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
	<controls:CarouselViewControl.ItemTemplate>
		<DataTemplate>
			<Image Aspect="AspectFill" Source="{Binding ImageUrl}"/>
		</DataTemplate>
	</controls:CarouselViewControl.ItemTemplate>
</controls:CarouselViewControl>`

I am using 2.3.2, but I also tried 4.2.7 on Forms 2.3.5.239-pre3.
What could possibly cause this issue and how can I resolve it?

Thanks

**Comment by alexrainman** [comment]
Can you provide a demo project reproducing the issue?

**Comment by mcpummec** [comment]
Wow, that was a quick response.
While this demo doesn't make a lot of sense, it shows how I try to populate CarouselView with images and how I am running into a NullReferenceException.

[DemoApp.zip](https://github.com/alexrainman/CarouselView/files/1044048/DemoApp.zip)

Thanks

**Comment by shoeIT** [comment]
I thought I have the same problem therefore I had a look into DemoApp. I think you are missing the initialization of the control:
CarouselViewRenderer.Init(); in MainActivity.cs

**Comment by mcpummec** [comment]
you are right, i am missing the initialization in this demo. but adding the line won't solve my problem.

**Comment by shoeIT** [comment]
jep but it shows that the problem is probably not relatet to a bug in the first place its more related to reading the documentation correctly.
I actually don't understand your DemoApp project. Its not a real XF project you cannot add references and its not a portable. Please notice the second line in the Readme:
Install in your PCL project and Client projects.
You did not install the package in the PCL since there is no pcl. Btw. you are using ItemSource with binding but you have no view model and you set the source twice, by binding and in code behind.
So there are many reasons for not working correctly.

**Comment by alexrainman** [comment]
@shoeIT it's not working for you because you are not using PCL.

**Comment by shoeIT** [comment]
yes thats what I mentioned to mcpummec, I don't have a problem anymore.
I use your controll inside my PCL and it works fine.
