### ISSUE TITLE
Getting null exceptions after updating to v2.0

### ISSUE THREAD

**Issue by shnaz** [alexrainman/CarouselView#14]
Hey @alexrainman 

I finally upgraded to v2.0, thanks for the improvement but I am partially delighted because some of the improvements break our app.

The reasons are:

**1.** I am now getting a null exception when setting `App.Current.MainPage = new Page();`. 
In your Demo project I can see that it is in the ExtendButtonRenderer, where `Element` is null.
<img width="476" alt="screen shot 2016-07-30 at 18 12 18" src="https://cloud.githubusercontent.com/assets/6933856/17271740/4f649f26-5684-11e6-8011-d31df7e38772.png">
<img width="805" alt="screen shot 2016-07-30 at 18 11 57" src="https://cloud.githubusercontent.com/assets/6933856/17271737/45d9be46-5684-11e6-8c6a-f9b9b9bd4264.png">

**2.** Local renderers are overriden by the ones added in v2.0. 
A major upset, because we have multiple local renderers for button, editor, entry, etc. that are used to customise the controls.

**Comment by alexrainman** [comment]
I will test this and, the renderers are needed for HeightRequest. I can remove them but them you will need to declare height request for each component. Something else i can do is provide custom controls that you will override with your renderers.

**Comment by shnaz** [comment]
I think so, because local renderers are used commonly in Xamarin.Forms app and it is definitely not recommended to override those. :/

**Comment by alexrainman** [comment]
I will add custom controls for all my renderers and your renderers will override them :)

**Comment by alexrainman** [comment]
Later today!

**Comment by alexrainman** [comment]
An update is on the way. For your custom renderers, instead of, for example implement ButtonRenderer, it will implement CVButtonRenderer. Why? I need my renderers to fix HeightRequest issue. Thanks

**Comment by shnaz** [comment]
As long as it doesnt override my local renderers, I am happy. (Y) good work!

**Comment by alexrainman** [comment]
They wont override yours, yours will override them

Button -> CVButton -> yourbutton

Thanks

**Comment by shnaz** [comment]
Great!

**Comment by alexrainman** [comment]
Did version 2.1 worked well for you?

**Comment by shnaz** [comment]
Worked great. Thanks alot, @alexrainman!

**Comment by alexrainman** [comment]
Adding Vertical swipe in the next release :)

**Comment by shnaz** [comment]
Great, I am sure it will be nice!

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
