### ISSUE TITLE
Lazy Loading?

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#140]
It appears the loading time of my UI strongly depends on the number of pages I have. I realize there's more markup to parse, but am not sure whether the rendering etc already takes places. Do you have some lazy loading built into the control? If not, would there be any way for an carousel page to know when it's being rendered?

**Comment by alexrainman** [comment]
This related to the same i mentioned in the other thread: indicators in the background and the way i was creating them was eating memory. It will be fixed in the next release.

**Comment by hardcodet** [comment]
With regards to lazy / eager loading, may I suggest the following:

* I assume the 3 cached views are hardcoded somewhere. Could you make those configurable? In tab scenarios, you may have 4 or 5 tabs for example, and recreating those views over and over again may be expensive (like all my use cases, where they are views that need layouting), while in other scenarios, developers might want to free memory immediately (e.g. flipping through tons of items or images).

* When it comes to the loading strategy, I would love to see either (or both) those variants:
  * lazy loading everything (only load pages when they are needed in order to decrease loading time, which is a huge issue with Xamarin Forms)
  * load current and next page (next page preferable with low priority in order not to affect foreground performance)

For a tabbed UI, this would allow me to have a quick startup (only the initial tab is rendered), acceptable swipes, and quick swiping back (since I would want to keep all the tab pages cached once the expensive rendering was done).

**Comment by alexrainman** [comment]
Let me clarify: thats exactly the way the control is behaving.

UIPageViewController actas like that. 

What is affecting performance is the pageControl that i am using for the indicators. Currently inam hiding it even when there are tons of pages, which is wrong.

I am fixing that.
