### ISSUE TITLE
Significant performance step backwards

### ISSUE THREAD

**Issue by nikolaybedrov** [alexrainman/CarouselView#141]
Hi, I love this component and have used it in previous projects with great success but it looks like something has gone wrong somewhere between versions 4.1.2 and the current one.

The more items you bind the more time it takes it to load the carousel which makes sense but not to this extent. In my previous project I was using the component to show over 2000 items, each used to populate a simple template and it was loading in a split second. Currently I have 300 items and it takes about 10sec to open the carousel and it is quite clunky. I loaded up my previous project to check if I'm missing something but it can't even load up the carousel at all.

It looks like it is loading every item in memory on first load or something like this. Does this sound reasonable?

Cheers!

**Comment by alexrainman** [comment]
Android or iOS?

**Comment by nikolaybedrov** [comment]
iOS

**Comment by alexrainman** [comment]
Yeah, i know wheres the problem. Can you try version 4.2.6 and tell me if the problem happens?

**Comment by nikolaybedrov** [comment]
I'll do that right away, thanks for the immediate reply!

**Comment by nikolaybedrov** [comment]
Hi, so unfortunately the problem is still there with 4.2.6 (and 4.2.5 :) )

**Comment by alexrainman** [comment]
Can you keep trying previous versions?

**Comment by nikolaybedrov** [comment]
OK, I stopped at 4.2.3, I'll try some more :)

**Comment by alexrainman** [comment]
Thanks

**Comment by alexrainman** [comment]
I partially identified that indicators are affecting the performance.

**Comment by nikolaybedrov** [comment]
Well I got down to 3.1.1 and it started missing some methods so I'll stop :) 

If it helps I'm not using indicators at all. If there is something I can do to disable them completely - happy to do it if it will fix the issue.

Thanks for looking into it, much appreciated!

**Comment by alexrainman** [comment]
You are not using them but they still running in background. My mistake. I am changing that.

**Comment by nikolaybedrov** [comment]
Hi mate, thanks for looking into this issue!
I don't want to be pushy or anything but just so I know what to do, do you know if this will be fixed in the next few days or is the fix going to be released in a few weeks? Just trying to figure out how to handle my project since it heavily relies on this functionality.

Cheers and thanks again!

**Comment by alexrainman** [comment]
It will be released in the next couple of days.

**Comment by nikolaybedrov** [comment]
You are a GOD! Thank you!

**Comment by alexrainman** [comment]
The change is implemented and tested in iOS and Android. I have to make it work on UWP which is slightly different.

**Comment by alexrainman** [comment]
When using the carousel with a long list of elements, set ShowIndicators to false or you will get a long loading delay in iOS and UWP and the carousel will be clunky.

**Comment by nikolaybedrov** [comment]
Thanks for doing this so quickly!
I don't think I got the fix though I removed the package in Xamarin and downloaded it again using the nuget window. Is this not the right way to update it?

**Comment by alexrainman** [comment]
I just uploaded version 4.2.8

It should appear soon in nuget.

**Comment by nikolaybedrov** [comment]
OOOOHHH THE SLICKNESS!!!
It is fantastic thank you for the awesome support and the great product!
