### ISSUE TITLE
Pages recreated over and over again?

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#142]
Hi Alex

I did some debugging due to performance issues and noticed that my views are recreated all the time while flipping back and fourth. On one view, I have four pages in a carousel and just loading it causes 5 view instances to be created, and more while flipping back and forth. The views are just created through a DataTemplate, ItemsSource is a simple List (not ObservableCollection).

Thanks,
Philipp

**Comment by alexrainman** [comment]
iOS dont? Can you test version 4.2.6?

**Comment by alexrainman** [comment]
Only a maximum of 3 views will be kept in memory, the rest will be released as soon as they are not needed.

**Comment by alexrainman** [comment]
Also, i make a change in version 4.2.7 that its causing this.

**Comment by hardcodet** [comment]
I tested this in 4.2.7 and 4.2.6, and it's similar on iOS and Android. I have a carousel with 4 pages (for a tabs control):

* On Android, I'm getting 5 instances immediately. For all of them, LayoutChildren is immediately invoked.
* On iOS, I'm getting 4 instances immediately. For two of them, LayoutChildren is immediately invoked.
  * Strange enough, When I attempt from the first to the second carousel page, a 5th instance is being created and layouted, while instances 3,4 don't ever seem to be used. The same repeats when I navigate further. By the time I'm at the 4th tab, 7 instances have been created. Moving back to tab 3 creates another instance, then moving back to tab 2 creates yet another one, and moving back to the first tab seems to reuse a cached instance.

Apart from fixing those bugs, may I suggest the following:
* I assume the 3 cached views are hardcoded somewhere. Could you make those configurable? In tab scenarios, you may have 4 or 5 tabs for example, and recreating those views over and over again may be expensive (like all my use cases, where they are views that need layouting), while in other scenarios, developers might want to free memory immediately (e.g. flipping through tons of items or images).
* When it comes to loading strategy, I would love to see either (or both) those variants:
  * lazy loading everything (only load pages when they are needed in order to increase loading time, which is a huge issue with Xamarin Forms)
  * load current and next page (next page preferable with low priority in order not to affect foreground performance)

Thanks for all the good work so far!

**Comment by hardcodet** [comment]
Addendum: It appears the initial frenzy of page creations has been triggered by a generic property change event in the view model (no property name given to refresh the whole UI during initialization). This caused the carousel to recreate parts of the pages, even though they were still the same. I can't tell why some are kept and others thrown away, but that might be a corner case that can be ignored.

However, in order to avoid a complete recreation, I'm using an ObservableCollection now as the ItemsSource, and conditionally insert items. I thought that was supported (there is some code related to INotifyCollectionChanged), but on my Insert operation, the carousel doesn't create a new page unfortunately.

                int index = ItemsSource.IndexOf(tab);

                //insert column into ObservableCollection (in my case that's index 0)
                TabItems.Insert(index, tab);


For debugging purposes, I aso tried TabItems.Add(tab), but that also didn't do anything.

**Comment by hardcodet** [comment]
Edit: I bound to an ObservableCollection, but also used a converter, which transformed the data and returned a new enumerable. Accordingly, the carousel didn't see the source collection I guess. However, strangely enough, if I remove the converter, the carousel doesn't render anything anymore at all, no matter whether I insert items, recreate the list or throw property change events. As soon as the converter is back in the mix, everything is fine. I have no idea what's going on here - I'll have to do some further analysis and post back.

**Comment by alexrainman** [comment]
You can use ObservableCollection and as soon you: Insert, Remove, Clear, Move or Replace, the UI will refresh. Dont know whats the issue you are having.

As i mentioned in the other thread, the control keeps at least 3 pages in memory and also caches them in iOS and saves its state in Android.
