### ISSUE TITLE
iOS: Crash due to disposed objects when jumping back and forth

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#143]
I don't know whether this was introduced recently since I'm mainly developing on Android, but I noticed that if I jump back and forth with the carousel using the index (not swiping, so I can jump from page 4 back to 1 etc), it pretty quickly crashes. ~~If I just swipe, it seems to be ok as far as I can tell.~~ Swiping also causes the issue eventually.

I noticed that if I remove a page so that I only have three pages, I can't seem to reproduce the issue. Is this some page recreating issue maybe (you dispose one and then try to access it)?

Object name: 'ScrollViewRenderer'.
Foundation.NSObject.get_SuperHandle()NSObject2.cs:423
UIKit.UIView.RemoveFromSuperview()UIView.g.cs:1396
Xamarin.Forms.Platform.iOS.Platform.DisposeModelAndChildrenRenderers(Element view)
Xamarin.Forms.Platform.iOS.Platform.HandleChildRemoved(object sender, ElementEventArgs e)
Xamarin.Forms.Element.OnDescendantRemoved(Element child)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Element.OnDescendantRemoved(Element child)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Element.OnChildRemoved(Element child)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.OnChildRemoved(Element child)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnInternalRemoved(View view)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
System.Collections.ObjectModel.ObservableCollection<T>.OnCollectionChanged(NotifyCollectionChangedEventArgs e)<dfac2ad8ae7c42209218a908c3070036>:0
System.Collections.ObjectModel.ObservableCollection<T>.OnCollectionChanged(NotifyCollectionChangedAction action, object item, int index)<dfac2ad8ae7c42209218a908c3070036>:0
System.Collections.ObjectModel.ObservableCollection<T>.RemoveItem(int index)<dfac2ad8ae7c42209218a908c3070036>:0
System.Collections.ObjectModel.Collection<T>.Remove(T item)<2f4074c3120b4d80802e10af84b67d41>:0
Xamarin.Forms.Layout.OnInternalAdded(View view)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
System.Collections.ObjectModel.ObservableCollection<T>.OnCollectionChanged(NotifyCollectionChangedEventArgs e)<dfac2ad8ae7c42209218a908c3070036>:0
System.Collections.ObjectModel.ObservableCollection<T>.OnCollectionChanged(NotifyCollectionChangedAction action, object item, int index)<dfac2ad8ae7c42209218a908c3070036>:0
System.Collections.ObjectModel.ObservableCollection<T>.InsertItem(int index, T item)<dfac2ad8ae7c42209218a908c3070036>:0
System.Collections.ObjectModel.Collection<T>.Add(T item)<2f4074c3120b4d80802e10af84b67d41>:0
Xamarin.Forms.TemplateUtilities.OnContentChanged(BindableObject bindable, object oldValue, object newValue)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, BindableObject.SetValueFlags attributes, bool silent)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, BindableObject.SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.ApplyCore(object sourceObject, BindableObject target, BindableProperty property, bool fromTarget)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.Apply(object sourceObject, BindableObject target, BindableProperty property)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Binding.Apply(object newContext, BindableObject bindObj, BindableProperty targetProperty)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.ApplyBindings(bool skipBindingContext)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, object oldvalue, object newvalue)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, BindableObject.SetValueFlags attributes, bool silent)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, BindableObject.SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValue(BindableProperty property, object value, bool fromStyle, bool checkAccess)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValue(BindableProperty property, object value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.set_BindingContext(object value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
CarouselView.FormsPlugin.iOS.CarouselViewRenderer.CreateViewController(int index)<077f63f4957e4ec0b1125ab4fc0ac241>:0
CarouselView.FormsPlugin.iOS.CarouselViewRenderer.SetCurrentPage(int position)<077f63f4957e4ec0b1125ab4fc0ac241>:0
CarouselView.FormsPlugin.iOS.CarouselViewRenderer.OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)<077f63f4957e4ec0b1125ab4fc0ac241>:0
<Module>.invoke_void_object_PropertyChangedEventArgs(object, PropertyChangedEventArgs)(wrapper delegate-invoke)
Xamarin.Forms.BindableObject.OnPropertyChanged(string propertyName)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Element.OnPropertyChanged(string propertyName)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, BindableObject.SetValueFlags attributes, bool silent)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, BindableObject.SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.ApplyCore(object sourceObject, BindableObject target, BindableProperty property, bool fromTarget)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.Apply(bool fromTarget)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.BindingExpressionPart.<PropertyChanged>b__47_0()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Foundation.NSAsyncActionDispatcher.Apply()NSAction.cs:163
UIKit.UIApplication.UIApplicationMain(int, string[], intptr, intptr)(wrapper managed-to-native)
UIKit.UIApplication.Main(string[] args, IntPtr principal, IntPtr delegate)UIApplication.cs:79
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)UIApplication.cs:63
Ridr.Client.iOS.Application.Main(string[] args)

**Comment by alexrainman** [comment]
Can you provide a repo? I think this has been introduced with a recent change i did to force some UI elements to be collected.

**Comment by alexrainman** [comment]
I cannot reproduce this under version 4.2.8. There was an issue in version 4.2.7, which version are you using?

**Comment by alexrainman** [comment]
I used my demo and i jumped back and fort from position 0 to 3 (4 pages) and it doesn't crash.

**Comment by hardcodet** [comment]
That's in 4.2.8. My carousel's ItemsSource is a collection of views, that are wrapped through an ItemTemplate. If you would dispose any of those (you mentioned that you only keep 3 pages alive in another thread), attempting to navigate back to one of those would explain the crash.

**Comment by alexrainman** [comment]
There's only one thing to remove related to "memory leak" fix. I will remove it and see how that goes.

**Comment by hardcodet** [comment]
I'll check back as soon as the update is online. My guess would be that you discard your views, and then recreate them through the ItemTemplate. However, since the actual data source is a collection of views, you would recreate the actual templatd view, but not the content.

So basically, with the template below, you are creating a new wrapper ContentView, but that wrapper's content would have been disposed.

            
            <DataTemplate x:Key="TabsItemTemplate">
                <ContentView Content="{Binding }" />
            </DataTemplate>

**Comment by alexrainman** [comment]
You got it :)

**Comment by hardcodet** [comment]
One could argue that this isn't much of a problem, and the developer (in this case me) should make sure this can't happen (e.g. not using an ItemTemplate). OTOH, it provides flexibility, and I would prefer if I could set a property that would prevent disposal an recreation altogether once a carousel page has been created for performance reasons. In any case, thanks for the quick replies!

**Comment by Hasanajouz** [comment]
i have same problem in ios while it works perfect in android.
i am trying to make custom tab page where each DataTemplate is different view.
so when i change position in code it crashes.

**Comment by alexrainman** [comment]
Will release a new version later today.

**Comment by alexrainman** [comment]
@hardcodet @Hasanajouz pls test version 4.2.9

**Comment by Hasanajouz** [comment]
I tested it it is still the same.
TabCarousel.ItemsSource = new List<DataTemplate>()
            {
                new DataTemplate(() => view1),
                new DataTemplate(() => view2),
                new DataTemplate(() => view3)
            };
then i change the position in code it will crash;

**Comment by alexrainman** [comment]
Then this is something else. Pls share a demo.

**Comment by Hasanajouz** [comment]
i will try to create small one

**Comment by Hasanajouz** [comment]
@alexrainman 
can you download this small deom please:
https://1drv.ms/u/s!AqIxNvwvtTGgrMhKV-I1pigcyBsh9g
you will find  three labels; pressing in each one of them will change the position, try pressing randomly on them and it will throw exception in ios

**Comment by hardcodet** [comment]
I just upgraded to the latest version - seems to be ok on my end now - thanks Alex! The only difference I see to Hasan's code would be that I declare the item template and view instances separately in XAML. Accordingly, my views are the ItemsSource, and the data template, is declared indepdendently. This might make a difference if you disposed and/or attempted re-apply the templates.

**Comment by Hasanajouz** [comment]
@alexrainman 
hi alex,
did you try the code i sent?

**Comment by Hasanajouz** [comment]
can you download this small deom please:
https://1drv.ms/u/s!AqIxNvwvtTGgrMhKV-I1pigcyBsh9g
you will find three labels; pressing in each one of them will change the position, try pressing randomly on them and it will throw exception in ios

Hi @alexrainman this sample still doesn't work in iOS even with the last version

**Comment by Hasanajouz** [comment]
{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Foundation.MonoTouchException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x10f431d70; frame = (0 0; 414 514.333); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x17202b5c0>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x10e36b410>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x10f460d20>.
Native stack trace:
	0   CoreFoundation                      0x000000018bb7eff8 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018a5e0538 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018bb7ef28 <redacted> + 0
	3   UIKit                               0x0000000191d2af50 <redacted> + 248
	4   UIKit                               0x0000000191d2ae48 <redacted> + 48
	5   UIKit                               0x0000000191d2aad0 <redacted> + 424
	6   Nolitz.UniQuiz.Mobile.iOS           0x0000000100e4f520 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSendSuper_IntPtr_intptr_intptr_intptr + 112
	7   Nolitz.UniQuiz.Mobile.iOS           0x0000000100daf228 UIKit_UIViewController_set_View_UIKit_UIView + 216
	8   Nolitz.UniQuiz.Mobile.iOS           0x0000000102573554 CarouselView_FormsPlugin_iOS_CarouselViewRenderer_CreateViewController_int + 3572
	9   Nolitz.UniQuiz.Mobile.iOS           0x0000000102572588 CarouselView_FormsPlugin_iOS_CarouselViewRenderer_SetCurrentPage_int + 728
	10  Nolitz.UniQuiz.Mobile.iOS           0x000000010256e57c CarouselView_FormsPlugin_iOS_CarouselViewRenderer_OnElementPropertyChanged_object_System_ComponentModel_PropertyChangedEventArgs + 4924
	11  Nolitz.UniQuiz.Mobile.iOS           0x00000001009ada0c wrapper_delegate_invoke__Module_invoke_void_object_PropertyChangedEventArgs_object_System_ComponentModel_PropertyChangedEventArgs + 204
	12  Nolitz.UniQuiz.Mobile.iOS           0x00000001004704ac Xamarin_Forms_BindableObject_OnPropertyChanged_string + 236
	13  Nolitz.UniQuiz.Mobile.iOS           0x0000000100592310 Xamarin_Forms_Element_OnPropertyChanged_string + 128
	14  Nolitz.UniQuiz.Mobile.iOS           0x00000001004750e4 Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_BindableObject_SetValueFlags_bool + 1764
	15  Nolitz.UniQuiz.Mobile.iOS           0x0000000100472f8c Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_BindableObject_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags + 2284
	16  Nolitz.UniQuiz.Mobile.iOS           0x00000001004749a8 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool + 984
	17  Nolitz.UniQuiz.Mobile.iOS           0x000000010046fd4c Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object + 124
	18  Nolitz.UniQuiz.Mobile.iOS           0x00000001023cdefc CarouselView_FormsPlugin_Abstractions_CarouselViewControl_set_Position_int + 172
	19  Nolitz.UniQuiz.Mobile.iOS           0x0000000101090534 Nolitz_UniQuiz_Mobile_Pages_ProfilePage___ctorb__2_0_Nolitz_UniQuiz_Mobile_Views_ProfileTabHeaderView_int + 132
	20  Nolitz.UniQuiz.Mobile.iOS           0x00000001003aa854 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	21  Nolitz.UniQuiz.Mobile.iOS           0x00000001026212f0 mono_jit_runtime_invoke + 836
	22  Nolitz.UniQuiz.Mobile.iOS           0x000000010269a14c do_runtime_invoke + 112
	23  Nolitz.UniQuiz.Mobile.iOS           0x000000010269d8c0 mono_runtime_try_invoke_array + 1092
	24  Nolitz.UniQuiz.Mobile.iOS           0x0000000102660630 ves_icall_InternalInvoke + 652
	25  Nolitz.UniQuiz.Mobile.iOS           0x000000010020e3b0 wrapper_managed_to_native_System_Reflection_MonoMethod_InternalInvoke_System_Reflection_MonoMethod_object_object___System_Exception_ + 128
	26  Nolitz.UniQuiz.Mobile.iOS           0x000000010020e4b4 System_Reflection_MonoMethod_Invoke_object_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo + 148
	27  Nolitz.UniQuiz.Mobile.iOS           0x0000000100201dcc System_Reflection_MethodBase_Invoke_object_object__ + 60
	28  Nolitz.UniQuiz.Mobile.iOS           0x00000001004fbfc8 Xamarin_Forms_MessagingCenter_Subscription_InvokeCallback_object_object + 1352
	29  Nolitz.UniQuiz.Mobile.iOS           0x00000001004fa504 Xamarin_Forms_MessagingCenter_InnerSend_string_System_Type_System_Type_object_object + 1252
	30  Nolitz.UniQuiz.Mobile.iOS           0x0000000101113400 Xamarin_Forms_MessagingCenter_Send_TSender_REF_TArgs_INT_TSender_REF_string_TArgs_INT + 288
	31  Nolitz.UniQuiz.Mobile.iOS           0x000000010101bdcc Nolitz_UniQuiz_Mobile_Views_ProfileTabHeaderView_SelectTab_int_bool + 748
	32  Nolitz.UniQuiz.Mobile.iOS           0x000000010101bed4 Nolitz_UniQuiz_Mobile_Views_ProfileTabHeaderView_personal_OnTabbed_object_System_EventArgs + 132
	33  Nolitz.UniQuiz.Mobile.iOS           0x00000001004a1bc4 Xamarin_Forms_TapGestureRecognizer_SendTapped_Xamarin_Forms_View + 612
	34  Nolitz.UniQuiz.Mobile.iOS           0x0000000100cf8b54 Xamarin_Forms_Platform_iOS_EventTracker__c__DisplayClass12_0__GetNativeRecognizerb__0_UIKit_UITapGestureRecognizer + 644
	35  Nolitz.UniQuiz.Mobile.iOS           0x0000000100df539c UIKit_UITapGestureRecognizer_Callback_Activated_UIKit_UITapGestureRecognizer + 44
	36  Nolitz.UniQuiz.Mobile.iOS           0x00000001003aa854 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	37  Nolitz.UniQuiz.Mobile.iOS           0x00000001026212f0 mono_jit_runtime_invoke + 836
	38  Nolitz.UniQuiz.Mobile.iOS           0x000000010269a14c do_runtime_invoke + 112
	39  Nolitz.UniQuiz.Mobile.iOS           0x000000010269a0a8 mono_runtime_invoke + 208
	40  Nolitz.UniQuiz.Mobile.iOS           0x000000010259d9a0 _ZL31native_to_managed_trampoline_85P11objc_objectP13objc_selectorPP11_MonoMethodP22UITapGestureRecognizerj + 464
	41  Nolitz.UniQuiz.Mobile.iOS           0x000000010259d7c4 -[__UITapGestureRecognizer target:] + 60
	42  UIKit                               0x00000001922828d0 <redacted> + 64
	43  UIKit                               0x0000000192286104 <redacted> + 124
	44  UIKit                               0x0000000191e400b4 <redacted> + 252
	45  UIKit                               0x0000000191ce1fc4 <redacted> + 720
	46  UIKit                               0x00000001922763a8 <redacted> + 988
	47  UIKit                               0x0000000192275f78 <redacted> + 404
	48  UIKit                               0x0000000192275224 <redacted> + 268
	49  UIKit                               0x0000000191ce0350 <redacted> + 3164
	50  UIKit                               0x0000000191cb0f80 <redacted> + 340
	51  UIKit                               0x00000001924aaa20 <redacted> + 2400
	52  UIKit                               0x00000001924a517c <redacted> + 4268
	53  UIKit                               0x00000001924a55a8 <redacted> + 148
	54  CoreFoundation                      0x000000018bb2d42c <redacted> + 24
	55  CoreFoundation                      0x000000018bb2cd9c <redacted> + 540
	56  CoreFoundation                      0x000000018bb2a9a8 <redacted> + 744
	57  CoreFoundation                      0x000000018ba5ada4 CFRunLoopRunSpecific + 424
	58  GraphicsServices                    0x000000018d4c5074 GSEventRunModal + 100
	59  UIKit                               0x0000000191d15c9c UIApplicationMain + 208
	60  Nolitz.UniQuiz.Mobile.iOS           0x0000000100e5c6f4 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 340
	61  Nolitz.UniQuiz.Mobile.iOS           0x0000000100dfc02c UIKit_UIApplication_Main_string___intptr_intptr + 44
	62  Nolitz.UniQuiz.Mobile.iOS           0x0000000100dfbfec UIKit_UIApplication_Main_string___string_string + 172
	63  Nolitz.UniQuiz.Mobile.iOS           0x0000000100107784 Nolitz_UniQuiz_Mobile_iOS_Application_Main_string__ + 164
	64  Nolitz.UniQuiz.Mobile.iOS           0x00000001003aa854 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	65  Nolitz.UniQuiz.Mobile.iOS           0x00000001026212f0 mono_jit_runtime_invoke + 836
	66  Nolitz.UniQuiz.Mobile.iOS           0x000000010269a14c do_runtime_invoke + 112
	67  Nolitz.UniQuiz.Mobile.iOS           0x000000010269d370 do_exec_main_checked + 152
	68  Nolitz.UniQuiz.Mobile.iOS           0x0000000102605b4c mono_jit_exec + 268
	69  Nolitz.UniQuiz.Mobile.iOS           0x00000001027667e0 xamarin_main + 2148
	70  Nolitz.UniQuiz.Mobile.iOS           0x00000001025ac660 main + 96
	71  libdyld.dylib                       0x000000018aa6959c <redacted> + 4

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:319 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/runtime/Delegates.generated.cs:126 
  at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) ObjCRuntime.Messaging:void_objc_msgSendSuper_IntPtr (intptr,intptr,intptr)
  at UIKit.UIViewController.set_View (UIKit.UIView value) [0x00040] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:2729 
  at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.CreateViewController (System.Int32 index) [0x0019b] in <ce918892c84847dc8677549c144314bb>:0 
  at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.SetCurrentPage (System.Int32 position) [0x00069] in <ce918892c84847dc8677549c144314bb>:0 
  at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x002e6] in <ce918892c84847dc8677549c144314bb>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00012] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.BindableObject+SetValueFlags attributes, System.Boolean silent) [0x000fb] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.BindableObject+SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at CarouselView.FormsPlugin.Abstractions.CarouselViewControl.set_Position (System.Int32 value) [0x00000] in <0a222a95bbe4473b97a18f653d2620ee>:0 
  at Nolitz.UniQuiz.Mobile.Pages.ProfilePage.<.ctor>b__2_0 (Nolitz.UniQuiz.Mobile.Views.ProfileTabHeaderView header, System.Int32 i) [0x00001] in <be083c011e62471baa092e2a30aff2ad>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00046] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:313 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/reflection/methodbase.cs:229 
  at Xamarin.Forms.MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args) [0x00076] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x00069] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.MessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00013] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Nolitz.UniQuiz.Mobile.Views.ProfileTabHeaderView.SelectTab (System.Int32 t, System.Boolean fromswip) [0x00054] in <be083c011e62471baa092e2a30aff2ad>:0 
  at Nolitz.UniQuiz.Mobile.Views.ProfileTabHeaderView.personal_OnTabbed (System.Object sender, System.EventArgs e) [0x00001] in <be083c011e62471baa092e2a30aff2ad>:0 
  at Xamarin.Forms.TapGestureRecognizer.SendTapped (Xamarin.Forms.View sender) [0x0003b] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0 
  at Xamarin.Forms.Platform.iOS.EventTracker+<>c__DisplayClass12_0.<GetNativeRecognizer>b__0 (UIKit.UITapGestureRecognizer r) [0x00045] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.iOS\EventTracker.cs:94 
  at UIKit.UITapGestureRecognizer+Callback.Activated (UIKit.UITapGestureRecognizer sender) [0x00000] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIGestureRecognizer.cs:211 
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at Nolitz.UniQuiz.Mobile.iOS.Application.Main (System.String[] args) [0x0001b] in D:\UQ\Nolitz.UniQuiz.Mobile\Nolitz.UniQuiz.Mobile\Nolitz.UniQuiz.Mobile.iOS\Main.cs:24 }
