### ISSUE TITLE
iOs carousel.position is always 0 in  PositionSelected event

### ISSUE THREAD

**Issue by Hasanajouz** [alexrainman/CarouselView#145]
private void PositionSelected(object sender, int i)
        {
               int x=myCarousel.Position;
        }

is always giving 0 in iOs works fine in android

**Comment by alexrainman** [comment]
Which version are you using? That's not possible. I tested right now and both myCarousel.Position and position parameter are the same and match the selected item/page.

**Comment by alexrainman** [comment]
It should be something in your code.

**Comment by nikolaybedrov** [comment]
I also just tested it and is working properly for me too.
Why don't you just use the int i parameter?

**Comment by Hasanajouz** [comment]
strange i am sure about it i tested it in version 4.2.8 4.2.7 4.2.6

i will test again and tell you exactly when it is happening
thanks
