### ISSUE TITLE
iOS: Slow swipe towards center of next page does not trigger a new Position

### ISSUE THREAD

**Issue by twentytwokhz** [alexrainman/CarouselView#146]
Using Version 4.2.7 with the iOS renderer source code
On iOS when you swipe to the next page without letting go of the finger..
and drag until the next item appears in the middle you will see that in code the Position remains unchanged.
I debugged a bit and found that on PageController_DidFinishAnimating
the e.Finished is true..but the e.Completed is false 👎 
Not sure how can this happen since the animation should have completed when I let go of the finger from the screen.

It seems as if..maybe.. when you drag to the next position exactly where the animation SHOULD land..the event is not considered as completed? No idea what's happening here

**Comment by alexrainman** [comment]
Maybe i will use e.Finished

**Comment by alexrainman** [comment]
I am using e.Finished.

**Comment by alexrainman** [comment]
Version 4.2.9

**Comment by twentytwokhz** [comment]
Will try with 4.2.9 on monday

**Comment by alexrainman** [comment]
Any luck?

**Comment by twentytwokhz** [comment]
Tried it with latest 4.2.9 version and my specific code for the renderer. Still happens that when you slow swipe in a two item carousel control the selection is not triggered correctly..I mean for position.

**Comment by twentytwokhz** [comment]
PageController_DidFinishAnimating does not always trigger when doing a very slow swipe with the next item getting exactly in center. And even when I received e.Finished=true.. the e.Completed was false and the position that was computed was the old position:

        ```
void PageController_DidFinishAnimating(object sender, UIPageViewFinishedAnimationEventArgs e)
        {
            if (e.Finished)
            {
                var controller = (ViewContainer)pageController.ViewControllers[0];
                var position = Source.IndexOf(controller.Tag);
                isSwiping = true;
                Element.Position = position;
                prevPosition = position;
                isSwiping = false;
                SetIndicators();
                Element.PositionSelected?.Invoke(Element, position);

                CleanupChildViewControllers();
            }
        }
```

**Comment by alexrainman** [comment]
What do you mean by `with the next item getting exactly in center`?

**Comment by twentytwokhz** [comment]
So..I finally found the problem, and it's something deep inside the Xamarin iOS and maybe a bug from Apple related to the UIPageViewController not reporting the position correctly and consistently.
Here you can find some references:
https://stackoverflow.com/questions/8400870/uipageviewcontroller-return-the-current-visible-view
As pointed in the solution
https://stackoverflow.com/questions/22795883/disable-bounce-effect-in-uipageviewcontroller
"In that situation, every solution I've seen so far goes past the bounds of page 0. The core problem is that the underlying API is broken, and begins reporting a content offset relative to page 0 without calling our callback to let us know that it is showing a different page. Throughout this process, the API still claims to be showing page 1, going towards page zero even while it is really on page zero going towards page -1."

**Comment by alexrainman** [comment]
The thing is the bounce effect cannot be disabled or you cannot swipe between pages.
