### ISSUE TITLE
Attention ! CarouselView with twoimage conent bug

### ISSUE THREAD

**Issue by nfq6612** [alexrainman/CarouselView#147]
If there are only two pictures int  CarouselView conent ,when Left and right sliding it will unable change position.See Attach gif

.
![1](https://user-images.githubusercontent.com/21963633/26959994-72dabab6-4d06-11e7-877a-6551f3778880.gif)

**Comment by alexrainman** [comment]
Android?

**Comment by alexrainman** [comment]
This work for me.

**Comment by alexrainman** [comment]
It works both Android and iOS, is your problem in UWP?

**Comment by nfq6612** [comment]
in Android

**Comment by alexrainman** [comment]
Not happening to me.
