### ISSUE TITLE
Page Indicators on Top

### ISSUE THREAD

**Issue by fetbi** [alexrainman/CarouselView#149]
Is there a way to get the page indicators on top when the orientation is in Horizontal mode?

**Comment by alexrainman** [comment]
Not supported yet. I will add it to my roadmap.

**Comment by fetbi** [comment]
I've got it working for Android and UWP on my fork.  I haven't tested for IOS yet.
https://github.com/fetbi/CarouselView

**Comment by ruisilva450** [comment]
Any news on this?
@fetbi solution for this seems pretty straight forward.

**Comment by alexrainman** [comment]
Its not as straightforward as you think.
