### ISSUE TITLE
Carousel item is changed when scrolling on listview

### ISSUE THREAD

**Issue by Rocket567** [alexrainman/CarouselView#150]
I have a list view where in each item I have a carouselView that displays a set of images.  The issue is where the first item has a list of 8 images and the 4th item has 3 images. When I swipe the 1st line item to the last image then scroll to the 4th line item and swipe to the last image. if I scroll back to the top the 1st item will be at image number 3 instead of the last image. this Issue also happens in reverse scroll to the 4th item and swipe to the 3rd image then scroll to the top the carousel will be on the 3rd image. 

 
Here's My Xaml
[LocationSelectionPage.txt](https://github.com/alexrainman/CarouselView/files/1068717/LocationSelectionPage.txt)

and screen shots showing the indicators 
![1stitemonlastimage](https://user-images.githubusercontent.com/25143761/27042829-b662e39a-4f5d-11e7-9e97-be7d78654117.PNG)
![4thitemthatonlyhas3images](https://user-images.githubusercontent.com/25143761/27042833-b9e83114-4f5d-11e7-826b-3f985bc5a036.PNG)
![1stitemnowon3rdimage](https://user-images.githubusercontent.com/25143761/27042838-bc6aeba2-4f5d-11e7-8ebd-2159e1773af8.PNG)

**Comment by alexrainman** [comment]
My advice: don't use a ListView. Use a Nested carousel. Take a look at this repo: https://github.com/alexrainman/NestedCarouselView

**Comment by Rocket567** [comment]
I tried this approach and it creates more issues than it fixes. 
- I loose smooth scrolling now I have to swipe once for each item in the list. I can have up to 100 items in my list
- I have to tap on the nested carousel before any image is viewable 
- Once the 1st item is off screen by a few items and I scroll back to it. It is defaulted back to image number one not the image I left it on.  (I'm not a fan of this but I can live with it) 

Your control is great and any help is much appreciated

**Comment by alexrainman** [comment]
Up to 100 items? Tap on nested carousel? To keep the position of each carousel use a binding to a property in your model.

**Comment by Rocket567** [comment]
I could have up to 100 vehicles come back in my search and each vehicle will have anywhere from 1 to 10 images. 

No images are shown until I tap on the carousel. Once I tap then app images for that vehicle are shown in the carousel. 
![noimage](https://user-images.githubusercontent.com/25143761/27058326-13d64246-4f96-11e7-81ec-4fe9d2f2fc44.PNG)

 **TAP**
![images](https://user-images.githubusercontent.com/25143761/27058346-4dc55596-4f96-11e7-9eeb-b9a2db18af8d.PNG)

Every item has to be tapped to see the images. Which is not what my users will want. 

I'll try binding the position but using a ViewModel would the best approach be to use an event?

**Comment by alexrainman** [comment]
About the images not appearing, that should be your own issue. The carousel works fine w images.

**Comment by Rocket567** [comment]
No doubt the control works with images it only stopped working correctly when I added the nested carousel. I'm having issues getting the PositionSelected event to work since its the nested item that I need the event on. Any suggestions or sample code? 

I think I've been looking at it for too long today. I'll try again tomorrow with a fresh pair of eyes.

**Comment by alexrainman** [comment]
Did you take a look at the repo i sent? Nested carousel works with no issues. In the other hand, i never tested carousel inside a ViewCell on a ListView. It's strange use scenario :)

**Comment by alexrainman** [comment]
https://github.com/alexrainman/CarouselView/issues/151

**Comment by Rocket567** [comment]
I did and that's what gave me the scrolling issue and images not displaying issue. I reverted back to the listview approach and got the PositionSelected event working but there isn't much I can do with it. I'm basically back to my original issue. I've move on to something else right now and will circle back to this in a few days.

**Comment by JimSEOW** [comment]
@Rocket567 @alexrainman 
I tried the nested Carousel example: Great!!!!

Carouselview within ViewCell of ListView is not trivial . Will be great to see a partially working demo to help in debugging.

**Comment by alexrainman** [comment]
Please, try the latest version. There's a fix for on iOS that can make things like these to work.
