### ISSUE TITLE
CarouselView within a ListView

### ISSUE THREAD

**Issue by JimSEOW** [alexrainman/CarouselView#151]
Can this be done? 
I need only 20% of the ViewCells to be replaced with a CarouselView
The rest e.g. 80% of the ViewCells to be replaced by a Frame with Grids
https://github.com/xamarin/Xamarin.Forms.CarouselView/issues/29

FYI: I have read that you discouraged CarouselView within the ListView. Interested to learn more Why NOT?

**Comment by long-nguyentien** [comment]
We want this feature too! please.

**Comment by alexrainman** [comment]
Carousel works if you embed a ListView inside a page. I never tested it in the other way around. I never embed a Carousel in a ViewCell. I will need to run some tests.

**Comment by JimSEOW** [comment]
Similar types of [request](https://github.com/alexrainman/CarouselView/issues/197)
