### ISSUE TITLE
BUG: ViewGroup in ToAndroid Extension is null  

### ISSUE THREAD

**Issue by tombby11** [alexrainman/CarouselView#152]
Hello there in [ViewExtensions](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/ViewExtensions.cs) line 18 
   `  var viewGroup = vRenderer.ViewGroup;`  returns null , and thus getting null exception , I have fixed this isse in my local machine by updating xamarin.forms to the latest (currenly preview) and replaced the line with 
`var viewGroup = vRenderer.View`
and the method would return `global::Android.Views.View`

**Comment by alexrainman** [comment]
I cannot reproduce this with current stable version of Forms. Can you provide a demo project?

**Comment by tombby11** [comment]
sure [Here](https://github.com/alexrainman/CarouselView/files/1074667/DemoCourselViewProblem.zip) you have it with Xamarin.Forms **NON** stable (i.e. preview 3) 


And this one [here](https://github.com/alexrainman/CarouselView/files/1074754/DemoCourselViewProblem.zip) is with latest **stable** one .

**Comment by alexrainman** [comment]
I downloaded the stable one. No crash at all.

**Comment by alexrainman** [comment]
The NON stable one crashes. It seems they changes ViewGroup to View.

**Comment by alexrainman** [comment]
So, this is basically a Xamarin.Forms 2.3.5 issue.

**Comment by hardcodet** [comment]
Yup, Xamarin might have introduced a breaking change there. You probably already found it, but for other devs visiting here, see under "important notes":

https://forums.xamarin.com/discussion/93181/pre-release-xamarin-forms-2-3-5-253-pre5/p1
Deprecation: Android IVisualElementRenderer.ViewGroup is now obsolete. Please use View instead.

**Comment by mattrichnz** [comment]
Interesting, testing with XF 2.3.5.255-pre5 we are also getting a crash on Android.
When popping a page off the stack which contains a CarouselView, we get the following exception:

**Cannot access a disposed object.
Object name: 'Android.Graphics.Bitmap'.**

Stack trace is:
```
object.314d4935-71e8-4cc9-9725-728480311ca2( arg0,  arg1,  arg2) in 
Java.Interop.JniPeerMembers.AssertSelf(Android.Graphics.Bitmap self) in 
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualInt32Method(string encodedMember, Android.Graphics.Bitmap self, Java.Interop.JniArgumentValue* parameters) in 
Android.Graphics.Bitmap.get_Height() in 
Xamarin.Forms.Platform.Android.ButtonDrawable.Draw(Android.Graphics.Canvas canvas) in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\PageContainer.cs:23
Android.Graphics.Drawables.Drawable.n_Draw_Landroid_graphics_Canvas_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) in 
object.314d4935-71e8-4cc9-9725-728480311ca2( arg0,  arg1,  arg2) in 
```

This exception doesn't occur on XF 2.3.4.

**Comment by alexrainman** [comment]
Xamarin is changing some stuff in 2.3.5 and i will have to run some tests.

**Comment by mattrichnz** [comment]
Thanks @alexrainman. Don't worry, further investigation shows the disposed exception is not related to CarouselViewFormsPlugin but rather was a regression between XF 2.3.5-pre3 to 2.3.5-pre5.

**Comment by mattrichnz** [comment]
Currently testing 4.4.1 with XF 2.3.5-pre6 and all is working fine.
