### ISSUE TITLE
CarouselView within a scrollview

### ISSUE THREAD

**Issue by long-nguyentien** [alexrainman/CarouselView#153]
Hello, I'd like to ask if anyone has experience in using CarouselView inside a vertical scrollview? I want to put a carousel of images inside a vertical scrollview. Currently only scrollview reacts to my scroll event, and I can not swipe horizontally 😞. Please help.

**Comment by alexrainman** [comment]
No need to use the Carousel inside a vertical ScrollView.The Carousel supports vertical swiping already. Just use `orientation=Vertical` and you are good to go.
