### ISSUE TITLE
Possible memory leak in 4.2.9

### ISSUE THREAD

**Issue by PendulumJames** [alexrainman/CarouselView#154]
[Demo attached](https://github.com/alexrainman/CarouselView/files/1075761/CarouselTest.zip), tested on Android but have experienced crashes on iOS in a project using the same principles.

Continuously swiping through a carousel with an ItemSource containing 100 view models, each slide showing a custom view, a view is being created for each slide but never released from memory. Views are being recreated even when going back to slides previously seen. This is causing the amount of memory being used to increase indefinitely.

Running my demo on Android and observing the debug log, you can see that when the app is running low on memory, the garbage collector tries to clean up and the memory in use is shown. I was going to add images to the demo but since I could see the problem without them, I wanted to show you that images aren't causing the issue (you just need to swipe through all the slides and maybe back a few too to trigger the garbage collection). Although this very small app is unlikely to crash, on another app I'm building with each custom view having multiple images and running on a low-memory device, it quickly crashes with an out-of-memory exception after swiping through only a small number of slides.

I think this might be related to #125 but I'm no Xamarin nor C# expert so my coding or understanding might be wrong.

Let me know if you need any more information. Any advice would be greatly appreciated, thanks!

**Comment by alexrainman** [comment]
I applied some fixes in previous versions to fix this but they were causing crashes on fast scrolling.

**Comment by hardcodet** [comment]
Seeing this with a carousel and only four items. I added a map control to the carousel pages, and after swiping back and forth a few times, things get laggier, and the map seems to be recreated all the time. Still would love to see a switch to keep pages in memory once they were created to prevent that :)

**Comment by alexrainman** [comment]
I am trying a fix, lets see if works.

**Comment by alexrainman** [comment]
HA i think i fixed this thing :)

**Comment by alexrainman** [comment]
UIPageViewControllers keep a ghost list of ViewControllers used to facilitate smooth swiping and it controls internally how many of them there. When its not a custom View, like Maps, ChildViewControllers keep growing and not matter if i force Dispose them the custom views stay in memory.

What i am doing different? Well, instead of creating a new controller when swiping, i return it if exist in ChildViewControllers (the ghost UIViewControllers list that UIPageViewController keeps in code behind). I am also disposing the UIViews when Dispose is automatically called by UIPageViewController in my ViewContainer implementation.

It seems to work like a charm. Will release a new version as soon as i fix another important issue.

**Comment by hardcodet** [comment]
That's iOS only, right? (I noticed the laggyness and map recreation on Android.)

**Comment by alexrainman** [comment]
Thats completelly normal in Android. Its the way the ViewPager works, unless i create something like iOS to keep a ghost collection of pages which i dont recommend.

**Comment by alexrainman** [comment]
In Android i implemented SaveState before but code is commented because it's never called. Will try to something about it, which is the right way.

**Comment by hardcodet** [comment]
Btw, a related idea - let me know if you want me to create a feature request:

I was thinking that it might be helpful if the view and/or view model of the pages could implement an optional interface which would tell them when they are being activated or deactivated. That might allow developers to delay complex operations, or do cleanup accordingly. This would be easy to implement for you I guess, and similar to MVVM frameworks, where initialization code of your view/vm is often super important.

**Comment by alexrainman** [comment]
This is the only fix that works:

The problem:

To facilitate smooth swiping, UIPageViewController keeps a ghost copy of the pages in a collection named ChildViewControllers. This collection is handled internally by UIPageViewController to keep a maximun of 3 items, but when a custom view is used from Xamarin.Forms side, the views hang in memory and are not collected no matter if internally the UIViewController is disposed by UIPageViewController.

Fix explained:

Some code has been added to GetPreviousViewController and GetNextViewController to return a child controller of exists in ChildViewController. Also Dispose has been implemented in ViewContainer to release the custom views. Dispose is called in the finalizer thread (UI) so the code to release the views from memory has been wrapped in InvokeOnMainThread.

Releasing a new version.
