### ISSUE TITLE
CarouselView not functionnal/display on ios.

### ISSUE THREAD

**Issue by vlafargue** [alexrainman/CarouselView#155]
Hello,

I try to implement a CarouselView with your nuget package. The carousel is fully functionnal on Android But on my iOS project it doesn't work. Nothing appears on the screen, only my background color. I don't understand why. If some one have an idea ?

My package is already install everywhere.

**Comment by alexrainman** [comment]
You need to call Init() in your iOS project.

**Comment by vlafargue** [comment]
Okay i'm gonna try but i don't even call init on android project.

**Comment by alexrainman** [comment]
Somehow Android works without calling Init()

**Comment by vlafargue** [comment]
Thanks fir the answer. But this is my AppDelegate file and still have the problems on IOS.

using System;
using System.Collections.Generic;
using System.Linq;

using Foundation;
using UIKit;
using CarouselView.FormsPlugin.iOS;

namespace AnorraReload.iOS
{
	// The UIApplicationDelegate for the application. This class is responsible for launching the 
	// User Interface of the application, as well as listening (and optionally responding) to 
	// application events from iOS.
	[Register("AppDelegate")]
	public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
	{
		//
		// This method is invoked when the application has loaded and is ready to run. In this 
		// method you should instantiate the window, load the UI into it and then make the window
		// visible.
		//
		// You have 17 seconds to return from this method, or iOS will terminate your application.
		//
		public override bool FinishedLaunching(UIApplication app, NSDictionary options)
		{
			global::Xamarin.Forms.Forms.Init ();
            CarouselViewRenderer.Init();

            LoadApplication(new AnorraReload.App ());

			return base.FinishedLaunching (app, options);
		}
	}
}

**Comment by vlafargue** [comment]
I put the init()  function in the iOS project and Android project and now my carousel view of Android crash my app and the view of iOS as not change

**Comment by vlafargue** [comment]
Does I have to use ObservableCollection instead of list ? or this is optionnal ?

**Comment by alexrainman** [comment]
I really don't know whats the issue you are having unless you share a demo project.

**Comment by vlafargue** [comment]
If you succed to run this part of my code. I already add the init function on my AppDelgate file and MainActivity. I have the last version of Xamarin Forms and the last one of your plugin. I use an SDK similutaor who run a version android 7.1 - API25 and tfor IOS an iphone 6 on ios10.

I don't know if have some problems of compatibility with others plugins, or version.

My XAML:
```
             xmlns:CarouselControl="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
/*some code like title and ting*/
  <ScrollView>
        <StackLayout>
            <Label Text="Product Name" HorizontalOptions="Center" TextColor="Black"/>

            <CarouselControl:CarouselViewControl x:Name="CarousselPictures" ItemsSource="{Binding ProductImages}" IndicatorsTintColor="DarkGray" CurrentPageIndicatorTintColor="Black" ShowIndicators="True"  Position="{Binding Position}" BackgroundColor="Aqua" HeightRequest="{Binding Width}">
                <CarouselControl:CarouselViewControl.ItemTemplate>
                    <DataTemplate>
                        <Image Source="{Binding PicUri}" Aspect="AspectFit" HorizontalOptions="FillAndExpand"/>
                    </DataTemplate>
                </CarouselControl:CarouselViewControl.ItemTemplate>
            </CarouselControl:CarouselViewControl>

        </StackLayout>
    </ScrollView>
```


My CS:
    ```
    public class ProductImage
        {
            public string PicUri { get; set; }
        }
        public ObservableCollection<ProductImage> ProductImages { get; set; }

      public ProductDetailPage()
        {
            ProductImages = new ObservableCollection<ProductImage>
            {
                new ProductImage() {PicUri = "https://media/catalog/product/8/0/8051-34876.jp" },
                new ProductImage() {PicUri = "https://media/catalog/product/8/0/8051-34876.jpg" },
                new ProductImage() {PicUri = "https://media/catalog/product/8/0/8051-34876.jp" },
                new ProductImage() {PicUri = "https://media/catalog/product/8/0/8051-34876.jp" },

            };
            BindingContext = this;
           }
```

**Comment by vlafargue** [comment]
EDIT: This code works perfectly in a project start from from scratch. So I have to search the conflict.

**Comment by alexrainman** [comment]
Good to know :)

**Comment by vlafargue** [comment]
Thanks a lot for the repsonse and your time
