### ISSUE TITLE
allow ItemsSource to contain Views

### ISSUE THREAD

**Issue by fschwiet** [alexrainman/CarouselView#159]
Given a scenario where the cost to create/destroy a view is more significant than the cost of just creating the views once upfront, I'd like to be able to include Views in the ItemsSource instead of DataTemplates.

  I did a spike on this, it seems to work: https://github.com/fschwiet/CarouselView/tree/itemssource-as-views.  I don't have a deep understanding of the codebase so maybe this would cause problems in other places (maybe some view-caching mechanism will get confused).

  People will run into problems if they try to bind the same views to different carousels, in that case they should use DataTemplates.

**Comment by fschwiet** [comment]
As a side question, would all these changes make it into https://github.com/xamarin/Xamarin.Forms/pull/853 or a later version of Xamarin.Forms someday?  

A further off and hypothetical concern, any idea of Mac support will happen someday?

**Comment by alexrainman** [comment]
I guess i can easily support Views as ItemsSource.

**Comment by JimSEOW** [comment]
@fschwiet @alexrainman  Does that mean we could have "nested" CarasoulView using the MyTabbedpage.xaml as an example?

**Comment by fschwiet** [comment]
@JimSEOW   I don't know.

**Comment by JimSEOW** [comment]
@fschwiet I tried, only background colour.

**Comment by fschwiet** [comment]
I hit some binding problem using a private build of my spike of View support.  Tomorrow I will try to repro with the test project to understand whats going on, but I wanted to give a heads up.  The binding is using a reference binding ( Model="{Binding BindingContext.Something.PlotModel, Source={x:Reference ParentControl}}) and the reference binding works if I use a DataTemplate...  so I'm not sure what is up yet.

I will try to setup a repro in the Demo project tomorrow, but wanted to mention in now.

**Comment by JimSEOW** [comment]
@fschwiet Xamarin Forms team always concern of performance. While developers like to push the limit of the Xamarin Forms technology that is conceptually logical. LottieUWP is currently hitting this performance limit. However, the Mobile hardware keeps getting faster. So, there is nothing wrong but creative to keep testing the logical concept. If a view would work, so should the rest of control based on the View.

=> I have tried both versions of Carouselview (both Xamarin and Alex), no luck in embedding the carouselview inside the ViewCell of a ListView. In both cases, outside ListView under same XF PCL works fine. It would be great if your work would reveal the limitations of existing approach.

**Comment by alexrainman** [comment]
@fschwiet @JimSEOW i have been busy as you guys have been talking here :)

Don't know yet when the control will make it to a Xamarin.Forms release but as that happens, i keep maintaining it and making it better.

As part of the next release, i am going to add Views as ItemsSource support, which is actually really easy. I am trying to solve another issues https://github.com/alexrainman/CarouselView/issues/129 and https://github.com/alexrainman/CarouselView/issues/138 in that release but maybe i release what i have before that.

**Comment by alexrainman** [comment]
@fschwiet your code is kind of close to what i am doing but i am facing an issue in iOS that i have to figure it out before being able to release this functionality.

**Comment by fschwiet** [comment]
Thanks Alex.  I would like to test the VIews in ItemSource with my current project.  When you've had a chance to try it, if its not something thats released right away I'd appreciate it if you could push it to a private branch or something so I can try it out.

**Comment by alexrainman** [comment]
This works on Android and UWP like a charm but i have an issue in iOS that i think i cannot solved as i tried all my ideas.

**Comment by fschwiet** [comment]
I'm trying to work through some issues on my side...  Do you have a private branch so I could experiment with the iOS issue?

**Comment by fschwiet** [comment]
The problems I'm running into are with regards to data-binding in the views...  I guess what I'm really looking for is a layout control that does the carousel behavior while letting me defines the carousel panes in XAML.  Still trying to make that work though.

**Comment by alexrainman** [comment]
This control supports actually what you are looking for. You can define the panes in separated files and load them w a TemplateSelector or you can define the ItemsSource as DataTemplates completelly in xaml and if i make it work, it will support a List of Views as ItemsSource.

**Comment by fschwiet** [comment]
Hmm is there an example of that in the Demo app?  I couldn't make it work without a wrapper class.

Not so much wanting the child views in separate views, I'm looking for an example where the panes are defined as Xaml children.

**Comment by alexrainman** [comment]
Yeah theres an example.

**Comment by alexrainman** [comment]
Found the way to support a List<View> as ItemsSource in iOS and i was super simple :)

**Comment by fschwiet** [comment]
>>  Yeah theres an example.

Reviewing the demo, I couldn't find the example.  I think there is some misunderstanding.

**Comment by alexrainman** [comment]
Yeah, you are right. It used to be. It was deleted when i changed ItemsSource to support ObservableCollection. The thing is i couldn't find the way to declare INumerable ItemsSource in XAML.

**Comment by JimSEOW** [comment]
@alexrainman keep it up. Thanks for persisting to support user's requests

**Comment by alexrainman** [comment]
@JimSEOW @fschwiet with the next update im going to release today, the control will support declaring everything in XAML, like this:

```
<cv:CarouselViewControl BindingContext="{Binding Person}">
    <cv:CarouselViewControl .ItemsSource>
           <x:Array Type="{x:Type View}>

                    <!-- Page1 Display Photo -->
                    <Image Source="{Binding PhotoUrl}"/>

                    <!-- Page2 Display Bio -->
                    <Label FormattedString="{Binding Bio}"/>

                    <!-- Page2 Display contact information -->
                    <Label FormattedString="{Binding Info}"/>

           </x:Array>
    </cv:CarouselViewControl .ItemsSource>
</cv:CarouselViewControl >
```

With each element inside the array rendered as a page :)

**Comment by JimSEOW** [comment]
@alexrainman  I saw the Xamarin Forms Milestones, your control is on track to be included. Congratulation!

**Comment by alexrainman** [comment]
Where did you see that?

**Comment by JimSEOW** [comment]
**[Est Q3 2017](https://forums.xamarin.com/discussion/85747/xamarin-forms-feature-roadmap/p1)**
CarouselView v1 Stable
Stability and performance improvements. See[ PR](https://github.com/xamarin/Xamarin.Forms/pull/853).
