### ISSUE TITLE
incompatible with .NETStandard,Version=v1.6.

### ISSUE THREAD

**Issue by bbl-Laobu** [alexrainman/CarouselView#162]
I was wondering if or when support for .net Standard was planned? 

Right now when installing the nugget I get the following error:
One or more packages are incompatible with .NETStandard,Version=v1.6.
Incompatible packages: 1
Package restore failed. Rolling back package changes for 'SlideAnimatedCustomBack.Shared'.

**Comment by EdenCerberus** [comment]
Hi, You can download the source code here and add the needed targets and compile it. I, for example, downloaded the projects and added them to my solution for easier debugging.

Hope this helps a bit.

**Comment by alexrainman** [comment]
I havent targeted .Net standards just yet and i think i won't do it as the control is targeted to be included in Xamarin.Forms 3.0

**Comment by nazgul87** [comment]
@EdenCerberus  I Think that for now, that's the most acceptable solution.

Thanks
