### ISSUE TITLE
MVVM support

### ISSUE THREAD

**Issue by predalpha** [alexrainman/CarouselView#164]
Hi Alex,

back again, still developping using your control ;)

Are there any properties to bind command or event for positionSelected with your Carousel control ?
I would like to use the carousel in a more MVVM way. 
It can be usefull when we have to reload some navigation menu when we change position on the Carousel.

Will you plan to develop that or maybe i havent found it ?

Regards

**Comment by alexrainman** [comment]
In previous versions it was possible to bind PositionSelected, but i have to change it EventHandler so i can invoke it from each platform renderer. After that, no more binding option. Instead you need to assign it in code behind with a delegate ```myCarousel.PositionSelected += PositionSelected;```

**Comment by predalpha** [comment]
Thank you alex. 
I can use it that way but could be an interesting feature in order to avoid making code in page codebehind (if it is not too difficult to implement).
