### ISSUE TITLE
100+ FlipViewItem in UWP instead of 5

### ISSUE THREAD

**Issue by matteobortolazzo** [alexrainman/CarouselView#167]
Hi, in UWP my view takes 20 seconds to display.
Using the VS profiler I've found that 100+ FlipViewItem are created instead of 5.
On iOS and Android everything works fine.

`<carousel:CarouselView ItemsSource="{Binding Media}" VerticalOptions="Start" HeightRequest="240"
                    BackgroundColor="{StaticResource BackgroundColor}"
                    ItemTemplate="{StaticResource MediaDataTemplateSelector}" />`

`<ResourceDictionary>
            <DataTemplate x:Key="ImageTemplate">
                <forms:CachedImage  LoadingPlaceholder="placeholder.jpg" ErrorPlaceholder="placeholder.jpg" HorizontalOptions="FillAndExpand" Aspect="AspectFill" DownsampleToViewSize="True" Source="{Binding Url}" />
            </DataTemplate>
            <DataTemplate x:Key="VideoTemplate">
                <Grid >
                    <forms:CachedImage HorizontalOptions="FillAndExpand" Aspect="AspectFill" DownsampleToViewSize="True" Source="{Binding Url}" />
                    <Image Source="icon_play.png" HeightRequest="48" HorizontalOptions="Center" VerticalOptions="Center" >
                        <Image.GestureRecognizers>
                            <TapGestureRecognizer
                                Tapped="PlayTapped"
                                NumberOfTapsRequired="1" />
                        </Image.GestureRecognizers>
                    </Image>
                </Grid>
            </DataTemplate>
            <helpers:MediaDataTemplateSelector x:Key="MediaDataTemplateSelector" 
                ImageTemplate="{StaticResource ImageTemplate}" VideoTemplate="{StaticResource VideoTemplate}" />
        </ResourceDictionary>`

 
    public class MediaDataTemplateSelector : DataTemplateSelector
    {
        public DataTemplate ImageTemplate { get; set; }
        public DataTemplate VideoTemplate { get; set; }

        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            switch (((AppMedia)item).Type)
            {
                case ApplicationMediaType.Unknown:
                case ApplicationMediaType.Banner:
                case ApplicationMediaType.Image:
                    return ImageTemplate;
                case ApplicationMediaType.Video:
                    return VideoTemplate;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
    }
![cattura](https://user-images.githubusercontent.com/15217470/27741004-13dfbd54-5db4-11e7-88cf-ffa09af70f43.PNG)

**Comment by alexrainman** [comment]
Can you provide a repo? I am curious how is this happening.

**Comment by matteobortolazzo** [comment]
I'm so sorry I opened the issue in the wrong repo. I was using Xamarin's CarouselView. I tried yours and It works perfectly. Your solution saved me!! Thanks and sorry again.

**Comment by matteobortolazzo** [comment]
I'm so sorry I opened the issue in the wrong repo. I was using Xamarin's CarouselView. I tried yours and It works perfectly. Your solution saved me!! Thanks and sorry again.
