### ISSUE TITLE
iOS:  Not all items are loaded when user can start swiping

### ISSUE THREAD

**Issue by IanCaz** [alexrainman/CarouselView#169]
Xamarin Forms/XAML

I'm loading 20-30 items into a CarouselView.  As soon as the page comes up, if the user swipes right (moving to lower items) then it appears that some are missing & it skips 5-6 pages.  If the user swipes left first (going to higher items) they are fine, also if they then swipe right, the lower values are there as well.

I'm trying to create a "test project" that shows my issue, but it's taking more time than I thought it would & I figured I'd put this out there in case you had already seen this behavior.

**Comment by alexrainman** [comment]
As far as i can tell, this is not possible. Please share a repo project.

**Comment by IanCaz** [comment]
Okay, don't mean to sound like an idiot, but what do you mean "repo project"?

**Comment by alexrainman** [comment]
No worries. I mean a demo that reproduces the issue. Thanks

**Comment by IanCaz** [comment]
Okay, I'm still trying to get a scaled down version of my project working (since building from the ground up didn't reproduce the problem).

In the meantime, I found out if I change Position="{Binding Position}" to Position="5" (or any number) then the problem goes away.

**Comment by IanCaz** [comment]
Okay, I've got a scaled down project that reproduces the problem I'm seeing.  Unfortunately, I can't seem to attach the ZIP file to this comment.  What is the "normal way" people submit these projects?

**Comment by johnnysbug** [comment]
@IanCaz you can shrink the zip size by deleting the `packages` folder contents and your `bin` and `obj` folders. I think the limit in attachment size is 10MB

**Comment by IanCaz** [comment]
Thanks @johnnysbug for the input!  Ah well, it still won't let me attach it.

**Comment by IanCaz** [comment]
@alexrainman were you able to access that project I posted?

**Comment by alexrainman** [comment]
Sorry, i just saw it. Will take a look.

**Comment by alexrainman** [comment]
@IanCaz you reported this for iOS but your demo is only Android. It happens on Android also?

**Comment by IanCaz** [comment]
Nope, this problem is iOS only.  I just re-downloaded my solution and I'm showing the 3 projects (Portable, Android & iOS).  This is a Visual Studio 2017 project, if that makes a difference?

**Comment by alexrainman** [comment]
The problem is packages.config is missing in the iOS project.

**Comment by IanCaz** [comment]
I'm not sure what happened to that file, but it existed on my base application.  I've included it & re-uploaded the project.  

I've also posted a video showing the behavior I'm seeing:  https://youtu.be/PY7pChMOiWY

**Comment by alexrainman** [comment]
A very weird issue. Will run some tests later today.

**Comment by IanCaz** [comment]
Hey man, was just wanting to check in to see if you had a chance to look at this any more?

**Comment by alexrainman** [comment]
I am running your code and i can confirm the issue but i don't know what is causing it. Will add your code to my repo and see deeply to see whats the issue.

**Comment by alexrainman** [comment]
I am out of ideas about why you are facing this issue. Cannot figure it out. Same thing works on other scenarios.

**Comment by alexrainman** [comment]
I found the solution for your problem. The thing is you are assigning the ItemsSource before assigning the position, so with a little change in your code, everything works as supposed to work:

```
ObservableCollection<Operation> ocOps = await GetStaticOperations();
//AlertOperations = ocOps;

//AlertOperations = lstOps;
if (ocOps.Count == 0)
{
	//no operations returned
	Errors = string.Format("No records returned for order {0}.", currAlert.Order_No);
}
else
{
	//got operations
	Operation opCurr = ocOps.Where(op => op.Operation_No == currAlert.Operation).FirstOrDefault();
	Position = ocOps.IndexOf(opCurr);
        AlertOperations = ocOps; // Assign ItemsSource after assigning Position
}
```

This is required only at startup.
