### ISSUE TITLE
Failed to resolve assembly: 'CarouselViewControl.FormsPlugin.Abstractions, Culture=neutral, PublicKeyToken=null' 

### ISSUE THREAD

**Issue by DottorPagliaccius** [alexrainman/CarouselView#17]
Hi, lastest stable version of Xamarin Studio, Xf version 2.3.2.127, I can't use CarouselViewControl in xaml page, I get 

Failed to resolve assembly: 'CarouselViewControl.FormsPlugin.Abstractions, Culture=neutral, PublicKeyToken=null' 

(if I use compiled xaml)

or

Could not load file or assembly 'CarouselViewControl.FormsPlugin.Abstractions' or one of its dependencies

(at runtime)

Bye,
Dottor Pagliaccius

**Comment by alexrainman** [comment]
Android or iOS?

**Comment by DottorPagliaccius** [comment]
pardon, iOS

**Comment by alexrainman** [comment]
Did you update to latest Xamarin.iOS?

**Comment by DottorPagliaccius** [comment]
Of course, all components are up to date, stable channel. The issue happens when compiling the PCL project only (if I use compiled xaml)

**Comment by alexrainman** [comment]
The issue must be on your end because i can compile and run the demo with latest Xamarin update and latest XCode. There's a confirmed bug on Xamarin.Android 7, you must downgrade to previous version.

**Comment by alexrainman** [comment]
By the way, i add [assembly: XamlCompilation (XamlCompilationOptions.Compile)] at Application level and not in the page.

**Comment by SamVanCutsem** [comment]
How did you resolve this? I'm on the latest version of Xamarin.Forms (2.3.2.127) and CarouselViewControl version 2.3.0. I get the same error. Also Xaml Compilation is turned on.

**Comment by DottorPagliaccius** [comment]
I've resolved using a CarouselPage :/

**Comment by SamVanCutsem** [comment]
Found the issue. The used namespace in the ReadMe is wrong. It shoud be xmlns:controls="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions" instead of xmlns:controls="clr-namespace:CarouselView**Control**.FormsPlugin.Abstractions;assembly=CarouselViewControl.FormsPlugin.Abstractions"

**Comment by DottorPagliaccius** [comment]
Good to know (for the next time ;))

**Comment by alexrainman** [comment]
Let me fix the readme.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
