### ISSUE TITLE
NRE on iOS

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#173]
I got NREs on iOS since upgrading the control:

```
[ViewExtensions ToiOS(Xamarin.Forms.View view, CoreGraphics.CGRect size)]
System.NullReferenceException: Object reference not set to an instance of an object 

CarouselView.FormsPlugin.iOS.ViewExtensions.ToiOS(View view, CGRect size)<1ba1f337c4fc4193a21f593f958f7937>:0
CarouselView.FormsPlugin.iOS.CarouselViewRenderer.CreateViewController(int index)<1ba1f337c4fc4193a21f593f958f7937>:0
CarouselView.FormsPlugin.iOS.CarouselViewRenderer.SetNativeView()<1ba1f337c4fc4193a21f593f958f7937>:0
CarouselView.FormsPlugin.iOS.CarouselViewRenderer.Element_SizeChanged(object sender, EventArgs e)<1ba1f337c4fc4193a21f593f958f7937>:0
<Module>.invoke_void_object_EventArgs(object, EventArgs)(wrapper delegate-invoke)
Xamarin.Forms.VisualElement.SetSize(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.Layout(Rectangle bounds)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Grid.LayoutChildren(double x, double y, double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.UpdateChildrenLayout()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnSizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.<>c.<OnChildMeasureInvalidated>b__39_0()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Foundation.NSAsyncActionDispatcher.Apply()NSAction.cs:163
UIKit.UIApplication.UIApplicationMain(int, string[], intptr, intptr)(wrapper managed-to-native)
UIKit.UIApplication.Main(string[] args, IntPtr principal, IntPtr delegate)UIApplication.cs:79
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)UIApplication.cs:63
Ridr.Client.iOS.Application.Main(string[] args)
```

Edit: I can repro this reliably now on a page during initialization of the control. Works fine on Android.

**Comment by alexrainman** [comment]
Share a repro project please.

**Comment by hardcodet** [comment]
Hmm, I have no idea why it's crashing on one page but not on another. I'll try debugging it later, but will have to get and build your sources in order to get some debug symbols. (Would be nice if you could deploy them along with your package, at least during heavy development btw - that would make it much easier for reporters to help you triangulate issues).

**Comment by hardcodet** [comment]
Ok, PDBs for the win :). I compiled it locally and copied the debug symbols into my solution's package folder. It appears I still can't step into your code with VS for Mac, but at least I got a line number: #25 in iOS.ViewExtensions.cs:

    vRenderer.Element.Layout (size.ToRectangle());

This indicates that `Element `can be null without any checks. I did a quick hack and this indeed solved the issue:

    vRenderer.Element?.Layout(size.ToRectangle());

However, I guess that's not a good solution, and you should abort earlier (I'm just guessing though, I don't know the rendering pipeline). Hope that helps!

**Comment by hardcodet** [comment]
Ok, it seems I was too early. I only just saw that the carousel doesn't get another pass at rendering that page, so I end up without an exception, but also without content.

**Comment by hardcodet** [comment]
This seems to be somehow related to using a ScrollView in the mix, and it's super weird. If I wrap the carousel's content in a ScrollView with a red background, the ScrollView is actually rendered (screen turns red), but all its contents are gone (not rendered in the first place, or rendered outside of the screen).

This just affects the first tab. If I switch my page order, it's another page that doesn't get rendered, while my red scroll view's contents show up just fine on the second tab. In any case, the root cause is probably the null element reported above.

My dirty workaround for now is to wrap the ScrollView itself in a grid. Now, everything works like a charm again.

**Comment by alexrainman** [comment]
Well i advice not to wrap in ScrollView at all. Instead each page conteng should be wrapped in ScrollView.

**Comment by alexrainman** [comment]
Is this solved?

**Comment by alexrainman** [comment]
Can you share a repro project?

**Comment by hardcodet** [comment]
No repro, sorry - this is nested, in a custom control etc. Debugging it and finding the cause of the crash (null Element) is as far as I could go in this case, but I wouldn't know the root. I "solved" this with the Grid hack in my case. Feel free to close. As far as Scroll Views go: I think they are perfectly valid within a carousel. After all, I don't want to scroll my whole UI up and down, but the particular nested content within the carousel page.
