### ISSUE TITLE
Carousel page with MasterDetail page creates an Out of memory exception

### ISSUE THREAD

**Issue by Harshadcse** [alexrainman/CarouselView#174]
I have using Xamarin.Forms.CarouselView (2.3.0-pre2). this issue is happing in Android Only.

[MonoDroid] Java.Lang.OutOfMemoryError: Exception of type 'Java.Lang.OutOfMemoryError' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
[MonoDroid] at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0003b>
[MonoDroid] at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.d9739b70-6ef3-4aef-ac57-bdd7fa5679b5 (intptr,intptr) <IL 0x00011, 0x0001f>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.OutOfMemoryError
[MonoDroid] 	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
[MonoDroid] 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
[MonoDroid] 	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
[MonoDroid] 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:452)
[MonoDroid] 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:482)
[MonoDroid] 	at dalvik.system.NativeStart.run(Native Method)
[AndroidRuntime] Shutting down VM
[dalvikvm-heap] Clamp target GC heap from 99.873MB to 96.000MB
[dalvikvm-heap] Forcing collection of SoftReferences for 8305932-byte allocation
[dalvikvm-heap] Clamp target GC heap from 99.873MB to 96.000MB
[dalvikvm-heap] Out of memory on a 8305932-byte allocation.
[skia] --- allocation failed for scaled bitmap
[skia] --- allocation failed for scaled bitmap

**Comment by alexrainman** [comment]
It is known there's problem with MasterDetail and the carousel. Can you share a repro project?

**Comment by alexrainman** [comment]
Please, move to latest stable version of Xamarin.Forms

**Comment by 7lol** [comment]
I also had this crash, with stable forms, and plugin 4.4.0 on samsung SM-G800F

`FAILED TO ALLOCATE A 13086732 BYTE ALLOCATION WITH 2210568 FREE BYTES AND 2MB UNTIL OOM
dalvik.system.VMRuntime.newNonMovableArray VMRuntime.java
android.graphics.BitmapFactory.nativeDecodeAsset BitmapFactory.java
android.graphics.BitmapFactory.decodeStream BitmapFactory.java:856
android.graphics.BitmapFactory.decodeResourceStream BitmapFactory.java:675
android.graphics.BitmapFactory.decodeResource BitmapFactory.java:703
android.graphics.BitmapFactory.decodeResource BitmapFactory.java:733
android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray BitmapDrawable.java:779
android.graphics.drawable.BitmapDrawable.inflate BitmapDrawable.java:741
android.graphics.drawable.Drawable.createFromXmlInner Drawable.java:2551
android.graphics.drawable.LayerDrawable.inflateLayers LayerDrawable.java:254
android.graphics.drawable.LayerDrawable.inflate LayerDrawable.java:164
android.graphics.drawable.Drawable.createFromXmlInner Drawable.java:2551
android.graphics.drawable.Drawable.createFromXml Drawable.java:2322
android.content.res.Resources.loadDrawableForCookie Resources.java:4277
android.content.res.Resources.loadDrawable Resources.java:4156
android.content.res.Resources.getDrawable Resources.java:2045
com.android.internal.policy.PhoneWindow.generateLayout PhoneWindow.java:4658
com.android.internal.policy.PhoneWindow.installDecor PhoneWindow.java:4706
com.android.internal.policy.PhoneWindow.getDecorView PhoneWindow.java:2271
android.app.ActivityThread.handleResumeActivity ActivityThread.java:4353
android.app.ActivityThread.handleLaunchActivity ActivityThread.java:3426
android.app.ActivityThread.access$1100 ActivityThread.java:229
android.app.ActivityThread$H.handleMessage ActivityThread.java:1821
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:148
android.app.ActivityThread.main ActivityThread.java:7331
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1230
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1120`

**Comment by alexrainman** [comment]
What about latest version of the plugin?

**Comment by Harshadcse** [comment]
@alexrainman  - issue fixed.
