### ISSUE TITLE
How to load data details when we switch to next view

### ISSUE THREAD

**Issue by olivierclaude** [alexrainman/CarouselView#175]
Hello,

I'm trying to find the best solution to fetch data from server (to load more details) only when the user switch to the next-previous views.

For the moment, in the setter of my SelectedPhoto index property, I execute async call to my backend and then I notify changes. It's working fine but I'm not sure that is the best solution.

```
int selectedPhoto;
public int SelectedPhoto
{
	get { return selectedPhoto; }
	set
	{
		var selectedIndex = value;

		Device.BeginInvokeOnMainThread(async () =>
		{
			var photoDetails = await PhotoService.GetPhotoDetails(Medias[selectedIndex].Id);
			photoDetails.Annotations = photoDetails.Annotations ?? new System.Collections.ObjectModel.ObservableCollection<Annotation>();

			this.Medias[selectedIndex].Annotations = photoDetails.Annotations;
			this.Medias[selectedIndex].LikedBy = photoDetails.LikedBy;
                        OnPropertyChanged(nameof(Medias));
		});

		SetProperty(ref selectedPhoto, selectedIndex);
	}
}

public IncrementalLoadingCollection<Photo> Medias { get; private set; }
```

In the same context, on my view I can send a comment or a like to the server, but I'm not able to refresh the view to display data changes.

Thank you in advance for your help.
Olivier

**Comment by alexrainman** [comment]
You can use PositionSelected callback event for that.
