### ISSUE TITLE
Android support library update

### ISSUE THREAD

**Issue by Trivias91** [alexrainman/CarouselView#178]
The Android support libraries should be be updated to the newest version since CarouselView is targeting the newest version of Android.

**Comment by alexrainman** [comment]
Xamarin.Forms uses support library 23.3.0.

**Comment by Trivias91** [comment]
Hey Alex,

While it is true that Xamarin.Forms use to be locked into support library
23.3.0,  more recent versions, including the current stable version, that
can use MonoAndroid 7.0 can use support libraries greater than or equal to
23.3.0.  They are still locked into 23.3.0 however with MonoAndroid 1.0.
If you look here (https://www.nuget.org/packages/Xamarin.Forms/2.3.4.247
<https://www.nuget.org/packages/Xamarin.Forms/2.3.4.231>) at the Nuget
package you'll see this to be true.

Best Regards,

Travis
