### ISSUE TITLE
Reattaching views crashes on iOS

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#180]
This is the similar exception to the closed #93, I just ran into this myself. I think this happens if you add / remove / add a view to the carousel through a binding to an ObservableCollection. While removing the view from the collection renders the carousel properly, adding it to the collection again causes the issue, because it doesn't seem to have been detached completely from the hierarchy when it was removed:

`Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x156469b50; frame = (0 53.5; 375 549.5); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x17682db00>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x1564710b0>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x15499d200>.' `

**Comment by hardcodet** [comment]
Workaround in case anybody runs into this: I solved this simply by introducing an optional builder func for my Content. When I'm removing a carousel page, I reset the `Content` property, which then causes a view recreation if I'm adding the carousel page item again:

        /// <summary>
        /// Builder func that enables view recreation in case
        /// the tab's availability is being toggled. Just set
        /// the Content to null in order to trigger recreation
        /// when necessary.
        /// </summary>
        internal Func<object> ContentBuilder { get; set; }

        private object content;

        public object Content
        {
            get
            {
                if (content == null)
                {
                    content = ContentBuilder?.Invoke();
                }

                return content;
            }
            set => content = value;
        }
    }

**Comment by alexrainman** [comment]
I tested this without your workaround and it doesn't crash for me. I can add, remove, add the same view again without any problems.
