### ISSUE TITLE
Feature Request: Enable / disable swiping direction individually

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#181]
Small feature request - hope that would be easy given that you already have `IsSwipingEnabled`:

It would be a nice feature to instead have a `EnableSwipe` property or something with an enum here:

    public enum SwipeDirection
    {
        Both = 0,
        Left,
        Right,
        Disabled
    }

This would enable wizard style carousels (where you can control whether you can go back or to the next page) and other scenarios where we currently have to dynamically add/remove carousel pages in order to prevent swiping.

**Comment by alexrainman** [comment]
This will be extremely complicated and will require a lot of code refactoring. I will have it on mind but i don't know if i will be able to do it before Xamarin.Forms 3 release.
