### ISSUE TITLE
The event PositionSelected doesn't insert whenever i use double key TAB

### ISSUE THREAD

**Issue by andresgutice** [alexrainman/CarouselView#182]
Hi everyone, my problem is this, i want to catch whenever CarouselView change of item, according to
documentation i can use the event PositionSelected but Apparently this is not working for me, this is my code:
`mycarouser.PositionSelected +=`
The CarouselView i get it like x:Name mycarouser; As you can see it, that code doesn't allow me autocomplete using double key TAB for create the method when the item is selected.

Please tell me how can i use this event?

Thanks and sorry for my English :)

**Comment by alexrainman** [comment]
I don't what is your issue but you can add PositionSelected this way:

```
myCarousel.PositionSelected +=  PositionSelected;

public void PositionSelected (object sender, int position)
{
	Debug.WriteLine("Position " + position + " selected");
}
```

**Comment by andresgutice** [comment]
@alexrainman Thanks man, your response was helpful to me...

**Comment by andresgutice** [comment]
@alexrainman Hello again, what I want to do is a behavior that cature the event that tells me when the item changes the CarouselView, this is my code:

public class CarouselViewBehavior : Behavior< CarouselViewControl >
    {
        protected override void OnAttachedTo(CarouselViewControl bindable)
        {
            base.OnAttachedTo(bindable);
            bindable.PositionSelected += PositionSelected;
        }

        protected override void OnDetachingFrom(CarouselViewControl bindable)
        {
            base.OnDetachingFrom(bindable);
            bindable.PositionSelected -= this.PositionSelected;
        }

        void PositionSelected(object sender, int position)
        {
            var carousel = sender as CarouselViewControl;
            if (carousel != null)
            {
                //code
            }
        }
    }

Apparently when the application starts detecting this event for the first time, but after changing the item in the CarouselView does not continue to activate the event, I hope you help me friend
