### ISSUE TITLE
(Android) Does not re-measure its layout on Height Changed

### ISSUE THREAD

**Issue by JKennedy24** [alexrainman/CarouselView#184]
I have an absolute layout that takes up the whole screen which contains a carousel view (which contains a listview).
I then have a button that i press and this halves the height of the absolute layout (and subsequently carousel view)

But the view inside the carousel view does not remeasure itself meaning my listview does not re-evaluate whether scrolling should be enabled (i.e. when whole screen only half the listview on the screen is filled with items, hence no scroll enabled, when halfed now items are cut off so should enable scrolling but as carousel view does not re-measure itself scroll is not enabled).

If I look at [Android ](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs#L150)
I can see it doesnt relayout unless the `width` of the control changes

```
if (ElementWidth.Equals(rect.Width))
      return;
```

On [ios](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs#L181) it remeasures every time size has changes as long as `height > 0` which makes sense

**Comment by JKennedy24** [comment]
I notice that `ElementHeight` has been [commented out](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs#L154). To fix this possibly should it be:

```
if (ElementWidth.Equals(rect.Width) || ElementHeight.Equals(rect.Height))
      return;

ElementWidth = rect.Width;
ElementHeight = rect.Height;
```

**Comment by alexrainman** [comment]
Can you provide a sample code of the scenario you are using the Carousel?

**Comment by alexrainman** [comment]
If i do this change, then when soft keyboard appears, the entire thing will resize which is wrong.

**Comment by JKennedy24** [comment]
[CSSizeTest.zip](https://github.com/alexrainman/CarouselView/files/1180084/CSSizeTest.zip)

I've attached a sample.

Steps to reproduce:
1.  Click "Add to list button" untill you have over half the list full
2. Press the "Resize" button and that will half the size of the carousel view
3. the listview does not resize itself as the carousel has not resized so therefore scrolling is not enabled

I'd imagine this would be a problem for other controls inside a Carousel not just a list.

You say it would re-layout when the soft keyboard appears, I think that the carousel should re-layout when the keyboard appears. If the height or width of the carousel has changed then the content inside should also change regardless of why it changed

**Comment by alexrainman** [comment]
Yeah but then the input will lose focus and the keyboard will be gone.

**Comment by JKennedy24** [comment]
@alexrainman so from what I understand the problem comes when you click an Entry and it pops up the keyboard - which would resize the view and relayout the view and unfocus the Entry?

I dont think not resizing the View on Height changed is a solution for the Entry bug. I think it will cause more issues in the long run

**Comment by alexrainman** [comment]
Agree. Im trying to find a way to resize the view and focus the previously focused entry.

**Comment by JKennedy24** [comment]
I think that is the correct solution. I will have a think about it to and let you know if I get a solution to re-focusing the Entry after keyboard appeared

**Comment by alexrainman** [comment]
I just released a new version but a fix for this still not there as i have to handle a complicated scenario related to soft-keyboard.

**Comment by EmmanVazz** [comment]
I also have this issue. Waiting for the fix.

**Comment by alexrainman** [comment]
Updated in next release.
