### ISSUE TITLE
MemoryLeak and cause of potential errors when changing ItemsSource.

### ISSUE THREAD

**Issue by janniklind** [alexrainman/CarouselView#186]
When the Element changes, then the CarouselViewImplementation (Renderer) correctly subscribes on CollectionChanged events on the new ItemsSource and unsubscribes from the old one.

However when ItemsSource as a property on the existing Element changes (OnElementPropertyChanged), then the renderer on Android correctly subscribes to CollectionChanged events on the new ItemsSource, but forgets to unsubscribe from the old ItemsSource.

https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs#L218

https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs#L258

**Comment by alexrainman** [comment]
Is this affecting you?

**Comment by alexrainman** [comment]
Because i don't see any memory leaks.

**Comment by mmcarson** [comment]
Are you using the Xamarin Forms Image class? Because that has memory leaks on its own. We solved it by calling the garbage collector.

**Comment by alexrainman** [comment]
That's why i advice to use XFImageLoading.

**Comment by salamoun** [comment]
I'm find out similar problem on Android. 
When is set ImageSource, heap allocate memory, that is never released.
Whit FFImageLoading is problem smaller, but still, if I invalided FFImageLoading cache and then set new images to Carousel, still there is memory allocated that is never released.
