### ISSUE TITLE
On iOS, there was a crash

### ISSUE THREAD

**Issue by DataZhenLiu** [alexrainman/CarouselView#188]
When you swipe left to the right on the iOS platform, if you swipe a few more times, the app crashes。
And this is  the Bug detail : `*** Assertion failure in -[UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UIPageViewController.m:2083
2017-08-07 18:02:45.319 KKMobile.iOS[10984:173611] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
libc++abi.dylib: terminate_handler unexpectedly threw an exception`
[https://gyazo.com/93991c75c55953a1894b1ec4a5b21d69](url)

**Comment by alexrainman** [comment]
Can you provide a demo?

**Comment by DataZhenLiu** [comment]
Ok, I'll give you a demo as soon as I'm free.
