### ISSUE TITLE
How can i reach a view from code?

### ISSUE THREAD

**Issue by Hasanajouz** [alexrainman/CarouselView#189]
Hi,
I have this carousel 

<abstractions:CarouselViewControl x:Name="TabCarousel">
                    <abstractions:CarouselViewControl.ItemsSource>
                        <x:Array Type="{x:Type View}">
                                <views:v1 x:Name="v1" ></views:v1>
                                <views:v2></views:v2>
                        </x:Array>
                    </abstractions:CarouselViewControl.ItemsSource>
                </abstractions:CarouselViewControl>

how can i reach a public method in v1 from code behind?
when i try to use v1 anywhere in the code it will be null.

Thanks in advance.

**Comment by alexrainman** [comment]
?

**Comment by Hasanajouz** [comment]
for example: If there is a public function in view1 i want to call it after loading the carousel in a page
v1.publicfunction();
v1 will be always null

I don't know if you got my idea.
in other way:
there is a page and inside this page i am using CarouselViewControl
and in this CarouselViewControl i am giving names to the items.
How can i access those items from this page?
Is there a way to reach the CarouselViewControl items and cast them to the TYPE?

thanks.

**Comment by alexrainman** [comment]
((View)carousel.ItemsSource[0]).publicFunction()

**Comment by Hasanajouz** [comment]
@alexrainman thanks very much for the hint but for a correction it should be like this:
((View)carousel.ItemsSource.GetItem(0)).publicFunction()
because your answer will give this
Cannot apply indexing with [] to an expression of type 'IEnumerable<>

**Comment by alexrainman** [comment]
Yeah, you should use the extensions i provide :)
