### ISSUE TITLE
TapGestureRecognizer doesn't work when added to CarouselViewControl (Android)

### ISSUE THREAD

**Issue by abelgs1987** [alexrainman/CarouselView#191]
I'm facing the same problem as commented in issue #66 and even if the tapgesturerecognizer is on its parent, the tap event is not fired.
On iOS works well.
By the way, there is not an ItemTapped event yet as mentioned it would be in next release

**Comment by savageqm** [comment]
Found my issue.  On Android I was using a Custom button rendered that was using  Control.SetSingleLine.  replacing this with SetMaxLines solved my issue.

**Comment by abelgs1987** [comment]
Why have you closed it @alexrainman? The problem has not been solved. I have not any button or renderer. Just a layout (with tap gesture) containing a carousel with images. It is not working on Android.
