### ISSUE TITLE
[iOS] If a List View is in one of the Carousel View’s Views, and you push a page, on pop the List View will always scroll to the top

### ISSUE THREAD

**Issue by paulb39** [alexrainman/CarouselView#192]
Repo: https://www.dropbox.com/s/9kcdao17fmtyaek/HeaderTemplateBug.zip?dl=0   (ignore the name, I modified a different bug sample I had)
 
This bug is kind of hard to explain, but to reproduce, on an iOS device, scroll down to the last item in the list view, tap that item, then go back. Note that you are now scrolled to the top of the list view.

Because of bug 56072 (https://bugzilla.xamarin.com/show_bug.cgi?id=56072), to remove the tab bar when I push a page, I am adjusting the Page’s frame height on push/pop. If you comment out the NavCustomRenderer class where I am doing this, this bug does not occur.
 
So something is getting messed up when one of the Carousel View’s page’s height is changed. I originally thought that this was caused by bug 43947 (https://bugzilla.xamarin.com/show_bug.cgi?id=43947), but I can only reproduce this using the Carousel View.

Any help with this would be greatly appreciated, I was planning on releasing an app soon, but I don’t really want to release it without a workaround for this bug.

Thanks

**Comment by alexrainman** [comment]
Exactly, if you change the height of the page, the control will render again and each view will be rendered again, it's the normal behavior.

**Comment by paulb39** [comment]
@alexrainman But it works fine on Android, doesn't that make it a bug? Could you think of a workaround I could do?

**Comment by alexrainman** [comment]
Please, provide a demo project.

**Comment by paulb39** [comment]
Repro from above, https://www.dropbox.com/s/9kcdao17fmtyaek/HeaderTemplateBug.zip?dl=0

**Comment by paulb39** [comment]
@alexrainman apologies, didn't realize I didn't set up the Android part in the repro. 
Updated link: https://www.dropbox.com/s/x3js0ljf0ogfdyb/carousellistviewbug.zip?dl=0

**Comment by paulb39** [comment]
@alexrainman Any advice on this would be greatly appreciated. I spent all week on this and the only workaround I was able to come up with is to use ScrollTo on the list view when the detail page is popped, but that scrolls to the top and then down to the right cell, and it looks terrible.

Thanks

**Comment by paulb39** [comment]
@alexrainman Just wondering why this is now labeled cantfix? Is this a bug with Xamarin forms instead of this control? Thanks

**Comment by alexrainman** [comment]
It means i don't have a feasible way to fix it for now.

**Comment by alexrainman** [comment]
The problem with this is that the navigationbar is shared between pages so if you hide it in the second one, that will trigger the first page to resize the carousel control so the ListView is rendered again.

**Comment by paulb39** [comment]
@alexrainman Any idea why this issue isn't happening on Android? After the resize, is it not rendering the list view again for some reason? Also, if I just have the list view on the main page, without the carousel control, it works fine, if the issue is with the list view rendering again, shouldn't the issue occur that way as well?

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
