### ISSUE TITLE
Can't get carousel to show up

### ISSUE THREAD

**Issue by mmcarson** [alexrainman/CarouselView#193]
[CarouselFiles.zip](https://github.com/alexrainman/CarouselView/files/1202000/CarouselFiles.zip)
Here are my files. I do 
`var images = new List<string>();
            images.Add("https://pbs.twimg.com/profile_images/814155292778921986/RFwwHFm1.jpg");
            images.Add("https://pbs.twimg.com/profile_images/814155292778921986/RFwwHFm1.jpg");
            images.Add("https://pbs.twimg.com/profile_images/814155292778921986/RFwwHFm1.jpg");
            images.Add("https://pbs.twimg.com/profile_images/814155292778921986/RFwwHFm1.jpg");
            images.Add("https://pbs.twimg.com/profile_images/814155292778921986/RFwwHFm1.jpg");
            ImageArea.Children.Add(new ImageCarouselView(images));` 
and it does not work. Nothing shows up.

**Comment by shoeIT** [comment]
Hey mmcarson, I think you should provide more information how you try to use the controll. Do you use xaml and MVVM ? Where do you initialize the controll?
Did you follow the hints on the top page?
Why don't you use the example and alter the code to your needs?

**Comment by alexrainman** [comment]
ViewCell is not supported. Use ContentView instead. Make sure you are calling Init in each platform specific project.
