### ISSUE TITLE
I'm using the C# example and nothing shows up

### ISSUE THREAD

**Issue by mmcarson** [alexrainman/CarouselView#195]
`InitializeComponent();

			var myCarousel = new CarouselViewControl();
			myCarousel.ItemsSource = new ObservableCollection<int> { 1, 2, 3, 4, 5 }; // ADD/REMOVE PAGES FROM CAROUSEL ADDING/REMOVING ELEMENTS FROM THE COLLECTION
			//myCarousel.ItemTemplate = new MyTemplateSelector(); //
            myCarousel.ItemTemplate = new DataTemplate (typeof(MyView));
			myCarousel.Position = 0; //default
			myCarousel.InterPageSpacing = 10;
			myCarousel.Orientation = CarouselViewOrientation.Horizontal;

            Stack.Children.Add(myCarousel);`

**Comment by mmcarson** [comment]
I did do the Init on both projects.

**Comment by alexrainman** [comment]
Don't know whats the problem you are facing.

**Comment by helzgate** [comment]
@mmcarson I had the same issue.  But after 2 days I finally got a demo working.  I have no idea what exactly it was that was causing it not to work but at least you can look at my demo and maybe it will help you.  You can find it [HERE](https://github.com/helzgate/carouselview-example)

**Comment by mmcarson** [comment]
Thanks so much @helzgate for the example! I got it working and added images 😄
