### ISSUE TITLE
Children not resized properly in this edge case

### ISSUE THREAD

**Issue by mathiassoeholm** [alexrainman/CarouselView#196]
I ran into a problem, where at first I didn't suspect the CarouselView. But I can confirm that it doesn't occur without it.

I have a UI with a bar in the top. The bar's height gets smaller when the device changes to landscape mode. This is due to an orientation change of a stack layout that contains the two labels A and B.
A Grid takes care of resizing everything, because the first row is set to AUTO and the second is set to *. In the second row I have the following structure:

-CarouselViewControl
--Array
---ContentView
----ScrollView
-----StackLayout
------Labels

You can see in the screenshot, that when the device orientation changes to landscape, the scrollview is not big enough. This does not happen if the scrollview is simply placed within a ContenView, or nested directly in the Grid.

![screenshot_20170809-103159](https://user-images.githubusercontent.com/1747242/29112983-f93c06c8-7cef-11e7-907f-c97620545882.png)
![screenshot_20170809-103208](https://user-images.githubusercontent.com/1747242/29113019-1823abd6-7cf0-11e7-96c4-44177964b43b.png)

The two relevant files are here:
https://gist.github.com/mathiassoeholm/34c7f33443ca6a494747e6e75167ff1e

As you can see I have a ContentView tag around the ScrollView. This is of course unnecessary here, but this is the setup I had in my other project, and this is just a repro.
The funny thing is that if I remove this ContentView tag around the scroll view, everything works.

So it's like the resize operation is not being propegated to all the children or something like that. I'm not completely sure how it works though.

**Comment by alexrainman** [comment]
Having a ContentView around Scrollview is a wrong setup. If removing it solve your problem then do it.
