### ISSUE TITLE
[UWP] Adding an Item to the CarouselView Causes Exception when ShowIndicators = False

### ISSUE THREAD

**Issue by jommille** [alexrainman/CarouselView#198]
I just realized two days ago that Xamarin is dropping their CarouselView in favor of this one, so I made the switch, started testing, and ran into an issue in UWP. Android is working and iOS is untested. 

In UWP when I try to add an item to the CarouselView I am getting a NULL reference exception when ShowIndicators is set to false. On my project, when I set ShowIndicators to true, the issue goes away, which is a problem because I need this carousel to hold a few hundred items so I need to not have indicators. 

In the sample project that comes with the source it is for some reason happening for me no matter what I set ShowIndicators to. But, if you click on "Update Carousel" when the Carousel is visible, it will throw the exception on `Dots.Insert(position, CreateDot(position, Element.Position));` on the InsertPage method in the renderer. 

I tracked the root of the problem to be that SetIndicators()  only initializes Dots if ShowIndicators is set to true, but InsertPage attempts to update Dots regardless. 

The easiest fix that I see for it would be in the InsertPage method to add
`if(Element.ShowIndicators == true)`
before 
`Dots.Insert(position, CreateDot(position, Element.Position));` 

I should also add, that I just notice that the RemovePage method is also susceptible to a NULL reference exception for the exact same reason. 

Thank you for all the work you have done in creating this Carousel and getting it ready for integration into Xamarin.

**Comment by alexrainman** [comment]
Will fix this in next release.

**Comment by jommille** [comment]
Much appreciated.
