### ISSUE TITLE
Update on rotation

### ISSUE THREAD

**Issue by JoshuaNovak919** [alexrainman/CarouselView#2]
Is there a way to update the child views on rotation? Right now they seem to be stuck at the original size even if I rotate the device.

**Comment by alexrainman** [comment]
Yes, rotation works by default in iOS but, it wasn't on Android. I already fixed and i will push an update in a few minutes 👍

**Comment by alexrainman** [comment]
Done!

**Comment by alexrainman** [comment]
Fixes #2

**Comment by JoshuaNovak919** [comment]
@alexrainman Works perfect! Thanks!!!

**Comment by alexrainman** [comment]
Good. Be aware that the Carousel is under active development so, always update to the latest version. Thanks

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
