### ISSUE TITLE
TapGestureRecognizer doesn't work when added to CarouselViewControl (Android)

### ISSUE THREAD

**Issue by abelgs1987** [alexrainman/CarouselView#200]
I'm openning again this issue because it was closed (#191) without being solved
I'm facing the same problem as commented in issue #66 and even if the tapgesturerecognizer is on its parent, the tap event is not fired.
On iOS works well.
By the way, there is not an ItemTapped event yet as mentioned it would be in next release

**Comment by Cardinal-DeepSea-Blues** [comment]
I'm having this issue as well, still no idea what cause it

**Comment by ivanfenoy** [comment]
Any news of this issue? I'm having the same problem

**Comment by alexrainman** [comment]
I have this working already but it will work only with TapGestureRecognizer Command. Tapped EventHandler won't work because there's no way i can invoke it from native code:

```
var gesture = new TapGestureRecognizer();
gesture.Command = new Command((obj) => {
    Debug.WriteLine("tapped");
});

myCarousel.GestureRecognizers.Add(gesture);
```

**Comment by Cardinal-DeepSea-Blues** [comment]
tried above code, still can't get it working, please reconfirm it before you close this issue

**Comment by abelgs1987** [comment]
Again closed as #191 without a solution. On android it doesn't work.
The only workaround i have found is adding de tapgesture inside the template for each item in the carousel, which it is a bad practice (memory leak) and it should be the main control which handles the tap

**Comment by alexrainman** [comment]
Guys, let me release the fix first :)

**Comment by siuhleung7** [comment]
It was worked before by adding a transparent BoxView,
But I updated it to 4.4.4 it could not be worked anymore....

**Comment by alexrainman** [comment]
TapGesture is already supported by default. You don't need to add a BoxView to make it work.

**Comment by siuhleung7** [comment]
Sorry, It would not work and I don't know why..
It was worked perfectly before (added a BoxView).

Again, iOS always work perfectly but Android....

            <ListView ItemsSource="{Binding ListViewItemsGrouped}" ItemTapped="Handle_ItemTapped" ItemSelected="Handle_ItemSelected" HasUnevenRows="true" IsGroupingEnabled="true" GroupDisplayBinding="{Binding Key}" BackgroundColor="White">
                <ListView.Header>
                    <cv:CarouselViewControl x:Name="CarouselPromotion" Orientation="Horizontal" ItemsSource="{Binding Promotions}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" HeightRequest="170" IndicatorsShape="Circle" ShowIndicators="true">
                        <cv:CarouselViewControl.ItemTemplate>
                            <DataTemplate>
                                <ffimageloading:CachedImage Grid.RowSpan="2" Aspect="AspectFill" Source="{Binding ImageUrl}" DownsampleToViewSize="true" DownsampleHeight="170" />
                                <StackLayout Grid.Row="1" BackgroundColor="#80000000" Padding="12" IsVisible="{Binding HasTitle}">
                                    <Label TextColor="White" Text="{Binding Title}" FontSize="16" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" />
                                </StackLayout>
                            </DataTemplate>
                        </cv:CarouselViewControl.ItemTemplate>
                    </cv:CarouselViewControl>
                </ListView.Header>
----------------
            var gesture = new TapGestureRecognizer();
            gesture.Command = new Command<int>((obj) => {
                System.Diagnostics.Debug.WriteLine("Tapped with " + obj + " as parameter.");
            });
            gesture.CommandParameter = 1;

            CarouselPromotion.GestureRecognizers.Add(gesture);

**Comment by alexrainman** [comment]
Oh, your carousel is in the header of a ListView. Maybe the tap listener of that header is blockinh the tap recognizer you are adding.

**Comment by siuhleung7** [comment]
I tried to make it outside the ListView, the tap event still not fired. :(
Sad, I will try to rollback to previous setting. I will let you know why it happened.

Thanks so much :)

**Comment by alexrainman** [comment]
Try adding InputTransparent="True" to the ListView or the Header.

**Comment by alexrainman** [comment]
The binding of the ListView? This has to be something not related to the Carousel.

**Comment by siuhleung7** [comment]
No, I said empty carousel item.

I tried 4 cases:
1, Carousel inside ListView Header with Carousel items, Tap event not fired.
2, Carousel outside ListView Header with Carousel items, Tap event not fired.
3, Carousel inside ListView Header with empty Carousel, Tap event fired.
4, Carousel outside ListView Header with empty Carousel, Tap event fired.

I think isn't related to ListView at all..

**Comment by siuhleung7** [comment]
I temporary solved the problem by rolling back the:
Droid/xxx.Droid.csproj
Droid/packages.config

And then avoid update the **CarouselView.FormsPlugin** and **Xamarin.Forms** of Android project.

Keep the version:
  <package id="Xamarin.Forms" version="2.3.4.270" targetFramework="monoandroid71" />
  <package id="CarouselView.FormsPlugin" version="4.4.3" targetFramework="monoandroid71" />

then work fine again.

**Comment by ufuf** [comment]
Any luck getting this work?

**Comment by SandipAhluwalia** [comment]
As mentioned in #364, for people using v5.2.0 of the plugin, I resolved this issue by adding a tap gesture inside the data template, but still binding to one command property in the parent view model as follows:

        <cv:CarouselViewControl
            x:Name="myCarouselViewCtrl"
            ItemsSource="{Binding MyItems}"
            ShowArrows="true"
            ShowIndicators="true"
            Orientation="Horizontal">
            <cv:CarouselViewControl.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding Path=BindingContext.ViewItemsDetailsCommand, Source={x:Reference Name=myCarouselViewCtrl}}"
                                                  CommandParameter="{Binding}"/>
                        </Grid.GestureRecognizers>
                        <ffimageloading:CachedImage
                            Aspect="AspectFill"
                            DownsampleToViewSize="False"
                            FadeAnimationEnabled="True"
                            FadeAnimationForCachedImages="True"
                            Source="{Binding ImageUri}"
                            ErrorPlaceholder="error.png">
                            <ffimageloading:CachedImage.LoadingPlaceholder>
                                <OnPlatform x:TypeArguments="ImageSource">
                                    <On Platform="UWP">Assets/loadingplaceholder.png</On>
                                    <On Platform="Android, iOS">loadingplaceholder.png</On>
                                </OnPlatform>
                            </ffimageloading:CachedImage.LoadingPlaceholder>
                        </ffimageloading:CachedImage>
                    </Grid>
                </DataTemplate>
            </cv:CarouselViewControl.ItemTemplate>
        </cv:CarouselViewControl>

This solution works for both iOS and Android (and maybe even UWP - untested).

**Comment by crashnnburn** [comment]
You're a life saver @SandipAhluwalia that worked as expected. Had wasted a whole day trying to get this working. Thank you!
