### ISSUE TITLE
Using control implemented with a renderer

### ISSUE THREAD

**Issue by bremy** [alexrainman/CarouselView#202]
Is it possible to use in CarouselView, controls implemented by using a renderer?
I have in my project a CustomWebView using IOS and Android renderer, in particular to enable zoom in and zoom out on the web content.
Using it in a Carousel page, this control is never displayed, while a regular WebView has no issue (if HeightRequested and WidthRequest are setup). No problem has well to display Label, Image, ....

Do you think that could be a "renderer" issue?

thanks

**Comment by alexrainman** [comment]
If you provide a demo project maybe i can help.

**Comment by bremy** [comment]
Hi Alex. I got it working. So even using a component view with a renderer all is working nicely in a carasoul

BR

Envoyé de mon iPad

**Comment by alexrainman** [comment]
Great
