### ISSUE TITLE
Unhandled exception in UWP on version 4.4.1+

### ISSUE THREAD

**Issue by BurningAXE** [alexrainman/CarouselView#203]
On version 4.4.1 and 4.4.2 I get an unhandled exception in App.g.i.cs:
`#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif`

When I tweaked the exception breaking settings I reached somewhat deeper to uncover that it's actually:
> HRESULT E_FAIL has been returned from a call to a COM component.

This still gave me no clue as to where the problem was coming from but after lots of experimenting I found that if I downgrade CarouselView on UWP to 4.4.0 the problem disappears.
If you can't reproduce it I'll strip my project and send you a reproducible example.

**Comment by alexrainman** [comment]
No idea why is this happening but i will take a look.

**Comment by jommille** [comment]
I believe this is related to #138.

**Comment by alexrainman** [comment]
Could be. Im trying to fix another issue related to resizing. UWP sucks :)

**Comment by alexrainman** [comment]
Releasing a fix today.
