### ISSUE TITLE
Carousel doesn't render on iOS

### ISSUE THREAD

**Issue by Project4MobileDev** [alexrainman/CarouselView#206]
The carousel renders correctly on Android and UWP but the content within the DataTemplate doesn't render on iOS. I've attached a code example of the problem. 

[CarouselViewBugDemo.zip](https://github.com/alexrainman/CarouselView/files/1267042/CarouselViewBugDemo.zip)

**Comment by alexrainman** [comment]
Have you called Init() in AppDelegate?

**Comment by Project4MobileDev** [comment]
Ah that was it! Thanks very much :) 

Also I noticed on the roadmap that you're planning to add infinite scrolling (wrap around) at some point, is there any estimated date on that? Thanks again

**Comment by alexrainman** [comment]
As soon as im able to fix a critical issue with soft-keyboard then i will work on that.
