### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by 7lol** [alexrainman/CarouselView#208]
Hello,
i got memory leak on android when using CarouselView with FFImageLoading. I appears to not disposing page with image, so it wont release memory. When i got like 30 fullscreen images to swipe thru im getting OOM and then i got crash. 

Thats part of my view:
```
<CarouselViewControl ItemsSource="{Binding Leaflet.Pages}" x:Name="CarouselImages" HorizontalOptions="FillAndExpand"  VerticalOptions="FillAndExpand"  AnimateTransition="true" InterPageSpacing="10" Orientation="Horizontal" Position="{Binding Position}">
       <CarouselViewControl.ItemTemplate>
            <DataTemplate>
                <ContentView IsClippedToBounds="True">
                    <ContentView.Content>
                        <ffimageloading:CachedImage Source="{Binding Url}" Aspect="AspectFit" VerticalOptions="Center" HorizontalOptions="Center" DownsampleUseDipUnits="True" DownsampleToViewSize="true" LoadingPlaceholder="loading.png" ErrorPlaceholder="error.png" CacheDuration="{Binding CacheDuration}"/>
                    </ContentView.Content>
                </ContentView>
            </DataTemplate>
        </CarouselViewControl.ItemTemplate>
    </CarouselViewControl>
```

though its FFImageLoading fault, but its not since it work just fine with ListView. Original issue:  https://github.com/luberda-molinet/FFImageLoading/issues/708

**Comment by alexrainman** [comment]
Can you provide a demo?

**Comment by 7lol** [comment]
Here i got repro:
https://github.com/7lol/MemoryLeak

**Comment by alexrainman** [comment]
@7lol why are you using Xamarin.Forms pre-release 2.4.*? That's why you are having this issue. I downgraded your project to latest stable release, which the control is compatible with, and everything just work fine.

**Comment by Ruddy2007** [comment]
This is still a problem on the stable release 2.4.0.282.
