### ISSUE TITLE
NullReferenceException during creation if control is not visible.

### ISSUE THREAD

**Issue by Hangarspace** [alexrainman/CarouselView#21]
In my situation the carousel view control is not visible until the user taps a button, this raises an exception during creation. The control is within a <Frame> that has a bound IsVisible property. 

Easy to replicate using the projects demo app my making the simple change to MainPage.xaml....

<Frame IsVisible="false">
       <controls:CarouselViewControl x:Name="myCarousel" Orientation="Vertical" InterPageSpacing="10" PageIndicators="true" Grid.Row="0" Grid.Column="0" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />
</Frame>

Error :

System.NullReferenceException: Object reference not set to an instance of an object.
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.ButtonHide(FlipView f, String name)
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.FlipView_Loaded(Object sender, RoutedEventArgs e)

**Comment by alexrainman** [comment]
This will be a quick fix :)

**Comment by alexrainman** [comment]
Upcoming release.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
