### ISSUE TITLE
MyTabbedPage() showing blank carousel on iOS

### ISSUE THREAD

**Issue by cassionandi** [alexrainman/CarouselView#212]
Hi!
Just cloned the project to run all demons. When running MyTabbedPage() on iOS emulator iPhone 10.3, the carousel is empty as the screenshot shows. On Android it works.

<img width="380" alt="captura de tela 2017-09-13 as 14 17 41" src="https://user-images.githubusercontent.com/699167/30391114-ad204582-988e-11e7-8fab-b6f62e86393a.png">

**Comment by alexrainman** [comment]
Just change this vertical options of the carousel control: VerticalOptions="FillAndExpand"
