### ISSUE TITLE
Scroll percentage?

### ISSUE THREAD

**Issue by justjoeyuk** [alexrainman/CarouselView#214]
It would be super useful to know the percentage of the scroll, or at minimum the offset, when the user is moving between carousels.

For example, if I have 3 pages and I am on the first page and I'm half-way between scrolling to the second page, it would be nice to know I am around 15% of the total scroll capacity of the carousel view so I can animate that elsewhere.

**Comment by alexrainman** [comment]
How this will be useful?

**Comment by justjoeyuk** [comment]
In the case of being able to potentially animate other controls based of the scroll state. An example would be having a tab control + carousel. When I am scrolling the carousel, it would be great to animate the tab accent along with it, for a smoother look and feel. At the moment, everything is snappy.
