### ISSUE TITLE
Android - Not rendering page in Nested CarouselView when navigated 2 pages away

### ISSUE THREAD

**Issue by gklappe** [alexrainman/CarouselView#215]
On my project I have a CarouselView in a CarouselView, with custom pages. This sounds a bit inception like, but it works great and it's overall a pretty straighforward UI. 

However on Anddroid when I scroll 2 pages away and back on the parent CarouselView, let's say from the first page to the third page and back, the nested CarouselView does not render it's page. The paging indicators are rendered as well as the rest of pages, but the page itself not. But when the control is tapped or swiped the page is rendered. 

The first time on application load the page is rendered and everything works as expected, it is only after navigating away for 2 pages that the nested CarouselView does not display it's first page and only on Android. 

Any ideas for an Android workaround?

edit: I see now that this is maybe related to 157 and 129, which are both fixed. But those problems existed on multiple platforms and this only on Android, plus there was no nesting of carouselviews.

**Comment by alexrainman** [comment]
Please, check this 2 repos for a solution:

https://github.com/alexrainman/NestedCarouselView

https://github.com/alexrainman/TabbedCarouselView
