### ISSUE TITLE
Crashing hard on Android with latest XF 2.4.0.280

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#216]
The carousel works on my start page that has a carousel on it, but crashes the app when opening a new page that contains a carousel. Looking at the stack trace, I think there was an issue with the new XF version and ViewGroups, so that may be a breaking change in XF 2.4 and further.

Maybe the note at this ticket here is helpful?
From https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/issues/22
> This appears related to the deprecation of IVisualElementRenderer.ViewGroup in Android[1]. VisualElementTracker now accesses View instead of ViewGroup[2] and since PullToRefreshLayoutRenderer[3] has not implemented it, it throws a Java.Lang.AbstractMethodError.

Stack Trace:

`
Xamarin caused by: java.lang.AbstractMethodError
md5fa3be16b83ce3acd3be83265686c14de.CarouselViewRenderer_PageAdapter.n_instantiateItem(Native Method)
md5fa3be16b83ce3acd3be83265686c14de.CarouselViewRenderer_PageAdapter.instantiateItem()CarouselViewRenderer_PageAdapter.java:49
android.support.v4.view.ViewPager.addNewItem()ViewPager.java:1034
android.support.v4.view.ViewPager.populate()ViewPager.java:1248
android.support.v4.view.ViewPager.populate()ViewPager.java:1116
android.support.v4.view.ViewPager.onMeasure()ViewPager.java:1642
android.view.View.measure()View.java:21045
android.widget.RelativeLayout.measureChildHorizontal()RelativeLayout.java:715
android.widget.RelativeLayout.onMeasure()RelativeLayout.java:461
android.view.View.measure()View.java:21045
md5b60ffeb829f638581ab2bb9b1a7f4f3f.ViewRenderer_2.n_onLayout(Native Method)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.ViewRenderer_2.onLayout()ViewRenderer_2.java:47
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout()FormsViewGroup.java:28
md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout()VisualElementRenderer_1.java:72
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout()FormsViewGroup.java:28
md5270abb39e60627f0f200893b490a1ade.NavigationPageRenderer.n_onLayout(Native Method)
md5270abb39e60627f0f200893b490a1ade.NavigationPageRenderer.onLayout()NavigationPageRenderer.java:65
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout()FormsViewGroup.java:28
md5270abb39e60627f0f200893b490a1ade.MasterDetailContainer.n_onLayout(Native Method)
md5270abb39e60627f0f200893b490a1ade.MasterDetailContainer.onLayout()MasterDetailContainer.java:53
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
android.support.v4.widget.DrawerLayout.onLayout()DrawerLayout.java:1193
md5270abb39e60627f0f200893b490a1ade.MasterDetailPageRenderer.n_onLayout(Native Method)
md5270abb39e60627f0f200893b490a1ade.MasterDetailPageRenderer.onLayout()MasterDetailPageRenderer.java:68
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(Native Method)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout()PlatformRenderer.java:63
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
android.widget.RelativeLayout.onLayout()RelativeLayout.java:1079
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
android.widget.FrameLayout.layoutChildren()FrameLayout.java:323
android.widget.FrameLayout.onLayout()FrameLayout.java:261
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
android.widget.LinearLayout.setChildFrame()LinearLayout.java:1741
android.widget.LinearLayout.layoutVertical()LinearLayout.java:1585
android.widget.LinearLayout.onLayout()LinearLayout.java:1494
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
android.widget.FrameLayout.layoutChildren()FrameLayout.java:323
android.widget.FrameLayout.onLayout()FrameLayout.java:261
com.android.internal.policy.DecorView.onLayout()DecorView.java:887
android.view.View.layout()View.java:18798
android.view.ViewGroup.layout()ViewGroup.java:5951
android.view.ViewRootImpl.performLayout()ViewRootImpl.java:2648
android.view.ViewRootImpl.performTraversals()ViewRootImpl.java:2364
android.view.ViewRootImpl.doTraversal()ViewRootImpl.java:1515
android.view.ViewRootImpl$TraversalRunnable.run()ViewRootImpl.java:7091
android.view.Choreographer$CallbackRecord.run()Choreographer.java:927
android.view.Choreographer.doCallbacks()Choreographer.java:702
android.view.Choreographer.doFrame()Choreographer.java:638
android.view.Choreographer$FrameDisplayEventReceiver.run()Choreographer.java:913
android.os.Handler.handleCallback()Handler.java:751
android.os.Handler.dispatchMessage()Handler.java:95
android.os.Looper.loop()Looper.java:154
android.app.ActivityThread.main()ActivityThread.java:6682
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1520
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1410`

**Comment by hardcodet** [comment]
My bad! This might actually have been James' PullToRefresh control that's causing the exception in yours. Subsequent rebuild caused the pages to work again. I'll close this for now.

**Comment by carlasampaio01** [comment]
This is a real problem when the carousel is trying to load resources images.

It says: Object reference not set to an instance of an object.
In iOS it works. but on Android it doesn't.

My code:

`
			List<string> listaImagens = new List<string>();
			listaImagens.Add("bg11.jpg");

			imagensSlide = new CarouselViewControl
			{
				ItemsSource = listaImagens,
				ItemTemplate = new DataTemplate(() =>
				{
					var cachedImage = new Image
					{
						HorizontalOptions = LayoutOptions.Center,
						VerticalOptions = LayoutOptions.Center,
						Aspect = Aspect.AspectFill,
					};
					cachedImage.SetBinding(Image.SourceProperty, new Binding("."));

					return cachedImage;
				})
			};`
