### ISSUE TITLE
Rendering glitch on first page

### ISSUE THREAD

**Issue by hardcodet** [alexrainman/CarouselView#217]
XF 2.4.0, latest Carousel package, Android:

I noticed a weird glitch on a carousel with 3 pages:

* I open the carousel with the 2nd page initially.
* If I then swipe to the 1st page, the labels are not rendered (or not visible, or have a height of 0, dunno)
* If I swipe to the 3rd page first and then to the 1st page, the labels render just fine.
* With a bad card, if I then go to the 3rd page and back to the 1st, this also corrects the issue. (Maybe the page is recreated and properly rendered this time)

Strange enough, it only affects the labels in one of my cards, the rest renders nicely. Never had that before, so I assume that was introduced recently. Maybe that's also related to the height measurement issues that were reported in other issues?

<img src="https://user-images.githubusercontent.com/873009/31015917-c9cb4c36-a522-11e7-865e-97819882c768.png" width="300"></img>

**Comment by alexrainman** [comment]
I will be releasing a new version which requires Xamarin.Forms 2.4.x and above. I cannot reproduce your issue so the new version should resolve your problem.

**Comment by hardcodet** [comment]
Thanks for the quick replay, Alex! I'll test with the new release once it's available and report back.

**Comment by hardcodet** [comment]
Hi Alex

Unfortunately, upgrading to the latest version didn't solve the issue. Here's a screencast of it - hope that helps:

https://www.dropbox.com/s/8xbmz2fecl1of4y/carousel-issue.mp4?dl=0

**Comment by alexrainman** [comment]
The thing is I cannot reproduce this :(

**Comment by hardcodet** [comment]
Hmm, it might be a Xamarin issue. Let me raise it with the team. I'll post back here.

**Comment by hardcodet** [comment]
Opened a bug report here:
https://bugzilla.xamarin.com/show_bug.cgi?id=60097

If you can contribute as to how the carousel renders/layouts (which might explain why it works when I go to the third carousel view and back), please comment. This might help the Xamarin team to triangulate.
