### ISSUE TITLE
TypeLoadException

### ISSUE THREAD

**Issue by marlonribeiro01** [alexrainman/CarouselView#22]
I'm getting this on CarouselViewRenderer.Init()

> System.TypeLoadException: Could not load type 'CarouselView.FormsPlugin.Android.CarouselViewRenderer' from assembly 'CarouselView.FormsPlugin.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Xamarin.Forms version 2.3.2.127 (Latest stable)
CarouselView.FormsPlugin version 2.2.0

**Comment by alexrainman** [comment]
Will confirm this tomorrow and its actually a bug, the fix will be included in next release by end of month. For now a possible solution is to downgrade XForms. Thanks

**Comment by alexrainman** [comment]
I updated to latest XForms and the control still working.

**Comment by marlonribeiro01** [comment]
What version are you using? I am not sure if my problem is the XForms version, I've tried a lot of versions but it is still not working,

**Comment by alexrainman** [comment]
Did you updated to Xamarin.Android 7?

**Comment by marlonribeiro01** [comment]
No.

**Comment by alexrainman** [comment]
Well, i updated to latest XForms and latest Xamarin.Android (7.0.1.2) and still working, so i cannot confirm your issue. I also installed SDK 24 with build tools 24.

**Comment by alexrainman** [comment]
Any updates on this from your side?

**Comment by marlonribeiro01** [comment]
Oh sorry, I answered on another open issue.
I uninstalled Xamarin e reinstalled the Cycle 7 stable version and it's all working now! (Including another bug which was crashing my app using the MediaPlugin when opening the camera on some devices).
Thanks!

**Comment by alexrainman** [comment]
Thanks

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
