### ISSUE TITLE
Crashing hard on Android with latest XF 2.4.0.280

### ISSUE THREAD

**Issue by carlasampaio01** [alexrainman/CarouselView#220]
It says: Object reference not set to an instance of an object.
In iOS it works. but on Android it doesn't.

My code:

`
List listaImagens = new List();
			listaImagens.Add("bg11.jpg");

			imagensSlide = new CarouselViewControl
			{
				ItemsSource = listaImagens,
				ItemTemplate = new DataTemplate(() =>
				{
					var cachedImage = new Image
					{
						HorizontalOptions = LayoutOptions.Center,
						VerticalOptions = LayoutOptions.Center,
						Aspect = Aspect.AspectFill,
					};
					cachedImage.SetBinding(Image.SourceProperty, new Binding("."));

					return cachedImage;
				})
			};`

The error occurs when it gets the image from the resources.

This is only when I add:

`Forms.SetFlags("FastRenderers_Experimental");`

to android activity.

**Comment by soile1991** [comment]
same here it's not compatible with XF 2.4.0.280  - XF 2.4.0.282 .

images and background colors are not displayed

**Comment by alexrainman** [comment]
I will be releasing a version that is compatible with XF 2.4.*
