### ISSUE TITLE
Multiple view instances getting created and hence binding getting called multiple times.

### ISSUE THREAD

**Issue by Mohit-Kharbanda** [alexrainman/CarouselView#222]
Hi Alex,
Thanks for the CarouselView control and appreciate your hard work and efforts in creating and sharing it.

I am using the control and DataTemplateSelector to have different ContentView. Now the issue is that my view instance is getting created again and again whenever I swipe through the carousel control. Due to this my bindings hit multiple times in the respective ViewModel.

I have created a demo and here you can see the SelectedItem property of the NoContentViewModel hits multiple times. The behavior is not specific for just this property and this view model.

Is there any way I can dispose the view instance before those gets created again so at any instance unnecessary instances are not in the memory.
[CarouselViewDemo.zip](https://github.com/alexrainman/CarouselView/files/1361477/CarouselViewDemo.zip)

**Comment by hilpara** [comment]
I'm having the same problem at the moment. It will create every time the view is loaded 1 instance of view and for some reason 3 view models.  The views and view models aren't ever disposed. This leads to memory problems because the objects won't be gc'ed.

**Comment by hilpara** [comment]
OK it seems that multiple view models creation is a xamarin.forms bug (https://bugzilla.xamarin.com/show_bug.cgi?id=57081), but creating multiple views and not deleting them is a carousel view problem.

**Comment by alexrainman** [comment]
@Mohit-Kharbanda I can see whats your problem here. When you use the CarouselControl with Images, you have to use FFImageLoading or dispose images yourself. XF doesn't handle images well. They stay in memory. Also, Views are created and disposed as needed. To keep the control lite, views are collected and only 3 of them stay in memory to keep the swipe smooth.

**Comment by alexrainman** [comment]
Also, why you implement your own indicators if the control has its own?

**Comment by Mohit-Kharbanda** [comment]
Thanks Alex for replying.
Actually the demo I have shared is using the images as-is, however in my actual project I am using FFImageLoading. So the issue does not seems to be related to the image. The concern here is regarding the multiple binding which is getting triggered due to multiple instances of view being created.

I have implemented the indicators as I needed the indicators to be tappable. Tapping on any indicator shall show the respective view.

Can you please advise on the multiple instances of view part as it is resulting in slowness of the app over the time.

**Comment by alexrainman** [comment]
This is something I resolved before. I am trying to figure it out why your views are not being collected.

**Comment by alexrainman** [comment]
If you want to avoid your Views to be created multiple times then use a collection of Views as ItemsSource.

**Comment by alexrainman** [comment]
It's on the documentation. Something like this:

```
<cv:CarouselViewControl BindingContext="{Binding Person}">
    <cv:CarouselViewControl.ItemsSource>
           <x:Array Type="{x:Type View}">

                <!-- Page1 Display Photo -->
                <Image Source="{Binding PhotoUrl}"/>

                <!-- Page2 Display Bio -->
                <Label FormattedString="{Binding Bio}"/>

                <!-- Page2 Display contact information -->
                <Label FormattedString="{Binding Info}"/>

           </x:Array>
    </cv:CarouselViewControl.ItemsSource>
</cv:CarouselViewControl>
```

Or do it programmatically.

**Comment by alexrainman** [comment]
I think this is the right way to use the control.

**Comment by hilpara** [comment]
I'm using your carousel view to show different views (content views). I have followed your example and the ItemsSource is a list of ints and then I use the template selector to show the correct view. The views will be created new but never disposed. I have implemented a OnParentSet override function to one of the views and it shows that the parent will be set to carousel view but the it will never be set back to null. So I think that leaves the reference to carousel view and it will never be collected.

**Comment by alexrainman** [comment]
Found a fix.

**Comment by alexrainman** [comment]
This issue is Android no?

**Comment by Mohit-Kharbanda** [comment]
I have used the CarouselView only on Android so far.

**Comment by hilpara** [comment]
My problem is with iOS.

**Comment by hilpara** [comment]
What is still mystery to me is, even tho I create data template list only once and OnSelectTemplate returns always the same template from the list, why is the view created new? I thought it would use the same view every time. Is this Xamarin feature or a problem in carousel view? I'm using the carousel view same way as in a project I made for the Indicator shape problem.

**Comment by hilpara** [comment]
So I made little bit more testing. I changed the views to singletons. I'm still using the DataTemplate way to show the views. The iOS version will crash because: "A view can only be associated with at most one view controller at a time!". It's the same error message which comes if I try to use List<View> as items source. On Android no problems. The views are created only once and the performance much better. The iOS version is slow when swiping because it's creating the views always new. 
If the views aren't singletons then the views will be also created on Android every time new and I will have the same problem as Mohit-Kharbanda.

**Comment by hilpara** [comment]
Sorry for spamming. I just saw that you had a made a new version (4.4.4) and I tested it. Nothing changed under iOS or Android for me. I still see creating new views, but I have never hit an breakpoint on Dispose, OnParentSet (Parent=null) or finalizer and I can see multiple calls to bindings.

**Comment by alexrainman** [comment]
Version 4.4.4 was for something else. Will release another later today.

**Comment by hilpara** [comment]
I tested your new version 4.4.5. Now the parent of the view will be set to null, but for some reason it happens directly after it is created. I thought it would be set when the view goes out of sight or, If I recall correctly the carousel view can only have 3 views in "cache", after these 3 views has been created. Do you know if the bindings from the view to view model can prevent the garbage collection? I can't set the binding to null when the parent is set to null because the view is still visible and then the bindings doesn't work.

**Comment by alexrainman** [comment]
So, whats the issue now? I set the parent to null because the Xamarin View is not needed anymore at that point, at least when the ItemsSource is not a List of Views or DataTemplate.
Let me see if i can do it when the Native view is collected. I mean destroy parent and binding context.

**Comment by alexrainman** [comment]
Anyway, i dont see any memory leak. It has been corrected before. Can you show me?

**Comment by hilpara** [comment]
The issue is that the bindings are still there and are still getting fired multiple times.

**Comment by hilpara** [comment]
My ItemsSource is a list of ints because I can't set (or at least before) it to list of views on iOS.

**Comment by alexrainman** [comment]
What do you mean with “fired” multiple times? The control keeps a “cache” of 3 views max. Views outside of that cache will be collected and created when needed again as the user swipe. Also sometimes Xamarin Forms triggers “height” property changed twice at first launch. If thats what what you mean with “fired” multiple times.

**Comment by alexrainman** [comment]
It can be a list of Views and a list of DataTemplate also.

**Comment by hilpara** [comment]
I have a list of views which I shoe on carousel view. Every view has also its view model to which is bound. The ItemsSource is a list of int as a index for data templates. The views are returned then as a data template from ItemTemplate. You have this setting also in your Demo. If I try (I can try tomorrow if it is still the case) to set my views to ItemsSource I will get a "A view can only be associated with at most one view controller at a time!" error.
Now when the first view comes visible it will be created but at the same time the parent will also be set to null. The bindings to view model still works. If I then go forward 2 pages (to page 3) and come back the first page will be created again. I can still see the bindings for the first page to be fired as many times as these are created new from the carousel view. Even if the carousel view it self isn't any more visible the bindings keep triggering. This means that the views are still "active" in memory.

**Comment by alexrainman** [comment]
Maybe thats the problem. The view binding context is set internally in the control to each element in the ItemsSource. In this case you are using a list of integers. But you are using a ViewModel bound to each view. Can you try putting those view models as ItemsSource? Or, use a list of views?

**Comment by hilpara** [comment]
If I use list of views as ItemsSource (no templates) it will crash as always when I come back to carousel view with error: "A view can only be associated with at most one view controller at a time!". If I change the list to data template I will get again multiple views firing my bindings. I have slowly a feeling that I'm doing something wrong.

**Comment by alexrainman** [comment]
Which version of the control are you using? Because a List of Views as ItemsSource has been supported for a while and it doesn't cause a crash. Just take a look at the demo MainPage.

**Comment by Mohit-Kharbanda** [comment]
I tried my demo with the latest release of carousel view and seems like it is still triggering the view model binding multiple times. I swiped from the initial page to the last page and it worked fine. However when I swiped back to initial page the bindings (get/set of view model property) hit two times. Similarly when I traversed more than twice the bindings were getting triggered those many times.

**Comment by alexrainman** [comment]
It's because the Native views are collected and only 3 of them stay in memory. When a Xamarin.Forms View is converted to Native, all the bindings and layouts are triggered. There's noting wrong here.

**Comment by hilpara** [comment]
I use the newest 4.4.5. I don't know if the problem comes when you have nested carousel views. I have one carousel view which works as a tabview. If I go to my second tab where the second carousel view is located, and use the views as ItemSource it works normally and I can swipe through the pages. If I then go to for example back to first tab from the primary carousel view and come back to second tab where the nested carousel view is located it will crash.

**Comment by hilpara** [comment]
Here is test project where you will actually see both of my problems. 
1 problem. Just swipe to page 4 and come back to page 3 and it will crash.
2 problem. Go to page 2 and from nested carousel go also to page 4. It should only count ones (in debug window) because the nested window 1 should stop but it doesn't. Because If you go to view 4 from the main carousel view the view1 count stops. But because the program crashes when I try to come back to page 2 where the nested carousel view is, I don't know if the counting would then be tripled.
[CarouselIndicatorTest.zip](https://github.com/alexrainman/CarouselView/files/1391154/CarouselIndicatorTest.zip)

**Comment by Mohit-Kharbanda** [comment]
@alexrainman Does this mean that the viewmodel bindings will always hit multiple times when ever any action will be triggered by the user like selecting a listview item. Not sure if it sounds fine as surely the user will swipe across multiple times and it will always result in application becoming slow.

**Comment by hilpara** [comment]
I have made a very small and simple project where the carousel view doesn't delete it's views (at least on iOS). It contains only a Xamarin.Forms and CarouselView libraries.
The main file is CarouselViewTestPage.xaml. In this file I will either embed BackView or show BackView in CarouselView control. If the BackView is embed in page, then actually two BackViews will be created which doesn't matter. If you go back to the first page from this view then both counters will stop showing values on debug window. If I come back to the view new views will be created, but it will always have only these two views triggering the bindings.
If I change it to show the same page through CarouselView, it will first create one view as it should. If I then go back to first page the counters (bindings) continue to trigger. When I come back it will again create a new window and then I have two views triggering the bindings. Every time I come back it will add one more view to trigger the bindings. 
This can't be intended behavior.
[CarouselViewTest.zip](https://github.com/alexrainman/CarouselView/files/1394370/CarouselViewTest.zip)

**Comment by MarcusSpecht** [comment]
Exactly the same here. I am on UWP and Xamarin.Forms 3. This seems to be a major issue.

**Comment by Ruddy2007** [comment]
Also seeing this problem in UWP, Xamarin.Forms 3.

**Comment by Ruddy2007** [comment]
@alexrainman Any chance you could come back to this post? It may be Xamarin.Forms but it does appear to currently be this plugin causing the issue. 

Not 100% sure my problem is the same as this as the custom view I made being used as the datatemplate is created 2 times. The first one seems to be disposed, tested by putting a button on view and setting a clicked event. 

If it helps we could chat via a messenger and I could walk you though the problem?

**Comment by sauravchaudhary94** [comment]
Is this issue resolved ? I am still facing the same issue in iOS and due to that App is crashing . As I am seeing thread is closed but without proper fix. If anyone have any workaround please help.

**Comment by RuddyOne** [comment]
@sauravchaudhary94 Since my issue was on UWP and this project died, I had to fork it and fix it myself. https://github.com/Ruddy2007/CarouselView/issues/1

Not sure if it's the same issue on iOS but may help you.
