### ISSUE TITLE
[iOS] NullReferenceException when CarouselView hidden 

### ISSUE THREAD

**Issue by L3xer** [alexrainman/CarouselView#224]
Here is the repro project 

https://github.com/L3xer/CarouselBugRepro

To reproduce the issue follow the steps
1. In VS click on Debug->Window->Exception Settings select "Common Language Runtime Exceptions"
![devenv_2017-10-07_18-57-19](https://user-images.githubusercontent.com/8818052/31309681-04234d54-ab93-11e7-8fc8-e9ee1bfd7e62.png)

2. Run project and click "Page 1" button
3. Click back button in the navigation bar, you should  see the exception
![devenv_2017-10-07_19-05-15](https://user-images.githubusercontent.com/8818052/31309699-3231ac4a-ab93-11e7-971c-8d937fc6631b.png)

The actual problem will arrise when you click "Page 2" button and then "Back" button, there will be a blank screen  
![2017-10-07_19-18-33](https://user-images.githubusercontent.com/8818052/31309777-5aab9e28-ab94-11e7-9e90-8fb4867350f4.gif)

**Comment by alexrainman** [comment]
What relation this has with the CarouselControl?
