### ISSUE TITLE
(iOS) CarouselView 4.4.3 Vertical XF ScrollView inside template is automatically disabled.

### ISSUE THREAD

**Issue by kleswing** [alexrainman/CarouselView#225]
I have a Xamarin Forms project where I use a Vertical ScrollView on one of the templates inside of the CarouselView control.  I set the CarouselView to scroll only horizontally purposefully and set the XF ScrollView to only scroll vertically inside the template.  iOS does not permit me to scroll the ScrollView control at all; while Android has no problems and can scroll vertically.

**Comment by alexrainman** [comment]
If you take a look at the Demo, I use Horizontal carouselControl with Views that have Vertical ScrollView and they works.

**Comment by kleswing** [comment]
Alex..  thanks for the quick response.  I'm going to borrow your code and see what the difference is between how I implemented my logic vs your demo.  I will let you know if I notice anything.

**Comment by kleswing** [comment]
Alex ...  I think I figured it out.  Hopefully you find this helpful.  In my ContentPage, I was using a StackLayout control where I only had two controls in its content.  One of them was the CarouselView and the other was just a top label.  When I followed your code sample in the demo project in GitHub, I noticed you used the Grid control instead.  I replaced the StackLayout control with a Grid control for my own layout and it worked.  

To be sure it wasn't something unintended, I modified your Demo pages and referenced a StackLayout control instead of the Grid and ran into the same issue (where I can't get the scrollview to work in iOS).  BTW, it works fine in Android.  I am including the demo pages that I modified so that you can see what I mean.  Thank you for the time you put into making a rather robust control.  

[DemoPageReplacement.zip](https://github.com/alexrainman/CarouselView/files/1369805/DemoPageReplacement.zip)

**Comment by alexrainman** [comment]
I ran into issues with StackLayout and MasterDetailPage before and couldn't find ways to solve them. They are related to Xamarin.Forms layout engine.

**Comment by alexrainman** [comment]
I will continue working on this control 'til it gets included in XF code base for version 3. Thanks
