### ISSUE TITLE
CarouselView crash when swiping backwards after iOS 11 update in mobile devices.

### ISSUE THREAD

**Issue by EnriqueEgremy** [alexrainman/CarouselView#227]
We already had a carousel view that contains an ObservableCollection<DataTemplate> with some custom views inside, and all was working fine until we upgrading to iOS 11.
Now its only work when we swipe forward in the carousel, if we tried to swipe backward it crashed, but only on mobile devices, it doesn't crash in the emulator.

Foundation.MonoTouchException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x114067af0; frame = (0 344; 375 147); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x1c562c900>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x114070360>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x11408a630>.
Native stack trace:
	0   CoreFoundation                      0x00000001816c7d50 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180bdc528 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001816c7c80 <redacted> + 0
	3   UIKit                               0x000000018ab4fb28 <redacted> + 248
	4   UIKit                               0x000000018ab4fa20 <redacted> + 48
	5   UIKit                               0x000000018ab4f6f4 <redacted> + 468
	6   Valida.IOApp.iOS                    0x0000000101fc50a0 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSendSuper_IntPtr_intptr_intptr_intptr + 112
	7   Valida.IOApp.iOS                    0x0000000101f6e468 UIKit_UIViewController_set_View_UIKit_UIView + 216
	8   Valida.IOApp.iOS                    0x00000001028c7ee0 CarouselView_FormsPlugin_iOS_CarouselViewRenderer_CreateViewController_int + 3600
	9   Valida.IOApp.iOS                    0x00000001028c9384 CarouselView_FormsPlugin_iOS_CarouselViewRenderer__SetNativeViewb__20_0_UIKit_UIPageViewController_UIKit_UIViewController + 468
	10  Valida.IOApp.iOS                    0x0000000101f45d4c UIKit_UIPageViewController__UIPageViewControllerDataSource_GetPreviousViewController_UIKit_UIPageViewController_UIKit_UIViewController + 60
	11  Valida.IOApp.iOS                    0x00000001013a9404 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	12  Valida.IOApp.iOS                    0x0000000102cdd31c mono_jit_runtime_invoke + 824
	13  Valida.IOApp.iOS                    0x0000000102d430e4 do_runtime_invoke + 108
	14  Valida.IOApp.iOS                    0x0000000102d43044 mono_runtime_invoke + 208
	15  Valida.IOApp.iOS                    0x00000001010ecb08 _ZL31native_to_managed_trampoline_91P11objc_objectP13objc_selectorPP11_MonoMethodP20UIPageViewControllerP16UIViewControllerj + 664
	16  Valida.IOApp.iOS                    0x00000001010eccac -[UIKit_UIPageViewController__UIPageViewControllerDataSource pageViewController:viewControllerBeforeViewController:] + 68
	17  UIKit                               0x000000018b44421c <redacted> + 108
	18  UIKit                               0x000000018b449ce8 <redacted> + 268
	19  UIKit                               0x000000018b449dd0 <redacted> + 64
	20  UIKit                               0x000000018b53cd78 <redacted> + 108
	21  UIKit                               0x000000018b53d41c <redacted> + 128
	22  UIKit                               0x000000018b53d7a8 <redacted> + 196
	23  UIKit                               0x000000018b53fc60 <redacted> + 168
	24  UIKit                               0x000000018b53d2ac <redacted> + 636
	25  UIKit                               0x000000018b5408cc <redacted> + 1060
	26  UIKit                               0x000000018b53c3c8 <redacted> + 200
	27  UIKit                               0x000000018aad5000 <redacted> + 1256
	28  QuartzCore                          0x00000001856a50b4 <redacted> + 184
	29  QuartzCore                          0x00000001856a9194 <redacted> + 332
	30  QuartzCore                          0x0000000185617f24 <redacted> + 336
	31  QuartzCore                          0x000000018563e340 <redacted> + 540
	32  QuartzCore                          0x00000001855930d4 <redacted> + 928
	33  IOKit                               0x000000018193230c IODispatchCalloutFromCFMessage + 392
	34  CoreFoundation                      0x0000000181656080 <redacted> + 188
	35  CoreFoundation                      0x00000001816709dc <redacted> + 56
	36  CoreFoundation                      0x00000001816700e0 <redacted> + 440
	37  CoreFoundation                      0x000000018166dbb4 <redacted> + 2196
	38  CoreFoundation                      0x000000018158e2d8 CFRunLoopRunSpecific + 436
	39  GraphicsServices                    0x000000018341ff84 GSEventRunModal + 100
	40  UIKit                               0x000000018ab3b880 UIApplicationMain + 208
	41  Valida.IOApp.iOS                    0x0000000101fc3020 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 368
	42  Valida.IOApp.iOS                    0x0000000101f51d0c UIKit_UIApplication_Main_string___intptr_intptr + 44
	43  Valida.IOApp.iOS                    0x0000000101f51ccc UIKit_UIApplication_Main_string___string_string + 172
	44  Valida.IOApp.iOS                    0x00000001011090a0 Valida_IOApp_iOS_Application_Main_string__ + 128
	45  Valida.IOApp.iOS                    0x00000001013a9404 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	46  Valida.IOApp.iOS                    0x0000000102cdd31c mono_jit_runtime_invoke + 824
	47  Valida.IOApp.iOS                    0x0000000102d430e4 do_runtime_invoke + 108
	48  Valida.IOApp.iOS                    0x0000000102d45ae8 do_exec_main_checked + 144
	49  Valida.IOApp.iOS                    0x0000000102cc6ca0 mono_jit_exec + 268
	50  Valida.IOApp.iOS                    0x0000000102ddbeec xamarin_main + 2220
	51  Valida.IOApp.iOS                    0x0000000101108f98 main + 96
	52  libdyld.dylib                       0x00000001810b256c <redacted> + 4

I don't know why is now telling us that is multiple association with viewcontrollers, and only when swiping backward (from left to right).
There is something that changed with the new MonoTouch 11?

I'm using the most updated xamarin,xamarion.ios and CarouselView packages.

Regards

**Comment by fabienmwamba** [comment]
Hi @EnriqueEgremy have you tried to revert the CarouselView packages to  4.4.2 and run that on iOS 11 and see what the behavior is.

**Comment by EnriqueEgremy** [comment]
@fabienmwamba  same error.

Unhandled managed exception:
Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x13e720d30; frame = (0 344; 375 147); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x1c5c2c020>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x13e7d7a00>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x141943340>.

I'm still trying to figure in what moment is trying to associate the CarouselView again to the renderer and only when swiping backward (i.e from pos 2 to 1, or 3 to 2). I can't reproduce it on the emulator.
What would have changed from iOS10.3 to iOS11 ? 
I'm using an iPhone6 for testing, and i already have installed an older build (with xamarin using 10.3 sdk) and is not crashing. Only when deploy to iOS 11 is when the problem occur.

**Comment by alexrainman** [comment]
Can you guys share a demo? I cannot reproduce this issue. It's working fine for me in iOS 11.

**Comment by EnriqueEgremy** [comment]
@alexrainman tanks for your reply.
Ok, let me detail a little bit more the setting.

Basically i have a tabbed page as my MainPage using the carousel view control. Now Inside the tabbed page i have a list DataTemplates as ContentView and in one the Content View i had another carousel view control (which shows some others dinamically generated content views).
The problem is in the second carousel view control when swiping backward, maybe there is a problem when putting carousel view inside a carousel view?
 
For the demo, i guess i can share you the app im currently working in testflight. Or try to reproduce the error in a fresh new app.

**Comment by alexrainman** [comment]
How are combining TabbedPage with CarouselControl? Because a nested carousel works without issues.

**Comment by alexrainman** [comment]
https://github.com/alexrainman/NestedCarouselView

https://github.com/alexrainman/TabbedCarouselView

**Comment by EnriqueEgremy** [comment]
@alexrainman  again, thanks for your help.

ok, i found the problem.
Looks like something doesn't like it to the carousel view when i populated dinamically its content.

col = new ObservableCollection<DataTemplate>();

var frame = new ActivitieFrame(item, carouselLimit);
col.Add((new DataTemplate(() => { return frame; })));    <---- this make it crash on mobile.

myCarousel.ItemsSource = col;

if i use this.

col.Add((new DataTemplate(() => { return new ActivitieFrame(item, carouselLimit); })));   <-- this doesn't crash.


Now im experiencing a problem when trying to "remember" at what position where the carousel, when clicked at its content.
Looks like if i put the position number in a static variable, and return later to the page with the carousel giving it the position on the static variable, something happens that crash the app with an index out of array. It's weird because the error is in the upper carousel :/
I'm start to think that there is a problem when you play with carouserl.Position in nested carousel views.

Regards!

**Comment by EnriqueEgremy** [comment]
Well ,looks like it was an error on our implementation, due a a change position on or initialization that called the position changed event, calling a selected pin event (from a map view) that at the same time was calling again the position change event, making a loop 
We fixed the logic error and looks like is working normally again.
Thanks for your help
