### ISSUE TITLE
CarouselView without navigation

### ISSUE THREAD

**Issue by Maxima078** [alexrainman/CarouselView#228]
Hi,
When I use the CarouselView within a ContentView I got the same error than https://github.com/alexrainman/CarouselView/issues/52 when I add item. Here the Carousel is just hidden (IsVisible = false) while other operations are running such as take new pictures.

Maybe it does not support "CollectionChanged"? 

I tried to navigate to a new page with this same Carousel (collection,template etc.) and obviously it works because there is no collection change. But I don't want to navigate, is it possible?

Thanks,

Max.

**Comment by alexrainman** [comment]
Can you provide a demo so I can understand what you want to do.

**Comment by Maxima078** [comment]
Hi, 

You will find a demo project attached.
[Sample_Carousel_GitHub.zip](https://github.com/alexrainman/CarouselView/files/1379918/Sample_Carousel_GitHub.zip)

To reproduce the crash follow these steps:
- hit HIDE/SHOW
- hit ADD
- hit HIDE/SHOW
- try to swipe

OR:
- hit ADD
- try to swipe

Thanks.

**Comment by Maxima078** [comment]
I just realized I was using version 2.5.1 and then I read your release notes and found you were not supporting ObservableCollection before 4.0.

It works perfectly with version 4.4.
