### ISSUE TITLE
Child view doesn't update on Screen rotation

### ISSUE THREAD

**Issue by shnaz** [alexrainman/CarouselView#23]
Hey @alexrainman,

So I have this peculiar case where the child view of CarouselView isn't rotated when screen is rotated. 

The wierd part is that it WORKS if the phone starts by being in landscape mode and then rotates to portrait and/or back to landscape. 

But if the page containing the carouselView is opened portrait mode, then it doesn't work when I rotate the phone to landscape. Seems like the child view's size isn't updated. 

So far I have only tested on iOS devices. I have installed the latest plugin version 2.2.0.

![image](https://cloud.githubusercontent.com/assets/6933856/18907784/49b04fc2-856d-11e6-930b-b707e76e5497.png)

![image](https://cloud.githubusercontent.com/assets/6933856/18907799/5f9c56dc-856d-11e6-9c91-f4a425219ae9.png)

Code:
![image](https://cloud.githubusercontent.com/assets/6933856/18907974/1b536f8c-856e-11e6-8da1-43474351ce79.png)

**Comment by shnaz** [comment]
Okay so after further testing, where I stripped the page to just contain the carouselViewControl as its ONLY child, it works. :S

**Comment by alexrainman** [comment]
Do you want me to work on this? I guess control has to work when it's not the only child.

**Comment by alexrainman** [comment]
In the demo app, i use a grid but with "*" for height and width instead.

**Comment by shnaz** [comment]
In my case, I find a workaround by using AbsolutLayout instead, works fine with all screen rotations.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
