### ISSUE TITLE
Changing Width of Carousel View resets back to first item on UWP

### ISSUE THREAD

**Issue by JKennedy24** [alexrainman/CarouselView#230]
Carousel View in a page containing list of items.

scroll to item around the middle

Change width of carousel - resets back to first item on UWP

**Comment by alexrainman** [comment]
Which version of CarouselControl?

**Comment by JKennedy24** [comment]
4.4.4 - Haven't tried 4.4.5 yet

**Comment by alexrainman** [comment]
Will try to reproduce this. Thans

**Comment by alexrainman** [comment]
Fixed. Next release.
