### ISSUE TITLE
Request for Scroll Event Notification

### ISSUE THREAD

**Issue by samialawadhi** [alexrainman/CarouselView#231]
Feature request: I needed an event that triggers whenever there a change in the status of carousel scrolling (started/stopped). in order to disable/enable gesture interactions with another control (jamesmontemagno: PullToRefresh to be specific). I ended up solving the problem by subclassing CarouselViewRenderer and accessing viewPager through reflection, which contained scrolling information which I then used to call on a custom event.

It took me a while to figure out how to solve the issue. I think that a built in "ScrollStatusChanged" event would be beneficial.

**Comment by alexrainman** [comment]
Have you checked PositionSelected event? It happens exactly after scrolling finish. I think o can add Scrolling started but finished will be same as PositionSelected.

**Comment by samialawadhi** [comment]
Yes I tried that, but PositionSelected only triggers when a page in the CarouselView snaps to position. What I needed was an event that triggers even with tiny scrolling. 

My case is very specific, which is a CarouselViewControl inside the PullToRefreshLayout. What happens is if I scroll the CarouselViewControl horizontally, and then if there is even slight gesture down, then the PullToRefreshLayout takes over, and the CarouselViewControl is reset, which is annoying from the user experience perspective.

**Comment by alexrainman** [comment]
Then you want to know when the control is being scrolled

**Comment by samialawadhi** [comment]
yes

**Comment by samialawadhi** [comment]
Also consider that knowing the exact scrolling would allow linking with other controls to create a nice scroll parallax effect
