### ISSUE TITLE
Question/Feature Request - Tabbed View Indicator

### ISSUE THREAD

**Issue by ahoefling** [alexrainman/CarouselView#232]
I am leveraging this library to build out a cross-platform tabbed page view that looks the same across each platform. 

**Background**
When I was experimenting with Tabbed Pages, it wasn't powerful enough to handle creating a uniform look and feel across the devices. Which makes sense, because each platform implements it slightly different. There are still some cases where you want it to look identical across the platforms.

**My Solution**
I was able to write some code on top of this library to create a new indicator section above or below the carousel view. This indicator section has a horizontal indicator bar and icons for each tab. When the user selects the tab it updates the indicator bar and the position of the CarouselView. There are also arrows on the right and left of the page where applicable so the user can use them to navigate to the next screen.

**My question**
This seems like a common feature request I have seen on some of the forums and around the Xamarin Community. Is this something I should submit a pull request for or do you think this is something that is really a separate project that just depends on this library.

Here is an example of what it could look like with the implementation I am explaining:
![image](https://user-images.githubusercontent.com/17751436/31625849-96cdafb2-b275-11e7-8882-5d227257c78e.png)

The more I think about this now that I have written it down, the more I think this should be it's own project since it does extend the functionality here quite a bit. @alexrainman would you like to see a PR or do you think this is better off in a new project?

**Comment by alexrainman** [comment]
I will like to take a look at what you did. You can do a PR if you want but please try to highlight your code somehow so I can easily explore your changes. Thanks

**Comment by alexrainman** [comment]
I think this should be a separated library that you can use with the Carousel to add TabStrip, which is the right name for it. The arrows? Maybe they can be part of the Carousel itself.

**Comment by ahoefling** [comment]
I have been talking to some colleagues about this and they recommended the same approach. I haven't had a chance to put together a pull request as of yet so no work wasted there. Making this a separate project will be easier for my MVP approach.

If anyone is interested in following progress I have created a new repository
https://github.com/ahoefling/TabStrip

**Comment by alexrainman** [comment]
Awesome. We can add the back and fort arrows to Android and iOS as UWP support them by default.
