### ISSUE TITLE
How can I bind the "PositionSelected" event to a ViewModel command

### ISSUE THREAD

**Issue by sergio11** [alexrainman/CarouselView#234]
I need to run a ReactiveCommand that next to the current position can load the data of each graph that is displayed in each screen of the Carousel.

I tried the following

```
<controls:CarouselViewControl.Behaviors>
<behaviors:EventHandlerBehavior EventName="PositionSelected">
                <behaviors:InvokeCommandAction 
                          Command="{Binding RefreshChart }" 
                          Converter="{ StaticResource DefaultReactiveUnitConverter}" />
                </behaviors:EventHandlerBehavior>
   </controls:CarouselViewControl.Behaviors>
```
The following exception occurs:

![captura de pantalla 2017-10-20 a las 14 26 08](https://user-images.githubusercontent.com/6996211/31820681-ae262114-b5a2-11e7-8563-0fd2856b2d0d.png)

I can not run the ReactiveCommand from the code-behind because it does not work:

```
void Handle_PositionSelected(object sender, int pos) {
            Debug.WriteLine("Chart pos -> " + pos);
            ViewModel.RefreshChartCommand.Execute(pos);
 }
```

Can you tell me how I can execute a command when the PositionSelected event is launched?

thanks in advance

**Comment by alexrainman** [comment]
Well i may add a PositionSelectedCommand in this case. Wait for next release. Anyway a reactive command can be executed: https://reactiveui.net/docs/handbook/commands/invoking-commands

**Comment by Umar3x** [comment]
Could be a great feature to include the "PositionSelectedCommand". Thank you for your work @alexrainman
