### ISSUE TITLE
TapGestureRecognizer under CarouselView sort of working.

### ISSUE THREAD

**Issue by Ruddy2007** [alexrainman/CarouselView#236]
Im not 100% sure if this is a Xamarin problem or a Carousel View problem.

I have a StackLayout as "pages" in the carousel view with a `TapGestureRecognizer`. On Android this appears to only work with a quick tap, if you hold your finger for more then 250ms (just a guess) and it will not register the tap. I have tested this without the Carousel View and the taps work fine (long holds etc). 

I can only guess the Carousel View is taken control thinking it is a swipe or something? Anyway around this?

**Comment by alexrainman** [comment]
That was the only way to make it work. You are right, if you press longer, Android think you are trying to swipe. Anyway i will take a look.

**Comment by Ruddy2007** [comment]
@alexrainman Thank you got taken a look. I will also have a little look and see what I can find.

**Comment by Ruddy2007** [comment]
@alexrainman This could be related to this? https://bugzilla.xamarin.com/show_bug.cgi?id=59863

**Comment by alexrainman** [comment]
Definitely.

**Comment by Ruddy2007** [comment]
Quick update on this. Is does seem to be related directly to the bug I posted before. 

I have put XF back to version `2.3.4.247`, Xamarin Android Support to `25.3.1` and this seems to have got the taps working again. Using the latest of this plugin seem to crash it (is that due to XF 2.4+?) so I am now using version 4.4.3.

**Comment by alexrainman** [comment]
Lets wait for Xamarin to fix their own bug :)
