### ISSUE TITLE
Dynamic Resizing of CarouselViewControl has issues

### ISSUE THREAD

**Issue by vikram-ma** [alexrainman/CarouselView#238]
I have my CarouselView inside AbsoluteLayout, which looks like this
```XAML
<AbsoluteLayout>
    <CarouselViewControl AbsoluteLayout.LayoutFlags="All"
                                         AbsoluteLayout.LayoutBounds="0,1,1,0.25 
                                         x:Name="CarouselViewControl" />
</AbsoluteLayout>
``` 
then in the source code I change the bounds in source as below during runtime,
```C#
    AbsoluteLayout.SetLayoutBounds(this.CarouselViewControl, new Rectangle(0f,1f,1f,0.75f));
```
The position of CarouselViewControl is updated to be correct location, but size does not change.
I tested with Other simple controls, they behave as expected, so I suspect it is issue with CarouselViewControl.

Thank you for time!

**Comment by alexrainman** [comment]
Why to wrap the Carousel into AbsoluteLayout in the first place? If it is the only element, you don't need the AbsoluteLayout. Use a Grid or ContentView or nothing.

**Comment by vikram-ma** [comment]
I have other controls in AbsoluteLayout. I want to be able to pull up the CarouselView from bottom, then slide left/right for more information. In the example I have given, to make it simple I removed all other objects.

**Comment by alexrainman** [comment]
Is this solved?

**Comment by vikram-ma** [comment]
Hey sorry for the late reply. The issue itself is not fixed. But I was able to find a work-around, instead of resizing the CarouselView, I change the Y position of it.
