### ISSUE TITLE
CarouselView Not appearing on Android

### ISSUE THREAD

**Issue by AshaneSilva** [alexrainman/CarouselView#24]
Carousel View works fine on IOS but not appearing on android. 
I called `CarouselViewRenderer.Init(); ` method on my droid project after `Forms.Init(this, bundle); `functions.
CVButton is not visible on IOS 
It doesn't throw any Exceptions for above issues

**Comment by alexrainman** [comment]
Which version of XForms please?

**Comment by AshaneSilva** [comment]
2.3.2.127

**Comment by alexrainman** [comment]
Question, did you update to latest Xamarin.Android? Version 7?

**Comment by alexrainman** [comment]
Because i cannot reproduce this.

**Comment by AshaneSilva** [comment]
Xamarin.Android 7.0.0.6

**Comment by alexrainman** [comment]
Thats the problem. Xamarin.Android 7 has a confirmed issue. Please update to latest one and test or, you will have to downgrade to version 6.

**Comment by alexrainman** [comment]
I am updating to latest one and i will do some test. What i know is that latest Xamarin update hs introduced lot of bugs.

**Comment by AshaneSilva** [comment]
Ok ill try the above solution and update. What about CVButton not showing on IOS

**Comment by alexrainman** [comment]
All custom controls will be deprecated in upcoming release except for CVLabel, so instead you use the standard control specifying the HeighRequest with OnPlatform:

```
<Button Text="Remove this page" Clicked="Handle_Clicked">
	<Button.HeightRequest>
		<OnPlatform x:TypeArguments="x:Double"
            Android="48"
            iOS="44"
			WinPhone="32"/>
	</Button.HeightRequest>
</Button>
```

Or by code like this:

```
Device.OnPlatform(
	iOS: () => myButton.HeightRequest = 44,
	Android: () => myButton.HeightRequest = 48,
	WinPhone: ()=> myButton.HeightRequest = 32
);
```

Let me know if works for you.

**Comment by alexrainman** [comment]
XForms (2.3.2.127) and Xamarin.Android (7.0.1.2). I also installed SDK 24 with build tools 24.

**Comment by marlonribeiro01** [comment]
I uninstalled Xamarin e reinstalled the Cycle 7 stable version and it's all working now! (Including another bug which was crashing my app using the MediaPlugin when opening the camera on some devices).
Thanks!

**Comment by AshaneSilva** [comment]
Thank you for the support `myButton.HeightRequest ` solution worked. But buttons and labels are not appearing on list view. Do I need to uninstall xamarin completely? (Including xamarine.android , Xamarin.iOS, Xamarin.Mono)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by ahmedelashkerpersonal** [comment]
I had the same problem, but it was due to some proxy configurations made in the network I'm working at.

I have no idea though why it's allowing the iOS simulator and not the Android emulator to load online images.

**Comment by mariaguutierrez** [comment]
Hi! We're having the same problem. The CarouselView is working great with iOS, but when we're trying to run it on Android it doesn't show any data. We're using Android Mono 8.

Are you planning to work to fix this error or do you recommend us to use another control?
