### ISSUE TITLE
[Android] Bound ItemSource not updating when model is updated

### ISSUE THREAD

**Issue by IanCaz** [alexrainman/CarouselView#240]
In my CarouselViewControl I have the binding set in XAML like this:
` ItemsSource="{Binding Operations}" `
The page has its BindingContext set to my ViewModel & one of the properties of this ViewModel is:
```C#
        private ObservableCollection<Operation> operations;
        public ObservableCollection<Operation> Operations
        {
            get { return operations; }
            set
            {
                operations = value;
                NotifyPropertyChanged("Operations");
            }
        }
```
When I grab a new list of Operations (as the result of a Picker being changed), I assign them to Operations, but the items in the Carousel don't update, it keeps showing the old items.

**Comment by alexrainman** [comment]
Can you provide a demo? Which platform?

**Comment by IanCaz** [comment]
This is on Android.   Haven't tried in iOS.  I'll try to get a demo
together.

Thanks,
Ian

**Comment by alexrainman** [comment]
Are you implementing PropertyChanged on the ItemsSource?

**Comment by giaesp** [comment]
I've a very similar issue. It happens only in Android (iOS works perfectly) and only when the Carousel container page is opened via Navigation.**PushModalAsync** (works perfectly in Android using PushAsync).
In this specific condition seems there is no binding at all: ObservableRangeCollection in my case is correctly loaded, but on the Carousel nothing happens, nor template views init.

**Comment by giaesp** [comment]
Just for your info, I had a previous release of my app in which everything works fine. The issue I described in the previous post seems to be appeared when I updated Xamarin Forms to 2.5.0122203.
