### ISSUE TITLE
[iOS] NSInternalInconsistencyException Reason: Invalid update: invalid number of rows in section

### ISSUE THREAD

**Issue by jeromeliger** [alexrainman/CarouselView#241]
I'm building a professionnal App, wich turn around an Agenda...
I can't use agenda plugins because I need to control weeks synchronisation and other special things...

By the way, I discover your awesome plugin, and I decided to create my own control with it :
- One Carousel for my "Weeks" (navigate or add weeks dynamicaly)
- Another Carousel for the "Days" of the current week (navigate on the current week days)

I've done a demo, and it works (quite) perfectly on Android.
But when I want to test it on iOS, I got errors when I want to "Add a week" (before or after the current) :

`Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (2) must be equal to the number of rows contained in that section before the update (2), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).`

I've tried to update with or without "BeginInvokeOnMainThread" the Carousel Datasource (witch is an ObservableCollection of my ViewModels), or Lock my Collection, or... 
But I can't make it work on iOS...

Did I miss something ?
Does I have to update in another way ?
Is there a bug with ObservableCollection<ViewModels> as Carousel DataSource ? (I doubt,  but maybe...)

Thanks for your lightening (I'm turning crazy...)

(PS: anybody can feel free to use my sample... and to make remarks if you see better way to evolve my code ^^)

[TestCalPCL.zip](https://github.com/alexrainman/CarouselView/files/1425121/TestCalPCL.zip)

[Demo](https://www.dropbox.com/s/4kboru89ncgd1gf/TestCalPCL.zip?dl=0)

**Comment by alexrainman** [comment]
Sorry, i have been sick. Will take a look at this.

**Comment by alexrainman** [comment]
And i dont get this error in iOS. It actually works but yes PositionSelected is called twice. I have to analize your code first.

**Comment by jeromeliger** [comment]
Thanks for your response.

With my sample, I reproduce each time... (I'm compiling agains iOS 10.3 -> I need to run app on iPhone4 x86, I cannot compile against iOS11)

But it seems that my original problem came with an iOS ObservableCollection "Clear()" Datasource Binding (not your CarouselView plugin).

For people who get the same error, there is a solution (DayViewModels is my carousel Datasource) :

bug on iOS (works on Android):
`DayViewModels.Clear();`

Resolution :
`while (DayViewModels.Count > 0)
{
     DayViewModels.RemoveAt(0);
}`

But it generates others doubts about carouselview :
 
- When the previous code is doing a "DayViewModels.RemoveAt(0);" -> the Position Binded is fired (PositionChanged)

- after that "Clear Hack", I need to add new DayViewModels (7, one for each day), and when I do a "DayViewModels.Add(new dayviewmodel)" -> The Position binded is fired (PositionChanged) too...

**Comment by jeromeliger** [comment]
Edit : The previous "hack" is not a good solution...

When I did the "While{VM.RemoveAt(0)}" and add after that new VM, a very strange comportment is happening... the new VM are messed-up and not in correct order...

I don't know if it is a special case with my code... but with the "VM.Clear()" method, it works perfectly on Android (but crash on iOS)

So I'm blocked and I can't make my sample work...

**Comment by codebeaulieu** [comment]
I'm having this issue as well when performing programmatic index changes on a static number of views. Just wanted to add my stack trace.

`Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Don't know about flushed view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x11fd6c770; frame = (0 0; 398 531); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x1c2633020>>
Native stack trace:
	0   CoreFoundation                      0x0000000183eb637c <redacted> + 148
	1   libobjc.A.dylib                     0x00000001830fc528 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183eb6238 <redacted> + 0
	3   Foundation                          0x00000001848737f4 <redacted> + 112
	4   UIKit                               0x000000018dd41328 <redacted> + 580
	5   UIKit                               0x000000018dd413e4 <redacted> + 160
	6   UIKit                               0x000000018de36d10 <redacted> + 132
	7   UIKit                               0x000000018de36e9c <redacted> + 368
	8   UIKit                               0x000000018de3a5c8 <redacted> + 1060
	9   UIKit                               0x000000018de36268 <redacted> + 100
	10  UIKit                               0x000000018d54c8f0 <redacted> + 464
	11  UIKit                               0x000000018d71b244 <redacted> + 300
	12  QuartzCore                          0x0000000187e03710 <redacted> + 672
	13  IOKit                               0x0000000184121190 IODispatchCalloutFromCFMessage + 392
	14  CoreFoundation                      0x0000000183e44290 <redacted> + 188
	15  CoreFoundation                      0x0000000183e5f000 <redacted> + 56
	16  CoreFoundation                      0x0000000183e5e704 <redacted> + 440
	17  CoreFoundation                      0x0000000183e5c1d8 <redacted> + 2196
	18  CoreFoundation                      0x0000000183d7be58 CFRunLoopRunSpecific + 436
	19  GraphicsServices                    0x0000000185c48f84 GSEventRunModal + 100
	20  UIKit                               0x000000018d41c8c8 UIApplicationMain + 236
	21  Flash.iOS                           0x00000001033151a0 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 368
	22  Flash.iOS                           0x0000000102bf9bac UIKit_UIApplication_Main_string___intptr_intptr + 44
	23  Flash.iOS                           0x0000000102bf9a6c UIKit_UIApplication_Main_string___string_string + 172
	24  Flash.iOS                           0x000000010212b6ec Flash_iOS_Application_Main_string__ + 140
	25  Flash.iOS                           0x000000010266abd4 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	26  Flash.iOS                           0x00000001065568e0 mono_jit_runtime_invoke + 824`
