### ISSUE TITLE
HELP NEEDED

### ISSUE THREAD

**Issue by alexrainman** [alexrainman/CarouselView#244]
@mattrichnz @predalpha @ac2112 @rdaniel0 @johnnysbug @GuyMicciche do any of you guys know or can help me to figure it out how to change the style of FlipView navigation buttons?

I am planning a release with lot of bug fixes, NetStandard support and Navigation Arrows in all platforms. They will look like UWP in Android and iOS and i have them working already. I am adding two new properties to change "background" and "foreground" color of the buttons but, i cannot figure it out how to change it on UWP.

I have a method that finds the buttons and play with their visibility, and that works, but applying new colors doesn't have any effect on them:

```
private void ButtonVisibility(FlipView f, string name)
{
    var b = FindVisualChild<Windows.UI.Xaml.Controls.Button>(f, name);
    if (b != null)
    {
        b.Opacity = Element.ShowArrows ? 1.0 : 0.0;
	b.IsHitTestVisible = Element.ShowArrows;
        b.Background = (SolidColorBrush)converter.Convert(Element.ArrowsBackgroundColor, null, null, null);
        b.Foreground = (SolidColorBrush)converter.Convert(Element.ArrowsTintColor, null, null, null);
    }
}
```

Any help will be appreciated!

**Comment by GuyMicciche** [comment]
Hey! So I'm thinking you should start basic, such as using:

`b.Background = new SolidColorBrush(Color.FromArgb(255, 38, 186, 154));`

Try that, and see if that will work. If it does, then just replace the values in the FromArgb method. If it does not work, then maybe you are accessing the wrong VisualChild. Let me know if the above statement works. If it doesn't then I can go and do more research...

**Comment by alexrainman** [comment]
Already tried that w no luck.

**Comment by GuyMicciche** [comment]
Can you send me a project with the code you are using for testing so I can take a look? I have a few suspicions...

Guy

**Comment by alexrainman** [comment]
I am going to commit my changes here so you can download and run your tests.

**Comment by GuyMicciche** [comment]
Thanks Alex, can you let me know when you do it? Also, where exactly I can download your changes, cause i'm new to the whole git thing. Thanks!

**Comment by alexrainman** [comment]
You can download the repository as a zip or use github client to clone it.
