### ISSUE TITLE
[iOS] Blank Page

### ISSUE THREAD

**Issue by Raystorm7** [alexrainman/CarouselView#248]
Hi, 
I load the ItemSource of the CarouselView with a List of DataTemplate. In Android and UWP works like a charm, but in iOS nothing is showed, only the blank page.

[Here the link to stackOverflow] (https://stackoverflow.com/questions/47133700/xamarin-carouselview-ios-blank-page)

[Here the link to the full sample project] (https://uploadfiles.io/h9446)

I use the version 4.4.6.

**Comment by aboulinguez** [comment]
I'm facing a similar problem. My CarouselView works perfectly in Android but still blank in iOS.

**Comment by Raystorm7** [comment]
On stackOverflow a user posted this solution: 
edit the AppDelegate.cs in IOS project like this

`public override bool FinishedLaunching(UIApplication app, NSDictionary options) {
    global::Xamarin.Forms.Forms.Init();
    CarouselViewRenderer.Init();   //Add this line.
    LoadApplication(new App());

    return base.FinishedLaunching(app, options);
}`

Now the IOS project works!

**Comment by aboulinguez** [comment]
This is what happens when you configure the Android project and then the iOS project few weeks later... you forget the CarouselViewRenderer.Init(); ...

Thanks @Raystorm7 and thanks to @alexrainman for its component !
