### ISSUE TITLE
Get/Set BindingContext value from ContentView

### ISSUE THREAD

**Issue by Raystorm7** [alexrainman/CarouselView#249]
Hi,
I have a CarouselView configurated in this way:

    _AggiungiRigaWOViewModel = new AggiungiRigaWOViewModel(_WoSelezionato);
    CarouselView.Position = 0;
    CarouselView.ItemsSource = new ObservableCollection<DataTemplate>() { /
                new DataTemplate(() => { return new AggiungiRigaWOData(); }),
                new DataTemplate(() => { return new AggiungiRigaWOViaggioAndata(); })
            };
            CarouselView.BindingContext = _AggiungiRigaWOViewModel.WoSel;

Then, in the first page, i need to create dynamically some views like this:

    public AggiungiRigaWOData() {
            InitializeComponent();
            
            DatePicker Dpicker = new DatePicker() {
                VerticalOptions = LayoutOptions.CenterAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
            };

            Dpicker.SetBinding(DatePicker.DateProperty, "dt_inizioIntervento"); // dt_inizioIntervento is a property of _AggiungiRigaWOViewModel.WoSel
            StackLay.Children.Add(Dpicker, 0, 1);
    [...]

Then I would like to make a button that get all values of the bindingContext to see what is changed.
How can I do this?

Thank you! :)

EDIT: [here ](https://uploadfiles.io/utans)a zip with full project

**Comment by Raystorm7** [comment]
The button will be located inside one (or more) of `ContentView `inside the main `CarouselView`.

**Comment by alexrainman** [comment]
To make it work use a List or ObservableCollection as CarouselView ItemsSource. The list will include the objects or ViewModel you want to use as BindingContext of each View in the Carousel. Then you use a TemplateSelector to return the View you want on each position. The Carousel internally will assign BindingContext. Later you can see what changed just checking CarouselView.ItemsSource.
