### ISSUE TITLE
Using DynamicResource for view inside CarouselView

### ISSUE THREAD

**Issue by JimmyPun610** [alexrainman/CarouselView#250]
Xamarin Form version : 2.4.0.282
CaroselView version : 4.4.6

After update my Xamarin Form from 2.3.4.267 to 2.4.0.282 and CarouselView form 4.4.3 to 4.4.6. I found out control in carouselview will not causing change in value. But the problem not happen with 4.4.3 and 2.4.0.282.

Sample here : https://www.sendspace.com/file/wa6c97

**Comment by alexrainman** [comment]
What do you mean with this "I found out control in carouselview will not causing change in value."?

**Comment by JimmyPun610** [comment]
I mean when our listview cell item using dynamic resource to control its content, if the dynamic resource changed, the content of cell will not change in version 4.4.5 or above. The simplest sample we can make is that we create a listview inside one of page in carouselview. Set the cell text color by dynamic resource, every time we refresh the list, change the dynamic resource. you will see the textcolor do not change with the dynamic resource in version 4.4.5 or above.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
