### ISSUE TITLE
Horizontal Scrolling Too Sensitive

### ISSUE THREAD

**Issue by NeilIrvingMacc** [alexrainman/CarouselView#251]
Hi Guys

We are looking at your CarouselView as it seems the recommended alternative to the current Xamarin Forms CarouselView.

We have your example code of how to use it and have upgraded the Nuget packages so it works with XF 2.4.0.38779 (Latest)

When we run it on Android, Ios or Windows if we are inside a Carousel View which comes from a DataTemplate and has a ListView inside it, if we while scrolling up and down the list go to the left or right a small amount the current view or page in Carousel changes.  How can we prevent this from happening on such a small swipe gesture?

Thanks

Neil

**Comment by alexrainman** [comment]
That's a bug on Xamarin.Forms and not the control. There's a bug in bugzilla https://bugzilla.xamarin.com/show_bug.cgi?id=59863
