### ISSUE TITLE
Can we use the carousel with XAML only? No bindings? 

### ISSUE THREAD

**Issue by KieferJohnson** [alexrainman/CarouselView#252]
Is it possible to add this carousel in xaml without needing a binding? Or is it currently set up to only be created from data?
Something like this is what im trying to get at.

```
<controls:CarouselViewControl HeightRequest="200">
    < carouselSlideOne>
          < stacklayout>
               //static xaml content
         </ stacklayout>
   </ carouselSlideOne>
   < carouselSlideTwo>
        < stacklayout>
              //static xaml content
        < /stacklayout>
   < /carouselSlideTwo>
</controls:CarouselViewControl>
```

Thanks

**Comment by alexrainman** [comment]
Yes, it is possible. The answer is on the documentation :)

**Comment by KieferJohnson** [comment]
Ok so it is possible. I'm new to using xamarin, so I must just suck at reading docs haha.

Thanks for the response.

**Comment by alexrainman** [comment]
No worries. Just explore the repository Readme file and you will find how to do it.
