### ISSUE TITLE
Custom CarouselViewRenderer not working?

### ISSUE THREAD

**Issue by michalstachecki** [alexrainman/CarouselView#254]
Hello,

I'm using CarouselViewControl 4.4.2 with Xamarin.Forms 2.3.4.231. I'm trying implement custom view renderer for CarouselViewControl, but it's not firing. Could you explain me why?

Code example:

```
using System;
using Xamarin.Forms;
using MyWebView.Droid.CustomRenderers;
using CarouselView.FormsPlugin.Abstractions;
using Android.Views;
using Android.App;
using Android.Widget;
using Xamarin.Forms.Platform.Android;
using CarouselView.FormsPlugin.Android;

[assembly: ExportRenderer(typeof(CarouselViewControl), typeof(CarouselCustomRenderer))]
namespace MyWebView.Droid.CustomRenderers
{
    public class CarouselCustomRenderer : CarouselViewRenderer
    {
        protected override void OnElementPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);
        }

        protected override void OnConfigurationChanged(Android.Content.Res.Configuration newConfig)
        {
            base.OnConfigurationChanged(newConfig);
        }

    }
}

```

**Comment by michalstachecki** [comment]
Up

**Comment by adrianknight89** [comment]
@michalstachecki I tried your code and wasn't able to get it to work either. It seems the custom renderer is not being registered. For example, this did not throw an exception:

```
public CarouselCustomRenderer()
{
     throw new Exception();
}
```

I've never had to create a custom renderer for a third-party library, so I'm not sure if this is specific to this library or all plugins. Did it work in previous versions?

**Comment by michalstachecki** [comment]
@adrianknight89 4.4.2 is my first development with Carousel View. I've tried other versions (from 4.0.0 above) and renderer not working too.

Thanks for reply, issue could be closed on this moment.

**Comment by alexrainman** [comment]
This a Xamarin Forms issue. If you create a subclass of the carousel control the custom renderer will be called:

MyCarouselControl : CarouselViewControl
{
}

Did you add the annotation to register the custom renderer?

**Comment by michalstachecki** [comment]
@alexrainman Your code works, thanks. What do you mean by "annotation to register the custom renderer"?
