### ISSUE TITLE
Scroll percent of view / page inside the carouselview

### ISSUE THREAD

**Issue by modplug** [alexrainman/CarouselView#255]
This is more of a feature request than an actual issue. But I just want to know if you think it's feasible to get the amount of scroll for each slide? I need something like this in order to make parallax effects with the CarouselView. 

Keep up the good work 👍

**Comment by alexrainman** [comment]
I already tried to implement this. Not doable.

**Comment by alexrainman** [comment]
I was able to implement this.

**Comment by modplug** [comment]
Great news! 👌
