### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by OpticNectar** [alexrainman/CarouselView#256]
I'm getting this error using the `CarouselView`with `ffimageloading:CachedImage`:

```
Cannot access a disposed object. Object name: 'Android.Graphics.Bitmap'
```

I tried setting `DownsampleToViewSize` and `DownsampleWidth`, but the error still happens and I need the width to fill the view anyway.

**Comment by alexrainman** [comment]
Not related to this control.
