### ISSUE TITLE
[Android] ListView scrolls to the top as you swipe right and left on the CarouselView

### ISSUE THREAD

**Issue by adrianknight89** [alexrainman/CarouselView#258]
I created three custom views where the content in each is a ListView.

User steps:
 - Scroll on the first ListView
 - Swipe left and scroll on the second ListView
 - Swipe left and scroll on the third ListView
 - Swipe right to the first position

Issue:
 - Observe that list views no longer have their latest position as they default to the first item in the collection

Observations:
- Resetting seems to happen with the **first** and **last** views in the CarouselView and _only_ after the third view is shown to the user.
- When there are only two views (A and B), the issue does not exist.

Please see attached demo:

[App3.zip](https://github.com/alexrainman/CarouselView/files/1476783/App3.zip)

Tested on an S6 device with CarouselView 4.4.6 and XF 2.5.0.77107.

**Comment by adrianknight89** [comment]
@alexrainman The issue seems to be happening because of https://github.com/alexrainman/CarouselView/blob/30d89a711ee62ccc80a8332f7ad4961113c24d4b/CarouselView/CarouselView.FormsPlugin.Android/ViewExtensions.cs#L15

May I ask why this line was commented out? A new renderer is being created each time position changes.

**Comment by alexrainman** [comment]
The issue is not caused because of that line. In both platforms a max of 3 views is kept on memory for a smooth swipe transition. The views that go off screen are G collected and removed from memory. They are created again once you swipe back to that position. I tested keeping views in memory but users complained about memory leaks on large carousels. Are you using a list of views as source? That line was commented because it was causing another issue i dont remember now.

**Comment by adrianknight89** [comment]
Yes. The source was 

`myCarousel.ItemsSource = new ObservableCollection<ContentView> { new A(), new B(), new C() };`

I also tried 

```
myCarousel.ItemsSource = new List<DataTemplate>()
{
        new DataTemplate(() => { return new A(); }),
        new DataTemplate(() => { return new B(); }),
        new DataTemplate(() => { return new C(); })
};
```

`ViewPager` has a setter for off screen page limit: [setOffScreenPageLimit()](https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int)). By default, it's set to 1. 

Looks like XF has exposed it as a platform-specific property in `TabbedPage`.

https://github.com/xamarin/Xamarin.Forms/blob/b2e2a8ff2a768e01fd8ee155c519de4bee310fb3/Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/TabbedPage.cs#L44

Should the same be exposed in `CarouselView` as well?

As for the line that was commented out, I think it might be a good idea to add some documentation there so that it's not uncommented in the future, especially if this is going to be rolled into the XF main branch (not sure if it's still happening?).

**Comment by alexrainman** [comment]
What about the same scenario in iOS?

**Comment by adrianknight89** [comment]
It works on iOS. This is only an Android issue.

**Comment by alexrainman** [comment]
You are right, commenting this line https://github.com/alexrainman/CarouselView/blob/30d89a711ee62ccc80a8332f7ad4961113c24d4b/CarouselView/CarouselView.FormsPlugin.Android/ViewExtensions.cs#L15 was causing this issue. Will release new version soon.

**Comment by adrianknight89** [comment]
@alexrainman Was this fix ever released?

**Comment by alexrainman** [comment]
Yes.

**Comment by adrianknight89** [comment]
This issue still exists in 5.2.0 and XF 2.5.0.122203. See the updated repro.

[fgg.zip](https://github.com/alexrainman/CarouselView/files/1672096/fgg.zip)
