### ISSUE TITLE
[Android] Using ListViewCachingStrategy.RecycleElement throws a runtime error

### ISSUE THREAD

**Issue by adrianknight89** [alexrainman/CarouselView#259]
If each view is using a `ListView` which opts in for `RecycleElement` strategy, this results in a runtime error when the app is run.

See repro.

[App3.zip](https://github.com/alexrainman/CarouselView/files/1477271/App3.zip)

If you change this to `RetainElement` in the constructor of `CListView`, then everything runs fine.

Tested on an S6 device with CarouselView 4.4.6 and XF 2.5.0.77107.

**Comment by alexrainman** [comment]
I am trying to identify where this issue is coming from.

**Comment by adrianknight89** [comment]
I ran this on top of latest XF master branch. I don't see a runtime error, but cell recycling does not work. (Items 1-20 loaded in place of items 21-99).

I will test this again with the fix for #258 and a future XF release.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
