### ISSUE TITLE
CarouselView not worked with ListView in Xamarin.Forms version above 2.3.1.114 on Android

### ISSUE THREAD

**Issue by windsql** [alexrainman/CarouselView#26]
Add a ListView to the CarouselView it worked well in Xamarin.Forms  2.3.1.114,but not worked above it.
[CarouselView.zip](https://github.com/alexrainman/CarouselView/files/518749/CarouselView.zip)

**Comment by alexrainman** [comment]
@windsql the issue is not related to CarouselView. There's a bug in Xamarin.Forms  core. This:

```
Platform.SetRenderer(view, Platform.CreateRenderer(view));
```

Doesn't works anymore and the exception comes from native android ListView.SetAdapter call.

I cannot do anything about it. My advice? downgrade to previuos version of Forms. Basically the last two version of Forms are buggy.

**Comment by windsql** [comment]
Ok,I found another CarouselView control,it worked well with the new version
of Xamarin.Forms ,
Xamarin.Forms.CarouselView(https://github.com/alexrainman/CarouselView)
maybe you will find something in it.


2016-10-12 11:27 GMT+08:00 Alex Rainman <notifications@github.com>:

**Comment by alexrainman** [comment]
@windsql you just send me a link to my own repo :)

**Comment by windsql** [comment]
Sorry,the correct is https://github.com/xamarin/Xamarin.Forms.CarouselView

2016-10-12 11:42 GMT+08:00 Alex Rainman <notifications@github.com>:

**Comment by alanspires** [comment]
So is this to say that you don't plan on supporting newer versions of Xam.Forms?

**Comment by alexrainman** [comment]
Not until the release an stable version. Both latest releases are buggy and don't play good with Xamarin.iOS 10 and Xamarin.Android 7. Also latest couple of releases of Xamarin Studio generates bugs when you build you app.

**Comment by alexrainman** [comment]
By the way, carousel will work with latest versions of Forms but you cannot use a ListView inside a page. I reported the problem to Xamarin.

**Comment by alanspires** [comment]
Unfortunately that's exactly what I'm trying to do lol. What exactly is the issue with that and can I get the bugzilla link so i can track it?

**Comment by alexrainman** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=44846

**Comment by alanspires** [comment]
Doesn't look like they are going to touch that without a repo.

**Comment by alexrainman** [comment]
I am going to refer them to this plugin repo, easier way to reproduce it.

**Comment by alexrainman** [comment]
Fixed.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
