### ISSUE TITLE
Crashing on Android with the 2.5+ packages of Xamarin.Forms

### ISSUE THREAD

**Issue by JaridKG** [alexrainman/CarouselView#261]
I plan on investigating this further today, just wanted to log it before hand in case anyone had any ideas first.

Xamarin.Forms: 2.5+
Support libraries: 25.0.4.2
Carousel package: 4.4.6

**Exception Thrown:**
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.InvalidCastException: Specified cast is not valid.
[MonoDroid]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer+PageAdapter.DestroyItem (Android.Views.ViewGroup container, System.Int32 position, Java.Lang.Object object) [0x00000] in <987b2fd695d94047809eece606991303>:0 
[MonoDroid]   at Android.Support.V4.View.PagerAdapter.n_DestroyItem_Landroid_view_ViewGroup_ILjava_lang_Object_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_container, System.Int32 position, System.IntPtr native__object) [0x00018] in <fc4222de5c684a9abf7cc4821baac4cd>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object:bd754f98-f043-4a88-8d40-ed8af91773a0 (intptr,intptr,intptr,int,intptr)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

**Comment by JaridKG** [comment]
It appears that @Object doesn't always get passed in as type ViewGroup, changing the code to use as rather than a direct cast to allow it to be null is at least a temporary fix

**Comment by arnaudmaichac** [comment]
After updating my app to Xamarin.Forms 2.5, I have the exact same issue on my side.

**Comment by arnaudmaichac** [comment]
@JaridKG by recompiling the CarouselView with Xamarin.Forms 2.5 and adapting the implementation of the CarouselViewRenderer on Android (the default constructor of ViewRenderer is obsolete as of version XF 2.5), I don't have the issue anymore.

**Comment by alexrainman** [comment]
The default constructor of ViewRenderer is obsolete as of version 2.5?

**Comment by arnaudmaichac** [comment]
@alexrainman Have a look at the release notes of XF 2.5 https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.5/2.5.0-stable/

**Comment by alexrainman** [comment]
Im in the process of a big update of the plugin. I updated to 2.5 and saw no difference. Will take a look.

**Comment by alexrainman** [comment]
If i implement the new constructor then i get an exception: System.MissingMethodException Constructor on type 'CarouselView.FormsPlugin.Android.CarouselViewRenderer' not found.

**Comment by JaridKG** [comment]
Try adding public CarouselViewRenderer()
            : base(null) {
            // Default constructor needed for Xamarin Forms bug?
        }


worked for me off a forum post

**Comment by alexrainman** [comment]
Thats what i did :)

**Comment by alexrainman** [comment]
Will close this and release new version.

**Comment by JaridKG** [comment]
@alexrainman the 5.0 version is still crashing for me

**Comment by alexrainman** [comment]
No idea why. Please provide a demo.

**Comment by JaridKG** [comment]
So it looks like just having a cached image in the data template was crashing. Wrapping it in a ContentView fixed it. I think a cached image can't be force cast to ViewGroup in the new versions
