### ISSUE TITLE
[Request] Create a UI Test project so automation can detect breaking changes

### ISSUE THREAD

**Issue by adrianknight89** [alexrainman/CarouselView#262]
Just wondering if we can add some UI tests and automate them with every release so breaking changes can be detected. I know there is a Demo project, but it's not run through the Xamarin.UITest API.

**Comment by alexrainman** [comment]
If you can create that project and do a pull request, i will include it. Thanks

**Comment by adrianknight89** [comment]
@alexrainman Should we expect `CarouselView` to be merged to XF soon? Since they have a UI test project there, it'll be easy to submit test cases. Also, I believe the issues here would also need to be migrated to their backlog.

**Comment by alexrainman** [comment]
Yeah, Xamarin just asked me to target their master branch. Im fixing some bugs first. I think it will be merged in version 3.
