### ISSUE TITLE
Navigation Arrows doesn't disappear when using swipe

### ISSUE THREAD

**Issue by ruisilva450** [alexrainman/CarouselView#265]
Hi,
I recently updated to version 5.0.0 and now I can see the navigation arrows on Android (and iOS I assume).
Thanks for that!

However, when I navigate using swipe, it seems that the arrows don't update according to position.
For example, when I have 3 views to navigate, I swipe to the third view and the right arrow is still there and there is no left arrow yet. In this case, if I tap the right arrow the view doesn't change but the left arrow appears. If I tap the right arrow again, this on disappears leaving only the left one. At this stage, I tap the left arrow and the carousel navigates to the second view correctly.

My conclusion is that swipe updates one "Position" and arrows update another "Position".

**Comment by alexrainman** [comment]
Thanks for reporting this. Releasing version 5.0.1 today.
