### ISSUE TITLE
[iOS] Sticky carousel view on swipe

### ISSUE THREAD

**Issue by Ruddy2007** [alexrainman/CarouselView#266]
I have a `ListView` with a image header and `ImageCell` on my `CarouselViewControl` for each page (max of 8 pages all the same layout of `ListView`). On iOS when swiping left or right the view "sticks" for a few seconds/milliseconds causing what seems like "lag". The scrolling then jumps when its "unstuck".

I cannot find a way to make this smooth, I'm guessing its how the carousel view locks on to a page and then releases the lock on the page to allow scrolling. Fixing this issue would give us the amazing smooth scroll we need.

If you moving the carousel view after the page is locked (scroll a little) and let it still sit on the same page, when scrolling from then its smooth again (no jumping affect as you already have "unlocked" the view).

Same app running on android and I do not get this sticking problem.

Any ideas for this?

**Comment by alexrainman** [comment]
How are you configuring the carousel source? That lag may be related to each view rendering but why there's a lag in iOS? No idea. I will have to see some code.

**Comment by Ruddy2007** [comment]
@alexrainman Hey, sorry for not showing any code. Its a project I am unable to share but I will try to get a example project so we can do some testing on this.

**Comment by Ruddy2007** [comment]
Just having a little look (will still try and post some code soon) but it seems to be where I have the `listview` `itemsource` binding. So instead I am now using `OnBindingContextChanged` and setting the `itemsource` that was but having the same slow, lagging experience. 

Just as a test I have put a 5 second delay inside `OnBindingContextChanged` before setting the `itemsource` and the carousel view runs smooth until the `listview` is populated. 

This could just be bad optimisation on the Xamarin side for `ListView` but Im not sure yet. Just a quick update before I forget.

**Comment by alexrainman** [comment]
Can i close this?

**Comment by Ruddy2007** [comment]
@alexrainman Sorry, I have been a bit busy. Will get back to this when I have an example to show.
