### ISSUE TITLE
Carousel Not Updating when Collection Set to Item Source Changes

### ISSUE THREAD

**Issue by jommille** [alexrainman/CarouselView#267]
The title sums it up pretty well, when we update the collection that is set to the ItemSource the Carousel is not updating to reflect that change. We are seeing this in 5.0.1 on UWP and Android. We haven't tested iOS.  

What we have is an ObservableCollection of ViewModels that is set to the ItemSource for the Carousel. 
When we insert a new ViewModel into to the collection, the Carousel is not updating to display the new item.

This item might be related to or a duplicate to #240.

**Comment by alexrainman** [comment]
Adding a new item is not enough, you have to change the position to the index where the new item has been inserted or swipe to it.

**Comment by jommille** [comment]
I've tried both setting the position and swiping to it and the item isn't anywhere in the carousel.

**Comment by jommille** [comment]
My apologies, the problem was a subtle error on the part of a developer that left like 4 weeks ago. I'm still not sure how we didn't catch the error sooner.
