### ISSUE TITLE
How to get hold of the datatemplate instance?

### ISSUE THREAD

**Issue by joshk6** [alexrainman/CarouselView#275]
Hi, wondering if there is some way to get hold of actual instance of the data template shown on a carousel page so I can call a method on it.  The only way I can figure out how to do that is to cache the created pages in the constructor of the content page that is created by the carousel view, but seems like there must be an easier way.

**Comment by alexrainman** [comment]
Do you want to call a method on the DataTemplate or in View returned by it? Because if thats the case you can use a List of Views as source of the carousel and then based on the position you can identify the current view and call your method.
