### ISSUE TITLE
Swiping not working on iOS with another gestures in the same Page

### ISSUE THREAD

**Issue by stringo** [alexrainman/CarouselView#276]
I'm using the plugin in an image gallery for both platforms (iOS & Android)

Basically, I've created a custom Image class that supports double tap and gestures for zoom purposes.

The issue is:

I can't swipe the CarouselView if I try to do it in the image itself, I think there's a conflict with the image's gestures. If I try to swipe outside the image it works as expected. This issue happens in iOS only.

Here's my code:
https://gist.github.com/stringo/45d40a3a0511e2894c5b962bd4c0c2a4

Here's a live demo of the issue:

![Screen capture iOS](https://media.giphy.com/media/xUOxflz5raTOAZOpfW/giphy.gif) 

In Android this is working OK:

![Screen capture Android](https://media.giphy.com/media/3osBL4AnRkKCu70AGk/giphy.gif)

**Comment by alexrainman** [comment]
Can you try setting InputTransparent to true on this custom images?

**Comment by stringo** [comment]
@alexrainman, it works but I lost the Zoom capabilities.

**Comment by stringo** [comment]
@alexrainman  I think I got it, let me work on this and will let you know asap.

**Comment by alexrainman** [comment]
Great, this is a very cool functionality.

**Comment by alexrainman** [comment]
Did you get it working? Can i close this?

**Comment by stringo** [comment]
Not there yet, but you can close it for now. I'll open another issue if needed. Thanks!
