### ISSUE TITLE
InvalidCastException after second swipe on CarouselViewControl (it crashes app)

### ISSUE THREAD

**Issue by AndreiMisiukevich** [alexrainman/CarouselView#277]
version 5.0.2
Error occurs only on Android OS
On iOS is ok

**Comment by AndreiMisiukevich** [comment]
`ItemTemplate = new DataTemplate(() => new Label {
                                    Text = "afsasfaf"
                                }),`

**Comment by AndreiMisiukevich** [comment]
```
 new DataTemplate(() => new ContentView {
                                    Content = new Label 
                                    {   
                                    }
                                });
```

But it works

**Comment by AndreiMisiukevich** [comment]
And I think you hastened to set constraints for Xamarin.Forms.
Because the latest pack is unstable. Sometimes it crashes on viewcellrenderer (on ios...)

XF 2.4.0.282 more stable

**Comment by alexrainman** [comment]
ViewCell is not needed in the carousel.

**Comment by AndreiMisiukevich** [comment]
Sorry)
My last message isn't related to problem)
It's just proposition and reason example.

Because your pack requires latest XF (

**Comment by AndreiMisiukevich** [comment]
So
ItemTemplate = new DataTemplate(() => new Label { Text = "afsasfaf" }), //CRASH

 new DataTemplate(() => new ContentView {
                                    Content = new Label 
                                    {   
                                    }
                                }); // invalidcastexception occurs


Maybe, somewhere there is cast to **Layout** type, not to **View** type

**Comment by alexrainman** [comment]
I cannot reproduce this. It works for me.

**Comment by AndreiMisiukevich** [comment]
thanks for feedback
if I have time, I will explain more info and create sample project.

Because I found WorkAround for me (using ContentView with Label content instead of just Label)
