### ISSUE TITLE
[Android] Out of memories (FFImageLoading + CarouselView)

### ISSUE THREAD

**Issue by idimkk** [alexrainman/CarouselView#279]
Hello.

I use CarouselView and FFImageLoading (Xamarin Forms) to display pictures from archives in the stream. Full-size images, full-page.
Usually one image weighs after extraction 1.5MB (format jpg/png). When rendering, images are usually about 6MB.

With a standard heap - about 200-250MB, the overflow is very fast, 10-20 photos are enough, depending on the settings of DownsampleWidth.
Desired result: view 150+ photos.
Pictures are displayed sequentially. It is necessary to store only 3-5 nearest photos from behind and in front.

I tried several implementations that would change the collection and fill it up on demand, but the old images are not unloaded from their RAM. I use the Using design everywhere - it does not help either.
I attached a piece of my implementation, with detailed comments.

[Sample code](https://pastebin.com/e219v8ev)

I'm not sure what the problem is in your library. But perhaps you can suggest a solution to this problem.

Best Regards,
Dmitriy.

**Comment by alexrainman** [comment]
Let me take a look but it should work.

**Comment by alexrainman** [comment]
Why do you need to open images using Streams? Do you know image names before loading them?

**Comment by idimkk** [comment]
Thank you for your response. The images are in the archive, if it is required, I can unpack them and take them from there.
I tried this implementation, created a collection of images on the disk.
RAM still added to 6MB, with each page view(with a width of 1080/ 3mb at 680). And it was not cleared when the image ceased to be visible.

**Comment by alexrainman** [comment]
In this part of the code:

```
var newStream = entry.OpenEntryStream();
var ImageStream = new MemoryStream();
newStream.CopyTo(ImageStream);
newStream.Dispose();
 
var byteArray = ImageStream.ToArray();
collection.Add(new CachedImage()
{
    Source = ImageSource.FromStream(() => new MemoryStream(byteArray)),
}
```

Can you use newStream or ImageStream directly as source of the CachedImage?

You are creating 3 streams.

**Comment by idimkk** [comment]
Yes, I can do so. 
```
var newStream = entry.OpenEntryStream();
collection.Add(new CachedImage()
{
    Source = ImageSource.FromStream(() => newStream)
}
```
This does not change the situation. I can collect a test project for you, if it is more convenient.
Thank you for your help.

**Comment by alexrainman** [comment]
Take a look at this thread https://github.com/alexrainman/CarouselView/issues/297, maybe you are facing the same issue. Are you implementing PropertyChanged in the ItemsSource?

**Comment by idimkk** [comment]
Yes, I do it. It did not help.

**Comment by KSchau** [comment]
I am also encountering the same thing - I have a large collection of images (100+) that I am putting in the carousel and they are never being unloaded from memory. Each time I swipe through 10-20 images, even with FFImageLoading, I am running out of memory.

I use the CarouselViewControl in XAML as follows: (with a few modifications for brevity)

`<controls:CarouselViewControl x:Name="Carousel"
                              ItemsSource="{Binding Articles}"
                              IsVisible="{Binding CarouselVisible}"
                              Position="{Binding Position}"
                              IsEnabled="{Binding CarouselEnabled}"
                              InterPageSpacing="10"
                              HorizontalOptions="FillAndExpand">
	<controls:CarouselViewControl.ItemTemplate>
		<DataTemplate>
			<ScrollView Orientation="Vertical"
					    HorizontalOptions="FillAndExpand">
				<ff:cachedImage Source="{Binding ImageFilePath}"
							    Aspect="AspectFit"
								
						            HorizontalOptions="FillAndExpand" VerticalOptions="Start"/>
			</ScrollView>
        </DataTemplate>
    </controls:CarouselViewControl.ItemTemplate>		
</controls:CarouselViewControl>`

Where 'Articles' is an ObservableCollection<Article> and each 'Article' in the collection has an 'ImageFilePath' that points to the location of the File on the device. 

I have tried everything I in the ReadMe and everything from above suggestions without much luck. Do you have any suggestions in regards to eliminating the OutOfMemoryException I get when swiping through images in the carousel?

**Comment by KSchau** [comment]
I dug a little deeper today and took a look at the CarouselViewRenderer. I noticed that in the PageAdapter class (CarouselView.FormsPlugin.Android.CarouselViewRenderer.PageAdapter), if I call `view.Dispose( )` as below, I am able to swipe through as many images as I like:

CarouselView.FormsPlugin.Android.CarouselViewRenderer [635]
`public override void DestroyItem( AViews.ViewGroup container, int position, Java.Lang.Object @object )
{
    var pager = (ViewPager)container;
    var view = (AViews.View)@object;
    pager.RemoveView( view );
    **view.Dispose( );**
}`

The memory still progressively climbs when using the carousel, however, albeit at a much slower rate. Without `view.Dispose( )`, memory was increasing by a massive amount (20MB or so) with every image scrolled. After adding it, increases are more like 1-2MB and happen sporadically rather than with every swipe. 

Running GC every few `DestroyItem` calls also seems to help keep the memory usage down when using the Carousel.

Hope this helps!

**Comment by alexrainman** [comment]
I will add this in the new release.

**Comment by KSchau** [comment]
Thank you! This is the only issue I've had with your phenomenal control and I look forward to future use.

**Comment by SilvioFusaro** [comment]
Hi Alex, as KSchau said "The memory still progressively climbs when using the carousel, however, albeit at a much slower rate.".
I am including several images in each slide. The memory requirement increases progressively as the user moves through them. The view.Dispose (); helps but I believe that GC is not clear the view at all. Looking for how to solve the problem I found this article ((http://blog.vicreative.nl/category/xamarin/)
which says that Views have a callback that prevents them from being released by the GC. Perhaps the problem can be completely solved by simply adding view.Background.Callback = null; before the dipose method.
Hope this helps!

**Comment by alexrainman** [comment]
I am incorporating this fix to the next release.

**Comment by SilvioFusaro** [comment]
Thank you. Excellent work!
