### ISSUE TITLE
Android error - Attribute "radius" already defined with incompatible format.

### ISSUE THREAD

**Issue by hachirokoo** [alexrainman/CarouselView#28]
Hi, Thanks for the great component by the way,
I got the following error while compiling my Xamarin forms Android project.
It seems like some clash with other libraries. I am using Xamarin Forms 2.3.2.127.
Thanks!

![capture](https://cloud.githubusercontent.com/assets/3174253/19953710/2dd02ff6-a1c5-11e6-8be2-9afc9629f2b9.PNG)

**Comment by alexrainman** [comment]
Hi, can you review your project and take a look where "radius" is defined? Or, tell me which other libraries are you using? Thanks

**Comment by alexrainman** [comment]
Next release.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
