### ISSUE TITLE
Need help to extend the controll

### ISSUE THREAD

**Issue by shoeIT** [alexrainman/CarouselView#280]
Hello, 
I try to extend your controll, but I don't succeed maybe you have a tip.
If I am on the first page (position 0) and swipe left nothing happens, since there is no position -1.
But I need to react on this event to open a global menue. Is it possible to catch that gesture in some way?

I've created a custom renderer, which is basically your CarouselViewRenderer and tried to adapt the 
'pageController.GetPreviousViewController' function, but no luck until now.

**Comment by alexrainman** [comment]
This is only iOS?

**Comment by alexrainman** [comment]
I am planning to add something called LoadMore. It will be an event that will be called when you drag from the right side.

**Comment by alexrainman** [comment]
But, you can use MR.Gestures to add that type of event on top of the Carousel or the View that you have in position 0.

**Comment by shoeIT** [comment]
Thanks for your tip Alex, it helped and I could figure it out wit Mr.Gestures.
A LoadMore event on both ends of the control would be awsome!
