### ISSUE TITLE
Images not showing when inside a scrollview in Xamarin Forms 2.4.x and 2.5.x

### ISSUE THREAD

**Issue by soile1991** [alexrainman/CarouselView#281]
This worked fine on 2.3.x.
do i need to do something deferent in this version in order to have the carousel an the ability to scroll vertically and be able to show images?

 `
<controls:CarouselViewControl Orientation="Horizontal" InterPageSpacing="5" Position="0" ItemsSource="{Binding myItems}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" x:Name="myCarousel">
  <controls:CarouselViewControl.ItemTemplate>
    <DataTemplate>
      <ScrollView x:Name="scrollView" Orientation="Vertical" VerticalOptions="FillAndExpand">
        <StackLayout Orientation="Vertical" VerticalOptions="FillAndExpand">
          <ffimageloading:CachedImage DownsampleToViewSize="true" Aspect="Aspect" Source="image1.png" />
          <Image Source="{Binding iTestIcon}" VerticalOptions="Start" HorizontalOptions="End" />
        </StackLayout>
      </ScrollView>
    </DataTemplate>
  </controls:CarouselViewControl.ItemTemplate>
</controls:CarouselViewControl>
`

**Comment by alexrainman** [comment]
There's a problem with ScrollView in 2.4.x and up. Why you need ScrollView then Stacklayout wrapping the image?

**Comment by soile1991** [comment]
I need it because I have many clickable images stacked vertically in each Carousel Tab.
See the images below.

![screenshot_20171201-124900](https://user-images.githubusercontent.com/2981939/33479789-10c3c19a-d697-11e7-82ca-da09b1a98600.png)
![screenshot_20171201-124906](https://user-images.githubusercontent.com/2981939/33479795-150a9076-d697-11e7-8e5b-464259287995.png)

**Comment by alexrainman** [comment]
Try Wrapping ScrollView into another StackLayout.

**Comment by anoopmom** [comment]
guys, did you find a solution for this?
