### ISSUE TITLE
Xamarin Android project resource errors

### ISSUE THREAD

**Issue by malibu** [alexrainman/CarouselView#282]
I'm getting a lot of undefined resource errors when compiling with latest 5.0.0 and above
(Visual studio 2015) cross platform with android.

Brand new project, add 5.0.0 nuget, compile, get a ton of the following compilation error messages

c:\development\<appp>\Resources\Resource.Designer.cs(43,117,43,130): error CS0117: 'Resource.Animation' does not contain a definition for 'tooltip_enter'
... and about few hundred other resources

**Comment by alexrainman** [comment]
No idea but not related to this control.

**Comment by malibu** [comment]
OK. I fixed it. It depends on a higher version of Xamarin.Android.Support.v7.MediaRouter than what I had.

Just for the record, nuget didn't complain. You need latest xamarin update, latest support libs then things are fine
