### ISSUE TITLE
[UWP] Carousel Resets to first item on resizing the view

### ISSUE THREAD

**Issue by JKennedy24** [alexrainman/CarouselView#283]
If you have a carousel item with 20 items.

Your selected item is index 10.

Resize the application and it will reset to index 0

**Comment by JKennedy24** [comment]
Using V5.0.2. Doesnt happen in V4.4.6

**Comment by alexrainman** [comment]
Are you using .Net Standard? Can't reproduce this. I will be releasing an update with support for .Net Standard 2.0

**Comment by JKennedy24** [comment]
I am using .Net Standard 1.4. I will update to the latest version and test again and report back

**Comment by JKennedy24** [comment]
Can't replicate using latest version so will close this bug off
