### ISSUE TITLE
Nested Gesture Recogniztion

### ISSUE THREAD

**Issue by Panter0389** [alexrainman/CarouselView#284]
Hi :),
I'm using a nested carousel and inside that I need the user to be able to move an image left and right. 
I've added a PanGestureRecognizer to the image but i need the carousel to stay still while I move the image around.
Is there a way I can modify carousel's "slide trigger area"?  Or ignoring slide when I tap on another element?

Here a gif of the problem: https://gyazo.com/460282e9b919f848199ebebc23517d38
i need to be able to move the fiches in the lower bar without the outer carousel to scroll

Thanks, Gabriele

**Comment by alexrainman** [comment]
You can play with InputTransparent property to let the parent carousel pass the event to the child one.
