### ISSUE TITLE
[Android] Entry focus issues

### ISSUE THREAD

**Issue by mikeberlin** [alexrainman/CarouselView#286]
I'm having the exact same issue as #136 but it was closed after being acknowledged as a bug but then later removed.

There's a pull request that addresses it #242, but I doubt it's being considered since the branch has merge conflicts.

Will you please consider this pull request? I cannot use Entry fields at all since they constantly lose focus because of the bug as stated (and reproduced) in #136

**Comment by mikeberlin** [comment]
Also, I have confirmed that pull request #242 resolves the issue I am seeing.

**Comment by alexrainman** [comment]
Does this issue happens in iOS? I know there's a problem with keyboard in UWP.

**Comment by mikeberlin** [comment]
Not that I've seen. I have only been able to reproduce this behavior in Android.

**Comment by alexrainman** [comment]
I will try to incorporate the PR that fix this.

**Comment by alexrainman** [comment]
Fixed.
