### ISSUE TITLE
[Android] App Crashes in Release Mode [if ShowArrows="True" XAML]

### ISSUE THREAD

**Issue by iampawan** [alexrainman/CarouselView#289]
App crash in release mode at displayalert. It works fine in debug mode. 
Error is -

Java.Lang.RuntimeException: Attempt to invoke virtual method 'void android.view.ViewGroup.setVisibility(int)' on a null object reference

**Comment by iampawan** [comment]
@alexrainman please help . I have to submit the app today .

**Comment by iampawan** [comment]
After updating the plugin .. New Bug 
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
[AndroidRuntime]   at CarouselView.FormsPlugin.Abstractions.IEnumerableExtensions.GetCount (System.Collections.IEnumerable e) [0x00000] in <7e01c51281f74bf4ae70fc7b037633c2>:0 
[AndroidRuntime]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetArrows () [0x000fc] in <cc3c65ffbd86484ab01ec771e5b3361a>:0 
[AndroidRuntime]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetNativeView () [0x00134] in <cc3c65ffbd86484ab01ec771e5b3361a>:0 
[AndroidRuntime]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.Element_SizeChanged (System.Object sender, System.EventArgs e) [0x00026] in <cc3c65ffbd86484ab01ec771e5b3361a>:0

**Comment by alexrainman** [comment]
Can you provide a demo?

**Comment by iampawan** [comment]
It is not producing in versions > = 5 . But the app crashes if showArrows=True is manually entered in XAML.

**Comment by alexrainman** [comment]
Let me check.

**Comment by alexrainman** [comment]
Do you have any png image named up, down, left or right?
