### ISSUE TITLE
CarouselView has bug  in .Net Standard Project

### ISSUE THREAD

**Issue by winstongubantes** [alexrainman/CarouselView#290]
CarouselView has bug  in .Net Standard Project, i was not able to make it work on my project and it says "No constructor found for CarouselView".

**Comment by sjorsmiltenburg** [comment]
I'm getting a 

`System.MissingMethodException: Default constructor not found for type CarouselView.FormsPlugin.Android.CarouselViewRenderer` when I try to run the following:

`	public class BookCarousel : ContentPage
	{
		public BookCarousel ()
		{
            var data = new List<BookPageViewModel>()
            {
                new BookPageViewModel(new FileService()){
                    BookPage =new BB.Shared.Dto.AppBookPageDto{
                        Audio =new BB.Shared.Dto.AppFileDto{
                            Id =new Guid("269E846A-C6A0-4110-968A-3CD11D429085"),
                            FileExtension =".mp3" },
                        EndSilence =0,
                        StartSilence =0,
                        Image = new BB.Shared.Dto.AppFileDto
                        {
                            FileExtension =".jpg",
                            Id =new Guid("269E846A-C6A0-4110-968A-3CD11D429085")
                        }
                    }
                },
                new BookPageViewModel(new FileService()) {
                    BookPage =new BB.Shared.Dto.AppBookPageDto{
                        Audio =new BB.Shared.Dto.AppFileDto{
                            Id =new Guid("B3F226CA-CC6B-42CA-9628-E8BFF966D7DF"),
                            FileExtension =".mp3" },
                        EndSilence =0,
                        StartSilence =0,
                        Image = new BB.Shared.Dto.AppFileDto
                        {
                            FileExtension =".jpg",
                            Id =new Guid("6B2FAE59-F3C8-41B7-A124-FA0A0D6FA257")
                        }
                    }
                }
            };

            var carousel = new CarouselViewControl()
            {
                ItemTemplate = new DataTemplate(() =>
                {
                    var contentPage = new ContentPage();
                    var image = new Image();
                    image.SetBinding(Label.TextProperty, "Image");
                    contentPage.Content = image;
                    return contentPage;
                }),
                ItemsSource = new ObservableCollection<BookPageViewModel>(data),
                ShowIndicators = true,
                ShowArrows = true,
                IsSwipingEnabled = true
            };
            carousel.SetBinding(CarouselViewControl.PositionSelectedCommandProperty, "MyCommand");

            Content = carousel;
            BindingContext = new MainViewModel();
		}

        public class MainViewModel : INotifyPropertyChanged
        {
            public event PropertyChangedEventHandler PropertyChanged;

            public ICommand MyCommand { protected set; get; }

            public MainViewModel()
            {
                MyCommand = new Command(() =>
                {
                    // Add the key to the input string.
                    Debug.WriteLine("Position Selected");
                });
            }
        }
    }`

**Comment by JKennedy24** [comment]
also seeing this

**Comment by jfevia** [comment]
Same error here

`System.MissingMethodException: Default constructor not found for type CarouselView.FormsPlugin.Android.CarouselViewRenderer`

I came trying to replace Xamarin.Forms.CarouselView but seems like this component still needs some work done.

**Comment by alexrainman** [comment]
@jfevia this control has been out for a while. It was stable but after latest XF releases are causing bunch of issues that were not there before.

First question: which .Net Framework are you using? Because the control supports 1.4

**Comment by alexrainman** [comment]
It works just fine for on .Net Standard 1.4 project.

**Comment by alexrainman** [comment]
@winstongubantes @sjorsmiltenburg which vesion of .Net Standard are you using? Because i just tried it and it works with version 1.4

**Comment by jfevia** [comment]
@alexrainman Using .NET Standard 2.0

**Comment by alexrainman** [comment]
Guys, you have to read the project requirements first. .Net Standard 2.0 is not supported yet because UWP issue.
