### ISSUE TITLE
[Android] Demo nullreference exception

### ISSUE THREAD

**Issue by sjorsmiltenburg** [alexrainman/CarouselView#291]
When trying to run the Demo.Droid project I run into a nullreferenceexception 

method CarouselViewImplementation.SetNativeView
line 359: `viewPager.Adapter = new PageAdapter(Element);`
(viewPager == null)

pulling the code line
`viewPager = nativeView.FindViewById<ViewPager>(Resource.Id.pager);`
out of the if statement 
`if (orientationChanged)`
did not help (value is still null)

the uwp project did run as expected

**Comment by fluter01** [comment]
The same issue here, on android it will crashes in the renderer,

>
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.

at this line:

> viewPager.Adapter = new PageAdapter(Element);

viewPage is null here.

**Comment by fgiacomelli** [comment]
same problem for me

**Comment by alexrainman** [comment]
Are you using .Net Standard?

**Comment by sjorsmiltenburg** [comment]
I am also using .net standard 2.0

**Comment by alexrainman** [comment]
Please, downgrade to version 1.4

**Comment by amasasi** [comment]
Same with me

**Comment by alexrainman** [comment]
Next release will support net standard 2.0
