### ISSUE TITLE
[iOS] Could not initialize an instance of the type 'UIKit.UIImage' [if ShowArrows="True" XAML]

### ISSUE THREAD

**Issue by jokksontw** [alexrainman/CarouselView#292]
Version 5.0.2
Set CarouselView XML property  ShowArrows="True"   

run iOS project, get some error message, then app crash
--------------------------------------------------------
System.Exception: Could not initialize an instance of the type 'UIKit.UIImage': the native 'initWithContentsOfFile:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false.

**Comment by juancarlosdmz** [comment]
it is also happening to me, only in real device

**Comment by juancarlosdmz** [comment]
Found my issue, I had an up.png and a down.png in my project
