### ISSUE TITLE
[iOS] ItemSource update during transition leads to an exception

### ISSUE THREAD

**Issue by exxbrain** [alexrainman/CarouselView#294]

**Comment by alexrainman** [comment]
Are you using .Net Standard?

**Comment by alexrainman** [comment]
You are not supposed to do ItemsSource changes during a transition.

**Comment by alexrainman** [comment]
I would implement this in a different way if this functionality is needed but i have to test it.

**Comment by exxbrain** [comment]
The API allows to do it. So there is no reason not to do it )).

**Comment by alexrainman** [comment]
Great, then you will get this issue unless i prevent it to happen :)

**Comment by alexrainman** [comment]
I added a property named IsSwiping that you can check before changing ItemsSource during a transition. Anyway, the carousel itself prevents the exception to happen.

**Comment by exxbrain** [comment]
Great! Thanks.
