### ISSUE TITLE
[Android] Memory increases each time ItemsSource updated

### ISSUE THREAD

**Issue by willowvil** [alexrainman/CarouselView#297]
Hello,

I have a button that refreshes my carousel data. Every time I press the button, I first clean the ObservableCollection and then fill it with the new data I want to show, but the memory of my phone increases each time and it is not released. Here is my code:

```
CarouselViewControl formCarousel = new CarouselViewControl();
ObservableCollection<MyItem> viewsSource = new ObservableCollection<MyItem>();

public MyMainPage()
{
	formCarousel.ItemTemplate = new viewTemplate();
	formCarousel.ItemsSource = viewsSource;
	formCarousel.InterPageSpacing = 0;
	formCarousel.ShowIndicators = false;
}

private void refreshButton_Clicked(object sender, EventArgs e)
{
	viewsSource.Clear();
	
	viewsSource.Add(new MyItem
	{
		name = "User1",
		uds = 12
	});
	viewsSource.Add(new MyItem
	{
		name = "User2",
		uds = 5
	});
	viewsSource.Add(new MyItem
	{
		name = "User3",
		uds = 8
	});
}
```
The template is showing a Syncfusion chart.

I have noticed that in Android, iOS not tested.

Thank you!

**Comment by alexrainman** [comment]
Can you provide a demo?

**Comment by willowvil** [comment]
Hi,

After testing, the problem is not related to the use of graphics. I tried to load the data source only the first time, and in the successive calls just update it, and so the phone's memory does not increase, but now the problem is that the carousel data does not change according to the new information.

```
if (viewsSource.Count == 0)
{
	viewsSource.Add(new MyItem
	{
		name = "User1",
		uds = 12
	});
	viewsSource.Add(new MyItem
	{
		name = "User2",
		uds = 5
	});
	viewsSource.Add(new MyItem
	{
		name = "User3",
		uds = 8
	});
}
else
{
	viewsSource[0].name = "User1";
	viewsSource[0].uds = "9999";
	viewsSource[1].name = "User2";
	viewsSource[1].uds = "9999";
	viewsSource[2].name = "User3";
	viewsSource[2].uds = "9999";
}
```

Thanks.

**Comment by alexrainman** [comment]
Are you using .Net Standard? If you do, please use version 1.4

**Comment by willowvil** [comment]
Hi,

I´m not using .Net Standard. My installed version is 5.0.2.

Thanks.

**Comment by alexrainman** [comment]
Are you implementing PropertyChanged on the ItemsSource?

**Comment by alexrainman** [comment]
Also, each object property needs to implement PropertyChanged otherwise the UI won't know this properties changed and wont update itself. I use Fody PropertyChanged in my own projects, not only in ViewModels but also in strongly typed custom objects that will be properties in my ViewModels and its properties will be bind to UI.

**Comment by willowvil** [comment]
Implementing PropertyChanged refreshes the data correctly. By the way, thanks for Fody's comment, I didnt know that tool.
Having solved the problem of memory, for my part I closed the thread.

Thank you very much!

**Comment by alexrainman** [comment]
Yeah, Fody makes your ViewModels code simpler and cleaner.
