### ISSUE TITLE
[IOS] Crash and Swipe problem on iPad Pro 10.5 inch

### ISSUE THREAD

**Issue by BlackRamsis** [alexrainman/CarouselView#298]
Hy, 

i use the CarouselView to show webviews.
if i use an iPad Pro with 10.5 inch (12.9 inch is fine) i can't swipe to the right. I can only swipe left.
swiping right makes the scrollbar of the webview visible (Does not happen on other devices).
After some attempts to swipe right and some swipes to the left the app crashes.

Crash looks like this:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No view controller managing visible view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x7f92c7150400; frame = (0 0; 929.988 648.381); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x60c00062b9c0>>'

**Comment by alexrainman** [comment]
I don't have an iPad pro available to test :(

**Comment by BlackRamsis** [comment]
Me too,
i got the problem reported from another person, 
but i could reproduce the problem with the iPad Pro 10.5 Simulator in Visual Studio.

**Comment by BlackRamsis** [comment]
Hy,

this bug is really strange, needed a lot of time to write a new app with the excat problem.
[PRO105.zip](https://github.com/alexrainman/CarouselView/files/1643342/PRO105.zip)
It seems the grids are causing the problem. If i remove them, the problem is gone.

**Comment by alexrainman** [comment]
Will take a look.

**Comment by BlackRamsis** [comment]
thanks,

maybe some more information i can give.
in View1.xaml:
if u remove the Columdefinition everything is fine or u set the number for first and last column to 5*.

**Comment by alexrainman** [comment]
First, why do you need all the Grid stuff? It doesn't make sense to me. Also, even in your project, i don't see any crash as i swipe :)

**Comment by alexrainman** [comment]
Neither you need View1.xaml

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:PRO105"
    x:Class="PRO105.MainPage"
    xmlns:controls="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions">

    <controls:CarouselViewControl
        ItemsSource="{Binding MyItemsSource}"
        BackgroundColor="White"
        Orientation="Horizontal"
        InterPageSpacing="10">
        <controls:CarouselViewControl.ItemTemplate>
            <local:Selector />
        </controls:CarouselViewControl.ItemTemplate>
    </controls:CarouselViewControl>
    
</ContentPage>
```

**Comment by BlackRamsis** [comment]
sure its look stupid, cause i removed all other code.
i Need the code to look like this and if u try the code with the 10.5 simulator u will not be able to swipe to the right.  thats the main problem.

The second problem are the crashes. but i think i know why they happen:
if i swipe and have very big load on the app like rendering and downloading the next slide, then the swipe will stutter or hang vor a second. If a user swipes again in this time, it will crash. Cause we trigger a new animation while a animation is happening and iOS does not like this and crash.

**Comment by shoeIT** [comment]
hey, I think I have a similar problem. Everything worked fine until I added orientation chage. If I only work in  portrait mode I have no problems. When I change to landscape and back  and swipe around I get the error:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No view controller managing revealed view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer:

any news on this ?

**Comment by Muhi** [comment]
@shoelT
Hi did you get an place with your problem? if I try and go from portrait to landscape my app crashes . And I can't seem to see why :-(
