### ISSUE TITLE
Navigation arrows too transparent?

### ISSUE THREAD

**Issue by joshk6** [alexrainman/CarouselView#299]
On my ios app, and using a carousel view  I can barely see the navigation arrows, even though arrow color is set to white.  I think its probably because alpha is set to 0.5f in teh code.

Would it be possible to either have make the alpha value on the control bindable so I can set it higher, or have some other setting which enables you to override so the arrows have no transparency?

**Comment by alexrainman** [comment]
Will do.

**Comment by alexrainman** [comment]
Done but only for Android and iOS.

**Comment by joshk6** [comment]
Super thanks

**Comment by joshk6** [comment]
Alex, I don't understand where I can get this updated version.  It looks
like the last update on github was last month.
Or do I need to wait for a new release?

**Comment by alexrainman** [comment]
Yes, you have to wait for the new release. Later today.

**Comment by joshk6** [comment]
Hi Alex,

I installed the new version and now get an error when I try to set the
Carousel origintation.

On the line
myCarousel.Orientation  = CarouselViewOrientation.Vertical, i get a compile
time error  " The type 'Enum' is defined in an assembly that is not
referenced. You must add a reference to assembly 'netstandard,
Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
(CS0012) (CrowdWisdom)

Do I really need to do this in order to use CarouselView?

**Comment by alexrainman** [comment]
Not really. A very strange error. Will take a look later.

**Comment by joshk6** [comment]
I’ve got netstandard library v 2.0.1 installed so it is indeed strange.  I tried updating and refreshing rebuilding everything 

I had to backup to prior version (5.0.2) to get it to work again.   I’m guessing it’s breaking others also.

**Comment by alexrainman** [comment]
Releasing version 5.1.1 to fix portable library support. Previously i was using same assembly to target both pcl and netstandard. It seems with netstandard2.0 that's not possible.

**Comment by joshk6** [comment]
Saw that you updated.   Thanks seems to be working now.  (Arrows look good! Thanks)
