### ISSUE TITLE
Position not binding both ways

### ISSUE THREAD

**Issue by Dids** [alexrainman/CarouselView#30]
I'm trying to bind Position both ways, using `Position="{Binding TaskIndex, Mode=TwoWay}"`, but it doesn't seem to be working.

CarouselView is binding to TaskIndex properly, but if I change TaskIndex, Position is not affected.

Is this by design, and if so, any way around it?

**Comment by alexrainman** [comment]
Use SetCurrentPage method :)

**Comment by Dids** [comment]
That works, thanks. :)

Two way binding would've been simpler to implement, but ended up adding an EventHandler which triggers SetCurrentPage. Works equally well though!

**Comment by alexrainman** [comment]
I am working on update. Will include that functionality :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
