### ISSUE TITLE
5.1.0 Android CirclePageIndicator.SetStyle not found

### ISSUE THREAD

**Issue by smallcandles** [alexrainman/CarouselView#300]
In the 5.1.0 version of CarouselView, I get a runtime exception anytime I attempt to create a CarouselView --> Method 'Com.ViewPagerIndicator.CirclePageIndicator.SetStyle' not found.  This is on an Android device.

**Comment by alexrainman** [comment]
Just update to CirclePageIndicator 1.0.2. Fixed in version 5.1.1
