### ISSUE TITLE
App crashes on dynamic add to  ItemSource collection.

### ISSUE THREAD

**Issue by joshk6** [alexrainman/CarouselView#301]
While I am able to load the collection before the control is displayed, I have been unable to dynamically add pages once the view is displayed.    When I attempt to add new pages to my collection when the PositionSelectEvent fires, the app immediately shuts down.  I can't catch the error in a try catch block, it just stops.  I notice that whenever the PositionSelectedEvent fires, the IsSwiping property is true and perhaps that has something to do with it, but it doesn't look like there is any time when either PositionSelected fires or ScrolledEvent fires when IsSwiping is false.

Not sure why adding to a Observable collection should kill the app altogether, but I can't find a way around it.  

Here's the code: (PS I have tried this in an inline (not async) method, no difference.

Initialization:

    public ResultsPage(ResultsController ctrl)
    {
      this.ctrl = ctrl;
      myCarousel = new CarouselViewControl();
      //Container for pages in view.   
      mySource = new ObservableCollection<ResultsScroller>();
      myCarousel.Position = 1;
      myCarousel.InterPageSpacing = 10;
      myCarousel.Orientation = CarouselViewOrientation.Horizontal;
      myCarousel.ArrowsBackgroundColor = Locals.Colors.ResultsBackgroundBlack;
      myCarousel.ArrowsTintColor = Color.White;
      myCarousel.ArrowsTransparency = 1.0F;
      myCarousel.ShowArrows = true;
      myCarousel.Scrolled += ScrolledEventHandler;
      myCarousel.PositionSelected += PositionSelectedHandler;
      myCarousel.ItemsSource = mySource;
      Content = myCarousel;
    }

    public async Task<bool> PopulateResultsPages(List<NominalResult> resultList)
    {
      ResultsScroller template = null;
      if (resultList.Count == 0) return false;
      foreach (var nr in resultList)
      {
        template = new ResultsScroller();
        template.LoadData(nr);
         
        try
        {
          mySource.Add(template);     // <------  App crashes here.
        }
        catch (System.Exception e)
        {
          System.Diagnostics.Debug.WriteLine(e.Message);
        }
      }

      lastPosition = mySource.Count - 1;
      return true;
    }

**Comment by alexrainman** [comment]
When this event is being called?

**Comment by joshk6** [comment]
It's being called when PositionSelected is triggered.  

Here's the code for position selected:
(From ResultsPage)
    private void PositionSelectedHandler(object sender, PositionSelectedEventArgs e)
    {
      currentPosition = e.NewValue;
      lastPosition = mySource.Count - 1;
      System.Diagnostics.Debug.WriteLine($"Current Selected Position is {e.NewValue}");
      if (currentPosition > lastPosition - 2)
      {
        ctrl.LoadMorePages();
      }
    }

   From Results Controller:

   public async void LoadMorePages()
    {
      var rm = ResultsManager.GetInstance();
      var last = resultsPage.LowestSurveyCompleteSequence;
      var resultsList = await rm.GetResultsBatch(resultsPage.LowestSurveyCompleteSequence);
      if (resultsList != null)
      {
        await resultsPage.PopulateResultsPages(resultsList);  // <--- this method creates page and loads into observable collection;
      }
    }

**Comment by alexrainman** [comment]
I know whats the problem. Will release a hot fix later today.

**Comment by alexrainman** [comment]
When PositionSelected is called, IsSwiping should be false and still true, that's why your apps is hanging.

**Comment by joshk6** [comment]
Yeah,noticed that.  I tried to write alittle routine that waited for isswiping to go false before adding but it never seemed to happen.

**Comment by daniel-p** [comment]
@alexrainman I have the exam same problem as @K232. I'm on 5.2.0.
