### ISSUE TITLE
[Android] PositionSelected event is fired more late when moving forward

### ISSUE THREAD

**Issue by peppe130** [alexrainman/CarouselView#302]
Hi, I noticed that the PositionSelected event is fired more late when moving forward than moving backward. My App runs some UI effects when the user swipes and your library's delay makes those effects awful. Could you fire the event instantly? Thank you in advance.

**Comment by alexrainman** [comment]
Sorry but the answer is no. The event is called when the swipe animation finish on the native control.

**Comment by peppe130** [comment]
I made a few changes to your **Android** custom renderer code.

```c#
// To assign position when page selected
void ViewPager_PageSelected(object sender, ViewPager.PageSelectedEventArgs e)
{
    // To avoid calling SetCurrentPage
    isChangingPosition = true;
    Element.Position = e.Position;
    // Call PositionSelected from here when 0
    if (e.Position >= 0 && e.Position < Element.ItemsSource.GetCount())
    {
        SetArrowsVisibility();
        Element.SendPositionSelected();
        Element.PositionSelectedCommand?.Execute(null);
    }
    isChangingPosition = false;
}

int mViewPagerState;

// To invoke PositionSelected
void ViewPager_PageScrollStateChanged(object sender, ViewPager.PageScrollStateChangedEventArgs e)
{
    // ScrollStateIdle = 0 : the pager is in Idle, settled state
    // ScrollStateDragging = 1 : the pager is currently being dragged by the user
    // ScrollStateSettling = 2 : the pager is in the process of settling to a final position

    if (mViewPagerState != -1)
        mViewPagerState = e.State;

    // Call PositionSelected when scroll finish, after swiping finished and position > 0
    if (e.State == ViewPager.ScrollStateIdle && !isChangingPosition && Element.Position > 0)
    {
        /*SetArrowsVisibility();
        Element.SendPositionSelected();
        Element.PositionSelectedCommand?.Execute(null);*/

        Element.IsSwiping = false;
    }
}
```

What is going on? You are firing the **PositionSelected** event from two different methods also fired by **ViewPager** events. The ViewPager fires first the **PageSelected** event and then the **PageScrollStateChanged**. Furthermore you are firing the **PositionSelected** event from the **ViewPager_PageSelected** method only when the next position is equal to **0** without waiting for the swiping animation to finish. This explains why moving backward the **PositionSelected** event is fired before than moving forward. I've commented out the body of the second condition in the **ViewPager_PageScrollStateChanged** method, I think it's useless. So, now the code works just fine and you should decide whether to fire instantly the **PositionSelected** event or fire it after the swipe animation ends. The consistency above all.

Cheers,
Giuseppe Montuoro, Italy.

**Comment by alexrainman** [comment]
Firing the PositionSelected event from the ViewPager_PageSelected method only when the next position is equal to 0 without waiting for the swiping animation to finish doesn't explains why moving backward the PositionSelected event is fired before than moving forward because it happens only when Position = 0. There's a reason for me to do that but i don't remember which one :)

**Comment by alexrainman** [comment]
PositionSelected needs to be called when the animation ends not when it starts. That's why i call on PageScrollStateChanged because it is the latest event called. Actually, i think i will remove the code from PageSelected instead.

**Comment by alexrainman** [comment]
This is what happens when you transition from one page to another:

```
PageScrollStateChanged
PageSelected
PageScrolled
PageScrolled
PageScrolled
PageScrolled
PageScrolled
PageScrolled
PageScrolled
PageScrolled
PageScrollStateChanged
Position selected.
```

You get my point?

**Comment by peppe130** [comment]
I'll try to describe my scenario. I have two buttons and a CarouselView that contains two pages. By pressing a button, the CarouselView swipes to the page at the position requested by the clicked button and the other button's background become semi-transparent. This behaviour is applied to both buttons. Currently I'm making the button's background semi-transparent when the ** PositionSelected** event is fired. Since the event is fired when the animation ends, the user sees first the page animation and then the button that changes its background. If you fire the **PositionSelected** event from the **ViewPager_PageSelected** method, this graphic glitch doesn't happen. If you don't want to fire **PositionSelected** from **ViewPager_PageSelected** method, then add a **bool** property and let the developer free to choose. It's a bad idea?

**Comment by peppe130** [comment]
You can also create two different events.. **PositionSelected** that is fired by **ViewPager_PageSelected** and **PositionChanged** that is fired by **ViewPager_PageScrollStateChanged**

**Comment by alexrainman** [comment]
This is how it will look like:

```
        void ViewPager_PageSelected(object sender, ViewPager.PageSelectedEventArgs e)
        {
            // To avoid calling SetCurrentPage
            isChangingPosition = true;
            Element.Position = e.Position;
            isChangingPosition = false;
        }

        int mViewPagerState;

        void ViewPager_PageScrollStateChanged(object sender, ViewPager.PageScrollStateChangedEventArgs e)
        {
            Element.IsSwiping = true;

            mViewPagerState = e.State;

            if (e.State == ViewPager.ScrollStateIdle)
            {
                Element.IsSwiping = false;

                SetArrowsVisibility();
                Element.SendPositionSelected();
                Element.PositionSelectedCommand?.Execute(null);
            }
        }
```

**Comment by peppe130** [comment]
I can't get my desired result yet.. I'll keep my custom renderer. Have a nice day and thank you for your time
