### ISSUE TITLE
XAML compilation produces "Common Language Runtime detected an invalid program" when ItemSource is defined in XAML as View(s) and Button.Clicked is assigned an event handler

### ISSUE THREAD

**Issue by aeonblaire** [alexrainman/CarouselView#303]
`<xfcarou:CarouselViewControl HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" >
    <xfcarou:CarouselViewControl.ItemsSource>
        <x:Array Type="{x:Type View}">
            <StackLayout>
               <Button Text="TAP" Clicked="Button_Clicked" />
	    </StackLayout>
        </x:Array>
    </xfcarou:CarouselViewControl.ItemsSource>
</xfcarou:CarouselViewControl>`

**Comment by alexrainman** [comment]
Let me take a look.

**Comment by alexrainman** [comment]
To be fare? No freaking idea what this is :)

**Comment by alexrainman** [comment]
I wonder why Clicked is not available from code behind and it is from XAML declaration? Um

I can offer you a workaround: use a command binding instead :) It works.

**Comment by aeonblaire** [comment]
Well it works if XAML compilation is disabled :).

**Comment by alexrainman** [comment]
Soon this will be part of Xamarin.Forms. Any pending issues, let Xamarin to solve it. I am kind of tired of this second job :)
