### ISSUE TITLE
App crashes with the 5.1.2 version

### ISSUE THREAD

**Issue by nbodinripert** [alexrainman/CarouselView#305]
Hi!
I have a ListView that is binding with items that represent images urls and when I click on an item I want to add/remove image easily in the carousel. This piece of code worked (with the 5.0.2 version) before updating to v. 5.1.2 this morning. It is not working anymore and I have no logs or exception or errors.

## MyView:

**.xaml**

```
<cv:CarouselViewControl
    Orientation="Horizontal"
    ItemsSource="{Binding MyItems}"
    Position="0"
    ShowIndicators="true">
    <cv:CarouselViewControl.ItemTemplate>
        <DataTemplate>
            <Image
                Source="{Binding .}"
                Aspect="AspectFill"/>
        </DataTemplate>
    </cv:CarouselViewControl.ItemTemplate>
</cv:CarouselViewControl>

<ListView
    ItemSelected="ListView_ItemSelected">
    (...)
</ListView>
```

**.cs**
```
void ListView_ItemSelected(object sender, SelectedItemChangedEventArgs e)
{
    if (e.SelectedItem == null)
                return;
    ((MyViewModel)BindingContext).AddImage(((MyObject)e.SelectedItem).PictureUrl);
    ((ListView)sender).SelectedItem = null;
}
```

## MyViewModel:

```
public ObservableCollection<string> MyItems
{
    get;
    set;
}

public MyViewModel()
{
    MyItems = new ObservableCollection<string>();
}

public void AddImage(string imageUri)
{
    MyItems.Add(imageUri);
}
```

**Comment by shoeIT** [comment]
I think I have the same problem. I have been working with Carousel View since version 3.1 and I never had such a crash. No error message only"the app terminated". I don't do fancy stuff, just add a view to the observable collections, which is displayed by the carousel view. If I have time I will post some code.

**Comment by alexrainman** [comment]
Platform?

**Comment by shoeIT** [comment]
both, iOS and Android same problem!

**Comment by shoeIT** [comment]
hey Alex,
the crash only happens on iOS, sorry I thought I've already tested it on Andorid as well. On Android the Carousel View is not displayed at all, another Carousel View works fine (I have three pages each one shows a Carousel View). On iOS the CV is shown but when I click a cell, which leads to another View in the collection, the crash happens.

 public ObservableCollection<View> CarouselViewInputItems { get; set; }

 var view = new LocationView() { BindingContext = this };
 CarouselViewInputItems.Add(view);  -> CRASH

I tested with a very simply view, just one label:

<?xml version="1.0" encoding="UTF-8"?>
<ContentView
  xmlns="http://xamarin.com/schemas/2014/forms"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
   xmlns:customViews="clr-namespace:PathfinderMobile.CustomViews;assembly=PathfinderMobile"
 x:Class="PathfinderMobile.Pages.LocationView">
  <ContentPage.Content>
        <Label Text="TEST" x:Name="labelCount"/>
 </ContentPage.Content>
</ContentView>

**Comment by joshk6** [comment]
I'm still having this problem as well.

**Comment by alexrainman** [comment]
Guys unless you provide a demo reproducing the problem i cannot provide a solution.

**Comment by joshk6** [comment]
Alex, the same problem persists I told you about yesterday.  When you capture the PositionSelected event, IsSwiping is still coming up true.  I think you should probably be able to see what we're talking  about pretty easily which I gather is the root cause of this.

My app is not really amenable to uploading as a demo for you, as it there is a lot of server side stuff necessary for it to work.

**Comment by alexrainman** [comment]
I found the problem. Will release a hot fix.
