### ISSUE TITLE
Method 'Com.ViewPagerIndicator.CirclePageIndicator.SetStyle' not found.

### ISSUE THREAD

**Issue by sualk1000** [alexrainman/CarouselView#306]
Hi,
I get this error on Android in the Emulator (API Version 25) and Samsung S7. I can run the application on iOS

I am using MS Visual Studio Community 7.3.3 on Mac.

    <controls:CarouselViewControl 
            x:Name="myCarouselView"
            ShowArrows="true"
        ShowIndicators="true"  >

        <controls:CarouselViewControl.ItemsSource>
           <x:Array Type="{x:Type View}">
                <Label Text="Page 1"/>
                <Label Text="Page2"/>

           </x:Array>
    </controls:CarouselViewControl.ItemsSource>
    </controls:CarouselViewControl>

What can I do? 

Thanks - Klaus

**Comment by alexrainman** [comment]
Update CirclePageIndicator to version 1.0.2

**Comment by sualk1000** [comment]
I am using 1.02. That's why I am wondering about this.

**Comment by alexrainman** [comment]
Can you uninstall the app from those devices. Clean the project and try again?

**Comment by sualk1000** [comment]
I will try tomorrow. Thanks a lot for your quick support!

**Comment by sualk1000** [comment]
Ok - looks better. Thanks a lot!
