### ISSUE TITLE
Crash when Replace/Move action was invoked in ItemsSource

### ISSUE THREAD

**Issue by myroot** [alexrainman/CarouselView#307]
I was test with Demo

Add a button into MainPage and add below handler on button.Clicked

```C#
void Handle_Clicked(object sender, System.EventArgs e)
{
    _vm.MyItemsSource.Move(0, 2);
}
```

It cause IndexOutOfRangeException 
https://github.com/alexrainman/CarouselView/blob/407d2e73b6affd93dc458b4d0daffbc7d073a548/CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs#L171

It is the spec of NotifyCollectionChangedEventArgs.NewItems 
https://msdn.microsoft.com/en-us/library/system.collections.specialized.notifycollectionchangedeventargs.newitems(v=vs.110).aspx

**Comment by alexrainman** [comment]
I know what is causing this. Something i added i the latest version which i will remove or fix.
