### ISSUE TITLE
[Android] Ability to change ViewPager's OffscreenPageLimit value

### ISSUE THREAD

**Issue by peppe130** [alexrainman/CarouselView#309]
Hi, you should provide a property to change ViewPager's OffscreenPageLimit in order to keep alive more than two pages (2 is the default value). Thanks

**Comment by alexrainman** [comment]
You can solve this very easy with a custom renderer. As there's not counterpart in other platforms for this, i don't provide it.

**Comment by iqbalansari** [comment]
I think the problem with custom renderer is that, the viewpager is a private variable hence the only way to access it would be via reflection which I think is very fragile. Am I missing something?

**Comment by alexrainman** [comment]
Yes, but the native Control containing the ViewPager is not :)

First create a custom CarouselView:

```
namespace Demo
{
    public class CustomCarouselView : CarouselViewControl
    {
    }
}
```

Then create a custom renderer for it:

```
[assembly: ExportRenderer(typeof(CustomCarouselView), typeof(CarouselViewCustomRenderer))]
namespace Demo.Droid
{
    public class CarouselViewCustomRenderer : CarouselViewRenderer
    {
        public CarouselViewCustomRenderer(Context context) : base(context)
        {            
        }

        protected override void OnElementPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);

            if (Control == null)
                return;

            var control = Control as Android.Views.View;
            var viewPager = control.FindViewById<ViewPager>(Resource.Id.pager);
            viewPager.OffscreenPageLimit = 2;
        }
    }
}
```

Then use the control from XAML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Demo.MainPage"
    xmlns:local="clr-namespace:Demo;assembly=Demo">

    <local:CustomCarouselView x:Name="carousel"
        ItemsSource="{Binding MyItemsSource}"
        ShowArrows="true"
        ShowIndicators="true"
        PositionSelectedCommand="{Binding MyCommand}"
        PositionSelected="Handle_PositionSelected"
        Scrolled="Handle_Scrolled"/>

</ContentPage>
```

**Comment by iqbalansari** [comment]
You right this approach would work, thanks!

**Comment by contrix09** [comment]
Hi @alexrainman , I tried your solution but when I am changing the `Orientation` property of the `CarouselViewControl`, it causes an exception in the renderer:

![image](https://user-images.githubusercontent.com/29834445/52319515-13637900-2a05-11e9-923d-5325b45bc805.png)

I changed the `Orientation` property as stated in this [solution](https://github.com/alexrainman/CarouselView/issues/406#issuecomment-453456895) for the same issue on that page.
