### ISSUE TITLE
Layout issues after device rotation

### ISSUE THREAD

**Issue by GamesAgeddon** [alexrainman/CarouselView#310]
The main problem is after device rotation the layout of the CarouselView gets completely destroyed.

I have a little dummy project to demonstrate the problem.

[DummyCarouselView.zip](https://github.com/alexrainman/CarouselView/files/1625592/DummyCarouselView.zip)

Some screenshots for better understanding.

![portrait](https://user-images.githubusercontent.com/28893667/34870886-c9dd0028-f78b-11e7-8bf1-4c3284f933c0.png)
![landscape](https://user-images.githubusercontent.com/28893667/34870885-c9c4d2fa-f78b-11e7-91f0-294d31eb31f9.png)

**Comment by alexrainman** [comment]
Actually i don't see any problem. You are just not setting the aspect ratio of your images so they adapt to the screen. Nothing wrong with carousel.

**Comment by GamesAgeddon** [comment]
IMHO I don't think that the missing aspect ratio matters.

Please watch the screencasts, because I can not explain what's happened there. 

If this behavior is the result of the missing aspect ratio it would be very weird.

![carouselview_screencast](https://user-images.githubusercontent.com/28893667/34929957-2c7ffc16-f9c7-11e7-9e00-6ef0a2bc0155.gif)
![carouselview_screencast1](https://user-images.githubusercontent.com/28893667/34929958-2c964548-f9c7-11e7-8c83-8857b9a97e65.gif)

**Comment by alexrainman** [comment]
Please, provide a demo where i can reproduce this.

**Comment by GamesAgeddon** [comment]
The dummy project I used for the screencasts.

[DummyCarouselView.zip](https://github.com/alexrainman/CarouselView/files/1625592/DummyCarouselView.zip)

**Comment by alexrainman** [comment]
Found your problem. You are wrapping each image with StackLayout or Grid and thats not needed:

```
<x:Array Type="{x:Type View}">

                    <Image HorizontalOptions="Fill"
                       VerticalOptions="CenterAndExpand"
                       Aspect="AspectFit"
                       Source="https://cdn.pixabay.com/photo/2017/12/26/15/36/baboon-3040740_960_720.jpg" />
                    
                    <Image Grid.Row="0"
                       HorizontalOptions="Fill"
                       VerticalOptions="CenterAndExpand"
                       Aspect="AspectFit"
                       Source="https://cdn.pixabay.com/photo/2017/12/26/15/36/baboon-3040740_960_720.jpg" />

                    <Image Grid.Row="0"
                       HorizontalOptions="Fill"
                       VerticalOptions="CenterAndExpand"
                       Aspect="AspectFit"
                       Source="https://cdn.pixabay.com/photo/2018/01/08/15/23/monkey-3069560_960_720.jpg" />

                    <Image Grid.Row="0"
                       HorizontalOptions="Fill"
                       VerticalOptions="CenterAndExpand"
                       Aspect="AspectFit"
                       Source="https://cdn.pixabay.com/photo/2013/11/21/12/22/gorilla-214826_960_720.jpg" />

                    <Image Grid.Row="0"
                       HorizontalOptions="Fill"
                       VerticalOptions="CenterAndExpand"
                       Aspect="AspectFit"
                       Source="https://cdn.pixabay.com/photo/2015/04/13/19/01/monkey-721108_960_720.jpg" />

                </x:Array>
```

**Comment by alexrainman** [comment]
By the way, your demo helped me to find an issue. Position is reset to 0 in screen orientation on Android.

**Comment by lassana** [comment]
@GamesAgeddon have you managed to fix this?

**Comment by krazazian** [comment]
@alexrainman I am running into this same issue on Android Tablets in the latest version.  I used to have this issue in iOS on iPads in the 4.3.0 version, but i created a work around.  I would push to the prev frame and go back to the current frame on device rotation.  The sizing seems to correct itself after it passes thru 2 slides.  I am using a Master-Detail navigation, so when I rotate the device, it looks like the CarouselView is Requesting for the Layout size too early.  Stepping thru code, it looked like it would set the size of the carouselview when the device rotates but before it the Detail page resizes itself.  The current version seems to have fixed the issue that i had in 4.3.0, but now that issue occurs in Android.  

It definitely has something to do with the datatemplate.  As you mentioned above, if you only have an image in there, it works fine, but if you're creating a custom view with a grid or something, then it runs into the layout issues.

This is what my DataTemplate looks like....

<DataTemplate x:Key="newsTemplate">
                
                <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>
                    <Image Grid.RowSpan="2" Aspect="AspectFill" Source="{Binding imageUrl}"/>
                    <Grid Grid.Row="1" RowSpacing="5" BackgroundColor="#95FFFFFF" Padding="12,5,12,3">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto"/>
                            <RowDefinition Height="Auto"/>
                            <RowDefinition Height="Auto"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*"/>
                        </Grid.ColumnDefinitions>

                        <Label Style="{StaticResource HeaderStyle}" Grid.Row="0" TextColor="Black" Text="{Binding Title}" HorizontalOptions="Start" VerticalOptions="CenterAndExpand"/>
                        <control:MultiLineLabel Style="{StaticResource MultiLabelStyle}" Grid.Row="1" TextColor="Black" Text="{Binding Content}" HorizontalOptions="StartAndExpand" VerticalOptions="StartAndExpand" Lines="2"/>
                        <Label  Style="{StaticResource LabelStyle}" Grid.Row="2" TextColor="Black" Text="Learn more >" HorizontalOptions="End" VerticalOptions="End" />
                        <Button Style="{StaticResource ButtonStyle}" Grid.RowSpan="3" Grid.Row="0" Grid.Column="0"  BackgroundColor="#00FFFFFF" Clicked="NewsItemClicked"/>
                    </Grid>
                </Grid>

            </DataTemplate>

**Comment by GamesAgeddon** [comment]
@lassana No not really. Removing the CarouselView from the app. ;)

**Comment by mclillill** [comment]
@LakMoore seems to work. I wraped it in an if clause:
```csharp
if(Device.RuntimePlatform == Device.Android)
{
  m_ctrlIssueCarousel.Orientation = CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Vertical;
  m_ctrlIssueCarousel.Orientation = CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Horizontal;
}
```

**Comment by ImproveMe-it** [comment]
> 
> 
> @LakMoore seems to work. I wrapped it in an if clause:
> 
> ```cs
> if(Device.RuntimePlatform == Device.Android)
> {
>   m_ctrlIssueCarousel.Orientation = CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Vertical;
>   m_ctrlIssueCarousel.Orientation = CarouselView.FormsPlugin.Abstractions.CarouselViewOrientation.Horizontal;
> }
> ```

Got the same Problem but this is working. Thank you.
