### ISSUE TITLE
UWP Could not load file or assembly 'CarouselView.FormsPlugin.Abstractions, Version=1.0.6585.25860, 

### ISSUE THREAD

**Issue by JKennedy24** [alexrainman/CarouselView#311]
After upgrading to V5.1.3 I get the following error on UWP:

Could not load file or assembly 'CarouselView.FormsPlugin.Abstractions, Version=1.0.6585.25860, 

I'd imagine this is a packaging error?

Can anyone else replicate?

**Comment by alexrainman** [comment]
Clean and rebuild. Also, UWP needs to target latest platform as min version if you use Net Standard 2.0

**Comment by JKennedy24** [comment]
@alexrainman I use .Net Standard 1.4
Does that mean I now need to target Fall Creators update?

**Comment by JTOne123** [comment]
I have the same issue with latest nugets.
And of course "Clean and rebuild" didn't help :(

Could not load file or assembly 'CarouselView.FormsPlugin.Abstractions, Version=1.0.6591.24917, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by 100s** [comment]
@alexrainman I have the same issue. I have a pcl common code project and UWP targeting 16229.

It worked fine on and UWP 10240 and nuget 5.0.2

Do I need to update my PCL to netstandard2.0?

The same error:
Could not load file or assembly 'CarouselView.FormsPlugin.Abstractions, Version=1.0.6591.24917, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
