### ISSUE TITLE
CV throws an error in the Android demo project 

### ISSUE THREAD

**Issue by shoeIT** [alexrainman/CarouselView#312]
Version 5.1.3 works fine on iOS but not on Android. In my project the Carousel View is not displayed at all and even in your demo project the app throws an error and there is only a white page.

Unhandled Exception:
System.InvalidCastException: Unable to convert instance of type 'Android.Support.V7.Widget.AppCompatTextView' to type 'Android.Support.V4.View.ViewPager'. occurred

Thats the line which throws the error: 
viewPager = nativeView.FindViewById<ViewPager>(Resource.Id.pager);
( CarouselView.FormsPlugin.Android line 426 )

**Comment by alexrainman** [comment]
Just clean the projectand rebuild.
