### ISSUE TITLE
Default constructor missing in CarouselView.FormsPlugin.Android.CarouselViewRenderer

### ISSUE THREAD

**Issue by jfidder** [alexrainman/CarouselView#315]
I've seen this issue mentioned and solved several times before but in v5.1.3 the exception 'Default constructor missing in CarouselView.FormsPlugin.Android.CarouselViewRenderer' is thrown upon initial navigation to a page containing the CarouselView.

This occurs in a clean Xamarin Forms solution using the Shared Project strategy running in the Visual Studio Android Emulator. 
The CarouselView is declared in XAML using the example provided in the readme and contains 3 simple labels.

**Comment by alexrainman** [comment]
By shared project you mean PCL? NetStandard?

**Comment by jfidder** [comment]
As far as I can tell neither, it's the default when creating a new cross platform Xamarin project in VS2017:

![image](https://user-images.githubusercontent.com/35542164/35065707-523dafc6-fbce-11e7-85c6-66ffd507d6cb.png)

![image](https://user-images.githubusercontent.com/35542164/35065732-63b98360-fbce-11e7-8818-d432bc5bfe80.png)

**Comment by alexrainman** [comment]
Can you share a demo project reproducing the issue?

**Comment by jasondmichaelson** [comment]
[CVDemo.zip](https://github.com/alexrainman/CarouselView/files/1805357/CVDemo.zip)
 This one demo's the problem with the ios simulator. I had a similar one set up as a shared project that had the same problem
