### ISSUE TITLE
[UWP] No render in Release

### ISSUE THREAD

**Issue by erossini** [alexrainman/CarouselView#316]
Hi guys,
I create an app in _Xamarin.Forms_ with your component. In debug it's working fine but in release the _CarouselView_ doesn't show anything.

Any idea or suggestion about it? Thanks in advance.

**Comment by alexrainman** [comment]
Target SDK? PCL or Net Standard?

**Comment by erossini** [comment]
PCL

    <TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>

**Comment by alexrainman** [comment]
I can confirm this is happening. Why? I don't know yet.

**Comment by alexrainman** [comment]
Add this to App.xaml.cs after rootFrame.NavigationFailed += OnNavigationFailed;

```
List<Assembly> assembliesToInclude = new List<Assembly>();
assembliesToInclude.Add(typeof(CarouselViewRenderer).GetTypeInfo().Assembly);
assembliesToInclude.Add(typeof(CachedImageRenderer).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```
