### ISSUE TITLE
How to call previous/next item from PCL

### ISSUE THREAD

**Issue by tematim** [alexrainman/CarouselView#32]
Hello,

I have the same architecture as your repo.

Each carousel item is linked with a description, and when the user tap on one item, the description is on the screen with left/right arrows.

My question is, how I can add an event that the control will raise, and the ios renderer can listen to change the carousel item ?

ATM, the only way to call AnimationEnding is sliding with hand/mouse. The positionSelected event doesn't work because the renderer don't have the knowledge of the description and I'm ok with that.

Could you help me ?

**Comment by tematim** [comment]
Update : I manage to add actions to the control and call implementations inside the renderer.

Now, I try to switch page programmatically : 
public void ScrollNext()
        {
            var currentItem = pageController.ViewControllers.FirstOrDefault();
            pageController.GetNextViewController.Invoke(pageController, currentItem);
            currentItem = pageController.ViewControllers.FirstOrDefault();
            var item = (ViewContainer) currentItem;
            var position = item.Tag + 1;
            Element.Position = position;
            Element.RaiseSelectionChanged(new SelectedPositionChangedEventArgs(position));
        }

The invoke go to the right line to createContent at the new position. But the image still the same.

How can I refresh the view to display the correct image ?

Regards

**Comment by alexrainman** [comment]
If what you want to do is move to next/prev page programmatically, use setCurrentPage(position).

**Comment by tematim** [comment]
Hello,

It's working, but the view is sliding to the wrong direction.

The natural way is to slide right to left to display the next item, but when I use the setCurrentController, the slide is left to right.
So the next item appear to come from left and not right.

Is it possible to change it ?

Regards

**Comment by alexrainman** [comment]
I don't know what are yo doing in your end but you should not use setCurrentController directly. You should use SetCurrentPage(position).

Please, take a look at the demo, you will find to methods to move back and fort from PCL.

```
public void OnPrev (object sender, TappedEventArgs e)
{
	if (myCarousel.Position > 0)
		myCarousel.SetCurrentPage(myCarousel.Position - 1);
}

public void OnNext(object sender, TappedEventArgs e)
{
	if (myCarousel.Position < myCarousel.ItemsSource.Count - 1)
		myCarousel.SetCurrentPage(myCarousel.Position + 1);
}
```

Thanks.

**Comment by tematim** [comment]
Hello,

I work on the iOS renderer. The SetCurrentPage isn't available for the Element. or pageController.
So I use the setCurrentController.

If I use the setCurrentPage, this change nothing, the image displayed doesn't change.

Any suggestions ?

Regards

**Comment by alexrainman** [comment]
Why you need to work directly in the iOS renderer? This is a XForms plugin. You suposed to use it from PCL with the provided cross-platform methods.

**Comment by tematim** [comment]
I manage to use your code and display a carousel.

Now, I have an issue with a cache. Because I open the carousel, I dispose it, and when I try to display a new one with a different ItemsSource, the carousel isn't displayed.

The itemsSource changed event is correctly called, the items source is correctly getted from the VM.

Any suggestions to display the new content ?

Regards

**Comment by alexrainman** [comment]
How are you pushing the new page?

**Comment by tematim** [comment]
Hello,

I change the current VM with a navigation service and a new presentationMessage part of a Galasoft.Messenger.

 private void OpenPresentation(PresentationMessage obj)
        {
            DocumentsControl.ItemsSource = App.Locator.PresentationVM.Documents;
            _isClosing = false;
            Opacity = 1;
            UpdateArrowVisibility();
            if (DocumentsControl.ItemsSource.Count > 0 && DocumentsControl.Position != -1)
                DocumentInformation.BindingContext = DocumentsControl.ItemsSource[DocumentsControl.Position];
            _isHeaderExpand = false;
            _isHeaderReduced = true;
            _isFooterExpand = false;
            ExpandControl(0); // Not expanding the description of the current item
        }

What is different  between the first creation of the control and his "reuse" ? What I need to add to display the new content correctly ?

Regards

**Comment by alexrainman** [comment]
What this means: ExpandControl(0);?

**Comment by tematim** [comment]
It's an inside method, to expand the description of the currentItem stored in another objet, nothink link with the carousel issue.

**Comment by alexrainman** [comment]
I don't really know what are you doing, not without the whole code :(

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
