### ISSUE TITLE
UWP fails to build: Windows Metadata file 'Type universe cannot resolve assembly:  netstandard, Version=2.0.0.0

### ISSUE THREAD

**Issue by ruisilva450** [alexrainman/CarouselView#320]
Hi,

I have a Xamarin Forms app with PCL Profile 111 and I tried to upgrade to version 5.2.0.
I know that this new version has netstandard and can become an issue but it installed correctly.

But on UWP, when I try to build, I get the following error:
```
Could not copy the file "obj\x86\Release\MainPage.xbf" because it was not found.	
Could not copy the file "obj\x86\Release\App.xbf" because it was not found.
Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: 
netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.'		
```

**Comment by alexrainman** [comment]
The description doesn't have any relation with the issue name :)

**Comment by alexrainman** [comment]
Latest version requires NetStandard 2.0 and minimum targeting latest platform version.

**Comment by eugeniipol** [comment]
@ruisilva450 How did you fixed this issue?
