### ISSUE TITLE
PositionSelected is not fired at the right time  

### ISSUE THREAD

**Issue by nbodinripert** [alexrainman/CarouselView#321]
I have an issue with the PositionSelected event: I have a ContentView (MyContentView) with a Carousel (MyCarousel) inside. 

This is **MyContentView.xaml**:

```
<cv:CarouselViewControl
    x:Name="MyCarousel"
    Orientation="Horizontal"
    ItemsSource="{Binding MyItems}">
    <cv:CarouselViewControl.ItemTemplate>
        <DataTemplate>
            <Image
                Source="{Binding .}"
                Aspect="AspectFill"/>
       </DataTemplate>
   </cv:CarouselViewControl.ItemTemplate>
</cv:CarouselViewControl>
```

this is **MyContentView.cs**:

```
public MyContentView()
{
    InitializeComponent();
    MyCarousel.Position = index;
    MyCarousel.PositionSelected += MyCarousel_PositionSelected;
}

void MyCarousel_PositionSelected(object sender, PositionSelectedEventArgs e)
{
   (...)
}
```

The problem is the next one: MyCarousel_PositionSelected is called even if I write "MyCarousel.PositionSelected += MyCarousel_PositionSelected;" AFTER setting the position. I do not understand why. Any ideas ?

I test on a iOS simulator (iPhone 5s iOS 11.2) with the 5.2.0 version of your package and the 2.5.0.122203 version of Xamarin.Forms.

**Comment by alexrainman** [comment]
PositionSelected is called when the initial position is shown on screen. Assigning the event before or after it doesn't makes any difference, it will always be called the very first time and any time you switch to a page.
