### ISSUE TITLE
Replacing Items in Android gives index out of range error

### ISSUE THREAD

**Issue by gtgatsby** [alexrainman/CarouselView#325]
In CarouselView.FormsPlugin.Droid.CarouselViewImplementation.cs, ItemsSource_CollectionChanged, around line 168 - you are using e.NewStartingIndex to get the index of the new item in e.NewItems. However, for NotifyCollectionChangedAction.Replace, e.OldStartingIndex and e.NewStartingIndex are the same, and refer to the index being replaced in the existing array. It does not refer to the NewItems array.

So, it works fine if you replace the index at position 0, because there is only one item in the NewItems array. However, if you try to replace an item at any other position, say NewStartingIndex = 1, you get an Index Out of Range exception, because NewItems only has one item, but you are trying to access the item at index 1.

I think it should be changed to: Source[e.OldStartingIndex] = e.NewItems[0];

**Comment by scastria** [comment]
This occurs on iOS as well.

**Comment by charmosz** [comment]
Hi,
Is the problem fixed ? How can I make it work ?
Thanks

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
