### ISSUE TITLE
CarouselView disappears when wrapped in elements

### ISSUE THREAD

**Issue by GregorioCunha007** [alexrainman/CarouselView#327]
I managed to make it work when CarouselView is not wrapped in anything else. But if I wrap it around a ScrollView or a StackLayout she disappears.

>      
       <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Chronocrops.Views.CropDetailPage"
             xmlns:views="clr-namespace:Chronocrops.Views;assembly=Chronocrops"
             xmlns:controls="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly
            =CarouselView.FormsPlugin.Abstractions">

      
        <StackLayout Orientation="Vertical">
            <Label Text="CarouselView" BackgroundColor="BlanchedAlmond"/>
            <controls:CarouselViewControl BackgroundColor="Bisque" ItemsSource="{Binding carouselViews}"/>
        </StackLayout>
     
    </ContentPage>

**Comment by wuhuangjia** [comment]
me too

**Comment by wuhuangjia** [comment]
Event like this
`    
<StackLayout VerticalOptions="Start">
        <Label Text="aaa" />
    </StackLayout>
    <cv:CarouselViewControl
        x:Name="carousel"
        ItemsSource="{Binding MyItemsSource}"
        ShowArrows="false"
        ShowIndicators="false" />
    <StackLayout VerticalOptions="End">
        <Label Text="bbb" />
    </StackLayout>
`

**Comment by alexrainman** [comment]
CarouselView wont show up on StackLayout if you dont specify HeightRequest. Use a Grid instead.

**Comment by GregorioCunha007** [comment]
ohh thanks!! But shouldn't you indicate that in the docs ? Many thanks

**Comment by wuhuangjia** [comment]
thanks a lot for you respond~~

**Comment by wuhuangjia** [comment]
@GregorioCunha007 hello did you try to put CarouselView into Grid or setting StackLayout's height? I am trying it but didn't work

**Comment by wuhuangjia** [comment]
oh sorry it is worked
`        <Grid BackgroundColor="Aqua" VerticalOptions="FillAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            <cv:CarouselViewControl
                x:Name="cv1"
                ItemsSource="{Binding cv1ItemsSource}"
                ShowArrows="false"
                ShowIndicators="false" />
        </Grid>
`

**Comment by GregorioCunha007** [comment]
Great I'll try it out later
