### ISSUE TITLE
carouselview render does not load sometimes

### ISSUE THREAD

**Issue by georgenistor** [alexrainman/CarouselView#328]
I use the CarouselView 5.2.0 like this inside a grid:
I have also the Init called.
Sometimes the carousel control does not load. It happens on Android.
Could someone help me?

`<?xml version="1.0" encoding="utf-8" ?>
<ContentView 
            xmlns:v="clr-namespace:HandlingWorkerMobile.Views"
            xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:vm="clr-namespace:HandlingWorkerMobile.ViewModels"
            xmlns:vc="clr-namespace:HandlingWorkerMobile.Views.Controls"
            xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
             x:Class="HandlingWorkerMobile.Views.Controls.AcceptanceCarousel"
            IsVisible="{Binding IsAcceptanceVisible}">

    <ContentView.BindingContext>
        <vm:AcceptanceViewModel x:Name="VmAcceptance"/>
    </ContentView.BindingContext>

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <StackLayout Grid.Row="0" Orientation="Horizontal" HorizontalOptions="Center" VerticalOptions="End">
            <BoxView BackgroundColor="{Binding Source={x:Reference CarouselViewTimeRec}, Path=Position, Converter={StaticResource colorCarouselIndicator}, ConverterParameter='Black|Gray'}" 
                     WidthRequest="10" HeightRequest="10" />
            <BoxView BackgroundColor="{Binding Source={x:Reference CarouselViewTimeRec}, Path=Position, Converter={StaticResource colorCarouselIndicator}, ConverterParameter='Gray|Black'}" 
                     WidthRequest="10" HeightRequest="10" />
        </StackLayout>

        <cv:CarouselViewControl x:Name="CarouselViewTimeRec" Grid.Row="1" Position="{Binding ChangePosition}">

            <cv:CarouselViewControl.ItemsSource>
                <x:Array Type="{x:Type View}">

                    <vc:TimeRecording/>

                    <vc:CountdownToJob/>

                </x:Array>
            </cv:CarouselViewControl.ItemsSource>

        </cv:CarouselViewControl>
    </Grid>
</ContentView>`

**Comment by shoeIT** [comment]
Maybe I have a similar problem, does it work the same with version 5.02, this version works fine in my case.

**Comment by georgenistor** [comment]
mine in 1 case from 10-20 does not load the carousel control. It is a sporadic bug I have.

**Comment by alexrainman** [comment]
Can you provide a demo?
