### ISSUE TITLE
TapGestureRecognizer in a CarouselView, is disabling carouselswipe on android (not iOS)

### ISSUE THREAD

**Issue by jeromeliger** [alexrainman/CarouselView#330]
Hi,

I have a CarouselView, with a XAML template (week calendar) that looks like this (surrounded in green) :

![carouseltapgesture](https://user-images.githubusercontent.com/3584319/35321593-8eea722e-00e7-11e8-8947-b22fef11cd87.png)

When I want to Swipe (from one week to another), on Android I can only swipe by touching the "header" (surrounded in Yellow).
It is because I've added TapGestureRecognizers on each days (surrounded in purple)

If I comment my TapGestureRecognizers on each days, I can normaly swipe by touching any area on the carouselview (any area in green : on the header/yellow AND on the days/purple)
But I need to keep this TapGestureRecognizers on each day... and I want to swipe the carouselview by touching any area on it (the header AND the Days too)

I think this is a conflict with the CarouselView Swipe and custom TapGestureRecognizer in it, and I can't make it work on Android (I repeat, all is working well on iOS -> I can swipe by touching a "day/purple" area AND I can "Tap" on one day)

I've tested all king of "InputTransparent=true", but no way to solve it... I think it's a bug relative to the android carouselviewrenderer... or android ViewPager incompatibility

Any idea to help ?

Thanks for your return...

**Comment by alexrainman** [comment]
Can you make the carousel and its children InputTransparent?

**Comment by jeromeliger** [comment]
If I make Carousel InputTransparent (with or without children InputTransparent, tested both), the carousel itself becomes not swipeable...

I've tested with all its children InputTransparent (without the carousel InputTransparent) -> the carousel is swipeable on all area touch, but I can't Tap on a day (TapGesture not fired).

I've tested with none of the childs transparent (except the "day Frame" InputTransparent) -> idem, carousel is swipeable, but I can't Tap on a day (TapGesture not fired).

I've tested without any InputTransparent -> the carousel is swipeable by touching the "header" area, and the "day area" can be tapped (TapGesture is recognized), but impossible to swipe by touching a "day area"... like the description of this issue...

Any other way to solve this ?

Thanks

**Comment by jeromeliger** [comment]
Hi,

I've corrected this bug...

It's only on Android, on the \Android \Implementation\HorizontalViewPager.cs (certainly in the verticalViewPager.cs too... but I don't use it...)

For remember, this bug happen when we are defining a "TapGestureRecognizer" in a template of items in a CarouselView... the TapGesture is recognized but we can't make the "swipe gesture" of the CarouselView on the "TapGesture defined area".

The HorizontalViewPager "OnInterceptTouchEvent(MotionEvent ev)" method was returning a "Move" event, even if we are just doing a "tap"... we just add a "tolerance" of 50 pixel, and if it's under 50, we triggered the "Tap" event, if it's over 50, the swipe is triggered (the "normal swipe" didn't moove under 50 too with this correction, but it's less impacting than the "not swipe at all").

Here's a "rapid correction" that works, I didn't make a PR, but you can do/improve this correction (on vertical too ?) and maybe embbed-it in the next release ? Thanks in advance.


`
public override bool OnInterceptTouchEvent(MotionEvent ev)
        {		

            if (ev.Action == MotionEventActions.Up)
            {
				// Fix TapGesture
				if ( (isTap) &&  (this.isSwipeEnabled) )  // If is detect as a Tap
				{
					// If there is a save_tap_event
					if (save_tap_event != null)
					{
						save_tap_event.Action = MotionEventActions.Down; // Todo : See why save_tap_event = UP , by reference ?
						DispatchTouchEvent(save_tap_event); // Simulate Event Tap
												
						bool return_val = base.OnInterceptTouchEvent(save_tap_event); // Consume it
						save_tap_event = null; // Set to null
						return return_val; // Return save value
					}

				}
				// End Fix TapGesture

				if (Element?.GestureRecognizers.GetCount() > 0)
                {
                    var gesture = Element.GestureRecognizers.First() as TapGestureRecognizer;
                    if (gesture != null)
                        gesture.Command?.Execute(gesture.CommandParameter);
                }
            }



			if (this.isSwipeEnabled)
            {


				// Fix TapGesture
				if (ev.Action == MotionEventActions.Down)
				{
					// Maybe it is a simple Tap
					isTap = true;

					// Save event
					if (save_tap_event == null)
						save_tap_event = ev;

					// Save coords
					LastX = ev.RawX;
					LastY = ev.RawY;

				}
			


				// Move detected
				if (ev.Action == MotionEventActions.Move)
				{

					// If the Move is more than X pixels (maybe can configure it)
					if ((Math.Abs(ev.RawX - LastX) > 50)) // || (Math.Abs(ev.RawY - LastY) > 50))
					{
						// It is a swipe , not a move !						
						save_tap_event = null;
						isTap = false;						
					}

				}
				// End Fix TapGesture

				// Modified (Fix TapGesture)
				if (isTap)
					return base.OnInterceptTouchEvent(ev);
				else
					return true;
				// End Modified (Fix TapGesture)
			}

			return false;
        }
`

**Comment by lubritto** [comment]
@jeromeliger how did you access the HorizontalViewPager ?

**Comment by jeromeliger** [comment]
@lubritto unfortunatly, I've download the alex source code to modify it and include my own implementation... the HorizontalViewPager is in \Android \Implementation\HorizontalViewPager.cs

With my custom implementation (describe above), I've corrected my tapgesture problem.

I've just forgot in my explaination above, to add the variables inside the class :
             // Fix TapGesture
             private bool isTap = false;
             private MotionEvent save_tap_event = null ;
             private float LastX = 0;
             private float LastY = 0;
             // End Fix TapGesture

**Comment by lubritto** [comment]
@jeromeliger Ok, Thanks for help!

**Comment by alexrainman** [comment]
@jeromeliger I am migrating my code to Xamarin.Forms CarouselView branch. I don't have time to maintain this plugin anymore so, once i'm done with that, you can do a PR there.

**Comment by jeromeliger** [comment]
@alexrainman I know it, I don't have enough time to do a PR neither (my fix is quite dirty, but it works in my case)
But when the CarouselView will be merged into Xamarin.Forms official branch, I'll migrate from this plugin to the Xamarin Forms CarouselView ;-) I hope it won't be hard to migrate and it won't have bug... but count on me, I will test it in real production implementation (so keep in mind the TapGesture for your tests ;-)) Thanks for your work.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
