### ISSUE TITLE
Updaing to v5.2.0 makes CarouselViewRenderer undefined in Android 

### ISSUE THREAD

**Issue by mwaqash** [alexrainman/CarouselView#331]
I have an app with Xamarin forms v2.5,0.122203 for android, iOS and UWP. Updating this plugin from 5.0.2 upwards causing CarauseViewRendered in android project become undefined. And if I build project there are linking errors in UWP project.

**Comment by alexrainman** [comment]
Seems XF 2.5 came with lot of issues. Will downgrade the dependency.

**Comment by alexrainman** [comment]
Latest version requires NetStandard 2.0 and to target latest UWP sdk. I can change that to.
