### ISSUE TITLE
UI issue : first swipe does not swipe carousel item entirely 

### ISSUE THREAD

**Issue by Umar3x** [alexrainman/CarouselView#332]
Hello,

I updated to last versions and I now have a UI bug. When initializing carousel, everything is perfect, but when I first swipe and/or change position programatically, the carousel position changes well, but the UI is half swiped, I got half of the previous item and half of the other.

When I swipe back to previous position and then going to next position again it works and item is fully swiped. Its really a UI behavior. 

I'm sorry not to give screenshots or repro project as it is a private business project. 

Android 7.0. XF 2.5, Carousel 5.2.0 

Thanks.

**Comment by alexrainman** [comment]
The only change in latest version is Xamarin Forms 2.5 dependency. Going to change that. Seems XF 2.5 came with lot of issues.

**Comment by Umar3x** [comment]
Hello,
Thanks for your fast answer. Is there a workaround ? Should I go to XF 2.4 and then downgrade your plugin too ?

**Comment by alexrainman** [comment]
Maybe. Will take me couple of days to release a new version.

**Comment by Umar3x** [comment]
I must say this happens only on Android, on iOS its working well.

**Comment by Zure1** [comment]
@Umar3x did you find a workaround? Got the exact same issue (Android 7.0, XF 2.5, Carousel 5.2.0)

**Comment by Umar3x** [comment]
@Zure1 

Nope, I was working on something else, but I'm going to debug it this week. I think that might be due to carousel position binding and/or specific layout used in it, as I have a carousel somewhere else in my app and do not have this bug (but in this other carousel I'm not binding position at all or using a complex layout). I'll keep you in touch. Maybe this could give you some clue too :)

**Comment by Zure1** [comment]
Good idea about the position binding. In my case, I also have several CarouselViews in my app, but this bug only appears in the one where I set the binding programmatically: I tap on an item in a ListView and then navigate to a page with the CarouselView, where the position is set accordingly to the item I just tapped.

Unfortunately I can only debug Android, so not sure about iOS but this looks like a bug which may only appear on one platform.

**Comment by Umar3x** [comment]
Hey @Zure1 . Same for me. I got this behavior only in one carousel where I'm doing the exact same thing as you, tapping on a pin on a map, and switching programmatically the carousel to the good position. The bug is happening even If I'm switching the position on the carousel manually (by swiping). I'm not sure this is happening cause of this control (but could be a possibility), as I was working a few months ago on this component and did not have this bug... I probably updated a lot of things since then so I need to investigate a little bit more. 

I can confirm the bug is not present on iOS.

**Comment by Umar3x** [comment]
@Zure1 @alexrainman 

I have found what was causing the prob for my case. I had a carousel within a grid within a stackLayout. 

I removed the grid and put the carousel directly into the stacklayout and bug disappeared. 

Grid I was using was simple : 

```
  var grid = new Grid();
   grid.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });
   grid.VerticalOptions = LayoutOptions.End;
```
I think that might be related to #298

**Comment by wegascee** [comment]
I had the following issue on iOS: When setting the position in code, the view was not completely visible. Either it the first 1/10 part was shown or the last 10/10 part was shown.

I think I solved this with:

`this.carouselView.AnimateTransition = false;`

Hope this helps anyone.
