### ISSUE TITLE
Sometimes, PositionSelected event not fire in iOS

### ISSUE THREAD

**Issue by cd155** [alexrainman/CarouselView#333]
Hi, 

I use the most new version of this plugin, but event PositionSelected didn't not fire every time on iOS. I use the iphone X simulator. Sometimes, PositionSelected fired when i swipe image, but sometimes it didn't. I tested on Android system, it works fine. 

private void CarouselView_PositionSelected(object sender, PositionSelectedEventArgs e)

**Comment by alexrainman** [comment]
Cant reproduce this.

**Comment by cd155** [comment]
Hi, 

When i swipe image, the PositionSelectedEventArgs didn't not fire sometimes. I put break point on this CarouselView_PositionSelected, it just not reach it sometimes. This only happen on iOS, and I build on my iphone, it has the same situation. Android system work as it expected.
