### ISSUE TITLE
[iOS]CarouselView not showing up at all

### ISSUE THREAD

**Issue by LeSanchez** [alexrainman/CarouselView#334]
I looked at multiple exemples online and can't seem to figure out what's wrong with my code.
Here's the c# partial code:

`
        public partial class CustomerPage : ContentPage
	{
        private Customer currentCustomer;
        public Customer CurrentCustomer { get => currentCustomer; set => currentCustomer = value; }

        private EventsItems eventItems;

        public CustomerPage()
        {
            InitializeComponent();
        }

        public CustomerPage(Customer customer)
        { 
            currentCustomer = customer;
            eventItems = new EventsItems(currentCustomer);
            BindingContext = eventItems;

            InitializeComponent();
        }
}
`

And the XAML code that goes with it
`<StackLayout BackgroundColor="{StaticResource MainColor}"
                         Margin="0" Padding="20" Spacing="10"
                         Orientation="Horizontal" 
                         VerticalOptions="Center" HorizontalOptions="FillAndExpand">

                <AbsoluteLayout BackgroundColor="{StaticResource MainColor}"
                                Padding="0,0,5,0"
                                WidthRequest="125" HeightRequest="150">

                    <Image x:Name="compagnieLogo" Source="ucaliselogo.png" 
                           Aspect="AspectFit"
                           AbsoluteLayout.LayoutBounds="1,0.5,0.75,0.75" AbsoluteLayout.LayoutFlags="All"/>

                </AbsoluteLayout>

                <StackLayout Orientation="Vertical"
                             Spacing="2" Margin="0,0,0,0" Padding="0"
                             VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand">

                    <Label x:Name="compagnieCategoryName"
                           Text="Restaurant" TextColor="White"
                           FontSize="20"/>

                    <Label x:Name="compagnieName"
                           Text="McDonald's" TextColor="White"
                           FontSize="20"/>

                    <Label x:Name="compagnieAdresse"
                           Text="3306 rue King Ouest" TextColor="White"
                           FontSize="20"/>

                </StackLayout>

            </StackLayout>
            
            <Label Text="NOTE" BackgroundColor="White" HorizontalTextAlignment="Center"
                   VerticalOptions="Center" HorizontalOptions="FillAndExpand"/>

            <controls:CarouselViewControl x:Name="carouselView"
                                          ItemsSource="{Binding events}"
                                          Orientation="Horizontal"
                                          VerticalOptions="CenterAndExpand" HorizontalOptions="FillAndExpand">
                <controls:CarouselViewControl.ItemTemplate>
                    <DataTemplate>
                        <StackLayout BackgroundColor="Black"
                                     VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                            <BoxView VerticalOptions="Center" HorizontalOptions="Center"
                                     Color="Blue"
                                     WidthRequest="50" HeightRequest="50"/>
                        </StackLayout>
                    </DataTemplate>
                </controls:CarouselViewControl.ItemTemplate>
            </controls:CarouselViewControl>
            
        `</StackLayout>

And the class EventItems for the binding 

'public class EventsItems
    {
        //temporaly with customer type for debugging (change type to events and suplly all events related 
       to the current customer)
        private ObservableCollection<int> events = new ObservableCollection<int>();
        private Customer compagnie;

        public EventsItems(Customer currentCompagnie)
        {
            compagnie = currentCompagnie;

            events.Add(1);
            events.Add(2);
            events.Add(3);
        }

        public ObservableCollection<int> Events { get => events; set => events = value; }
    }
'

For now I'm only trying to display a box in each view for debugging and I can't even make this work.
Thank you!

**Comment by alexrainman** [comment]
Are you calling Init() on each platform?

**Comment by LeSanchez** [comment]
Yes i did call Init()! I also included  the necessary namespace at the top of my XAML file

**Comment by alexrainman** [comment]
I know whats your problem. CarouselView doesn't show in a StackLayout unless you specify HeightRequest. Use a Grid instead. It is something related to XF 2.5.x, it works with previous versions.

**Comment by LeSanchez** [comment]
Hey Alex I just tried using a Grid too and it didn't work either. So I tried a stacklayout with HeightRequest specified and still nothing showed up. I even reverted back to the last XF 2.4.x and still it didn't apear, the problem must be somewhere else!

**Comment by alexrainman** [comment]
Then it should be something in your code.

**Comment by LeSanchez** [comment]
I know that, but I can't seem to figure out what's wrong with. I already spent a couple hours looking it.

**Comment by alexrainman** [comment]
Can you share a demo?

**Comment by LeSanchez** [comment]
I can't share the project i'm working on right now since it's for a private company, but I'll reproduce it in a new project and share it with you

**Comment by LeSanchez** [comment]
Here's a project that reproduces the issue 
https://github.com/LeSanchez/Demo

**Comment by LeSanchez** [comment]
Let me know when you've run it!

**Comment by LeSanchez** [comment]
Hey could you reopen the issue in case someone else ran into the same issue?

**Comment by Umar3x** [comment]
I'm running in the same issue with a carousel inside a grid for which itemsSource is an ObservableCollection<View>. Working well on Android nevertheless...

**Comment by asanka-indrajith** [comment]
I'm also getting this. It's frustrated to see this. It's works fine in android but not in iOS.
