### ISSUE TITLE
PositionSelected event contains incorrect Position in the eventargs (Android)

### ISSUE THREAD

**Issue by gtgatsby** [alexrainman/CarouselView#335]
Occasionally the PositionSelected event will have the current (ie, previous) Position as the e.NewValue in Android. It doesn't happen all the time, it seems to be some sort of race condition.

The problem seems to be that in the Android CarouselViewImplementation, the ViewPager_PageScrollStateChanged event occasionally fires before the ViewPager_PageSelected event.

The Position is not updated until the PageSelected Fires, so if they fire "out of order", you get the old Position instead of the new one. I'm not sure if there was a particular reason for using PageScrolledStateChanged in the first place, but I moved the Event firing code to PageSelected instead, and it seems to work fine now.

**Comment by alexrainman** [comment]
Yeah but then PositionSelected is called before the page is fully showing on the screen. This will mess with the implementation as PositionSelected will be called if you swipe a little and don't change the current page at all.
