### ISSUE TITLE
Issue where views 2 away from current position aren't being rendered properly when brought back into view

### ISSUE THREAD

**Issue by Nixon-Joseph** [alexrainman/CarouselView#338]
I've got a list of 4 ContentViews in my carousel view. On first appearance, they're all fine, but if I cycle to position 2, then go back to position 0, there are images/full width buttons not displaying properly. My button text is left aligned in the button, and images sometimes just don't show up.

This is all in android, haven't tested in IOS yet.

Initializing like so:

`ViewList = new ObservableCollection<View>()

            {
                new CheckoutStep1View(),
                new CheckoutStep2View(),
                new CheckoutStep3View(),
                new CheckoutStep4View()
            };
            StepCarousel = new CarouselViewControl()
            {
                ItemsSource = ViewList,
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                IsSwipeEnabled = false,
                BindingContext = this,
                ShowArrows = false
            };
            MainStackLayout.Children.Add(StepCarousel);`

I've tried a ForceLayout() on both the page and on the respective Carousel View called on PositionSelected. That didn't do anything to help.

It seems as though the carousel distorts or maybe just stops holding the view in memory once it's 2 away from current position. Is there perhaps some way to extend the buffer if that's the case? I won't ever have more than 4 views in this particular usage.
This option seems unlikely to me because the initial viewing of each page is fine, unless it handles previously viewed pages differently than fresh ones.

Could it potentially be an issue of not defining an ItemTemplate? I need the views in the ItemSource to display exactly as they are, and wasn't sure how to incorporate it into a separate view/Template.

This Carousel is really the only viable option we have for this particular piece of ui, so anything you can do to help will be greatly appreciated. Thanks!

P.S. I have attached several images showing the symptoms. I did notice, that if I get my keyboard to open, then the views display properly. There might be some way to force that same event?

P.P.S The image being pointed to in the third attachment is the one that sometimes doesn't show up. Couldn't get it to happen for my screenshots though.

![page1initial](https://user-images.githubusercontent.com/10250222/35595041-f4c3643c-05da-11e8-98e1-73b1e55f571e.jpg)
![page1after](https://user-images.githubusercontent.com/10250222/35595046-f8038492-05da-11e8-8604-a802752cb72f.jpg)
![page4initial](https://user-images.githubusercontent.com/10250222/35595050-fa1ff1de-05da-11e8-99a9-3d9aeecbd09e.jpg)
![page4after](https://user-images.githubusercontent.com/10250222/35595053-fcf36c2e-05da-11e8-92df-888e28a1a547.jpg)

**Comment by Nixon-Joseph** [comment]
I also just noticed that certain elements (Switches specifically) Aren't animating when toggled either.

**Comment by maximilianrublik** [comment]
I am having trouble with this problem as well.. As far as I know this is only an Android thing.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
