### ISSUE TITLE
In iOS, when setting position, carousel only goes to 2nd slide

### ISSUE THREAD

**Issue by IanCaz** [alexrainman/CarouselView#339]
In my mobile app, I have a list of orders.  In each order, I have a list of tasks.  These tasks are bound to the ItemSource of the CarouselView.  There is a pop-up ListView they can display to pick a specific task.  On selecting the task, I grab the index of that item & set the CarouselView's Position=thatIndex.

When the app first loads & I get my first order, everything works as expected.  If I change orders (which loads a new set of tasks) and then try to pick a specific task out of the ListView, the CarouselView will display the second "slide" (position 1), even though if I output the value of "Position" it will show 10 (or whatever item index I selected).

I'm working on trying to get a demo project together.

I'm under a huge time crunch on this project, so any help you can offer would be appreciated.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
