### ISSUE TITLE
ScrollView Inside Datatemplate not work

### ISSUE THREAD

**Issue by dashne** [alexrainman/CarouselView#34]
Hi, I have a label within a stacklayout,and and stacklayout inside scrollview with it is inside the datatemplate of carouselview control,this label holds a string that is bigger than the screen(vertically), therefore I need that scrollView,but the scrollview is not working. please can you provide any solution for this

thanks

**Comment by alexrainman** [comment]
If you take a look at the demo, i use StackLayout inside ScrollView and it works without issues.

```
<ScrollView>
    <StackLayout Padding="12" Spacing="12">
			
	<controls:CVLabel Text="Quod cum ita sit, paucae domus studiorum seriis cultibus antea celebratae nunc ludibriis ignaviae torpentis exundant, vocali sonu, perflabili tinnitu fidium resultantes. denique pro philosopho cantor et in locum oratoris doctor artium ludicrarum accitur et bybliothecis sepulcrorum ritu in perpetuum clausis organa fabricantur hydraulica, et lyrae ad speciem carpentorum ingentes tibiaeque et histrionici gestus instrumenta non levia."/>

    </StackLayout>
</ScrollView>
```

But, you have to use CVLabel. It's a custom control that set the height of the label depending on it's content.

```
public class CVLabel : Label
{
    public CVLabel()
    {
        SetBinding(Label.HeightRequestProperty, new Binding("WidthRequest", BindingMode.Default, new LabelHeightConverter(), this, null, this));
    }

    protected override void OnSizeAllocated(double width, double height)
    {
        base.OnSizeAllocated(width, height);

        WidthRequest = width;

        this.LayoutTo(new Rectangle(this.X, this.Y, width, height));

        this.InvalidateMeasure();
    }
}
```

**Comment by dashne** [comment]
Ok,I used CVLabel but still cannot scroll I dont know I use formattedText of Label because there is some text needs to be colorized like Titles and numbers,here its my xaml code:
`<ContentPage.Resources>
        <ResourceDictionary>
            <converter:PageToMainTextConverter x:Key="MainText" />
            <converter:PageToFooterTextConverter x:Key="FooterText" />
            <DataTemplate x:Key="PageData">
                <StackLayout Orientation="Vertical">
                    <ScrollView VerticalOptions="FillAndExpand" Orientation="Vertical">
                        <control:CVLabel FormattedText="{Binding Page, Converter={StaticResource MainText}}"
                               FontSize="30"
                               HorizontalTextAlignment="End" />
                    </ScrollView>                    
                </StackLayout>
            </DataTemplate>
        </ResourceDictionary>
    </ContentPage.Resources>
    <StackLayout>
        <StackLayout />
        <control:CarouselViewControl ItemsSource="{Binding Pages}"
                           VerticalOptions="FillAndExpand"
						   Orientation="Horizontal"
                           HorizontalOptions="FillAndExpand"
                           Position="{Binding PageIndex,Mode=TwoWay}"
                           ItemTemplate="{StaticResource PageData}"
                           x:Name="Pager">
            
        </control:CarouselViewControl>`

**Comment by alexrainman** [comment]
You label is not wrapped by ScrollView

**Comment by dashne** [comment]
sorry, I had problem with inserting code and still I have please Can you look at this now:
` <ContentPage.Resources>`
        `<ResourceDictionary>`
           ` <converter:PageToMainTextConverter x:Key="MainText" />`
           ` <converter:PageToFooterTextConverter x:Key="FooterText" />`
           ` <DataTemplate x:Key="PageData">`
               ` <StackLayout Orientation="Vertical">`
                   ` <ScrollView VerticalOptions="FillAndExpand" Orientation="Vertical">`
                      `  <control:CVLabel FormattedText="{Binding Page, Converter={StaticResource MainText}}"`
                              ` FontSize="30"`
                             `  HorizontalTextAlignment="End" />`
                   ` </ScrollView>`                    
               ` </StackLayout>`
           ` </DataTemplate>`
        `</ResourceDictionary>`
    `</ContentPage.Resources>`
    `<StackLayout>`
               `<control:CarouselViewControl ItemsSource="{Binding Pages}"`
                          ` VerticalOptions="FillAndExpand"  Orientation="Horizontal"`
                          ` HorizontalOptions="FillAndExpand"`
                           `Position="{Binding PageIndex,Mode=TwoWay}"`
                           `ItemTemplate="{StaticResource PageData}"`
                           `x:Name="Pager">`
            
        `</control:CarouselViewControl> `

**Comment by dashne** [comment]
Thank you alexrainman, you guided me to the right way I added another overload measure method and passed FormattedString instead of string variable type,and in implementation I just converted it to string by 
text.ToString(),then from LabelHeightConverter I used label.FormattedText and it works.

Again Thank you so much.

**Comment by alexrainman** [comment]
Can you share your implementation?

**Comment by dashne** [comment]
Off course:
int ITextMeter interface I added:

`double MeasureTextSize(FormattedString text, double width, double fontSize, string fontName = null);`

In Droid project: in TextMeterImplementation:

`public double MeasureTextSize(FormattedString text, double width, double fontSize, string fontName = null)
        {
            var textView = new TextView(global::Android.App.Application.Context);
            textView.Typeface = GetTypeface(fontName);
            textView.SetText(text.ToString(), TextView.BufferType.Normal);
            textView.SetTextSize(ComplexUnitType.Px, (float)fontSize);

            int widthMeasureSpec = AViews.View.MeasureSpec.MakeMeasureSpec(
                (int)width, AViews.MeasureSpecMode.AtMost);
            int heightMeasureSpec = AViews.View.MeasureSpec.MakeMeasureSpec(
                0, AViews.MeasureSpecMode.Unspecified);

            textView.Measure(widthMeasureSpec, heightMeasureSpec);

            return (double)textView.MeasuredHeight;
        }`
In LabelHeightConverter I used:

`var height = DependencyService.Get<ITextMeter>().MeasureTextSize(label.FormattedText, width, label.FontSize, label.FontFamily);`

That's all.

**Comment by alexrainman** [comment]
And iOS?

**Comment by dashne** [comment]
I didn't tested it, sorry

**Comment by alexrainman** [comment]
I released a new version with lot of fixes and improvements, including support for latest Forms.

**Comment by alexrainman** [comment]
Does latest release solve this?

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/
