### ISSUE TITLE
[iOS] Does not show content in bottom safe area on iphone X

### ISSUE THREAD

**Issue by maksirol** [alexrainman/CarouselView#340]
On iphone X it's impossible to use all area with carouselView control. I suppose it's correlated with iphone X safe area.

Code to reproduce it:

    public class MainPage : ContentPage 
    {
        public MainPage()
        {
            var pages = new List<string>
            {
                "test1",
                "test2"
            };

            var carousel = new CarouselViewControl
            {
                ItemTemplate = new DataTemplate(typeof(Test)),
                ItemsSource = pages
            };

            Content = carousel;
        }
    }

    public class Test : StackLayout
    {
        public Test()
        {
            for (int i = 0; i < 40; i++)
            {
                Children.Add(new Label { Text = "Hello" });
            }

            BackgroundColor = Color.Chartreuse;

        }
    }

![screen shot 2018-02-01 at 10 29 27](https://user-images.githubusercontent.com/6607569/35668748-556e9d40-073b-11e8-80d6-de1ad45d2c6c.jpg)

**Comment by alexrainman** [comment]
No idea. Don't have an ugly iPhone X to test :)

**Comment by cd155** [comment]
You need to set padding for this page or this control. 

[Using SafeArea layout](https://blog.xamarin.com/making-ios-11-even-easier-xamarin-forms/)

Hope this helpful

**Comment by rjcollingham** [comment]
@cd155 the original question was how to get the carouselview to use the bottom part of the iphone X screen. Using SafeArea doesn't help with this, in fact it adds extra padding.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by SagarPanwala** [comment]
Is there any update on this ?
Reason to message here to pop this question up as upcoming devices are now mostly with Safe Area.
