### ISSUE TITLE
Overlapping of upcoming elements

### ISSUE THREAD

**Issue by tomh4** [alexrainman/CarouselView#341]
Hello,

would it be possible to add "overlapping" of the upcoming slide to hint at a scrollable content ? 
Something like seen in this image : 
<img width="477" alt="grafik" src="https://user-images.githubusercontent.com/19487549/35707140-eb09ab20-07a8-11e8-8b02-8d71b27c8883.png">

As you can see here the upcoming slides' borders are already in the view so the users know he can scroll 

An optioun would be **negative** **InterPageSpacing**

**Comment by codebeaulieu** [comment]
+1 
We had a client that requested this recently. I think this would be a handy addition

**Comment by alexrainman** [comment]
This will require lot of code refactoring and research on each native control, and it is not possible with current implementation.

**Comment by tomh4** [comment]
Hmm sad to hear...
I've tried to work around the limitation by Translating the upcoming Content to the left, but unfortunately the upcoming page is rendered only at the time of scrolling. Is it possible to precache the upcoming page somehow?
