### ISSUE TITLE
Lazy / Deferred Loading

### ISSUE THREAD

**Issue by K232** [alexrainman/CarouselView#347]
Hi Alex,
I like your plugin, but I have a question regarding lazy or deferred loading. I've found #140 but my problem is a bit different. I have e.g. 100 pages to be shown in the Carousel. It takes some time to render, so I want to render only the current page and maybe 3 to the left and 3 to the right. As soon as the user scrolls / taps to the left or right, the next page should be rendered.
Unfortunately I could not get it to work as I could not update the observable collection. 
Do you think this should work and do you have any example for that?
Many thanks in advance!

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by K232** [comment]
How is the current situation regarding the merge into Xamarin Forms master branch?
