### ISSUE TITLE
UWP does not support any version lower than Fall Creators update

### ISSUE THREAD

**Issue by JKennedy24** [alexrainman/CarouselView#348]
Latest version of this library forces me to set my min version and target version to `Fall Creators Update`

Is this change on purpose or can this library allow versions less than `Fall Creators Update`

**Comment by JKennedy24** [comment]
To support lower versions of UWP this line here: https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.UWP/CarouselView.FormsPlugin.UWP.csproj#L15

Would need setting to a lower vesion

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
