### ISSUE TITLE
Nuget install disables listviews' context action  in Android 

### ISSUE THREAD

**Issue by Martin080793** [alexrainman/CarouselView#349]
Like the title says, this Nuget disables the context actions in listviews on android (ios still works). Just by installing it!!

Thats very sad, because aside from this issue this CarouselView is awesome.

## Update.
This issue only appears in Debug-Mode. After distributing and installing the apk-file on my Android phone it is working.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
