### ISSUE TITLE
Visualize more than one page at a time

### ISSUE THREAD

**Issue by acaliaro** [alexrainman/CarouselView#35]
Hi @alexrainman and thanks for this great works. Your Carousel works as "Xamarin" Carousel. If I swipe from right to left, the first page disappear and the second appears. Could be possible to add a property that does not made a "jump" from page1 to page2, but swipe can display part of page1 and part of page2 in the same time... hope to be clear...

**Comment by alexrainman** [comment]
@acaliaro as far as i know the platform specific widget used behind the scenes are not designed to work like that. By their name: Android ViewPager and iOS UIPageViewController :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
