### ISSUE TITLE
[iOS] Linked CarouselViews not updateing correctly

### ISSUE THREAD

**Issue by pandaloupe** [alexrainman/CarouselView#351]
I have a setting with two horizontal CarouselVieControls that bind their Position too the same Field in the ViewModel. It works fine on Android, so when I swipe either of the Carousles to the left or right the other one follows as soon as the Position changes. On iOS the "following" Carousel stops the animation just before reaching the final destination leaving a gap to the side. Is there another way updating the carousel Position so this doesn't happen?

![c7238e08-27b2-409c-8c5d-736d408e914c](https://user-images.githubusercontent.com/36296520/36023660-78598fa6-0d8d-11e8-9594-753f38cb78f1.jpg)
![5fdddad9-a610-4822-b046-9289ca5b4f29](https://user-images.githubusercontent.com/36296520/36023662-7ae2dbf6-0d8d-11e8-96f0-d8eff2010903.jpg)

The bindings are defined like this in Xaml: 
`Position="{Binding CarouselPosition}"`

The model's property works like this:

`
       public int CarouselPosition
        {
            get => _carouselPosition;

            set
            {
                _carouselPosition = value;
                InvokePropertyChanged();
            }
        }
`
The property change triggers an update of the model to extend it (endless scrolling), maybe this has something to do with this behaviour. But as stated above, it works fine on Android. I can provide you with more code if it helps you to resolve or reproduce this issue.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
