### ISSUE TITLE
Unable to resolve 'CarouselView.FormsPlugin (>= 5.0.2)' for 'UAP,Version=v10.0.15063'

### ISSUE THREAD

**Issue by ruisilva450** [alexrainman/CarouselView#352]
Hi,

I'm trying to compile the version 5.0.2 for UWP with minimum version of 15063 but I'm getting the error:

```
##[error]The nuget command failed with exit code(1) and error(NU1100: Unable to resolve 
'CarouselView.FormsPlugin (>= 5.0.2)' for 'UAP,Version=v10.0.15063'.
```

Any help with this? 
https://github.com/alexrainman/CarouselView/commit/32cf20f4d04bfc36a0981ee3bd1b2c7c76ad507a#diff-7b38f8e3f46b07ac0e19ad5e22f15df6L15

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
