### ISSUE TITLE
What happened to Control (ios, content blinking, invisible)?

### ISSUE THREAD

**Issue by bondarenkod** [alexrainman/CarouselView#353]
I have some strange behavior ([video](https://bdfss.blob.core.windows.net/shots/20180211_222432000_iOSTrim.mp4)) with the control with simple layout inside - content is blinking and becomes invisible.
Earlier I got this error with one image control inside but then I left only 1 empty colored grid with fixed size inside for test and I continued to observe this issue. 
What I'm doing wrong? 
Version - 5.2.0
ios - 11.5.2 
xamarin forms - 2.5.0.122203 (.net standart)

Demo: https://github.com/bondarenkod/CarouselViewVisualIssue
some unnecessary parts are skipped
[MainPage.xaml](https://github.com/bondarenkod/CarouselViewVisualIssue/blob/master/CarouselViewVisualIssue/CarouselViewVisualIssue/MainPage.xaml)
```
<ContentPage
    x:Class="CarouselViewVisualIssue.MainPage">
    <Grid>
        <abstractions:CarouselViewControl
            x:Name="cvc"
            HorizontalOptions="Fill"
            InputTransparent="False"
            InterPageSpacing="10"
            ShowIndicators="False"
            VerticalOptions="Fill">
            <abstractions:CarouselViewControl.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid
                            BackgroundColor="Aqua"
                            HeightRequest="100"
                            HorizontalOptions="Center"
                            VerticalOptions="Center"
                            WidthRequest="100" />
                    </Grid>
                </DataTemplate>
            </abstractions:CarouselViewControl.ItemTemplate>
        </abstractions:CarouselViewControl>
    </Grid>
</ContentPage>
```

[AppDelegate.cs](https://github.com/bondarenkod/CarouselViewVisualIssue/blob/master/CarouselViewVisualIssue/CarouselViewVisualIssue.iOS/AppDelegate.cs)
```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    global::Xamarin.Forms.Forms.Init();
    CarouselViewRenderer.Init();
    LoadApplication(new App());
    return base.FinishedLaunching(app, options);
}
```

**Comment by jcaffera** [comment]
I have the same issue, have you found any workaround for this?

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
