### ISSUE TITLE
Vertical carousel crash with buttons on Android phone

### ISSUE THREAD

**Issue by robinos** [alexrainman/CarouselView#354]
I downloaded the code directly from this repo for some testing after having a problem with crashes on actual android phones, and noticed the same problem I was having with it in my project.
If you have a vertical carousel with more than one ContentView element, and add a button to every view, it crashes on load. It works fine without buttons, with buttons in horizontal mode, or with only one element in vertical mode. Oddly enough, it also works fine in the android simulator, but not on an actual Galaxy S8 running Android 7.0 - API 24.

**Comment by robinos** [comment]
I can add that it seems to also work fine in vertical mode to have one ContentView with button and one ContentView without, but not both. As soon as there are at least two with buttons, however, it throws a Java.Land.IndexOutofBoundsException: <Timeout exceeded getting exception details> on the page.AddView(nativeConverted); line in the InstantiateItem method of the PageAdapter class.

**Comment by robinos** [comment]
Also, to clarify, if I add the view without the button first, it will fail even with only two ContentView elements. It only works if the view with the button is the first element and all other views have no button. My best guess is that there is a problem with it attempting to render a button off-screen and therefore out of bounds.

**Comment by robinos** [comment]
An update: My own project has suddenly started working with buttons on the vertical carousel (both Android and iOS), even if the downloaded version of this project does not. Unfortunately, I'm not sure why.  In either case, my previous guess seems to have been wrong. If anything, it might just be some odd incompatibility, or attributed to the manifestation of some other known problem.

I did change a few things back and forth in my attempts to fix it, such as changing which class my android MainActivity inherited from before reverting back to FormsAppCombatActivity.  The only real permanent change of note was how I updated my viewmodel once data was loaded - clearing the placeholder view and populating with several views of real data.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
