### ISSUE TITLE
shared project

### ISSUE THREAD

**Issue by clavoro** [alexrainman/CarouselView#356]
Hello Alex,

Does this work with a Xamarin "shared" project, or only for PCL?  

I am trying to get it to work with my shared project and it compiles, but the images will not display.

Thanks, Chris

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
