### ISSUE TITLE
[iOS] System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by autosoftmultimedia** [alexrainman/CarouselView#357]
Hi,
I got some error logs from devices running my app:
Here the logs:

```
Object reference not set to an instance of an object

CarouselViewRenderer.Scroller_Scrolled (System.Object sender, System.EventArgs e)
UIScrollView+_UIScrollViewDelegate.Scrolled (UIKit.UIScrollView scrollView)
(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by wattsdeveloper** [comment]
Hello, we also get the same error.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by autosoftmultimedia** [comment]
Hi Alex, thanks for your work!

**Comment by SagarPanwala** [comment]
@alexrainman  : As I read somewhere that this control is not going to merge in XF. So will there be any fix for this ? I'm using this control and XF carousel lacks lots of cool things.
