### ISSUE TITLE
When ShowArrows="True" the control crash 

### ISSUE THREAD

**Issue by tmt242001** [alexrainman/CarouselView#358]
When CarouselViewControl is setup as below

MasterDetailPage --> DetalPage --> NavigationPage -> ContentPage --> CarouselViewControl 

settings the ShowArrows="True" crashes the application. 

Error:
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
