### ISSUE TITLE
horizontal listview

### ISSUE THREAD

**Issue by acaliaro** [alexrainman/CarouselView#36]
I don't know if CarouselView can visualize an horizontal listview... It would be great if I have pages with small width so I could visualize more pages at the same time on the display....

**Comment by alexrainman** [comment]
Same as the previous one :) but, to be clear, if you want to show more than one page at a time you trick it. Use 2 column grid on each page, so basically you will be dividing each page in half :)

**Comment by acaliaro** [comment]
Yes, but then I have 1/2 and 3/4... never 2/3...
Thanks

**Comment by alexrainman** [comment]
Sorry, this is not possible with the platform specific components. I may create another plugin using UICollectionView and something else for Android. Anyway, you can achieve that really easy with pure XAML

```
<ScrollView Orientation="Horizontal">
    <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" HeighRequest="20">
        <Image HeighRequest="20" WidthRequest="20" />
        <Image HeighRequest="20" WidthRequest="20" />
        <Image HeighRequest="20" WidthRequest="20" />
    </StackLayout>
</ScrollView
```

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
