### ISSUE TITLE
Carousel view indicator strip is transparent on iphone X

### ISSUE THREAD

**Issue by meldesoysa** [alexrainman/CarouselView#360]
I have implemented your component on android and Ios and it works fine on every device except iphone X. 

It seems that the image doesn't fill the area behind the the indicator bar (which is transparent). I can still see the indicator circles though.

The carousel view is used within a few different layouts that make a sliding panel. However I don't think its the panel itself, because when I replaced the carousel view with an image, it  filled the area correctly.

Code that doesn't work on iphoneX:
 <cv:CarouselViewControl x:Name="CarouselLayers" HorizontalOptions="FillAndExpand"  VerticalOptions="FillAndExpand"
        ItemsSource="{Binding CarouselImages}" Position="{Binding Position, Mode=TwoWay}" ShowIndicators="True">
                    <cv:CarouselViewControl.ItemTemplate>
                        <DataTemplate>
                            <ff:CachedImage Source="{Binding .}"  Aspect="Fill"></ff:CachedImage>
                        </DataTemplate>
                    </cv:CarouselViewControl.ItemTemplate>
                </cv:CarouselViewControl>

**Comment by meldesoysa** [comment]
I added a background color and it is visible behind the indicator bar at the bottom, so for some reason the image isn't stretching or scaling correctly to be behind the indicators. Only a problem on iphone X

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by harsanji** [comment]
Hi meldesoysa. Did you find a workaround for this? I know this repo will be merged into Xamarin.Forms but we have the problem right now.

**Comment by NehaGawri** [comment]
Is there any update on this issue ?
