### ISSUE TITLE
Binary XML file line #1: Error inflating class CarouselView.FormsPlugin.Android.HorizontalViewPager

### ISSUE THREAD

**Issue by Nishita1121** [alexrainman/CarouselView#361]
I'm getting this exception in my project, but when I'm running the demo application it's working fine in android device.
I'm working on Xamarin forms.
What I'm missing?

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by BioTurboNick** [comment]
@Nishita1121 - I'm seeing this issue on a release build with ProGuard enabled. Odd though, because it doesn't always seem to be a problem?

In case that helps while we wait for the official release.

**Comment by smallcandles** [comment]
In my case I saw this error due to setting Linker properties to "Sdk and User Assemblies".  Changing it to "Sdk Assemblies Only" solved the problem.  Presumably some code is being stripped by the linker that is in fact used at runtime.

**Comment by cassionandi** [comment]
@alexrainman how do I know if this feature was released? My app is on debug mode and crashs with this error. I need a urgent solution : (

**Comment by taublast** [comment]
Why did you guys close this issue, 'SDK only' is not a solution but a workaround.

**Comment by gsgou** [comment]
For me in Android calling the CarouselViewRenderer.Init() **AFTER Forms.Init()**
as mentioned in the README solved the issue.
```
Xamarin.Forms.Forms.Init(this, savedInstanceState);
// After Xamarin.Forms initialization
CarouselView.FormsPlugin.Android.CarouselViewRenderer.Init();
```

**Comment by Kingamattack** [comment]
I have the same issue using XF on Android 8.X.X, it works fine on 9.X.X
Do we still have to wait the release of the XF's version or there is a fix?
