### ISSUE TITLE
carouselViewControl automatically height itself to itemsource of images

### ISSUE THREAD

**Issue by Nixon-Joseph** [alexrainman/CarouselView#363]
I would very much like the ability to have my carousel pick it's height from it's children. 

```
<local:CardView HorizontalOptions="FillAndExpand" VerticalOptions="StartAndExpand" Style="{ DynamicResource Card }">

                    <controls:CarouselViewControl 
                        Orientation="Horizontal" 
                        InterPageSpacing="10" 
                        Position="0"  
                        VerticalOptions="FillAndExpand" 
                        HorizontalOptions="FillAndExpand"
                        ShowIndicators="True">

                        <controls:CarouselViewControl.ItemsSource>

                            <x:Array Type="{x:Type View}">

                                    <Image Source="https://site.com/images/app/banner2.png" Aspect="AspectFill" />

                                    <Image Source="https://site.com/images/app/banner3.png" Aspect="AspectFill" />

                            </x:Array>

                        </controls:CarouselViewControl.ItemsSource>

                    </controls:CarouselViewControl>

                </local:CardView>
```

I've got this xaml code, and it works fine, only I can't see the images unless I set a HeightRequest on the CarouselViewControl element.

**Comment by Nixon-Joseph** [comment]
If I update the code more like this...
```
<local:CardView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Style="{ DynamicResource Card }">
                    <controls:CarouselViewControl 
                        Orientation="Horizontal" 
                        InterPageSpacing="10" 
                        Position="0"  
                        VerticalOptions="FillAndExpand" 
                        HorizontalOptions="FillAndExpand"
                        ShowIndicators="True">
                        <controls:CarouselViewControl.ItemsSource>
                            <x:Array Type="{x:Type View}">
                                <Image Source="https://site.com/images/app/banner2.png" />
                                <Image Source="https://site.com/images/app/banner3.png" />
                            </x:Array>
                        </controls:CarouselViewControl.ItemsSource>
                    </controls:CarouselViewControl>
                </local:CardView>
```

Then I get them to show up, but it's too tall.

**Comment by Nixon-Joseph** [comment]
If it helps, CardView inherits from Frame

**Comment by ddobrev** [comment]
When is this going to be fixed? It's quite problematic, any control should be able to auto-size itself by default.

**Comment by ddobrev** [comment]
Also, using VerticalOptions="FillAndExpand" causes handlers for a changed position to be attached twice. Please fix this bug as it is a blocker in an otherwise extremely useful component.

**Comment by Nixon-Joseph** [comment]
@ddobrev  I believe I saw in an earlier issue that the owner of this project is no longer supporting it. I think it's as far along as it's going to get.
Someone will need to branch off of it and make their own if we want these issues fixed.

**Comment by ddobrev** [comment]
@Nixon-Joseph thank you for this piece of information, it's important though sad. I am personally not aware of a carousel better than this one so it's such a shame.

**Comment by alexrainman** [comment]
@ddobrev @Nixon-Joseph sadly i don't have time right now to maintain and fix all the issues reported.

**Comment by alexrainman** [comment]
@ddobrev @Nixon-Joseph a new branch doesn't need to be created as the control will be officially released in Xamarin.Forms

**Comment by ddobrev** [comment]
@alexrainman this is great news! Is your carousel going to be incorporated or some other? When is this going to happen?

**Comment by alexrainman** [comment]
@Nixon-Joseph the carousel gets it's height from the available space its parent is providing, not the other way around. Its children will get height from what CarouselView is providing them. Remember, CarouselView is a View, not a Layout.

@ddobrev this carousel will be included in Forms.

**Comment by Nixon-Joseph** [comment]
That's really cool that it'll be included in Xamarin.Forms. Thank you for your info. 

And the view relation makes sense, but there are many use cases where you may not know the exact height of the contents you'll be placing in the carousel, and it would be nice if it auto heighted itself to its contents. 

I hate to peddle a different plugin on this, but @ddobrev, this one seems promising for the auto-heighted functionality (Haven't tested yet) - https://github.com/AndreiMisiukevich/CardView - I'm thinking it'll work well, because as Alex pointed out, CarouselView is a view, not a layout, this other plugin inherits from a layout.

For the moment, still using this carouselView for my app's checkout steps. It's super nice, and very useful.

**Comment by Nixon-Joseph** [comment]
@ddobrev Yeah, the other one is super young, but it is being actively supported. Also, if you're looking for an auto heighting carousel, it sounds like this one is a 'no go' no matter what. Although, I suppose it might be possible to height it yourself once it loads.

Either way, once Xamarin starts support for this class, updates may be more complete, but they will definitely further apart, as they won't be focused on this aspect alone.

Marking closed, because Auto heighting is outside the scope of this plugin.

**Comment by kerrpeter** [comment]
This is a great control, but there are some issues with the height. 
I find that it displays well if I have `FillAndExpand` on it, but as Nixon-Joseph  says, without that it doesn't show up at all. I don't really what FillAndExpand on it as I want the other controls on the page to use the available space.
However I found a strange workaround, in that, the second time my page is displayed, the Carousel displays correctly even when I don't have FillAndExpand on it. But this means I've had to add a hack to display a different page first, and then switch to my page. Not sure how or why this resolves the display issue - hope this gets fixed when its part of the official Xamarin.Forms

**Comment by otapi** [comment]
For those, who still struggle with this issue, I found a workaround, how to change the height of the CarouselView manually. Just put it into a Grid like this:
`       <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="30" />
            </Grid.RowDefinitions>

            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>

            <cv:CarouselViewControl Orientation="Horizontal" Grid.Row="0" Grid.Column="0">
                <cv:CarouselViewControl.ItemsSource>
                    <x:Array Type="{x:Type View}">
                        <Label Text="Breakfast" HorizontalTextAlignment="Center"/>
                        <Label Text="1st Snack" HorizontalTextAlignment="Center" />
                        <Label Text="Lunch"  HorizontalTextAlignment="Center"/>
                    </x:Array>
                </cv:CarouselViewControl.ItemsSource>
            </cv:CarouselViewControl>
        </Grid>`

**Comment by otapi** [comment]
For those, who still struggle with this issue, I found a workaround, how to change the height of the CarouselView manually. Just put it into a Grid like this:`        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="30" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>
            <cv:CarouselViewControl Orientation="Horizontal" Grid.Row="0" Grid.Column="0">
                <cv:CarouselViewControl.ItemsSource>
                    <x:Array Type="{x:Type View}">
                        <Label Text="Breakfast" HorizontalTextAlignment="Center"/>
                        <Label Text="1st Snack" HorizontalTextAlignment="Center" />
                        <Label Text="Lunch"  HorizontalTextAlignment="Center"/>
                    </x:Array>
                </cv:CarouselViewControl.ItemsSource>
            </cv:CarouselViewControl>
        </Grid>
`

**Comment by astralmaster** [comment]
> For those, who still struggle with this issue, I found a workaround, how to change the height of the CarouselView manually. Just put it into a Grid like this:` <Grid> <Grid.RowDefinitions> <RowDefinition Height="30" /> </Grid.RowDefinitions> <Grid.ColumnDefinitions> <ColumnDefinition Width="*" /> </Grid.ColumnDefinitions> <cv:CarouselViewControl Orientation="Horizontal" Grid.Row="0" Grid.Column="0"> <cv:CarouselViewControl.ItemsSource> <x:Array Type="{x:Type View}"> <Label Text="Breakfast" HorizontalTextAlignment="Center"/> <Label Text="1st Snack" HorizontalTextAlignment="Center" /> <Label Text="Lunch" HorizontalTextAlignment="Center"/> </x:Array> </cv:CarouselViewControl.ItemsSource> </cv:CarouselViewControl> </Grid>`

How is this a solution to the issue? The idea is for the height to be determined automatically based on carousel's items' content. not to set a fixed height.
