### ISSUE TITLE
TapGesture

### ISSUE THREAD

**Issue by ufuf** [alexrainman/CarouselView#364]
@alexrainman I tried all your suggestions from #66 #191 and #200  without any luck. Can you check this again?

This is my code:
```<!-- Image -->
        <cv:CarouselViewControl 
            Grid.Row="2" Grid.Column="1"
            Orientation="Horizontal" 
            InterPageSpacing="10" 
            VerticalOptions="StartAndExpand" HorizontalOptions="FillAndExpand" HeightRequest="200"
            ItemsSource="{Binding attachments}" 
            ShowIndicators="true"
            x:Name="carousel"
            >
            <cv:CarouselViewControl.ItemTemplate>
                <DataTemplate>
                    <ffimageloading:CachedImage Margin="0,10" FadeAnimationEnabled="true" Source="{ Binding preview_url }" Aspect="AspectFill" VerticalOptions="StartAndExpand" HeightRequest="{Binding ImageHeight}"></ffimageloading:CachedImage>
                </DataTemplate>
            </cv:CarouselViewControl.ItemTemplate>
            <cv:CarouselViewControl.GestureRecognizers>
                <TapGestureRecognizer Tapped="Handle_Tapped" CommandParameter="{Binding .}"/>
            </cv:CarouselViewControl.GestureRecognizers>
        </cv:CarouselViewControl>

**Comment by AndreiMisiukevich** [comment]
@ufuf 
@lightray 
@GamesAgeddon 

Hi) you can try my pack
https://github.com/AndreiMisiukevich/CardView
https://www.nuget.org/packages/CardsView/

**Comment by alexrainman** [comment]
@ufuf whats the problem you have here?

**Comment by ufuf** [comment]
@alexrainman  I added tapgesture to the carouselview. It is working on iOS but does not invoke on Android.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by SandipAhluwalia** [comment]
For people using v5.2.0 of the plugin, I resolved this issue by adding a tap gesture inside the data template, but still binding to one command property in the parent view model as follows:

        <cv:CarouselViewControl
            x:Name="myCarouselViewCtrl"
            ItemsSource="{Binding MyItems}"
            ShowArrows="true"
            ShowIndicators="true"
            Orientation="Horizontal">
            <cv:CarouselViewControl.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding Path=BindingContext.ViewItemsDetailsCommand, Source={x:Reference Name=myCarouselViewCtrl}}"
                                                  CommandParameter="{Binding}"/>
                        </Grid.GestureRecognizers>
                        <ffimageloading:CachedImage
                            Aspect="AspectFill"
                            DownsampleToViewSize="False"
                            FadeAnimationEnabled="True"
                            FadeAnimationForCachedImages="True"
                            Source="{Binding ImageUri}"
                            ErrorPlaceholder="error.png">
                            <ffimageloading:CachedImage.LoadingPlaceholder>
                                <OnPlatform x:TypeArguments="ImageSource">
                                    <On Platform="UWP">Assets/loadingplaceholder.png</On>
                                    <On Platform="Android, iOS">loadingplaceholder.png</On>
                                </OnPlatform>
                            </ffimageloading:CachedImage.LoadingPlaceholder>
                        </ffimageloading:CachedImage>
                    </Grid>
                </DataTemplate>
            </cv:CarouselViewControl.ItemTemplate>
        </cv:CarouselViewControl>

This solution works for both iOS and Android (and maybe even UWP - untested).

**Comment by rredoh** [comment]
Hi @SandipAhluwalia, your suggestion is not working for me ==

**Comment by SandipAhluwalia** [comment]
Hi @rredoh, have you set up your view model for the page with the ItemsSource and Command properties as indicated in my XAML suggestion? The pattern I use is quite standard now whenever you need a button or a UI control/container to be tap recognised within a data template for things like a CarouselViewControl or even a ListView.

**Comment by sparkhead95** [comment]
@SandipAhluwalia Thanks, your solution helped me a lot!
For those wondering - the `CommandParameter="{Binding}"` part of his solution allows you to assign the sender object to the class of your item source, allowing you to uniquely identify it within a list, upon click event
