### ISSUE TITLE
Cutting the last listview item

### ISSUE THREAD

**Issue by raisaspagnol** [alexrainman/CarouselView#365]
Good afternoon, I have a problem when using CarouselView, I have a listview inside the carousel and when I get to the last item in that list the item is not shown in full, it gets cut off and you can not go down the list anymore. At first I thought that I was doing something wrong, but I tested the same code using the Xamarin.Forms.Carousel component and it worked, so I think the problem is with the component itself.

I'm waiting for a solution, because my application is depending on it and I could not find another good component like yours. Thank you

Follow the attached files. I could not attach the entire project because it exceeds the mb limit.
[ClassesCarousel.zip](https://github.com/alexrainman/CarouselView/files/1759667/ClassesCarousel.zip)
![screenshot_20180223-174348 1](https://user-images.githubusercontent.com/15223105/36685831-4f888298-1b03-11e8-9095-b50bf85e1f95.png)

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
