### ISSUE TITLE
Abstractions.IEnumerableExtensions GetCount throws exception when ShowArrows="true"

### ISSUE THREAD

**Issue by NoleHealth** [alexrainman/CarouselView#367]
Using TabPage as main navigation all the pages get newed up before any thing happens.
In iOS only, This code throws exception when setting ShowArrows="true"
e is null i would imagine.  I set the ItemSource in the Init method of my View model (NInject, custom NavService)

CarouselView.FormsPlugin.Abstractions.IEnumerableExtensions

public static int GetCount(this IEnumerable e)
		{
            var enumerator = e.GetEnumerator();
			int i = 0;
			while (enumerator.MoveNext())
			{
				i++;
			}
			return i;
		}

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
