### ISSUE TITLE
Change_Arrow_Image

### ISSUE THREAD

**Issue by Shivaprabhu049** [alexrainman/CarouselView#368]
Hi How can i change the arrow image like Prev.png and next.png .. as i wants to use my own images 
and also how to hide the pager dots... and make it scroll only when user clicks on arrow.

Thanks in advance.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
