### ISSUE TITLE
ShowArrows / Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JaeWLee** [alexrainman/CarouselView#369]
When ShowArrows=True
Debug System say "Object reference not set to an instance of an object"

**Comment by tonholis** [comment]
+1

**Comment by alexrainman** [comment]
Platform? Demo reproducing the issue?

**Comment by JaeWLee** [comment]
Maybe this error is for Android only
My UWP App is working well

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
