### ISSUE TITLE
StackLayout or Grid does not redraw after device orientation change

### ISSUE THREAD

**Issue by zappalenti** [alexrainman/CarouselView#370]
In my application, i use a stack layout as carousel template and that layout fill the screen horizontaly.
When I change device orientation, 3 itens of my carousel (current, previous and next) does not redraw and stay with the old orientation width.
If I scroll to make then out of that 3 specific itens (scroll next twice, for example) than they redraw with the right size.
Changing SetNativeView() method to call viewPager.RefreshDrawableState() when orientation changes make the code works fine.
Its possible to fix it this way?

Thanks!

/******************************/
EDITED
/******************************/
Thats not the real solution, neither the real problem. I've tested again and the problem is:
Element_SizeChanged fires before Element.Width changes, so when InstantiateItem is called it render current, previous and next itens with the wrong size.
Got no time to investigate further, but as temporary fix I've changed OnElementPropertyChanged to watch for Width changes then call SetNativeView() at every width change.
This is bad, because when we change the device orientation SetNativeView() are called twice, but at least the UI worked fine.

**Comment by bpater-tp** [comment]
I am also observing the same behaviour. After device rotation 3 pages are in wrong size.

**Comment by GamesAgeddon** [comment]
Have the same issue [Issue 310](https://github.com/alexrainman/CarouselView/issues/310)

**Comment by AndreiMisiukevich** [comment]
@zappalenti 
@bpater-tp 
@GamesAgeddon 

Hi colleagues, you can try my realization of carousel https://github.com/AndreiMisiukevich/CardView
It's available on nuget)

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
