### ISSUE TITLE
Shows wrong content in CarouselViewControl in a reused view cell in a listview

### ISSUE THREAD

**Issue by harsanji** [alexrainman/CarouselView#372]
I have a ListView with cells each containing a CarouselViewControl. When scrolling in the ListView, cells are reused. When reusing the cells the CarouselViewControl is not updated with the new content which makes the CarouselViewControl show the wrong content. This is true for both Android and iOS.

**Comment by AndreiMisiukevich** [comment]
Hi @harsanji 
you can try my pack
https://github.com/AndreiMisiukevich/CardView
https://www.nuget.org/packages/CardsView/

**Comment by jvhgamer** [comment]
My solution was to set the CarouselViewControls source to null then to the updated source. Seems to work for me.
ex:
` CarouselViewControl myCarousel = new CarouselViewControl();`
` myCarousel.ItemsSource = null;`
 `myCarousel.ItemsSource = yourSource;`

**Comment by harsanji** [comment]
I made a pull request fixing this issue (for iOS and Android) 20 days ago but nothing has happened.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
