### ISSUE TITLE
Parallax effect using an image inside the DataTemplate

### ISSUE THREAD

**Issue by sthewissen** [alexrainman/CarouselView#374]
This is not so much an issue as it is an inquiry if someone managed to do this? I've seen a few issues here mention parallaxing and I'd love to see it in action, but as far as I can tell it's a tricky one to pull off. The parallax code itself isn't that tricky since that can be achieved by using a simple `TranslateTo` but what would be a good way to get a reference to an image inside the DataTemplate to be able to actually translate it?

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
