### ISSUE TITLE
Invisible when using VerticalOptions="StartAndExpand"

### ISSUE THREAD

**Issue by jopmiddelkamp** [alexrainman/CarouselView#375]
# Problem
The carousel view seems to be unable to calculate its own height based on its content when using the start and expand vertical option. When using a specific height or the fill and expand vertical option the carousel view does show up. I've only tested it on Android as I don't have a MacBook availible to use at the moment.

# Code used
    <cvcontrols:CarouselViewControl x:Name="DontsCarousel" Orientation="Horizontal" ItemsSource="{Binding Donts}" VerticalOptions="StartAndExpand" HorizontalOptions="FillAndExpand" ShowIndicators="True" InterPageSpacing="20" BackgroundColor="Yellow">
        <cvcontrols:CarouselViewControl.ItemTemplate>
            <DataTemplate>
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto" />
                    </Grid.ColumnDefinitions>
                    <Image Source="{Binding ImageSrc}" HorizontalOptions="FillAndExpand" Aspect="AspectFill" Grid.Row="0" Grid.RowSpan="2" />
                    <BoxView BackgroundColor="AliceBlue" Opacity=".7" Grid.Row="1" />
                    <Label Text="{Binding Description}" HorizontalOptions="Center" VerticalOptions="Center" HorizontalTextAlignment="Center" Grid.Row="1" Margin="0, 10, 0, 10" />
                </Grid>
            </DataTemplate>
        </cvcontrols:CarouselViewControl.ItemTemplate>
    </cvcontrols:CarouselViewControl>

# Packages used
CarouselView.FormsPlugin => 5.2.0
Forms => 2.5.0.280555

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by alexrainman** [comment]
I think it will be before 3.0 but not sure about that.

**Comment by Nico04** [comment]
OK, how will we be updated ?
