### ISSUE TITLE
[Xarmarin.Forms.Android] App crash when navigating to another page

### ISSUE THREAD

**Issue by jopmiddelkamp** [alexrainman/CarouselView#376]
# Problem
In my Android app I run into the problem that if I'll use the WidthRequest, HeightRequest or the ShowArrows attributes my app crashes after navigating to another page. 

# Reproduction
I've been able to reproduce the issues in [this repo](https://github.com/jopmiddelkamp/CarouselViewBug). There are two feature branches in which the different issues are reproduced:
- feature/Failure_with_show_arrows
- feature/Failure_with_static_height

# Error message
See the error below:

03-20 17:04:55.071 D/Mono    (29662): DllImport attempting to load: '/system/lib64/liblog.so'.
03-20 17:04:55.072 D/Mono    (29662): DllImport loaded library '/system/lib64/liblog.so'.
03-20 17:04:55.072 D/Mono    (29662): DllImport searching in: '/system/lib64/liblog.so' ('/system/lib64/liblog.so').
03-20 17:04:55.072 D/Mono    (29662): Searching for '__android_log_print'.
03-20 17:04:55.072 D/Mono    (29662): Probing '__android_log_print'.
03-20 17:04:55.072 D/Mono    (29662): Found as '__android_log_print'.
03-20 17:04:55.076 I/MonoDroid(29662): UNHANDLED EXCEPTION:
03-20 17:04:55.081 I/MonoDroid(29662): System.Exception: Cannot destroy BugReproduction.Views.MainPage. ---> System.NullReferenceException: Object reference not set to an instance of an object.
03-20 17:04:55.081 I/MonoDroid(29662):   at CarouselView.FormsPlugin.Abstractions.IEnumerableExtensions.GetCount (System.Collections.IEnumerable e) [0x00000] in <639d0f3e20414bd4b5ad6e88e6a0f174>:0 
03-20 17:04:55.081 I/MonoDroid(29662):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetArrowsVisibility () [0x0005a] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
03-20 17:04:55.081 I/MonoDroid(29662):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x002c7] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
03-20 17:04:55.081 I/MonoDroid(29662):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:138 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:401 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00107] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:594 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:391 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:174 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) [0x0006b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:77 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Binding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty) [0x00042] in D:\agent\_work\1\s\Xamarin.Forms.Core\Binding.cs:126 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext) [0x0003b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:422 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.ApplyBindings () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:126 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x0005a] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:120 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.View.OnBindingContextChanged () [0x00042] in D:\agent\_work\1\s\Xamarin.Forms.Core\View.cs:99 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x00060] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:121 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.TemplatedPage.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00008] in D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedPage.cs:35 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.Page.OnBindingContextChanged () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Page.cs:206 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.ContentPage.OnBindingContextChanged () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\ContentPage.cs:16 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x0000e] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:442 
03-20 17:04:55.081 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0011b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:597 
03-20 17:04:55.082 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:391 
03-20 17:04:55.082 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:544 
03-20 17:04:55.082 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:84 
03-20 17:04:55.082 I/MonoDroid(29662):   at Xamarin.Forms.BindableObject.set_BindingContext (System.Object value) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:25 
03-20 17:04:55.082 I/MonoDroid(29662):   at Prism.Common.PageUtilities.DestroyPage (Xamarin.Forms.Page page) [0x0003c] in <039c2eaa586846c2bf4ee93ab79399dc>:0 
03-20 17:04:55.082 I/MonoDroid(29662):    --- End of inner exception stack trace ---
03-20 17:04:55.082 I/MonoDroid(29662):   at Prism.Common.PageUtilities.DestroyPage (Xamarin.Forms.Page page) [0x00057] in <039c2eaa586846c2bf4ee93ab79399dc>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at Prism.Navigation.PageNavigationService+<ProcessNavigationForRemovePageSegments>d__31.MoveNext () [0x0018f] in <039c2eaa586846c2bf4ee93ab79399dc>:0 
03-20 17:04:55.082 I/MonoDroid(29662): --- End of stack trace from previous location where exception was thrown ---
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at Prism.Navigation.PageNavigationService+<ProcessNavigation>d__30.MoveNext () [0x0010f] in <039c2eaa586846c2bf4ee93ab79399dc>:0 
03-20 17:04:55.082 I/MonoDroid(29662): --- End of stack trace from previous location where exception was thrown ---
03-20 17:04:55.082 I/MonoDroid(29662):   at BugReproduction.ViewModels.MainPageViewModel+<OnSelectBuildingCommandExecuted>d__24.MoveNext () [0x000aa] in C:\Users\Midde\source\repos\BugReproduction\BugReproduction\ViewModels\MainPageViewModel.cs:64 
03-20 17:04:55.082 I/MonoDroid(29662): --- End of stack trace from previous location where exception was thrown ---
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
An unhandled exception occured.

03-20 17:04:55.082 I/MonoDroid(29662):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <ff199c98c3f84852925dd37a0ef6113a>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <ff199c98c3f84852925dd37a0ef6113a>:0 
03-20 17:04:55.082 I/MonoDroid(29662):   at (wrapper dynamic-method) System.Object.8b23e7e3-4792-4bc5-84a7-920b8f6b0d7d(intptr,intptr)
03-20 17:04:55.114 W/zygote64(29662): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-20 17:04:55.123 D/Mono    (29662): DllImport searching in: '__Internal' ('(null)').
03-20 17:04:55.123 D/Mono    (29662): Searching for 'java_interop_jnienv_throw'.
03-20 17:04:55.123 D/Mono    (29662): Probing 'java_interop_jnienv_throw'.
03-20 17:04:55.123 D/Mono    (29662): Found as 'java_interop_jnienv_throw'.
03-20 17:04:55.856 E/mono    (29662): 
03-20 17:04:55.856 E/mono    (29662): Unhandled Exception:
03-20 17:04:55.856 E/mono    (29662): System.Exception: Cannot destroy BugReproduction.Views.MainPage. ---> System.NullReferenceException: Object reference not set to an instance of an object.
03-20 17:04:55.856 E/mono    (29662):   at CarouselView.FormsPlugin.Abstractions.IEnumerableExtensions.GetCount (System.Collections.IEnumerable e) [0x00000] in <639d0f3e20414bd4b5ad6e88e6a0f174>:0 
03-20 17:04:55.856 E/mono    (29662):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetArrowsVisibility () [0x0005a] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
03-20 17:04:55.856 E/mono    (29662):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x002c7] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
03-20 17:04:55.856 E/mono    (29662):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:138 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:401 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00107] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:594 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:391 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:174 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) [0x0006b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:77 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.Binding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty) [0x00042] in D:\agent\_work\1\s\Xamarin.Forms.Core\Binding.cs:126 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext) [0x0003b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:422 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.ApplyBindings () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:126 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x0005a] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:120 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.View.OnBindingContextChanged () [0x00042] in D:\agent\_work\1\s\Xamarin.Forms.Core\View.cs:99 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x00060] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:121 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.TemplatedPage.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00008] in D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedPage.cs:35 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354 
03-20 17:04:55.856 E/mono    (29662):   at Xamarin.Fo
03-20 17:04:55.860 E/mono-rt (29662): [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Cannot destroy BugReproduction.Views.MainPage. ---> System.NullReferenceException: Object reference not set to an instance of an object.
03-20 17:04:55.860 E/mono-rt (29662):   at CarouselView.FormsPlugin.Abstractions.IEnumerableExtensions.GetCount (System.Collections.IEnumerable e) [0x00000] in <639d0f3e20414bd4b5ad6e88e6a0f174>:0 
03-20 17:04:55.860 E/mono-rt (29662):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetArrowsVisibility () [0x0005a] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
03-20 17:04:55.860 E/mono-rt (29662):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x002c7] in <892bb6a09e5d43ddbe9591d58bbf4c0e>:0 
03-20 17:04:55.860 E/mono-rt (29662):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:138 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:401 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00107] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:594 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:391 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:174 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) [0x0006b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:77 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.Binding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty) [0x00042] in D:\agent\_work\1\s\Xamarin.Forms.Core\Binding.cs:126 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext) [0x0003b] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:422 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.ApplyBindings () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:126 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x0005a] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:120 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.View.OnBindingContextChanged () [0x00042] in D:\agent\_work\1\s\Xamarin.Forms.Core\View.cs:99 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x00060] in D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:121 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.TemplatedPage.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00008] in D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedPage.cs:35 
03-20 17:04:55.860 E/mono-rt (29662):   at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354 
03-20 17:04:55.861 D/        (29662): HostConnection::get() New Host Connection established 0x7e1dc76c32e0, tid 29662

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
