### ISSUE TITLE
Not rendering inside parentview initally hidden

### ISSUE THREAD

**Issue by biermeister69** [alexrainman/CarouselView#377]
I'm using CarouselView inside a view which is initially hidden. Both ItemsSource and ItemTemplate are binded and propertyChanged raised, but when parentview "IsVisible" changes to true there's nothing showing on CarouselView.

Doing the same operation with "IsVisible" true from the beginning, everything works fine.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
