### ISSUE TITLE
CarouselView doesn't render with AbsoluteLayout on Android

### ISSUE THREAD

**Issue by jerone** [alexrainman/CarouselView#38]
We have successfully implemented the CarouselView in our application. When trying to put a few buttons for navigation on top of the CarouselView (background red), it got weird. We use `AbsoluteLayout`, because at one point we'll use a transparent background so the buttons will hover over the carousel content. However it won't render on Android, while it does work on iOS (see screenshot below).

The XAML looks like:

```xaml
    <AbsoluteLayout BackgroundColor="Yellow" VerticalOptions="Fill">
        <StackLayout BackgroundColor="Blue" VerticalOptions="FillAndExpand">
            <controls:CarouselViewControl
                x:Name="IntroCarousel"
                ItemTemplate="{StaticResource myTemplateSelector}"
                ItemsSource="{Binding Pages}"
                Position="0" />
        </StackLayout>
        <StackLayout
			AbsoluteLayout.LayoutBounds="1,1,.5,1" 
			AbsoluteLayout.LayoutFlags="All"
            BackgroundColor="Red"
            Orientation="Horizontal"
            VerticalOptions="End">
            <Button
                x:Name="prevBtn"
                IsVisible="false"
                Style="{StaticResource IntroPreviousBtnStyle}"
                Text="Previous" />
            <Button
                x:Name="nextBtn"
                Style="{StaticResource IntroNextBtnStyle}"
                Text="Next" />
        </StackLayout>
    </AbsoluteLayout>
```

## Current situation

Screenshot of our app on iOS (working):
![ios](https://cloud.githubusercontent.com/assets/55841/20841089/dd58e93c-b8b2-11e6-9b15-8c2a1a53f277.PNG)

Screenshot of our app on Android (not working):
![android](https://cloud.githubusercontent.com/assets/55841/20841133/fbfc0aa4-b8b2-11e6-8a44-51fc1f57ecb6.PNG)

## Expected situation

So we expected to see no yellow background and the first item of the CarouselView to be visible (purple).

Is this a bug with CarouselView?

---------

_XF 2.3.3.168_
_CarouselView 2.5.1_

**Comment by jerone** [comment]
So it appeared to be some inconsistency between Xamarin.iOS and Xamarin.Android, because the following XAML code works:

```xaml
	<AbsoluteLayout BackgroundColor="Yellow"
	                HorizontalOptions="Fill"
	                VerticalOptions="Fill">
		<StackLayout AbsoluteLayout.LayoutBounds="0,0,1,1"
		             AbsoluteLayout.LayoutFlags="All"
		             BackgroundColor="Blue"
		             HorizontalOptions="FillAndExpand"
		             VerticalOptions="FillAndExpand">
			<controls:CarouselViewControl x:Name="IntroCarousel"
			                              HorizontalOptions="FillAndExpand"
			                              ItemTemplate="{StaticResource myTemplateSelector}"
			                              ItemsSource="{Binding Pages}"
			                              Position="0"
			                              VerticalOptions="FillAndExpand" />
		</StackLayout>
		<StackLayout AbsoluteLayout.LayoutBounds="1,1,0.9,1"
		             AbsoluteLayout.LayoutFlags="All"
		             BackgroundColor="Red"
		             Orientation="Horizontal"
		             VerticalOptions="End">
			<Button x:Name="prevBtn"
			        IsVisible="false"
			        Style="{StaticResource IntroPreviousBtnStyle}"
			        Text="Previous" />
			<Button x:Name="nextBtn"
			        Style="{StaticResource IntroNextBtnStyle}"
			        Text="Next" />
		</StackLayout>
```

**Comment by alexrainman** [comment]
Did you solved this?

**Comment by jerone** [comment]
[**@alexrainman**](https://github.com/alexrainman) commented on [2 dec. 2016 18:26 CET](https://github.com/alexrainman/CarouselView/issues/38#issuecomment-264511049 "2016-12-02T17:26:57Z - Replied by Github Reply Comments"):
> Did you solved this?

Yeah, see code [above](https://github.com/alexrainman/CarouselView/issues/38#issuecomment-264509658). The trick was to use the `LayoutBounds` on both `StackLayout`.

**Comment by alexrainman** [comment]
Yes, Forms has some problems in Android.

**Comment by jerone** [comment]
I'm not sure which one was correct (iOS or Android), but still weird that they behave differently.  😞

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
