### ISSUE TITLE
How to set Image Visibility according to Position?

### ISSUE THREAD

**Issue by Srusti-Thakkar** [alexrainman/CarouselView#380]
Hi, I am using your plugin for carousel View implementation. I want to display image based on carousel view item position. How can I achieve this? 
This is my custom horizontal Listview code : 
`<cc:CustomScrollView x:Name="CalenderView" HeightRequest="75"  Orientation="Horizontal" ItemsSource="{Binding CalendarItemList, Mode=TwoWay}" >
                        <cc:CustomScrollView.ItemTemplate>
                            <DataTemplate>
                                <ViewCell>
                                    <StackLayout HorizontalOptions="FillAndExpand" Margin="5">
                                        <Label Text="{Binding ShortNameText}" TextColor="{Binding Color}" FontSize="10" HorizontalTextAlignment="Center" VerticalTextAlignment="Center" ></Label>
                                        <Grid HorizontalOptions="Center" VerticalOptions="Center">
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="30*"/>
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="30*"/>
                                            </Grid.ColumnDefinitions>
                                            <Image HorizontalOptions="Center" BindingContext="{x:Reference Name=CarouselMenuItems}" Source="ic_orange_circle.png" Grid.Row="0" Grid.Column="0" HeightRequest="30" IsVisible="{Binding IsSelected}" WidthRequest="30">
                                               
                                            </Image>
                                            <Label HorizontalOptions="Center" Text="{Binding DateNumber}" VerticalTextAlignment="Center" HorizontalTextAlignment="Center" TextColor="{Binding Color}" Grid.Row="0" Grid.Column="0" FontSize="16"/>

                                        </Grid>

                                    </StackLayout>
                                </ViewCell>
                            </DataTemplate>
                        </cc:CustomScrollView.ItemTemplate>
                    </cc:CustomScrollView>`

This is my Carousel Item Listview code : 

`<controls:CarouselViewControl x:Name="CarouselMenuItems" HorizontalOptions="FillAndExpand" InputTransparent="False" ItemsSource="{Binding CarousolMenuItemsList}" VerticalOptions="FillAndExpand" >
                    <controls:CarouselViewControl.ItemTemplate>
                        <DataTemplate>
                            <ContentView x:Name="ListviewContent">

                                <ListView x:Name="LstMenu" BackgroundColor="#F5F5F5" ItemSelected="LstMenuItemSelected"  ItemTapped="LstMenuItemTapped" 
                                          SeparatorVisibility="None" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                                          HasUnevenRows="True" ItemTemplate="{StaticResource MenuItemTemplateSelector}" 
                                          ItemsSource="{Binding Path=.}" 
                                          CachingStrategy="RecycleElement" Margin="5,5,5,5">

                                </ListView>
                            </ContentView>
                        </DataTemplate>
                    </controls:CarouselViewControl.ItemTemplate>
                </controls:CarouselViewControl>`

And my expected output is as below : 
![untitled1](https://user-images.githubusercontent.com/22439278/38190007-f878f8b4-367f-11e8-9468-868d84b78774.png)

I just want to display orange circle image on selected position. How can I do in xaml or c#?

**Comment by roshanchaminda** [comment]
Hi,
Please see below issue number, Down load Demo App(TestCalPCL.zip). Same solution that you required has been implemented. 

https://github.com/alexrainman/CarouselView/issues/241,

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
