### ISSUE TITLE
Position not set on Item click when switch tab in  Android device.

### ISSUE THREAD

**Issue by Srusti-Thakkar** [alexrainman/CarouselView#381]
Hi, I am using your plugin and I have one problem. I am setting position of Carousel View on clicking some button. But when I am switching from another tab and try to click first time PositionSelected method not firing. But if I click on another button then it works fine. Look at the following scenario in below image. 

![image](https://user-images.githubusercontent.com/22439278/38238826-b4b702aa-3748-11e8-8ae3-8fbffcb6a105.png)

Now in Android If I am switching tab and get back to this tab again Date number clicked not changing position. "PositionSelected" method is not calling.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
