### ISSUE TITLE
It works perfect on Android but cannot work correctly on Ios

### ISSUE THREAD

**Issue by TianyiChen-1** [alexrainman/CarouselView#382]
![20180407084911](https://user-images.githubusercontent.com/26310794/38456732-3cb023a4-3a45-11e8-8dbe-5800a1aed2d4.png)
  <forms:CarouselViewControl x:Name="myCarousel" BackgroundColor="Yellow">

                    <forms:CarouselViewControl.ItemTemplate>
                        <DataTemplate>
                            <Label Text="{Binding .}" FontSize="60"/>
                        </DataTemplate>

                    </forms:CarouselViewControl.ItemTemplate>

                </forms:CarouselViewControl>

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
