### ISSUE TITLE
Crash - CarouselView inside ListView

### ISSUE THREAD

**Issue by AlexTeixeira** [alexrainman/CarouselView#385]
I have a CarouselView inside a ListView and the position in my model like this :

```
public int SelectedPlantPosition {
			[CompilerGenerated]
			get;
			[CompilerGenerated]
			set;
		}

		public ICollection<SelectedPlant> SelectedPlants {
			[CompilerGenerated]
			get;
			[CompilerGenerated]
			set;
		}
```

The XAML : 

```
<ListView CachingStrategy="RecycleElement" ItemsSource="{Binding Garden, Mode=TwoWay}" RowHeight="40" x:Name="PlantListView" BackgroundColor="{StaticResource BackgroundListColor}" SeparatorVisibility="None">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                <cv:CarouselViewControl Position="{Binding Position}" Orientation="Horizontal" InterPageSpacing="10" ItemsSource="{Binding SelectedPlants}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                                    <cv:CarouselViewControl.ItemTemplate>
                                        <DataTemplate>
                                             <StackLayout>
                                                <StackLayout.GestureRecognizers>
                                                    <TapGestureRecognizer Tapped="CarouselItem_Tapped" />
                                                </StackLayout.GestureRecognizers>
                                                <StackLayout Orientation="Horizontal" Padding="10,0,10,0">
                                                    <Label WidthRequest="30" VerticalOptions="Center" FontSize="Small" Text="{Binding PriceDetail.Quantity}">
                                                    </Label>
                                                    <Image Aspect="Fill" VerticalOptions="Center" HeightRequest="35" WidthRequest="35" Source="{Binding PlantProperties.PlantImgURL}" />
                                                    <StackLayout Padding="10,0,0,0" VerticalOptions="Center" Orientation="Vertical">
                                                        <Label Font="14" Text="{Binding PlantProperties.LatinName}" FontSize="Small" />
                                                        <!--<Label Text="{Binding PlantProperties.LatinName}" FontSize="Small" TextColor="{StaticResource ThirdTextColor}" />-->
                                                    </StackLayout>
                                                </StackLayout>
                                            </StackLayout>
                                        </DataTemplate>
                                    </cv:CarouselViewControl.ItemTemplate>
                                </cv:CarouselViewControl>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
```

When I change the position of the carousel and then scroll my List, I will have this a crash.

> Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: No view controller managing revealed view <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x7fa0331464d0; frame = (0 0; 320 41); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x60400542a020>>
> Native stack trace:
> 	0   CoreFoundation                      0x000000011325a1e6 __exceptionPreprocess + 294
> 	1   libobjc.A.dylib                     0x0000000114123031 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000011325f472 +[NSException raise:format:arguments:] + 98
> 	3   Foundation                          0x0000000108ff4652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
> 	4   UIKit                               0x00000001062a6fa2 -[UIPageViewController queuingScrollView:willManuallyScroll:toRevealView:concealView:animated:] + 1124
> 	5   UIKit                               0x00000001063c78ce -[_UIQueuingScrollView _notifyDelegateWillManuallyScroll:toRevealView:concealingView:animated:] + 127
> 	6   UIKit                               0x00000001063c8fe5 __54-[_UIQueuingScrollView _didScrollWithAnimation:force:]_block_invoke + 466
> 	7   UIKit                               0x00000001063c8af6 -[_UIQueuingScrollView _didScrollWithAnimation:force:] + 483
> 	8   UIKit                               0x00000001063c42cf -[_UIQueuingScrollView layoutSubviews] + 179
> 	9   UIKit                               0x00000001059df808 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1515
> 	10  QuartzCore                          0x000000010b30c61a -[CALayer layoutSublayers] + 177
> 	11  QuartzCore                          0x000000010b31082b _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
> 	12  QuartzCore                          0x000000010b29729f _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 343
> 	13  QuartzCore                          0x000000010b2c4940 _ZN2CA11Transaction6commitEv + 568
> 	14  QuartzCore                          0x000000010b20f836 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 270
> 	15  QuartzCore                          0x000000010b351b2e _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 248
> 	16  CoreFoundation                      0x00000001131e94b9 __CFMachPortPerform + 169
> 	17  CoreFoundation                      0x00000001131e93f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
> 	18  CoreFoundation                      0x00000001131e9361 __CFRunLoopDoSource1 + 465
> 	19  CoreFoundation                      0x00000001131e0f64 __CFRunLoopRun + 2532
> 	20  CoreFoundation                      0x00000001131e030b CFRunLoopRunSpecific + 635
> 	21  GraphicsServices                    0x0000000116991a73 GSEventRunModal + 62
> 	22  UIKit                               0x00000001059100b7 UIApplicationMain + 159
> 	23  ???                                 0x00000001326bfe48 0x0 + 5140905544
> 	24  ???                                 0x00000001326bfa73 0x0 + 5140904563
> 

I think this is related to the issue #296 

Any idea why this is happening ?

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by shoeIT** [comment]
I have the sam error, it seems atm the control is not devoloped or supported anymore. Xamarin Forms has to decide which control is merged into XF.

https://forums.xamarin.com/discussion/comment/344811#Comment_344811
