### ISSUE TITLE
NullReferenceException on iOS

### ISSUE THREAD

**Issue by kvpt** [alexrainman/CarouselView#386]
Hi,

AppCenter report a lot of crash on iOS related to CarouselView, no problem on others platforms (Android, UWP). We use the latest version (5.2.0).

Here the report :
CarouselViewRenderer.Scroller_Scrolled (System.Object sender, System.EventArgs e)
System.NullReferenceException: Object reference not set to an instance of an object

> 1 CarouselViewRenderer.Scroller_Scrolled (System.Object sender, System.EventArgs e)
> 2 UIScrollView+_UIScrollViewDelegate.Scrolled (UIKit.UIScrollView scrollView)
> 3 (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
> 4 UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
> 5 UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
> 6 Application.Main (System.String[] args)

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by kvpt** [comment]
Sorry for the mistake.
You can create an ISSUE_TEMPLATE.md file at the project root to make that information more visible.

**Comment by js-ka** [comment]
I also find this error very often in the crash reports of our app:
_CarouselViewRenderer Scroller_Scrolled(System.Object sender, System.EventArgs e)
System.NullReferenceException:_

Unfortunately, the control is not yet included in Xamarin Forms.
And it looks as if this will not change in the near future (last commit in the feature-carouselview branch 3 months ago).
That means there is currently no support for the CarouselView?
