### ISSUE TITLE
Exception in one project, not in another

### ISSUE THREAD

**Issue by thomashoef** [alexrainman/CarouselView#389]
I have 2 identical droid projects which both reference the same .NET Standard Library which holds my Xamarin views and viewmodels.

On one view, we add the Carousel Control.

When running Droid project 1, all works fine, the carousel is rendered etc.
When running Droid project 2, the app crashes when rendering the exact same view. There is no real visible reason for this. Would you have any ideas?

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.SetNativeView () [0x00074] in <987b2fd695d94047809eece606991303>:0 
[MonoDroid]   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.Element_SizeChanged (System.Object sender, System.EventArgs e) [0x00026] in <987b2fd695d94047809eece606991303>:0 
[MonoDroid]   at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00031] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:790 
[MonoDroid]   at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0005d] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:159 
[MonoDroid]   at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:519 
[MonoDroid]   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:159 
[MonoDroid]   at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00144] in D:\agent\_work\1\s\Xamarin.Forms.Core\GridCalc.cs:48 
[MonoDroid]   at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x0014b] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:245 
[MonoDroid]   at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:205 
[MonoDroid]   at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:637 
[MonoDroid]   at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:788 
[MonoDroid]   at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0005d] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:159 
[MonoDroid]   at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:519 
[MonoDroid]   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:159 
[MonoDroid]   at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00144] in D:\agent\_work\1\s\Xamarin.Forms.Core\GridCalc.cs:48 
[MonoDroid]   at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x0014b] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:245 
[MonoDroid]   at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:205 
[MonoDroid]   at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:637 
[MonoDroid]   at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:788 
[MonoDroid]   at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0005d] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:159 
[MonoDroid]   at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:519 
[MonoDroid]   at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:159 
[MonoDroid]   at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00144] in D:\agent\_work\1\s\Xamarin.Forms.Core\GridCalc.cs:48 
[MonoDroid]   at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x0014b] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:245 
[MonoDroid]   at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\agent\_work\1\s\Xamarin.Forms.Core\Layout.cs:205 
[MonoDroid]   at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:637 
[MonoDroid]   at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:788 
[MonoDroid]   at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0005d] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:159 
[MonoDroid]   at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:519 
[MonoDroid]   at Syncfusion.SfNavigationDrawer.XForms.Droid.SfNavigationDrawerRenderer.ConvertFormsToNative (Xamarin.Forms.View view, Xamarin.Forms.Rectangle size, Syncfusion.SfNavigationDrawer.XForms.SfNavigationDrawer formsnavigationDrawer, System.Boolean contentView) [0x000b2] in <46a088e8bce44ce98f5c02896d8725a4>:0 
[MonoDroid]   at Syncfusion.SfNavigationDrawer.XForms.Droid.SfNavigationDrawerMapping.OnNavigationDrawerPropertiesChanged (System.String propertyName, Syncfusion.SfNavigationDrawer.XForms.SfNavigationDrawer formsnavigationDrawer, Com.Syncfusion.Navigationdrawer.SfNavigationDrawer nativenavigationDrawer, System.Single width, System.Single height) [0x0029c] in <46a088e8bce44ce98f5c02896d8725a4>:0 
[MonoDroid]   at Syncfusion.SfNavigationDrawer.XForms.Droid.SfNavigationDrawerRenderer.nativeCalendar_LayoutChange (System.Object sender, Android.Views.View+LayoutChangeEventArgs e) [0x00078] in <46a088e8bce44ce98f5c02896d8725a4>:0 
[MonoDroid]   at Android.Views.View+IOnLayoutChangeListenerImplementor.OnLayoutChange (Android.Views.View v, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom, System.Int32 oldLeft, System.Int32 oldTop, System.Int32 oldRight, System.Int32 oldBottom) [0x0001f] in <ff199c98c3f84852925dd37a0ef6113a>:0 
[MonoDroid]   at Android.Views.View+IOnLayoutChangeListenerInvoker.n_OnLayoutChange_Landroid_view_View_IIIIIIII (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom, System.Int32 oldLeft, System.Int32 oldTop, System.Int32 oldRight, System.Int32 oldBottom) [0x0000f] in <ff199c98c3f84852925dd37a0ef6113a>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.e70be877-6a4e-4bfd-a07b-5fd5c8eca7e8(intptr,intptr,intptr,int,int,int,int,int,int,int,int)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
