### ISSUE TITLE
Page indicator doesn't work on iOS

### ISSUE THREAD

**Issue by Mony25** [alexrainman/CarouselView#39]
With the same code as used in #38  we're not able to make page indicator visible on iOS, android is working fine. We have AbsoluteLayout with 2 StackLayouts, CarouselView is inside StackLayout, PageIndicators set to true however doesn't show up on iOS.

**Comment by alexrainman** [comment]
Can you share the XAML of the page containing the carousel?

**Comment by Mony25** [comment]
```XAML
 <AbsoluteLayout BackgroundColor="Yellow" VerticalOptions="Fill">
        <StackLayout BackgroundColor="Blue" VerticalOptions="FillAndExpand">
            <controls:CarouselViewControl
                x:Name="IntroCarousel"
                ItemTemplate="{StaticResource myTemplateSelector}"
                ItemsSource="{Binding Pages}"
                PageIndicators="True"
                Position="0" />
        </StackLayout>
        <StackLayout
			AbsoluteLayout.LayoutBounds="1,1,.5,1" 
			AbsoluteLayout.LayoutFlags="All"
            BackgroundColor="Red"
            Orientation="Horizontal"
            VerticalOptions="End">
            <Button
                x:Name="prevBtn"
                IsVisible="false"
                Style="{StaticResource IntroPreviousBtnStyle}"
                Text="Previous" />
            <Button
                x:Name="nextBtn"
                Style="{StaticResource IntroNextBtnStyle}"
                Text="Next" />
        </StackLayout>
    </AbsoluteLayout>
```

**Comment by alexrainman** [comment]
I know whats the problem and i know how to solve but then it creates another one :)

**Comment by Mony25** [comment]
What is the new problem and what is the solution for the current one?

**Comment by alexrainman** [comment]
I have the same plugin but for NativeScript and in that version i use UIView to hold the UIPageViewController and UIPageControl because of exactly the same problem you are facing. But in {N}, UIView size by itself, in Xamarin.Forms it doesn't :(

**Comment by alexrainman** [comment]
I found whats the problem. Its a combination of the plugin issue and your XAML. Will work on it and let you know when i am releasing an update.

**Comment by alexrainman** [comment]
First, your xaml may look like this:

```
<AbsoluteLayout BackgroundColor="Yellow" VerticalOptions="Fill">
        <StackLayout BackgroundColor="Blue" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
			AbsoluteLayout.LayoutBounds="0,0,1,.9" 
			AbsoluteLayout.LayoutFlags="All">
            <controls:CarouselViewControl x:Name="myCarousel" Orientation="Horizontal" InterPageSpacing="10" PageIndicators="true" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"/>
        </StackLayout>
        <StackLayout VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
			AbsoluteLayout.LayoutBounds="1,1,1,.1" 
			AbsoluteLayout.LayoutFlags="All"
            BackgroundColor="Red"
            Orientation="Horizontal">
            <Button
                x:Name="prevBtn"
                IsVisible="false"
                Text="Previous" />
            <Button
                x:Name="nextBtn"
                Text="Next" />
        </StackLayout>
    </AbsoluteLayout>
```

**Comment by alexrainman** [comment]
Your XAML is weird anyway because in this case you use a grid or StackLayouts :)

**Comment by alexrainman** [comment]
No reason to use AbsoluteLayout in this scenario. It is memory consuming.

**Comment by alexrainman** [comment]
Anyway it helped me to find a problem and apply a patch.

**Comment by Mony25** [comment]
My fault the xaml code was not the current one, which is the same as yours. Anyway thanks for the fix.

**Comment by jerone** [comment]
Hi @alexrainman, this issue reappeared again when updating from 2.9.0 to 3.0.0. Only iOS is affected. Do you know how you fixed it last time? I tried to look at your commit, but there's just to much changes in there.

_Microsoft Visual Studio Professional 2015 Version 14.0.25431.01 Update 3
Xamarin   4.3.0.784 (73f58d6)
Xamarin.Android   7.1.0.41 (9578cdc)
Xamarin.iOS   10.4.0.123 (35d1ccd)
Xamarin.Forms 2.3.3.193_

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
