### ISSUE TITLE
[Question] Is there any event to be fired when user scrolled?

### ISSUE THREAD

**Issue by bastianbecker21** [alexrainman/CarouselView#390]
I tried Scrolled and PositionSelected but they are fired when changing position programatically too. I need to know whether user manually scrolled or not.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
