### ISSUE TITLE
Setting ShowArrows to false is not retained once position changes

### ISSUE THREAD

**Issue by discgolfjoe** [alexrainman/CarouselView#392]
I'm creating a settings page on my app where the user can enable/disable the navigation arrows. This settings page, like many other pages of the app, has been created as an item on the carouselview control.

When the user modifies ShowArrows from false to true, everything looks good. When the user modifies ShowArrows from true to false, the arrows are removed from the settings (current) selection, but if the user swipes to change position, they return.

Initially, I thought this was a problem with the way I was using binding, but I removed the binding and tried manually setting the ShowArrows property from a PropertyChanged event handler. It seems like the problem is coming from the carouselview control.

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
