### ISSUE TITLE
master detail issue 

### ISSUE THREAD

**Issue by kamuran93** [alexrainman/CarouselView#394]
@alexrainman hi Alex,  ı had an issue to day with master detail page on android . when ı start to  android emulator my CV  in detail page does not show pictures. Can u give me some advices please

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks
