### ISSUE TITLE
Carousel doesn't load views on PushModalAsync

### ISSUE THREAD

**Issue by Jagbri** [alexrainman/CarouselView#396]
I'm trying to navigate to page with carousel on main page load, but carousel doesn't load views properly.
I have created an example project: [https://github.com/Jagbri/CarouselViewTest](url)

MainPage code:
```
 public MainPage()
{
    InitializeComponent();
    ShowPage();
}

private async void ShowPage()
{
    //Doesn't load views in Carousel
    await Navigation.PushModalAsync(new CarouselPage());

    //Works with other pages
    //await Navigation.PushModalAsync(new Page1());
}
```

**Comment by alexrainman** [comment]
This control has been merged into Xamarin.Forms master branch. Please, wait for it to be released as part of Xamarin.Forms and submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview. Thanks

**Comment by Nico04** [comment]
Still not included in X.F 3.0 ?
Do you have a approx roadmap please ?
Thanks !

**Comment by alexrainman** [comment]
You have to ask Xamarin about that :)

**Comment by Nico04** [comment]
Do you have an idea where can I ask ?

**Comment by dhindrik** [comment]
It seems to be a bit of work left before it will go in to master, https://github.com/xamarin/Xamarin.Forms/pull/1882
