### ISSUE TITLE
[Android] Page doesn't adjust itself when keyboard opens.

### ISSUE THREAD

**Issue by masiri201** [alexrainman/CarouselView#398]
Hi, i have a carouselview on a page and the items of that carousel are the contents of 2 content pages, on one of then i have to type something, but when the keyboard opens the page doesnt have the scrollview activated like it should. The carousel page indicators go up and respect the keyboard spacing but the page doesn't. 
I tried ran the page and it works fine but when inside the carousel its not succefull.
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="CalcXamarin.CarouselMyAccount.MyAccountEditar"
             xmlns:Controls="clr-namespace:CalcXamarin.Controls"
             xmlns:cImage="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions" BackgroundColor="Transparent">
    <ContentPage.Content>
                <StackLayout x:Name="StackContainer" Padding="10,3,10,10">
            <ScrollView Orientation="Vertical" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                <StackLayout>
                    <Label Style="{StaticResource LabelTitle}" Text="{Binding EditAccount}" Margin="0,0,0,10" HorizontalOptions="CenterAndExpand"/>
                    <cImage:CircleImage x:Name="ProfilePic" HorizontalOptions="CenterAndExpand" Margin="0,0,0,10" Source="icon.png" WidthRequest="100" HeightRequest="100" />

                    <StackLayout Padding="10,0,10,10">
                        <Label Text="{Binding lblUser}" Style="{StaticResource LabelConfig}"  />
                        <Entry Text=" teste" FontSize="16" TextColor="Black" BackgroundColor="{StaticResource EditarBackColor}" FontAttributes="Bold" VerticalOptions="Start" WidthRequest="150" Focused="entry_Focused" Unfocused="entry_Unfocused" />
                    </StackLayout>
                    <StackLayout Padding="10,0,10,10">
                        <Label Text="{Binding lblPass}" Style="{StaticResource LabelConfig}" />
                        <Entry Text=" teste" FontSize="16" TextColor="Black" BackgroundColor="{StaticResource EditarBackColor}" FontAttributes="Bold" VerticalOptions="Start" WidthRequest="150" Focused="entry_Focused" Unfocused="entry_Unfocused" />
                    </StackLayout>
                    <StackLayout Padding="10,0,10,10">
                        <Label Text="Email:" Style="{StaticResource LabelConfig}" />
                        <Entry Text=" teste@gmail.com" FontSize="16" TextColor="Black" BackgroundColor="{StaticResource EditarBackColor}" FontAttributes="Bold" VerticalOptions="Start" WidthRequest="150" Focused="entry_Focused" Unfocused="entry_Unfocused" />
                    </StackLayout>
                    <Button Text="{Binding SaveChangesButton}" Style="{StaticResource buttonStyleOrange}" Clicked="Button_Clicked" />
                </StackLayout>
            </ScrollView>
                </StackLayout>
    </ContentPage.Content>
</ContentPage>`

Other pages i have that take input react normally to the keyboard and do what their supossed to. 
If somebody knows the solution for this problem please help.
I know this control is going to be added to Xamarin forms but it's taking a while and if this isn't too hard or time consuming to solve this please help me! Thanks.

**Comment by AndreiMisiukevich** [comment]
hi, try this plugin instead https://github.com/AndreiMisiukevich/CardView

Because, this plugin was merged to XF..

**Comment by alexrainman** [comment]
@masiri201 is this Android or iOS?

**Comment by alexrainman** [comment]
@masiri201 with the latest code the carousel will resize as expected when keyboard shows but, you will have to add this line after LoadApplication in your MainActivity:

```cs
Xamarin.Forms.Application.Current.On<Xamarin.Forms.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);
```
