### ISSUE TITLE
Carousel Control within a Page

### ISSUE THREAD

**Issue by AlchemySolutionsPvtLtd** [alexrainman/CarouselView#4]
@alexrainman 

Hi,
We have a requirement where we need to show images in a carousel view. that is, we don't want the entire page to slide in the carousel but only the individual image controls. Is it possible using the Xamarin CarouselView? Because, this is then same as the Carousel Page provided by the Xamarin forms..

**Comment by alexrainman** [comment]
This is not like Xamarin CarouselPage. With this control you can have sticky nav bar and a footer and only swipe your images. I advice you to use FFImageLoading in Android if you are going to use the control with images.

**Comment by alexrainman** [comment]
Take a look at the demo. This control uses views and not pages :)

**Comment by AlchemySolutionsPvtLtd** [comment]
I think I didn't make myself clear.
We are using the Carousel View control as a control within a page with a top header and navigation buttons below, but what we require is something as shown in the link below :
[Carousel Example](http://coolcarousels.frebsite.nl/c/51/) 

Is that possible with the carousel control?

**Comment by alexrainman** [comment]
Nope. But what you want can be done with plain XAML, gestures and animations.

**Comment by alexrainman** [comment]
RelativeLayout or AbsoluteLayout plus MR.Gestures for left/right swipe. Bindable property for ItemsSource. For example, of you swipe left, change center image constrains and move it to the left with an animation, change right image constrains and move it to center with an animation, remove left image. Use some logic to get images sources from List.

**Comment by AlchemySolutionsPvtLtd** [comment]
alright thanks :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
