### ISSUE TITLE
SetCurrentPage doesn't work for "0" 

### ISSUE THREAD

**Issue by declandowling** [alexrainman/CarouselView#40]
Hello,

I am raising an event which is resetting the ItemSource of the CarouselView, each time I want to reset the CurrentPage to the first available (position 0), but I don't seem to be able to. An example of what I am doing is below. 

I am not able to set the current page to 0 each time the item source changes, but I can set the current page to 1, which makes me think that this is a bug.

```
CarouselView.PageIndicators = false;

var data = (IList<MyObject>) sender;
CarouselView.ItemsSource = (IList) data;

CarouselView.PageIndicators = true;

if (CarouselView.ItemsSource.Count > 0)
{
        // can set to 1, but not to 0
        CarouselView.SetCurrentPage(0);
}
```

Thanks.

p.s. Nice library, it's been much easier to use than Xamarin's own CarouselView.

**Comment by alexrainman** [comment]
Hi, can you tell me which platform? Thanks

**Comment by alexrainman** [comment]
Can you try adding this line before calling SetCurrentPage(0);?

```
await Task.Delay(100);
```

**Comment by declandowling** [comment]
Hi Alex. Sorry, it was on Android. I didn't get a chance to test on iOS yet. I'll try the await now and let you know how I get on.

**Comment by alexrainman** [comment]
Android ViewPager is a tricky piece of code. It took me a while to figure it out how to make it work this way.

**Comment by declandowling** [comment]
adding the `await Task.Delay(100);` before `SetCurrentPage(0)` didn't work.

I should mention that the items are in the right order, but its the PageIndicators that don't work properly, as in if I reset the item source, the page indicator will not reset and will stay on whatever it was before the reset. 

Setting it to `CarouselView.SetCurrentPage(CarouselView.ItemsSource.Count -1);` works as you'd expect, setting the indicator to the end, but I just can't get the indicator to work setting it at the start.

**Comment by declandowling** [comment]
adding the `await Task.Delay(100);` before `SetCurrentPage(0)` didn't work.

I should mention that the items are in the right order, but its the PageIndicators that don't work properly, as in if I reset the item source, the page indicator will not reset and will stay on whatever it was before the reset. 

Setting it to `CarouselView.SetCurrentPage(CarouselView.ItemsSource.Count -1);` works as you'd expect, setting the indicator to the end, but I just can't get the indicator to work setting it at the start.

**Comment by alexrainman** [comment]
Oh, its the indicator. Can you test iOS?

**Comment by alexrainman** [comment]
Actually, it works for me.

**Comment by alexrainman** [comment]
i can reset ItemsSource and then SetCurrentPage to 0 and it works. Indicators refresh.

**Comment by alexrainman** [comment]
I am releasing a new version that should fix this if its happening.

**Comment by declandowling** [comment]
Hi Alex,

I upgraded to Version 2.5.2 just now, and my code crashes (object reference not set to an instance of an object) on this line `CarouselView.ItemsSource = (IList) data;` from the example above. I downgraded back to 2.5.1 and that line works. [Here is a screenshot](https://i.imgur.com/aluWvrM.png) with the call stack, but it may not be of use.

**Comment by alexrainman** [comment]
One small advice, first check if the new source Count > before changing ItemsSource. So, you hide the Carousel if Count == 0 and change ItemsSource if Count > 0.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
