### ISSUE TITLE
Unable to access child elements [Question]

### ISSUE THREAD

**Issue by vikram-ma** [alexrainman/CarouselView#400]
In my project I have used ListView object as the ItemTemplate. I want to be able to access the ListView, so that I can programmatically control scroll of this ListView, however the LogicalChildren is empty and ChildAdded or ChildRemoved events are not being called either. 
I want to be able to do something like CarouselViewControl.CurrentChild.Children[0].ScrollToTop()
Here CurrentChild[0] will be the current ListView being shown.

I want use this feature to allow user to scroll back to the top when user has scrolled down the ListView.

Here is the structure of the CarouselView I am using,

```
<CarouselViewControl ItemSource="{Binding Something}">
    <CarouselViewControl.ItemTemplate>
        <DataTemplate>
            <Grid>
                <ListView ItemSource="{Binding Collection}">
                </ListView>
            </Grid>
        </DataTemplate>
    </CarouselViewControl.ItemTemplate>
</CarouselViewControl>
```

**Comment by AndreiMisiukevich** [comment]
@bart-256 hi, try this plugin instead https://github.com/AndreiMisiukevich/CardView

**Comment by alexrainman** [comment]
@vikram-ma there's not Children implementation on CarouselView and it is not possible as XF Views are converted to native views before they are added to the platform specific control the CarouselView is build on top.

But, this is possible if you access directly to the ItemsSource:

```
((ListView)carousel.ItemsSource[0]).ScrollToTop();
```
