### ISSUE TITLE
Control Property to disable dispose of view inside the DestroyItem

### ISSUE THREAD

**Issue by ChasakisD** [alexrainman/CarouselView#401]
I am currently using the CarouselViewControl to make something like a Wizard and a step by step view. I spawn DataGrids and other controls that with view.Dispose() are buggy when the user go back to them(At the first spawn it works fine). I tried just to comment the view.Dispose() at the CarouselViewImplementation.cs, Line: 733. Is there any way to create a bindable property of the CarouselViewControl that will be named e.g. DisposeItems and by default will be true, and on DestroyItem check: ```if(Element.DisposeItems) view.Dispose();```

I can make a fork, make this property and PR it back, but i would like to ask first.

**Comment by marceloh568** [comment]
Hello Friend. I'm going through the same problem. Were you able to solve it? I'm interested in the fork.

**Comment by AndreiMisiukevich** [comment]
hi, try this plugin instead https://github.com/AndreiMisiukevich/CardView

Because, this plugin was merged to XF..

**Comment by alexrainman** [comment]
@ChasakisD where you able to solve this issue?

**Comment by ChasakisD** [comment]
Yes I solved the issue by just comment the ```view.Dispose()``` inside the PagerAdapter's ```DestroyItem```. Actually the performance of ```PagerAdapter``` is very poor, is there any particular reason for choosing PagerAdapter rather than ```FragmentPagerAdapter``` or ```FragmentStatePagerAdapter```? I can work on it.

**Comment by alexrainman** [comment]
If i remember well, i couldn't make it work with Fragments.

**Comment by alexrainman** [comment]
The thing is that the renderer needs to return a native Android View

```cs
ViewRenderer<TView, TNativeView>
```

Fragments don't inherit from Android.Views.View.

**Comment by alexrainman** [comment]
I tried to implement SaveState without luck. Also tried to keep a local copy of Views in Android as i do in iOS to avoid memory leaks but, they are collected and i get a blank page.

**Comment by ChasakisD** [comment]
To properly use the ```FragmentPagerAdapter``` you render the ```Xamarin.Forms.View``` like you do, and then u create a ```FragmentContainer``` to host the rendered View. Then you add this ```FragmentContainer``` to the Adapter. This change does not affect the Renderer, while the ```ViewPager``` still remains a ```Android.Views.View```. There are some tricks to save the state of the Fragment with the ```FragmentStatePagerAdapter```. I can work on a branch if you would like to.

**Comment by alexrainman** [comment]
You are right about the renderer, my bad. You can work on a branch if that will help you.

**Comment by alexrainman** [comment]
I think i can make it work really easy with FragmentPagerAdapter.

**Comment by alexrainman** [comment]
Android.Support.V4.App.FragmentManager is not exposed in any way inside a ViewRenderer.

**Comment by ChasakisD** [comment]
Its exposed to AppCompatActivity, so on the init method just add a parameter so the user will pass its MainActivity reference. Then take the SupportFragmentManager from that one.

**Comment by alexrainman** [comment]
Meaning the user will need to use AppCompatActivity to be able to use my control and i don't want that.

Have you noticed that now ViewRenderer requires a constructor that receives Context?

```cs
public CarouselViewRenderer(Context context) : base(context)
{
    _context = context;
}
```

**Comment by ChasakisD** [comment]
Yeah, but the FragmentManager is exposed on the Activity level, no Context. In order to correctly use the FragmentPagerAdapter you need a FragmentManager which is in the Activity. There may be a trick to get the ChildFragmentManager which is  to the FragmentLevel but i don't think if it is gonna work. I think the trade off of using the FragmentPagerAdapter while requiring an extra parameter of user it is worth. At least for me. Maybe, for backwards compatibility, if the user passes the parameter then use the new adapter and if not, use the old one.

**Comment by alexrainman** [comment]
I know and actually that Context is of type AppCompatActivity :) it works with Fragments.

**Comment by ChasakisD** [comment]
Oh my bad then :(. Glad to hear that it works!

**Comment by alexrainman** [comment]
I will need to run a full round of tests as my carousel is dynamic so you can add/remove/move/insert and i don't know that will behave with FragmentPageAdapter.

**Comment by ChasakisD** [comment]
With FragmentStatePagerAdapter i think the only issue were not the dynamic itemssource changes, but the state saving on device rotation. I can share my version of the adapter if needed. :)

**Comment by alexrainman** [comment]
All the weird issues i faced while i was implementing a dynamic ViewPager are back if i switch to a FragmentPageAdapter.

**Comment by ChasakisD** [comment]
Please push your changes to a new branch, so I can work on

**Comment by alexrainman** [comment]
Sorry, i cannot focus on this now.

This is my version of the Fragment adapter:

```cs
class PageAdapter : FragmentPagerAdapter
{
    CarouselViewControl Element;

    // A local copy of ItemsSource so we can use CollectionChanged events
    public List<object> Source;

    public override int Count
    {
        get
        {
            return Source?.Count ?? 0;
        }
    }

    public PageAdapter(FragmentManager fm, CarouselViewControl element) : base(fm)
    {
        Element = element;
        Source = Element.ItemsSource != null ? new List<object>(Element.ItemsSource.GetList()) : null;
    }

    public override global::Android.Support.V4.App.Fragment GetItem(int position)
    {
        View formsView = null;

        object bindingContext = null;

        if (Source != null && Source?.Count > 0)
            bindingContext = Source.Cast<object>().ElementAt(position);

        var view = bindingContext as View;

        // Support for List<DataTemplate> as ItemsSource
        var dt = bindingContext as DataTemplate;
        if (dt != null)
        {
            formsView = (View)dt.CreateContent();
        }
        else
        {
            if (view != null)
            {
                formsView = view;
            }
            else
            {
                var selector = Element.ItemTemplate as DataTemplateSelector;
                if (selector != null)
                    formsView = (View)selector.SelectTemplate(bindingContext, Element).CreateContent();
                else
                {
                    // So ItemsSource can be ViewModels
                    if (Element.ItemTemplate != null)
                    {
                        formsView = (View)Element.ItemTemplate.CreateContent();
                    }
                    else
                    {
                        formsView = new Label()
                        {
                            Text = "Please provide an ItemTemplate or a DataTemplateSelector"
                        };
                    }
                }

                formsView.BindingContext = bindingContext;
            }
        }

        // HeightRequest fix
        formsView.Parent = this.Element;

        var nativeConverted = formsView.ToAndroid(new Rectangle(0, 0, Element.Width, Element.Height));
        nativeConverted.Tag = new Tag() { BindingContext = bindingContext }; //position;

        var fragment = new ViewContainer(nativeConverted);

        return fragment;
    }

    public override void DestroyItem(AndroidViews.ViewGroup container, int position, Java.Lang.Object @object)
    {
        var manager = ((ViewContainer)@object).FragmentManager;
        var trans = manager.BeginTransaction();
        trans.Remove((ViewContainer)@object);
        trans.Commit();
    }

    public override int GetItemPosition(Java.Lang.Object @object)
    {
        var tag = (Tag)((ViewContainer)@object).NativeView.Tag;
        var position = Source.IndexOf(tag.BindingContext);
        return position != -1 ? position : PositionNone;
    }
}
```

Not sure about DestroyItem.

This is a method to get support fragment manager if MainActivity is ```global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity```:

```cs
private FragmentManager GetManager()
{
    var activity = _context as AppCompatActivity;
    return activity.SupportFragmentManager;
}
```

Good luck!
