### ISSUE TITLE
Implement plugin can loop a view when last child

### ISSUE THREAD

**Issue by nhdanh** [alexrainman/CarouselView#402]
Hi All. Im using this plugin. It is so good. But I has a problem. When I swipe to last child. I cant continue swipe. So I want make this plugin can swipe to first child. Loop item in carousle. 

In react has a plugin can make it. So How can I implement this plugin can do it and autoplay as slide. 

This is a slide in lazada app. I think it using React. In Xamarin, how can I do it ?
Gif
[https://j.gifs.com/G5VWv3.gif](url)

video on youtube: https://www.youtube.com/watch?v=qdqlSVvyMpo

![g5vwv3](https://user-images.githubusercontent.com/32826936/40290394-068e3d9a-5ce8-11e8-9b05-8348485eedb0.gif)

**Comment by AndreiMisiukevich** [comment]
@nhdanh  hi, try this plugin instead https://github.com/AndreiMisiukevich/CardView (it provides such feature, just set IsCycling = true)

Because, this plugin was merged to XF..

**Comment by nhdanh** [comment]
thank you, I was custom this plugin can do it. So I see your card views plugin. That good plugin. I downloaded.

**Comment by alexrainman** [comment]
@nhdanh next release.
