### ISSUE TITLE
Auto scroll property and scroll to first page when scrolled from the last page

### ISSUE THREAD

**Issue by hashimks** [alexrainman/CarouselView#405]
Hi, I am using this plugin and to say this is the best of all. However, I found couple of features which will be good in this.

1. Auto scroll on a particular time set
2. scroll to first page when scrolled from the last page (manually/auto)

**Comment by AndreiMisiukevich** [comment]
@hashimks hi, try this plugin instead https://github.com/AndreiMisiukevich/CardView (It provides such features)

Because, this plugin was merged to XF..

**Comment by alexrainman** [comment]
@hashimks next release.
