### ISSUE TITLE
[iOS] CarouselViewControl images are appearing zoomed.

### ISSUE THREAD

**Issue by ghost** [alexrainman/CarouselView#407]
Please go through the screenshot attached below :
Images inside carousel view appears zoomed in iOS on all versions of OS 9.3,10.2,11.3 while it works fine on Android.

![simulator screen shot - iphone se - 2018-05-24 at 17 07 12](https://user-images.githubusercontent.com/9973688/40483317-3274424e-5f75-11e8-9c36-a77cf46b63ed.png)

**Comment by AndreiMisiukevich** [comment]
@Puneetk207 hi
try this plugin instead https://github.com/AndreiMisiukevich/CardView

**Comment by alexrainman** [comment]
@ghost can you share a demo?

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks
