### ISSUE TITLE
Problem with ListView inside CarouselView

### ISSUE THREAD

**Issue by ivanxamarin** [alexrainman/CarouselView#408]
When I try to use a ListView in one of the views from Carousel view array, I get following error:

Value cannot be null.
Parameter name: fieldType	

`

<controls:CarouselViewControl VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">

                <controls:CarouselViewControl.ItemsSource>
                    <x:Array Type="{x:Type View}">
                        <RelativeLayout>
                            <Image Source="pi.png"/>
                            </RelativeLayout>
                        <RelativeLayout>
                            <ListView>
                                <ListView.ItemTemplate>
                                    <DataTemplate>
                                        <Label>
                                        </Label>
                                    </DataTemplate>
                                </ListView.ItemTemplate>
                            </ListView>
                        </RelativeLayout>
                        <RelativeLayout>
                            <Label Text="this is 3"/>
                        </RelativeLayout>
                    </x:Array>
                </controls:CarouselViewControl.ItemsSource>
            </controls:CarouselViewControl>
`

and it fails to compile if anything is under this DataTemplate, otherwise not.

**Comment by AndreiMisiukevich** [comment]
@ivanxamarin hi
try this plugin https://github.com/AndreiMisiukevich/CardView

**Comment by ivanxamarin** [comment]
Thanks, tried it already and got the exact same exception. I managed to find a workaround by using DataTemplateSelector, creating three templates and setting collection of three numbers as ItemsSource. Although it's not so elegant since I have to use ViewModel in page binding context and also as static resource in templates, but it's working. I can see that this control is going to part of Xamarin.Forms.Core and I hope we will be able to use it as I had been intended to.

**Comment by AndreiMisiukevich** [comment]
@ivanxamarin how long ago did you try it?

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:viewModels="clr-namespace:PanCardViewSample.ViewModels"
    xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"
    xmlns:controls="clr-namespace:PanCardView.Controls;assembly=PanCardView"
    xmlns:ffimage="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    x:Class="PanCardViewSample.Views.CarouselSampleXamlView"
    BackgroundColor="Black"
    Title="Carousel Xaml">

    <ContentPage.BindingContext>
        <viewModels:CardsSampleViewModel/>
    </ContentPage.BindingContext>

    <cards:CarouselView 
        CurrentIndex="{Binding CurrentIndex}">

        <cards:CarouselView.Items>
            <x:Array Type="{x:Type View}">
                     <ContentView>
                    <Frame 
                        VerticalOptions="Center"
                        HorizontalOptions="Center"
                        HeightRequest="300"
                        WidthRequest="300"
                        Padding="0" 
                        HasShadow="false"
                        IsClippedToBounds="true"
                        CornerRadius="10">

                        
                    </Frame>
                </ContentView>
                 <ContentView>
                    <Frame 
                        VerticalOptions="Center"
                        HorizontalOptions="Center"
                        HeightRequest="300"
                        WidthRequest="300"
                        Padding="0" 
                        HasShadow="false"
                        IsClippedToBounds="true"
                        CornerRadius="10">
                        
                    </Frame>
                </ContentView>
                </x:Array>
        </cards:CarouselView.Items>


        <controls:IndicatorsControl/>
    </cards:CarouselView>
    
</ContentPage>
```

Here is my markup with  https://github.com/AndreiMisiukevich/CardView and it works perfectly (tested on iOS)
I propose you to try it again. And if you have errors, you can create in on my repo)

**Comment by ivanxamarin** [comment]
That would work for me to, something like that did actually, but with this as part of the Array:
`<RelativeLayout>
                        <ListView>
                            <ListView.ItemTemplate>
                                <DataTemplate>
                                    <Label>
                                    </Label>
                                </DataTemplate>
                            </ListView.ItemTemplate>
                        </ListView>
                    </RelativeLayout>`

it doesn't. If there is nothing under DataTemplate it compiles, otherwise not.

**Comment by AndreiMisiukevich** [comment]
@ivanxamarin yes, sorry, you are right.
Did you try to put List's dataTemplate to local resource dictionary?

**Comment by ivanxamarin** [comment]
Thanks, that's a good suggestion, I'll give it a try tonight.

**Comment by ivanxamarin** [comment]
I tried it with ListView DataTemplate in resource, but I don't think it can be done. What's happening is that when the ListView is under Array, static resources are not available. I'm pretty sure I didn't miss anything since template from resource works in ListView when not in Array.

This is my resource dictionary:
`<ContentPage.Resources>
        <ResourceDictionary>
            <DataTemplate x:Key="myCellTemplate2">
                <ViewCell>
                    <Label Text="{Binding Name}">
                    </Label>
                </ViewCell>
            </DataTemplate>
        </ResourceDictionary>
    </ContentPage.Resources>`

and this is Array:

`<x:Array Type="{x:Type View}">
                        <RelativeLayout>
                            <Image Source="pi.png"/>
                        </RelativeLayout>
                        <RelativeLayout>
                            <ListView x:Name="list" ItemTemplate="{StaticResource myCellTemplate2}">
                                <ListView.ItemsSource>
                                    <x:Array Type="{x:Type formstest:Person}">
                                        <formstest:Person Name="Steve1" Age="21" Location="USA" />
                                        <formstest:Person Name="Steve2" Age="21" Location="USA" />
                                        <formstest:Person Name="Steve3" Age="21" Location="USA" />
                                    </x:Array>
                                </ListView.ItemsSource>
                            </ListView>
                        </RelativeLayout>
                        <RelativeLayout>
                            <Label Text="this is 3"/>
                        </RelativeLayout>
                    </x:Array>`

When I start it this way I get a runtime exception that static resource is not found and if I take ListView out of Array, just anywhere on content page everything is fine.

**Comment by AndreiMisiukevich** [comment]
Okay, just create some markup in code)

**Comment by ivanxamarin** [comment]
This is the best I could. I'm not sure what's wrong.

**Comment by ivanxamarin** [comment]
@alexrainman 
Is this going to be possible any time soon? Using DataTemplateSelector is pretty much unnatural way for workaround and can get developer in a real mess.

**Comment by alexrainman** [comment]
@ivanxamarin actually DataTemplateSelector is not unnatural at all. It is supported by other Xamarin Forms controls, including ListView.

**Comment by alexrainman** [comment]
I was able to reproduce this but i cannot find the reason why this is happening.

**Comment by ivanxamarin** [comment]
> 
> 
> I was able to reproduce this but i cannot find the reason why this is happening.

Yes, it happens the same way on alternatives I tried. Could be some Xamarin problem.

Thanks a lot for this, it's a good workaround. I'll try it as soon as I can.

**Comment by JoeDurand3** [comment]
I was able to fix my particular issue by setting the item source to null, raising the property changed event, and then setting with the intented contents:

```
Schedule = null;
RaisePropertyChangedEvent("Schedule");
Schedule = newSchedule;
RaisePropertyChangedEvent("Schedule");
```

**Comment by ish-1313** [comment]
hit the same. 
assigned arrays of contenview in xaml
```
                <carouselview:CarouselViewControl.ItemsSource>
                    <x:Array Type="{x:Type ContentView}" x:Name="arrOfView">
                        <ContentView>
                            <Grid  x:Name="gridGeneral" > 
                             </Grid></ContentView>

                        <ContentView>
                            <Grid  x:Name="gridNutrients">
                            </Grid>
                           </ContentView>

                        <ContentView>
                            <ListView  x:Name="listCategories" ItemsSource="{Binding CurrentProduct.Categories.CatList}" >
                            </ListView>
                        </ContentView> 
                    </x:Array>
```

created itemtemplate for listview in page resourcedictionary
```
    <ContentPage.Resources>
        <ResourceDictionary>
            <DataTemplate x:Key="tmplCategories">
                    <ViewCell>
                        <Grid HorizontalOptions="Fill"  >
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <Label Text="{Binding name}" VerticalOptions="Center" />
                            <Entry Grid.Column="1" Text="{Binding weight}" Keyboard="Numeric" />
                        </Grid>
                    </ViewCell>
                </DataTemplate>
        </ResourceDictionary>
    </ContentPage.Resources>
```
init pageproperties in page constructor
```
          ContentView[] c = new ContentView[3];
            int i = 0;
            foreach (ContentView cv in cvMain.ItemsSource) c[i++] = cv;
            gridGeneral = (Grid)c[0].Content;
            gridNutrients = (Grid)c[1].Content;
            listCategories = (ListView)c[2].Content;
```
then assign template from xaml
`listCategories.ItemTemplate = Resources["tmplCategories"] as DataTemplate;`

**Comment by Quax82** [comment]
Do you still work on this? This is a really annoying bug. Any chance that this could be solved?
