### ISSUE TITLE
[iOS] The first page is blank with array of ScrollViews

### ISSUE THREAD

**Issue by azimuthdeveloper** [alexrainman/CarouselView#410]
When used on iOS, with an array of ScrollView's, the first page is always blank.  I have initialised scrollview on the iOS platform and the issue still persists.

**Comment by alexrainman** [comment]
Trying to reproduce this.

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks
