### ISSUE TITLE
LoadMoreEvent

### ISSUE THREAD

**Issue by 4gDad** [alexrainman/CarouselView#411]
I am build an app using the CarouselView the I will am displaying current items to the user but they will have the ability to "LoadMore" to see items that have been displayed in the past.  Does your control have this ability or is there plans to allow for this "Chunking \paging " of data.

**Comment by AndreiMisiukevich** [comment]
Hi @4gDad 
You can try this plugin https://github.com/AndreiMisiukevich/CardView
If you want to load more items, just add them to your observableCollection

**Comment by alexrainman** [comment]
I am going to release small update to support XF 3.x.x and maybe more.

**Comment by alexrainman** [comment]
@4gDad next release
