### ISSUE TITLE
DisplayAlert doesn't work in Main UI thread after launching on android

### ISSUE THREAD

**Issue by wonsuyon** [alexrainman/CarouselView#412]
Great thanks to your work.
i got some problem.
works fine on ios
but on android MainPage OnAppearing
DisplayAlert doesn't work in Main UI thread
so i code

        protected override async void OnAppearing()
        {
            base.OnAppearing();

            if (IsFirstTime && Device.RuntimePlatform == Device.Android)
            {
                await Task.Delay(500);
            }

            await DisplayAlert(....);
        }

now it's fine.
The threshold millisecondsDelay is about 100? on a geekbench multi 1000 score device.

Of course i coded

            global::Xamarin.Forms.Forms.Init(this, bundle);
            CarouselViewRenderer.Init(); // API 15+ (4.0.3)

and

        public App()
        {
                MainPage = new NavigationPage(new MainPage());
        }

thanks a lot

**Comment by AndreiMisiukevich** [comment]
Hi @Cheatmagnet 
you can try this plugin https://github.com/AndreiMisiukevich/CardView
