### ISSUE TITLE
UI error upon position change

### ISSUE THREAD

**Issue by TheSayvior** [alexrainman/CarouselView#414]
Hello, 

I have a setup where i use this carousel to display messages in a banner on the top of my screen. The Itemsource can therefore vary and messages can be deleted. The issue is that if I create a NotificationList of e.g. size 3 with three messages in it everything displays correctly. If I then delete one of the three messages changing the item count to 2 i get the following. 

1. message (BannerPosition = 0) displays correctly
![image](https://user-images.githubusercontent.com/12073424/41277655-200c207e-6e28-11e8-9114-9c76bdedd955.png)

2. message (BannerPosition = 1) displays incorrectly, dosent animate all the way in.
![image](https://user-images.githubusercontent.com/12073424/41277690-32dc6fb0-6e28-11e8-9574-e5a3e2d75cc5.png)

The odd thing is once the Banner has been swiped a couple of times, then the position of the message corrects itself.

Below is the xaml code:
  <ContentView
                x:Name="NotificationMessageArea"                
                Grid.Column="1">
                <carouselView:CarouselViewControl
                 x:Name="Banner"                        
                 InputTransparent="True"
                 InterPageSpacing="0"
                 ShowIndicators="False"
                 BackgroundColor="Transparent"
                 VerticalOptions="FillAndExpand"
                 HorizontalOptions="FillAndExpand"
                 Position="{Binding BannerPosition}"
                 ItemsSource="{Binding NotificationList}">

                  <carouselView:CarouselViewControl.ItemTemplate>
                    <DataTemplate>
                      <ContentView>
                        <controls:MainPageBannerControl
                          VerticalOptions="End"
                          HorizontalOptions="Start"
                          DisplayMessageTitle="{Binding Title}"
                          DisplayMessageText="{Binding Text}"/>
                      </ContentView>
                    </DataTemplate>
                  </carouselView:CarouselViewControl.ItemTemplate>
                </carouselView:CarouselViewControl>
              </ContentView>

I appoligize if i have missed something obvious.

**Comment by AndreiMisiukevich** [comment]
Hi
try this pack https://github.com/AndreiMisiukevich/CardView

**Comment by TheSayvior** [comment]
I appoligize, it seems to be an Xamarin problem, it was getting confused with my HorizontalOptions on the labels within the control (hadn't defined them) even though i told it to stay at start outside for the grid they where placed in. By specifically assigning the HorizontalOption to start on the labels within the control i can no longer reproduce the error.

**Comment by TheSayvior** [comment]
The Issue has resurfaced, it seems if you create your views from the template using an itemsource and you alter the source at runtime, then the animation between the pages can cause a bug where the screen assigns itselv to a position that it was on during the animation.

E.g. i have a list of 5 pictures and a carousel view presenting them. Then while at position 2 i delete the picture at position 2 in the list. Then the list updates and the carousel dosent handle that scenario correctly with the animation to go back to position 1.

**Comment by alexrainman** [comment]
I cannot reproduce this with my latest code.
