### ISSUE TITLE
CarouselView not showing

### ISSUE THREAD

**Issue by kevinwong15** [alexrainman/CarouselView#415]
Hi, I have a CarouselView in a ContentPage called MainPage. I have a button on a Login page which goes to the MainPage.

The Carouselview will not show when App.Current.MainPage = new MainPage().

Is this normal behaviour? The element does show on App.Current.MainPage = NavigationPage(new MainPage()).

**Comment by AndreiMisiukevich** [comment]
Hi
you can try this package https://github.com/AndreiMisiukevich/CardView

**Comment by ivanxamarin** [comment]
If you're using XF3.0, try reverting to 3.0.0.482510 for example. There might be a bug in some of newest versions of Xamarin Forms.

**Comment by alexrainman** [comment]
I am releasing an update to support XF 3.x.x. It will include some small fixes.
