### ISSUE TITLE
ShowIndicators - Indicators on Top

### ISSUE THREAD

**Issue by LuisDeHaro** [alexrainman/CarouselView#416]
Hi, my question is simple:

Is there a way to put the Indicators in the top of the Page instead of the bottom?

Thanks in advance!

**Comment by AndreiMisiukevich** [comment]
@LuisDeHaro hi
you can get it easily with this package https://github.com/AndreiMisiukevich/CardView
Just put indicatorsControl into your view and set layout)

**Comment by alexrainman** [comment]
@LuisDeHaro next release
