### ISSUE TITLE
CarouselView not appearing in Xamarin android

### ISSUE THREAD

**Issue by gnaree** [alexrainman/CarouselView#417]
I am using CarouselView v5.2.0 with Xamarin forms v3.0.0.561731 and Xamarin android v8.3

The same CarouselView is working fine in Xamarin iOS ,but in android it is not throwing any errors and white blank screen is coming.

**Comment by mclillill** [comment]
We have the same issue. No fix yet.

**Comment by wattsdeveloper** [comment]
We also have the same issue

**Comment by alexrainman** [comment]
Are you calling Init on Android?

**Comment by mclillill** [comment]
@alexrainman 
This is our MainActivity:
```csharp
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		//===========================================================================================
		protected override void OnCreate(
			Bundle oBundle
			)
		{
			TabLayoutResource = Funkinform.NewsApp.Droid.Resource.Layout.Tabbar;
			ToolbarResource = Funkinform.NewsApp.Droid.Resource.Layout.Toolbar;

			//Remove title bar
			RequestWindowFeature(WindowFeatures.NoTitle);
			//Remove notification bar
			Window.SetFlags(WindowManagerFlags.Fullscreen, WindowManagerFlags.Fullscreen);

			base.OnCreate(oBundle);

			CarouselViewRenderer.Init();
...
````

**Comment by wattsdeveloper** [comment]
We are also calling init(), and it was working fine before updating to xamarin forms 3.0....

**Comment by alexrainman** [comment]
Then it is a XF3 issue. Rollback and wait for XF3.x as this control has been merged and it will be released as part of Forms.

**Comment by wattsdeveloper** [comment]
okay, do you have any idea, when it will be merge to master? BTW, if i change the size of the android window, then it will be renderer.

**Comment by ivanxamarin** [comment]
v5.2.0 is working fine on 3.0.0.482510 for me. You can stay on XF3, no need to go to XF2, just revert a few versions back.

**Comment by less0** [comment]
> v5.2.0 is working fine on 3.0.0.482510 for me.

For me it doesn't. Just wanted to downgrade when I saw that I'm already on that very version.

**Comment by ivanxamarin** [comment]
That's strange.  Did you install it in both projects and caled Init() in Android main activity? Or could it be problem with some version of Xamarin.Android.Support.*? I'm still on 27.0.2, didn't upgrade to 27.0.2.1 yet.

**Comment by less0** [comment]
@alexrainman Any news on when this will be merged to the main codebase? 3.1 does not include it as far as I can tell.

**Comment by less0** [comment]
*Update:* I've stripped my example to the bare minimum (Just a `ContentPage` with a `CarouselView` showing pages with a single `Label` each) and it works with Xamarin.Forms 3.X (with X>=0). Maybe it has to do with 3.X changes, but if at all, the Xamarin.Forms version is not a sufficient, but merely a necessary condition.

I will try to bring the example to the point where it stops working and keep you updated. Maybe we can provide a fix for the time being while `CarouselView` is not merged to XF.

**Comment by alexrainman** [comment]
I am releasing an update to support XF 3.x.x. It will include some small fixes.

**Comment by xlbs-rm** [comment]
Bug still exist!
**The Reason is the missing NavigationPage**

On iOS this works fine:
`this.Navigation.PushModalAsync(new PageWithCarouselView(), true);`

On Android the Variable setters are not called:
```
   public class PageWithCarouselView : ContentPage
    {

        public PageWithCarouselView()
        {
            CarouselViewControl carousel = new CarouselViewControl
            {
                 //Code reached/called in iOS not in Android if no Navigation Page
                ItemTemplate = new DataTemplate(() =>
                {
                    Image img = new Image();
                    img.SetBinding(Image.SourceProperty, ".");
                    img.Aspect = Aspect.AspectFit;
                    return img;
                }),
                ItemsSource = images,
                ShowIndicators = true,
                Margin = new Thickness(0, 10),
            };
     [...]
}
```

This works on Android but unfortunately it serves a Navbar 
`this.Navigation.PushModalAsync(new NavigationPage(new PageWithCarouselView()), true);`
