### ISSUE TITLE
[iOS] System.MissingMethodException: Default constructor not found for type System.Array

### ISSUE THREAD

**Issue by brad302** [alexrainman/CarouselView#418]
I'm having an issue and it only occurs on my device, not on the simulator.  My device is iOS 11.4 and is an iPhone 6s.  The simulator is also running 11.4.

The CarouselView version I am running is 5.0.0 ... I tried upgrading to the latest version but apparently there's a compatibility issue with .netstandard 1.4.

It was working fine only days prior and I have confirmed that the CarouselView is the cause of the error.

Any ideas?  I'm more than happy to provide further info where needed.

**Comment by OKameric** [comment]
Check Link behavior option in iOS build window. For me, setting to "Don't Link" fixed the issue. But I didn't have enough time to investigate this further.

**Comment by brad302** [comment]
Thanks, that gets me by but obviously, in release mode doubles the size of the app.  Here's hoping you can find a permanent fix.  Thanks for the heads up anyway.

**Comment by alexrainman** [comment]
I am releasing an update to support XF 3.x.x. It will include some small fixes.
