### ISSUE TITLE
CarouselView inside CarouselView

### ISSUE THREAD

**Issue by SagarPanwala** [alexrainman/CarouselView#42]
How can we use CarouselView inside CarouselView?
I'm able to load it, but the scroll behaviour is not working properly.

**Comment by alexrainman** [comment]
This will work on iOS but not in Android as it goes against Google design guide line: don't put something scrollable inside something that scroll in the same direction. It seems it cannot be handled in the right way. Somehow you have to disable swiping/scrolling in container one.

**Comment by SagarPanwala** [comment]
How can I disable the swiping/scrolling in container one?
I remember that we can create Pager inside page without any problem.

**Comment by alexrainman** [comment]
There's a tutorial in the repo on how to render one page at a time. You can apply that to the outside carouselview.

**Comment by alexrainman** [comment]
This is possible out of the box but the inside carousel needs to be vertical to make it work in the right way: https://github.com/alexrainman/NestedCarouselView

**Comment by alexrainman** [comment]
It works (bot 100%) with both being horizontal if you provide some area for the touch event in the outside carousel wrapping the inside carousel in StackLayout or ContentView and giving it some padding.

**Comment by SagarPanwala** [comment]
Aahhhh, I see.
Actually, I want to use Outer Carousel for not swiping. I want to use as a container. I have to use CustomTabs which has image and text. Tab should also contains Plus icon between and on click of it I have to animate view from bottom. 
To accomplish this I created Tab with StackLayout and handled all the actions.
But as of now, on click of StackLayout I'm adding/removing view in middleview. So instead of doing this I want to use CarouselView.

**Comment by alexrainman** [comment]
Why you dont use tabpage instead? Inside each tab you can put a carouselview. You will have problems in Android as tabpage has swiping event which can be disabled dough.

**Comment by alexrainman** [comment]
You may use platform specific design guide lines. Android tabs at the top with no icons, iOS tabs at the bottom with icons. There are ways to add badges in both platforms tabs. You can rotate icon in iOS only. Animate a view from bottom is not a problem.

**Comment by SagarPanwala** [comment]
I agree that we have to use design specific. But I must have to use this one. So no other way for me.

**Comment by alexrainman** [comment]
Also its possible to add icons to android tabs :)

**Comment by alexrainman** [comment]
Ok good luck.

**Comment by SagarPanwala** [comment]
Hey man, thanks for help till now,but please suggest the way to do this. View animation also should be like Tray. We have to drag it.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
