### ISSUE TITLE
A lot of warnings after adding CarouselView.FormsPlugin

### ISSUE THREAD

**Issue by wing-ap** [alexrainman/CarouselView#420]
I created a new .net standard Xamarin forms project and after adding CarouselView from nuget and build, 26 warnings shows up.
I have called CarouselViewRenderer.Init(); in MainActivity.cs

My environment:
FormsPlugin 5.2.0
Xamarin.Forms 3.0.0.482510 ( also tried the latest one, still getting the warnings)

Warnings:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping test.Droid.Resource.Animation.design_fab_in. Please check that your Nuget Package versions are compatible. (XA0106) (test.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping test.Droid.Resource.Animation.design_fab_out. Please check that your Nuget Package versions are compatible. (XA0106) (test.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping test.Droid.Resource.Color.abc_tint_switch_thumb. Please check that your Nuget Package versions are compatible. (XA0106) (test.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping test.Droid.Resource.Color.design_textinput_error_color_dark. Please check that your Nuget Package versions are compatible. (XA0106) (test.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping test.Droid.Resource.Color.design_textinput_error_color_light. Please check that your Nuget Package versions are compatible. (XA0106) (test.Android)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping test.Droid.Resource.Layout.abc_action_bar_view_list_nav_layout. Please check that your Nuget Package versions are compatible. (XA0106) (test.Android)

and a lot more similar warnings (26 in total)
thanks

**Comment by AndreiMisiukevich** [comment]
hi
try this https://github.com/AndreiMisiukevich/CardView

**Comment by chiwing4** [comment]
thanks a lot, I will give it a try

**Comment by alexrainman** [comment]
This warnings will disappear when i release the new version that will support XF.3.4.x and latest Android packages.

**Comment by Monikaprime** [comment]
still getting error in XF.3.6. and plugin version 5.2.0
![image](https://user-images.githubusercontent.com/47033567/55457477-a258d000-5607-11e9-8995-e3bad043ef68.png)

please solve this at earliest
