### ISSUE TITLE
Scrolled Event is Ambiguous

### ISSUE THREAD

**Issue by ryanwilliams83** [alexrainman/CarouselView#424]
If a user performs a single drag operation to the left but then changes direction (without lifting their finger) and drags back to the right.

The following events will fire
Scrolled, Left, 1
Scrolled, Left, 2
Scrolled, Left, 3
Scrolled, Right, 2
Scrolled, Right, 1

Assuming the Position property is equal to 1; there is not enough information in the ScrolledEventArgs to determine if the user is looking at slides 0&1 or slides 1&2

Please consider reworking the ScrolledEventArgs to:
provide a percentage offset in the range of -100 to 100 relative to the slide indicated by the Position property; OR
provide the indexes of both slides that are visible during the transition.

**Comment by alexrainman** [comment]
It actually works as you are asking. It tells you the direction of the scrolling and the percent. I can easily make the percent negative while you scroll direction is to the left.
