### ISSUE TITLE
Crash only in Android on Xamarin Forms 3.1.0

### ISSUE THREAD

**Issue by NeilIrvingMacc** [alexrainman/CarouselView#426]
When I setup a CarouselViewControl on Android as stated below I get:

Unhandled Exception:

System.TypeLoadException: Could not resolve type with token 01000060 (from typeref, class/assembly System.Reflection.RuntimeReflectionExtensions, System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) occurred

I can get rid of this problem if I comment out this as well as the control that references it:

<localSelector:CarouselTemplateSelectorNeil x:Key="CarouselTemplateSelector" 
                                                       EvenTemplate="{StaticResource EvenTemplate}" 
                                                       OddTemplate="{StaticResource OddTemplate}"
                                                       ToolsTemplate="{StaticResource ToolsTemplate}"
                                                       OptionsTemplate="{StaticResource OptionsTemplate}"
                                                       WorkTrayModelTemplate="{StaticResource WorkTrayModelTemplate}"/>

The above is then connected to this class:

public class CarouselTemplateSelectorNeil : DataTemplateSelector

Any idea how to fix this?  It works fine on iOs and Windows

**Comment by NeilIrvingMacc** [comment]
Just in case this helps anyone if you skip XAML Compilation on the page containing the CarouselView it then works, question now is what still needs to be fixed?

[assembly: XamlCompilation (XamlCompilationOptions.Skip)]

**Comment by alexrainman** [comment]
@NeilIrvingMacc can you post an example so i can try to reproduce your crash?

**Comment by NeilIrvingMacc** [comment]
I no longer have this code sorry I gave up on this control and used the tab page instead, I may revisit one day if the carousel becomes part of Xamarin Forms itself

**Comment by alexrainman** [comment]
It will not but i am working on a big release with all the bugs fixed and brand new functionality.
