### ISSUE TITLE
[iOS] XamlParseException

### ISSUE THREAD

**Issue by Huaba93** [alexrainman/CarouselView#429]
Hi,
I have a problem with the CarouselView in my iOS project. When I add the CarouselView nuget into my projects, I get a _XamlParseException_ at runtime. 

`Xamarin.Forms.Xaml.XamlParseException: Position 11:13. Type CommonStuff+SomeId not found in xmlns clr-namespace:Our.Common.Stuff;assembly=Our.Common.Stuff`

The problem only occurs on iOS, Android is working fine. I tried Xamarin.Forms 2.5 and 3.1, same behavior. 

It's a shared project (.net standard 2.0). 

**Project structure:**
TL;DR: The iOS project references `Our.Common.Stuff` transitively.

Both platform dependent projects (Android & iOS) depend on `Our.App` (a .net standard 2.0 library which is containing the platform independent stuff). The project `Our.Common.Stuff` is referenced by `Our.App`.

Adding following line into `AppDelegate.FinishedLaunching` right after `global::Xamarin.Forms.Forms.Init();` solved the problem:

`Console.WriteLine(typeof(Our.Common.Stuff.CommonStuff));`

Changes to the behavior of the linker (so if unneeded parts are abolished) have no impact on the issue.

Any idea what's going wrong?

**Comment by alexrainman** [comment]
Where you able to solve this?

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks
