### ISSUE TITLE
CarouselView not displaying on Xamarin Forms Android or iOS

### ISSUE THREAD

**Issue by keshbach1** [alexrainman/CarouselView#434]
Could you check that I'm creating this CarouselView correctly, because try as I might, I cannot get it to display anything, and I am instead greeted by a blank space. I'm starting with what I believe is a barebones example, whose XAML contents I have pasted below.

```<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:CyclePay.UI.Feed"
             x:Class="CyclePay.UI.Feed.FeedView"
             xmlns:telerikPrimitives="clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives"
             xmlns:cv="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions">
  <ContentView.Content>
      <StackLayout BackgroundColor="Transparent" HeightRequest="270" VerticalOptions="FillAndExpand">
            <cv:CarouselViewControl ShowArrows="true" AnimateTransition="true" IsVisible="true" IsSwipeEnabled="true" IsEnabled="true" ShowIndicators="true" x:Name="carousel">
                <cv:CarouselViewControl.ItemsSource>
                       <x:Array Type="{x:Type Label}">
                            <Label Text="Hello" VerticalOptions="CenterAndExpand" FontSize="Large" HorizontalOptions="CenterAndExpand"/>
                            <Label Text="world" VerticalOptions="CenterAndExpand" FontSize="Large" HorizontalOptions="CenterAndExpand"/>
                            <Label Text="!" VerticalOptions="CenterAndExpand" FontSize="Large" HorizontalOptions="CenterAndExpand"/>
                       </x:Array>
                </cv:CarouselViewControl.ItemsSource>
            </cv:CarouselViewControl>
      </StackLayout>
  </ContentView.Content>
</ContentView>

**Comment by vpfrimmer** [comment]
I've been encountering the same kind of issue with the latest Xamarin.Forms updates.
I'm beggining to think this package is no longer compatible and needs to be updated.

Your code seems correct, by the way.

**Comment by ivanxamarin** [comment]
It seems that array of controls as ItemsSource of CarouselView is not working. There are many issues reported and some alternatives to CarouselView are also unable to work that way. You should try DataTemplate and TemplateSelector. Look for some examples of that.

**Comment by AndreiMisiukevich** [comment]
@ivanxamarin  @vpfrimmer hi https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs
you can try this plugin

**Comment by sandlergiovanni** [comment]
Same issue on Xamarin.Forms 3.2.0.839982 version (Android only)

**Comment by alexrainman** [comment]
The issue here is wrapping the carousel with StackLayout which is not needed if the carousel will fill the entire screen. StackLayout needs to know the height of its children to allocate its own height. Carousel doesn't know its height, not until its natively rendered.

Workaround? Use a Grid if you need to wrap the carousel and assign a height to it.
