### ISSUE TITLE
(iOS) Indicators Section Show White in iPhone X

### ISSUE THREAD

**Issue by tayminator** [alexrainman/CarouselView#436]
Hello,

Just starting with the CarouselView but having an issue that I cannot seem to figure out which is that the bottom portion of the screen where the indicators reside shows white in iPhone X.  Is there something I can do to make this area transparent in iPhone X, just as it is with other iPhone models?

Here's what it looks like:
![simulator screen shot - iphone x - 2018-07-24 at 22 30 24](https://user-images.githubusercontent.com/7624798/43176494-f682a76a-8f91-11e8-945e-fb2a7c5d5477.png)

Here's what it looks like in iPhone 8:
![simulator screen shot - iphone 8 - 2018-07-24 at 22 33 06](https://user-images.githubusercontent.com/7624798/43176508-0162852e-8f92-11e8-884b-cfedefc035e2.png)

Here's my code (MainPage2 is a ContentPage):

        public MainPage2()
        {
            InitializeComponent();

            PrepareLayout_Stack();
        }

        void PrepareLayout_Stack()
        {
            Padding = new Thickness(0, 0, 0, 0);
            StackLayout = new StackLayout();
            StackLayout.VerticalOptions = LayoutOptions.FillAndExpand;
            StackLayout.HorizontalOptions = LayoutOptions.FillAndExpand;
            StackLayout.BackgroundColor = Color.Transparent;

            var myCarousel = new CarouselViewControl();
            myCarousel.ItemsSource = new ObservableCollection<string> { "apple", "banana", "orange" };
            myCarousel.ItemTemplate = new DataTemplate(CreateCarouselItemTemplate);
            myCarousel.Orientation = CarouselViewOrientation.Horizontal;
            myCarousel.VerticalOptions = LayoutOptions.FillAndExpand;
            myCarousel.HorizontalOptions = LayoutOptions.FillAndExpand;
            myCarousel.BackgroundColor = Color.Transparent; 
            myCarousel.ShowIndicators = true;

            StackLayout.Children.Add(myCarousel);

            Content = StackLayout;
        }

        View CreateCarouselItemTemplate()
        {
            StackLayout stackLayout = new StackLayout();
            stackLayout.Padding = new Thickness(0);
            stackLayout.HorizontalOptions = LayoutOptions.FillAndExpand;
            stackLayout.VerticalOptions = LayoutOptions.FillAndExpand;
            stackLayout.BackgroundColor = Color.Pink;
            stackLayout.Orientation = StackOrientation.Vertical;

            Label label = new Label();
            label.FontSize = 60;
            label.FontFamily = "Helvetica";
            label.HorizontalOptions = LayoutOptions.CenterAndExpand;
            label.VerticalOptions = LayoutOptions.CenterAndExpand;
            label.SetBinding(Label.TextProperty, ".");

            Label labelFooter = new Label();
            labelFooter.Text = "footer";
            labelFooter.FontSize = 80;
            labelFooter.FontFamily = "Helvetica";
            labelFooter.HorizontalOptions = LayoutOptions.Center;
            labelFooter.VerticalOptions = LayoutOptions.End;

            stackLayout.Children.Add(label);
            stackLayout.Children.Add(labelFooter);
            return stackLayout;
        }

**Comment by JPLarouche** [comment]
Hi ! I have the same issue, were you able to find a solution to this ?? Thanks !

**Comment by alexrainman** [comment]
This is as easy as to set On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true); on the page containing the CarouselView.

**Comment by bondarenkod** [comment]
```
 xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
ios:Page.UseSafeArea="True" 
```
and in the .cs
```
	protected override void OnAppearing()
		{
			base.OnAppearing();

			var safeInsets = On<Xamarin.Forms.PlatformConfiguration.iOS>().SafeAreaInsets();
			safeInsets.Top = 0;
			safeInsets.Bottom = -1; // 0 - zero effect
			this.Padding = safeInsets;
		}
```

Try this one

**Comment by marceloarchiza** [comment]
@bondarenkod
I love you <3

**Comment by FruitAndAShape** [comment]
@bondarenkod I love you too. But what is...

> safeInsets.Bottom = -1; // 0 - zero effect
