### ISSUE TITLE
item onclick

### ISSUE THREAD

**Issue by ManojkumarKaliannan** [alexrainman/CarouselView#438]
how to get item onclick while clicked on image

**Comment by AndreiMisiukevich** [comment]
@ManojkumarKaliannan hi)
Try this plugin instead https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs

Use ItemTapped event or ItemTappedCommand

**Comment by alexrainman** [comment]
Will try this on next release but not sure i will be able to do it.
