### ISSUE TITLE
orientation issue

### ISSUE THREAD

**Issue by ManojkumarKaliannan** [alexrainman/CarouselView#439]
while orientation view get changed

**Comment by shoeIT** [comment]
which error do you have exactly?

**Comment by AndreiMisiukevich** [comment]
@ManojkumarKaliannan try this https://github.com/AndreiMisiukevich/CardView
Can't promise, but perhaps it will help you

**Comment by alexrainman** [comment]
I AM BACK.

Whats the issue?
