### ISSUE TITLE
CarouselView never removing CollectionChanged handler on old ItemsSource

### ISSUE THREAD

**Issue by scastria** [alexrainman/CarouselView#440]
When ItemsSource changes, CarouselView should be removing the CollectionChanged handler on the old value.  for example, if during cleanup of a Page, I set ItemsSource = null, the CarouselView is NOT removing the CollectionChanged handler on the original value of ItemsSource.  this leads to crashes since the handler still gets called, but ItemsSource is null and you get NullPointerException.

In other words, if I do this:

```
_carouselView.ItemsSource = A;
_carouselView.ItemsSource = B;
_carouselView.ItemsSource = C;
_carouselView.ItemsSource = D;
```

then the CarouselView will have listeners to all 4 collections simultaneously since nothing is removing the listener on the old ItemsSource.

**Comment by scastria** [comment]
It took me a while to remember the workflow that caused the crash.  At first I was trying to null out ItemsSource and then REMOVE an item from the ObservableCollection.  But that does NOT cause a crash because you handle removals with your local copy Source variable.  However, if you try to ADD an item to the ObservableCollection, it DOES crash because you handle adds with Element?.ItemSource which is null causing NPE.  Below is sample code that will demonstrate the crash.  Just click the crash button.

IMPORTANT:  One way to fix this issue is to use the local copy Source variable to handle adds like you do with removals.  However, that is NOT the right way to fix this.  The real problem is as I described above.  When the ItemsSource on the CarouselView is changed you MUST remove the Collection listener on the old value.  You NEVER want to be listening to something that you are not supposed to anymore.

    public class CarouselPage : ContentPage
    {
        private ObservableCollection<string> _items = null;
        private CarouselViewControl _carouselV = null;

        public CarouselPage()
        {
            Title = "Carousel";
            ToolbarItem crashTBI = new ToolbarItem {
                Text = "Crash"
            };
            crashTBI.Clicked += HandleCrashClicked;
            ToolbarItems.Add(crashTBI);
            _items = new ObservableCollection<string> {
                "One",
                "Two",
                "Three",
                "Four",
                "Five"
            };
            DataTemplate it = new DataTemplate(typeof(Label));
            it.SetBinding(Label.TextProperty, ".");
            it.SetValue(Label.HorizontalTextAlignmentProperty, TextAlignment.Center);
            it.SetValue(Label.BackgroundColorProperty, Color.Green);
            _carouselV = new CarouselViewControl();
            _carouselV.ItemsSource = _items;
            _carouselV.ItemTemplate = it;
            _carouselV.InterPageSpacing = 10;
            _carouselV.Orientation = CarouselViewOrientation.Horizontal;
            Content = _carouselV;
        }

        private void HandleCrashClicked(object sender, EventArgs e)
        {
            _carouselV.ItemsSource = null;
            _items.Add("Added");
        }
    }

**Comment by alexrainman** [comment]
Question: whats the point on setting ItemsSource to null?

**Comment by scastria** [comment]
This is just a test program to demonstrate the bug. In my real code, I was setting ItemsSource to null when my Page was popped to help GC free up memory. But it doesn’t matter why I set it to null. I should be able to without crash.

**Comment by alexrainman** [comment]
You don't have to set it to null to help GC while a page is popped. Everything will be collected automatically as my implementation of Dispose will be called.

**Comment by alexrainman** [comment]
Setting ItemsSource to null doesn't actually triggers a crash, at least not in my latest code. What triggers a crash is trying to add an item, and as the previous object doesn't exists then you will get a crash. There's nothing that tells me that the ItemsSource is being set as null so i can remove the CollectionChanged handler.

**Comment by alexrainman** [comment]
I found a way to prevent a crash when you try to add an item into a null ItemsSource.

**Comment by scastria** [comment]
How will keeping a local reference to Element.ItemsSource duplicate anything?  The Element.ItemsSource is already going to be keeping a reference to it.  Anytime anybody changes ItemsSource, you can use your local copy to remove the listener and then update your local copy to the new value of Element.ItemsSource.  so your local copy will only ever be pointing to the current Element.ItemsSource (except for the very small time when it was just changed where your local copy is still pointing to the old ItemsSource which allows you to remove the listener and then you immediately update it to point to the new ItemsSource).  Perhaps I am missing something.

Also, I just realized that you closed my PR (https://github.com/alexrainman/CarouselView/pull/441) and said "Merged".  This PR uses this idea of a local reference to remove old listeners.  I am just a beginner at GIT, but I don't see where my PR was merged in your code.  And if you merged it, why are you arguing against this idea?

**Comment by alexrainman** [comment]
I didn't merge. I close it. I already added some changes in iOS that where missing and where included before in Android. No need for another copy of ItemsSource.
