### ISSUE TITLE
(Android) Nested scrolling

### ISSUE THREAD

**Issue by SlyOtis** [alexrainman/CarouselView#444]
I'm having troubles with nested scrolling in the carousel view, I currently have placed an android view overriding  _OnTouch()_  in the carousel view that renderers an amplitude bar with horizontal scroll. This does receive some touch event, but not all, resulting in some scrolling to the amplitude bar and some to the carousel view.

**Comment by alexrainman** [comment]
It maybe the touchable are of the amplitude bar is to thin/small that you end up touching the carousel instead?

**Comment by alexrainman** [comment]
Same as #431
