### ISSUE TITLE
[Enhancement] Android Drag event inside CarouselView

### ISSUE THREAD

**Issue by Phenek** [alexrainman/CarouselView#446]
### Description
There no such DragEvent Feature in the CarouselView.
The issue concern just Android Part, because on iOS I can Drag the Carousel without adding gesture to it.

### Steps to Reproduce

1. Create a AbsolutLayout with a any ContentView inside
2. Add a PanGestureRecognizer on the ContentView, that can move the View or update any Value.
3. Add the CarouselView to the ContentView.
4. Figure it out that CarouselView didn't send any event inside it, 
so it's not possible to add Pan Gesture on Android. works Well on iOS without any code.

### Expected Behavior
The CarouselView could share his Gesture event.

### Actual Behavior
The CarouselView didn't trigger any event, even if I add one to it. 
So maybe ItemsViews Overlap the event, I don't know
```
            var panGesture = new PanGestureRecognizer();
            panGesture.PanUpdated += OnPanUpdated;
            CarouselView.Add(panGesture);
```
### Basic Information
- Xamarin.Forms: 3.1.0.697729

**Comment by AndreiMisiukevich** [comment]
hi @clovs 
try https://github.com/AndreiMisiukevich/CardView (make sure, that you disabled default panInteraction feature by setting IsPanInteractionEnabled to False.

```csharp
carouselView.IsPanInteractionEnabled = false;
``

**Comment by alexrainman** [comment]
What exactly do you mean with DragEvent?

**Comment by Phenek** [comment]
I was meaning Pan Gesture, 
cause my Carousel View is on a Bottom Menu that I can drag from bottom to top.
And the Carousel inside this menu was blocking the drag menu gesture on Android only.

I managed it by adding my PanGesture function to all ItemsViews.
Not by there Parent because DataTemplate don't provide a valid ParentView.
But by starting from Application.Current then then going up to the real Parent View
See the code above:

```
    public partial class CarouselCell : ContentView
    {
        CarouCellViewModel viewModel;

        public CarouselCell()
        {
            InitializeComponent();

            // Hack for Android PanGesture
            if (Device.RuntimePlatform == Device.Android
                &&((App)Application.Current).MainPage is MasterMenuPage master 
                && master.Detail is NavigationPage navPage 
                && navPage.RootPage is CarouselPage CarouselPage)
            {
                var panGesture = new PanGestureRecognizer();
                panGesture.PanUpdated += CarouselPage.OnPanUpdated;
                this.GestureRecognizers.Add(panGesture);
            }
         }
      }
```
