### ISSUE TITLE
Chart (MicroCharts)xamarin on CarouselView

### ISSUE THREAD

**Issue by NickSkrat** [alexrainman/CarouselView#447]
Hi alexrainman, I wanted implement a chart using MicroCharts with CarouselView on Xamarin but the chart doesn't render in IOS and Android. I don´t know if it´s an issue.
P.D: sorry if my english is regular and great nuGet.

This is the code:
XAML

<controls:CarouselViewControl x:Name="CGraficos" VerticalOptions="Start" HeightRequest="200" WidthRequest="400" BindingContext="{Binding Graficos}">
                    <controls:CarouselViewControl.ItemTemplate>
                        <DataTemplate>
                            <Grid>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*"/>
                                </Grid.RowDefinitions>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto"/>
                                </Grid.ColumnDefinitions>
                                <forms:ChartView
                                    Grid.Row="0"
                                    Grid.Column="0"
                                    x:Name="{Binding Nombre}"
                                    HeightRequest="140"
                                    WidthRequest="400"
                                    BackgroundColor="#37414f"/>
                            </Grid>
                        </DataTemplate>
                    </controls:CarouselViewControl.ItemTemplate>
                </controls:CarouselViewControl>

![evidencia](https://user-images.githubusercontent.com/35234988/44819453-50f4e800-abc3-11e8-99e2-01dd5c935717.PNG)

**Comment by NickSkrat** [comment]
thanks so much, i can solve to render the chart 
`<controls:CarouselViewControl x:Name="Charts"
                                              VerticalOptions="Start" 
                                              HeightRequest="200" 
                                              WidthRequest="400" 
                                              ShowIndicators="True"
                                              ShowArrows="True" 
                                              BindingContext="{Binding Graficos}">
                    <controls:CarouselViewControl.ItemsSource>
                        <x:Array Type="{x:Type StackLayout}">
                            <StackLayout>
                                <forms:ChartView
                            HeightRequest="300"
                            x:Name="Chart1"/>
                            </StackLayout>

                            <StackLayout>
                                <forms:ChartView
                            HeightRequest="300"
                            x:Name="Chart2"/>
                            </StackLayout>

                            <StackLayout>
                                <forms:ChartView
                            HeightRequest="300"
                            x:Name="Chart3"/>
                            </StackLayout>
                        </x:Array>
                    </controls:CarouselViewControl.ItemsSource>
                </controls:CarouselViewControl>`

and initialize on the code behind:

`ChartView Chart1= new ChartView();
ChartView Chart2= new ChartView();
ChartView Chart3= new ChartView();`

`Charts.ItemsSource = new List<ChartView>
            {
                Chart1,Chart2,Chart3
            };`

thanks and greeting.

**Comment by shirish8** [comment]
@alexrainman Can you please tell me how can we display the 3rd chart "Chart3" before another while the Carousel View appears on screen??
