### ISSUE TITLE
Get selected position using PositionSelectedCommand on ViewModel

### ISSUE THREAD

**Issue by benazir0** [alexrainman/CarouselView#448]
**1. How can I get the selected position of the observable collection binding PositionSelectedCommand to ViewModel?**

I'm showing a list of dates and I want to change my UI data based on the selected date. This is the code on the ViewModel

`        private ObservableCollection<SomeDate> _dateItems;
        public ObservableCollection<SomeDate> DateItems
        {
            set
            {
                SetProperty(ref _dateItems, value);
            }
            get
            {
                return _dateItems;
            }
        }`

`        private ICommand _selectDateCommand;
        public ICommand SelectDateCommand => _selectDateCommand ?? (_selectDateCommand = new Command<int>(ShowGoalsOfTheDay));`

`        private void ShowDataOfTheDay(int position)
        {
            Debug.WriteLine("Position selected command: " + position);
        }`

This way ShowDataOfTheDay is not called, but if I remove the int parameter from Command and on from the method, it calls the ShowDataOfTheDay, but I cannot get the position.

2. Am I passing the right parameter? If I pass the SomeDate object, it call the method, but the parameter value is always null.

3. Is it possible to get the selected item also?

**Comment by AndreiMisiukevich** [comment]
@benazir0 hi, This project, probably, will be merged to XF.
If you wish, you can try another one https://github.com/AndreiMisiukevich/CardView

SelectedIndex and SelectedItem properties will be help you =)

**Comment by benazir0** [comment]
@AndreiMisiukevich that is an excellent library. My background is white and the indicator is also white. How do I change the indicator color there? Is there any left and right indicator option like this library also?

**Comment by benazir0** [comment]
@AndreiMisiukevich I have managed to change the indicator color style setting

`<controls:IndicatorsControl SelectedIndicatorStyle="{StaticResource customStyle}">`

Is it possible to use value converter to change the resource style like bellow?

`<controls:IndicatorsControl SelectedIndicatorStyle="{Binding Item, Converter={StaticResource itemToStyle}}"/>`

Also please let me know if there is an option to add left and right indicator on the carousel view.

**Comment by AndreiMisiukevich** [comment]
@benazir0 
1) Yes, sure you can use bindings for setting style, once SelectedIndicatorStyle is bindable property
2) Left/Right indicators - do you mean Rigth/Left arrows for navigating through the carousel?
This feature is deferred https://github.com/AndreiMisiukevich/CardView/issues/38
Because, i decided, that nobody need it)
You can easy add arrow to carouselview by yourself (because carouselview is absolutelayout)
Just create views, set them in layout and add ProtectedViewBehavior to behaviors collection of those views.

**Comment by AndreiMisiukevich** [comment]
@benazir0 as Alex is returned, I think, we should create a new issue on my project and speak there.
Could you please create it? I will solve

**Comment by benazir0** [comment]
I have made binding work like this:

    <controls:IndicatorsControl>
        <controls:IndicatorsControl.SelectedIndicatorStyle>
            <Style TargetType="controls:IndicatorsControl">
                <Setter Property="BackgroundColor"  Value="{Binding item, Converter={StaticResource itemToStyle}}" />
                <Setter Property="HeightRequest" Value="25" />
                <Setter Property="HeightRequest" Value="25" />
            </Style>
        </controls:IndicatorsControl.SelectedIndicatorStyle>
    </controls:IndicatorsControl>

**Comment by benazir0** [comment]
@AndreiMisiukevich agreed.
