### ISSUE TITLE
[Android] StackLayout issue on Oreo

### ISSUE THREAD

**Issue by shirish8** [alexrainman/CarouselView#449]
When i have itemsource 2 stacklayouts....it will work fine in all versions except the android oreo...
The two stacklayouts are overlapped and when the orientation is changed its fine..it works properly..
Can you please help ma???

**Comment by AndreiMisiukevich** [comment]
@shirish8 Hi )
https://github.com/AndreiMisiukevich/CardView

Try this plugin (should work properly)

**Comment by shirish8** [comment]
@AndreiMisiukevich  
Thank you for the suggestion...
But its not taking list of stacklayouts as its itemssource...can you help me??

**Comment by shirish8** [comment]
@AndreiMisiukevich  and Its not taking MicroCharts aswell...

**Comment by AndreiMisiukevich** [comment]
@shirish8 
``` xml
<cards:CarouselView.ItemsSource>
            <x:Array Type="{x:Type View}">
                <ContentView>
                    <Image Source="yourImage.png"/>
                </ContentView>
                <RelativeLayout>
                    <Button Text="Click" />
                </RelativeLayout>
                <StackLayout>
                    <Label Text="any text"/>
                </StackLayout>
            </x:Array>
    </cards:CarouselView.ItemsSource>

```

**Comment by shirish8** [comment]
@AndreiMisiukevich 

<StackLayout x:Name="S1">
                <Label Text="हाजिरी" Font="15" Margin="10,30,0,0" TextColor="Black"/>
                <Label Text="विद्यार्थी" Font="12" Margin="10,20,0,0" TextColor="Black"/>
            </StackLayout>
                <StackLayout x:Name="S2">
                    <Label Text="हाजिरी" Font="15" Margin="10,30,0,0" TextColor="Black"/>
                    <Label Text="शिक्षक" Font="12" Margin="10,20,0,0" TextColor="Black"/>
                    <forms1:ChartView x:Name="Chart1"  HorizontalOptions="FillAndExpand" WidthRequest="150" HeightRequest="150" Margin="25,30,0,0"/>

                </StackLayout>


I want to add this two stacklayouts in the Carousel View...

**Comment by AndreiMisiukevich** [comment]
@shirish8 

<cards:CarouselView.ItemsSource>
            <x:Array Type="{x:Type View}">
                </StackLayout>
                </StackLayout>
            </x:Array>
    </cards:CarouselView.ItemsSource>

**Comment by shirish8** [comment]
@AndreiMisiukevich  Thank You...can you tell me about how to put the Indicators as well???

**Comment by shirish8** [comment]
@AndreiMisiukevich 
Thank you....Could you be more specific and explain a bit more about Indicators???

**Comment by AndreiMisiukevich** [comment]
@shirish8 just open my GitHub readme or docs .
Everything is explained there :)

**Comment by shirish8** [comment]
@AndreiMisiukevich 
Thank you very much :D.

**Comment by shirish8** [comment]
@AndreiMisiukevich  
i am having trouble using SelectedIndicatorStyle and UnSelectedIndicatorStyle properties...need your help??
any suggestions??

**Comment by alexrainman** [comment]
I AM BACK.

Will take a look.

**Comment by alexrainman** [comment]
@shirish8 do you mean 2 StackLayout in the same page/ItemTemplate?

**Comment by alexrainman** [comment]
I can't reproduce this.

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks
