### ISSUE TITLE
Resolution quality

### ISSUE THREAD

**Issue by hadihashem** [alexrainman/CarouselView#450]
Hi @alexrainman 
I'm unable to get the right picture quality from the first shot
Some of them (1st and 3rd) self improve on the second passage
The one in the middle still always the same
Please advise
Regards
![1_1](https://user-images.githubusercontent.com/34154847/44862927-0edbad00-ac7c-11e8-9222-f4755ef3c57a.jpg)
![2_1](https://user-images.githubusercontent.com/34154847/44862929-0edbad00-ac7c-11e8-8b37-23c07eee905e.jpg)
![3_1](https://user-images.githubusercontent.com/34154847/44862934-0f744380-ac7c-11e8-8032-75de84c7ad2c.jpg)
![2_2](https://user-images.githubusercontent.com/34154847/44862930-0edbad00-ac7c-11e8-9dcf-4e57439339ac.jpg)
![1_2](https://user-images.githubusercontent.com/34154847/44862928-0edbad00-ac7c-11e8-9f40-a02f9003fdb8.jpg)
![2_3](https://user-images.githubusercontent.com/34154847/44862931-0f744380-ac7c-11e8-83d3-8e58c7432a31.jpg)
![3_2](https://user-images.githubusercontent.com/34154847/44862935-100cda00-ac7c-11e8-9760-31e05d9c09ce.jpg)
![2_4](https://user-images.githubusercontent.com/34154847/44862932-0f744380-ac7c-11e8-9be3-c5bc8a5f69cd.jpg)

**Comment by AndreiMisiukevich** [comment]
@hadihashem hi
https://github.com/AndreiMisiukevich/CardView
try this

**Comment by hadihashem** [comment]
looks nice
will try it
thanks
