### ISSUE TITLE
[iOS] PositionSelected not working well on iOS 11.4

### ISSUE THREAD

**Issue by achyusuf** [alexrainman/CarouselView#451]
Event PositionSelected not call when first to second page, and indicator stay on first dot. This problem occurred when i added the CarouselView into a Grid Layout.

**Comment by alexrainman** [comment]
I AM BACK.

Trying to figure it out why.

**Comment by phamphu2911** [comment]
I have issue the same on ios 10.3, 12
You have solution for this?

**Comment by alexrainman** [comment]
I cannot reproduce this. @achyusuf @phamphu2911 can you post an example of your Grid Layout?

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks
