### ISSUE TITLE
UWP: Crash with complex app layout

### ISSUE THREAD

**Issue by scastria** [alexrainman/CarouselView#453]
I have started porting my XF app to UWP using the Native Forms technique (take XF ContentPages and call CreateFrameworkElement() and add them to native UWP UI).  This allows me to get much greater flexibility and power over the UWP layout without limiting myself to XF MasterDetailPage or XF TabbedPage.  I can use UWP NavigationView, for example.  But in doing so, one of my XF ContentPages that use your CarouselView crashes.  I added your source code to my project so that I can debug it and it the crash occurs in UWP CarouselViewIImplementation.cs in FlipView_Loaded.  The first time this method is called, ScrollingHost is null so it tries to find it with FindVisualChild.  But that also returns null.  So when the event handlers are being added, I get an NPE because ScrollingHost is still null.  If I simply add null protection (like you have for ButtonHide), everything works.  The reason is FlipView_Loaded get called again and this time it CAN find a ScrollingHost.

So I would suggest you add NPE protection for ScrollingHost.

**Comment by alexrainman** [comment]
Will do. Thanks

**Comment by uselessChiP** [comment]
I don't think the issue has been fully solved.
I have a Carousel which contains an image (using the FFImageLoading library) and from time to time when I navigate to this page the FindVisualChild inside FlipView_Loaded returns null causing the app to crash with an exception.

I'm using the version 5.2.0.
