### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [alexrainman/CarouselView#454]
@alexrainman How do I make the images auto-pass?

**Comment by alexrainman** [comment]
Like auto swipe? Use a timer and change the position programmatically.

**Comment by andersonvieiragomeslopes** [comment]
@alexrainman I want the images in the list to scroll automatically, without the user having to manually advance, or even, autoplay.

Timer? How do I do?

**Comment by salvador-guerrero** [comment]
I created an autoscroll behavior, it is a little bit unpolished (won't pause when user scrolls manually, for example) but it works

https://gist.github.com/salvador-guerrero/a8332a917af40f944ed8c3feb70eaca3

Usage:

`
<carousel:CarouselViewControl>
    <carousel:CarouselViewControl.Behaviors>
        
        <behaviors:AutoscrollCarouselBehavior Delay="5000"/>
    </carousel:CarouselViewControl.Behaviors>
</carousel:CarouselViewControl>
`

**Comment by alexrainman** [comment]
Very nice.

**Comment by andersonvieiragomeslopes** [comment]
@salvador-guerrero Very Nice, my brother! Congratulations!!!!!!
@alexrainman Thank you also for your help, it is good to have a support team, congratulations to the plugin, I see that, he is not the number 1 by chance, he is excellent. Can I close this problem or would you rather keep it open?

**Comment by alexrainman** [comment]
Done.
