### ISSUE TITLE
Blank screen on iOS using latest version

### ISSUE THREAD

**Issue by TedMobile** [alexrainman/CarouselView#458]
Hi
I was looking for a carousel implementation and I am currently using your one.
Android no problem at all.
iOS i get a blank screen as if it does not render at all.

Is this a  known issue?
Any suggestions.

Is this project still active?

many thanks

**Comment by alexrainman** [comment]
Did you called Init()?

**Comment by TedMobile** [comment]
Hi
thanks for quick reply.
**Silly me apologies!!!**  I was sure I did ,there you go.

I thought your control was part of the new carousel that Xamarin team is writing. Is still the case of they have gone for a total rewrite.

Are you planning any enhancement, eg autoplay etc...?

is there a way to move the indicators in a differnt place  eg top right corner etc..

many thanks for this control.

**Comment by alexrainman** [comment]
Yes, i am planning a big release that will fix lot of bugs and include new features.

**Comment by TedMobile** [comment]
that is great news ,What I like about your control  that is easy to use 
are are you in a position to give dates.Next week,next month etc..

**Comment by alexrainman** [comment]
Couple of weeks?

**Comment by TedMobile** [comment]
Hi there,
wondering if you are getting close to a new release as you mentioned a couple of weeks ago.

thanks
