### ISSUE TITLE
ArgumentOutOfRangeException when ItemsSource is empty (iOS)

### ISSUE THREAD

**Issue by mikegottlieb** [alexrainman/CarouselView#46]
In my iOS project I am seeing a consistent repro when trying to display a CarouselViewControl bound to an ItemsSource that is empty, but not null.

I attached a simple test project. You can see that a null collection or a filled collection is fine, but an empty collection is bad. Since it is common for programmers to always ensure that bound collections are initialized to empty instead of defaulting to null, I think it would be great if the CarouselViewControl could handle an empty collection without crashing.

[CarouselTest.zip](https://github.com/alexrainman/CarouselView/files/676131/CarouselTest.zip)

**Comment by AndriiTsok** [comment]
I'm struggling with the same problem.

**Comment by alexrainman** [comment]
Expect update later today.

**Comment by AndriiTsok** [comment]
@alexrainman are you going to publish an update to the NuGet today?

**Comment by alexrainman** [comment]
Yes 👍

**Comment by alexrainman** [comment]
Sorry, i couldnt release yesterday. I found that implementing ItemsSource changed, supporting null and empty array, was more complicated than planned. Im almost done, so expect this soon.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by AndriiTsok** [comment]
Hey,

I would like to do that :) just share needed details.

On May 4, 2017, at 8:00 PM, Alex Rainman <notifications@github.com<mailto:notifications@github.com>> wrote:


If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by BurningAXE** [comment]
Hi Alex,

I want to help you, too. You should give us at least your email since it's a required field.

**Comment by Hangarspace** [comment]
From the licence.md : alexrainman1975@gmail.com
