### ISSUE TITLE
[Android] Memory leak when CarouselView is used in a TableView cell

### ISSUE THREAD

**Issue by englebertnicolas** [alexrainman/CarouselView#460]
CarouselView is never disposed on Android when it is used in a TableView cell.
(But it is correctly disposed on iOS and correctly disposed on Android when NOT used in a TableView cell).

Consider the following page :
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App7"
             xmlns:cvc="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
             x:Class="App7.SubPageTableView">

    <TableView>
        <TableSection>
            <ViewCell>
                <cvc:CarouselViewControl />
            </ViewCell>
        </TableSection>
    </TableView>
</ContentPage>
```

Do the following actions several times : 
- push the page on navigation stack, 
- then pop it, 
- then execute CG.Collect(); CG.WaitForPendingFinalizers();
- and restart these actions several times.

=> Result : Android.CarouselViewRenderer.Dispose() is never called and memory is never released.

If you replace the TableView with a StackLayout, CarouselViewRenderer.Dispose() is properly called and memory is released.

Is your control designed to be used in a TableView ? 

This was tested with CarouselViewControl 5.2 and Xamarin.Forms 2.5 on an emulator and on physical devices.

Am I missing something ?
Thanks in advance for your help

**Comment by alexrainman** [comment]
Will try to reproduce this.
