### ISSUE TITLE
[Android] IllegalStateException

### ISSUE THREAD

**Issue by vikram-ma** [alexrainman/CarouselView#461]
Platform : Android
Version : 5.2.0

Details:
Unhandled Exception:

Java.Lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 3, found: 2 Pager id: mybundleremoved:id/pager Pager class: class md507f625f62cafec6e81efe0279defe3bb.HorizontalViewPager Problematic adapter: class md507f625f62cafec6e81efe0279defe3bb.CarouselViewRenderer_PageAdapter occurred

What I am doing

Scenario 1:
- I have 3 pages, let's call them 1, 2, 3
- I am currently viewing page 1
- I remove page 2
- I get IllegalStateException.

Scenario 2:
- I have 3 pages, let's call them 1, 2, 3
- I am currently viewing page 1
- I remove page 3
- Works fine.

Scenario 3:
- I have 3 pages, let's call them 1, 2, 3
- I am currently viewing page 1
- I remove all pages i.e 1, 2 & 3.
- Works fine.

**Comment by alexrainman** [comment]
I can't reproduce this.

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks
