### ISSUE TITLE
Negative InterPageSpacing deosn't work on iOS

### ISSUE THREAD

**Issue by vikram-ma** [alexrainman/CarouselView#463]
Platform: iOS
Version: 5.2.0

I want to set negative InterPageSpacing so the adjacent pages overlap, so that I can preview of previous and next item in the list. This works perfectly on Android, but doesn't work on iOS.

This feature is very important for me, 
Is there any chance you could fix that? If needed, I can take a look at your code make a PR, please point me to the place where I should start looking at.

Thank you for providing this package, I appreciate your contribution a lot.

**Comment by alexrainman** [comment]
This is not possible in the native control i am using (UIPageViewController). You are lucky it works on Android.
