### ISSUE TITLE
[Android] CarouselView does a partial Swipe  while navigating from higher(say 3) to lower index(say 2)

### ISSUE THREAD

**Issue by cjkarande** [alexrainman/CarouselView#464]
CarouselView does a partial Swipe while navigating from higher position index (say 3) to lower position index(say 2). This happens in both cases i.e. while using Position property from code or swipe from screen

**Comment by cjkarande** [comment]
Hi @alexrainman , appreciate your support on this.
Thanks in advance

**Comment by cjkarande** [comment]
No response so far. Anyone who's come across this issue?

**Comment by arkadiuszokon** [comment]
I have same issue, will try to fix this ;)

**Comment by alexrainman** [comment]
Hi guys. Sorry, i have been trying to make sometime to cheap a new version but it is not ready yet. Will keep you posted. Thanks

**Comment by cjkarande** [comment]
@alexrainman , thanks for your reply.
Will the new version carry a fix for this issue. Also approx by when do you plan to ship this new version?

**Comment by alexrainman** [comment]
Is this issue on Android or iOS?

**Comment by cjkarande** [comment]
@alexrainman for now its on Android. I am using CarouselView in a Popup page and all child elements in the CarouselView are ListViews. Pls refer to screenshot below.
![carouselview issue](https://user-images.githubusercontent.com/2056500/48309829-9a8c8680-e5a7-11e8-808a-14f512b9de14.jpeg)

**Comment by cjkarande** [comment]
@alexrainman , i am using a collection of ListViews inside the  CarouselView. I also tried wrapping the Listviews inside DateTemplate & StackLayout, however the issue still persisted. Finally to speed my work i have dropped this plugin and started writing by own lite version per my requirement. Hope it gets fixed in your next release.

**Comment by alexrainman** [comment]
I still cannot reproduce this.

**Comment by Zure1** [comment]
Had a similiar problem, I thought this is a bug in CarouselView. But what actually caused this was a Margin of -10 on BoxView on one of the ContentViews. @cjkarande check if you don't use any negative Margins in your layout, because this causes the controls to overlap onto another page.

This also explains why it only happens after swiping back, because before that the View was not loaded.
