### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by patchandthat** [alexrainman/CarouselView#466]
In the readme, infinite scrolling is on the roadmap.

Have you had any thoughts on how you would go about implementing this?  I currently have a need for something like this, I could possibly send a pull request for it if you're able to give me some direction.

In my use case, I've currently got 3 items in the carousel, and as I scroll I want to remove the oldest element and preload the next thing to be scrolled into view, but I'm having a bit of a headache over recentering the position after changing the content of the source collection.

**Comment by alexrainman** [comment]
Next release.
