### ISSUE TITLE
[iOS] Default constructor not found for type CarouselView.FormsPlugin.Abstractions.CarouselViewControl 

### ISSUE THREAD

**Issue by bkischel** [alexrainman/CarouselView#467]
Hey,

When I run my app on iOS 12 (release) I get the following error:

> Default constructor not found for type CarouselView.FormsPlugin.Abstractions.CarouselViewControl (System.MissingMethodException)
at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x0007b] in <05bb80b791d24be8b9b930a870852bd1>:0 ...

The error seams to appear when the app tries to create the CarouselView which is implemented in my xaml file like this:

`<c:CarouselViewControl x:Name="teaserCarousel"  Orientation="Horizontal" InterPageSpacing="0"
RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}" 
RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1.1}" />`

For some reason, the error only occurs when running with _release_ setting.
Running the app with _debug_ setting works fine on iPhone and iPhone Simulator.

**Comment by alexrainman** [comment]
Maybe the next release will solve this for you.

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This issue will be corrected.
