### ISSUE TITLE
Pages don't render when paging using SetCurrentPage

### ISSUE THREAD

**Issue by mikegottlieb** [alexrainman/CarouselView#47]
I'm seeing a strange rendering issue. My instance of the CarouselViewControl has an ItemsSource filled with all of my view models. I allow the user to swipe through the carousel, but I also provide arrow buttons to make this more discoverable.

The arrow buttons have handlers that call SetCurrentPage on the carousel to move to the next and previous pages. After using these buttons a bit I always end up in a state where the current page doesn't render and I have to swipe to get the view to correct itself.

It seems that it is getting stuck displaying the space in between pages, except I set that spacing to 0 so there shouldn't actually be any space there.

This occurs on both iOS and Android.

**Comment by alexrainman** [comment]
Can you share a demo project.

**Comment by alexrainman** [comment]
I cannot reproduce this.

**Comment by mikegottlieb** [comment]
I'm not seeing it anymore. I'm thinking it was related to something else. Feel free to close and I'll add more info if I see it again. Thanks!

**Comment by alexrainman** [comment]
Ok. Update to latest version for extra stability. Thanks

**Comment by mikegottlieb** [comment]
I'm seeing it again. I took a couple of screenshots in the Xamarin Inspector. It looks like the UIView that is at the root of CarouselViewControl is not the right size. According to Xamarin.Forms the Carousel should be 320 x 285, but the UIView is 640 x 853. So I think what is happening is that calling SetCurrentPage is causing it to scroll, but it is scrolling to blank whitespace instead of the area of the next page with my view. I'm attaching some screenshots of the inspector so you can see.
![screen shot 2017-01-05 at 12 04 08 pm](https://cloud.githubusercontent.com/assets/2380086/21696860/a5944c2e-d344-11e6-9248-80ab22acdb47.png)
![screen shot 2017-01-05 at 12 04 23 pm](https://cloud.githubusercontent.com/assets/2380086/21696863/a937b8a2-d344-11e6-9beb-c26f051f7402.png)

**Comment by alexrainman** [comment]
Can you share a demo project?

**Comment by mikegottlieb** [comment]
[CarouselTest.zip](https://github.com/alexrainman/CarouselView/files/688649/CarouselTest.zip)

Ok I figured it out. The issue I was seeing is a race condition. My Carousel contains views of different heights. What I do to work with that is change the height of the Carousel's GridCell when the position changes. If that height is changed before the slide to the new page animation completes then the carousel stops midway through the slide.

I believe the issue is in the difference between where you fire PositionSelected when the user swipes vs. when the position is changed programmatically.

When the user swipes the PositionSelected event is fired in `PageController_DidFinishAnimating` [here](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs#L259) and so everything works.

However, calling it programmatically in `SetCurrentController` [here](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs#L335) doesn't guarantee that it is called after the slide completes.

Also, if it is already going to be fired when the animation completes does it need to be fired in `SetCurrentController` at all?

**Comment by alexrainman** [comment]
When you swipe programmatically PageController_DidFinishAnimating is not called, thats why i call Position_Selected in SetCurrentController.

**Comment by alexrainman** [comment]
This native widgets were not designed to work the way i made them to work :)

**Comment by mikegottlieb** [comment]
So are you saying that this scenario just isn't supported? Meaning there is no way to programmatically slide the carousel and then update the UI after the animation has completed?

**Comment by mikegottlieb** [comment]
You might want to consider disabling animation then when you call SetCurrentPage or at least exposing a property that disables animation completely.

**Comment by alexrainman** [comment]
Theres no problem with animation. The thing is that when you move to next page programmatically DidFinishAnimating is not called so i have to call PositionSelected. Thats why i added a delay of 100 ms to give time to the view to appear. Maybe yours is taking more than that.

**Comment by alexrainman** [comment]
I know whats the problem. I am going to add a delay before calling "positionSelected" in SetCurrentPage. That should solve the problem you have.

**Comment by mikegottlieb** [comment]
Don't add a delay. What you need to do is move the call to `PositionSelected` into the completion block. According to the [docs](https://developer.apple.com/reference/uikit/uipageviewcontroller/1614087-setviewcontrollers) The completion block is called after the animating completes. So the code would look something like this:

```
var firstViewController = CreateViewController(position);
pageController.SetViewControllers(new[] { firstViewController }, direction, true, s =>
				{
                                       if (Element.PositionSelected != null)
					     Element.PositionSelected(Element, EventArgs.Empty);
				});

				ConfigurePageControl();
```

**Comment by mikegottlieb** [comment]
FWIW I still think that exposing a property that lets the developer control the value of the `animated` parameter also be great rather than just hard-coding true/false in different places.

**Comment by alexrainman** [comment]
That will be good also :)

**Comment by mikegottlieb** [comment]
Did you close this because we know what is going on and you plan to make the changes?

BTW thanks for being so responsive and building useful stuff like this. I'm using your SegmentedControl too 👍

**Comment by alexrainman** [comment]
Np. I have a pending issue to fix in SegmentedControl also. And yes, this fix should be enough so i will push an update.

**Comment by alexrainman** [comment]
I released the fixes in version 2.9.0 👍

**Comment by alexrainman** [comment]
Notice i also ship this plugin but for NativeScript https://www.npmjs.com/package/nativescript-carousel-view

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
