### ISSUE TITLE
[Android Only] Datatemplate with ContentView, Landscape issue 

### ISSUE THREAD

**Issue by ngalicoco** [alexrainman/CarouselView#470]
We are displaying ffcached images in carousel view, where each image is inside of a custom content view where we handle zoom, pan etc. When device is rotated to landscape the content view is no longer centered and starts of at bottom left corner, when swiped, 

the next image is centered though. But now when rotated back to portrait . the two images are shown side by side and it is all jacked up now.  We were on version 4.4.4, and upgrading to latest 5.2.0 caused this issue. Downgrading back to 4.4.4, it works perfectly. But we wanted to be on latest, as I see some important crash issues have be resolved over the time. Looks like it is broken version >5.0.2.

Here the XAML for the page
`<Grid BackgroundColor="{StaticResource Color06}"
	      HorizontalOptions="FillAndExpand"
	      VerticalOptions="FillAndExpand">
		<cv:CarouselViewControl ItemsSource="{Binding Images}"
		                        Position="{Binding SelectedImageIndex}"
		                        InterPageSpacing="10"
		                        HorizontalOptions="FillAndExpand"
		                        VerticalOptions="FillAndExpand">
			<cv:CarouselViewControl.ItemTemplate>
				<DataTemplate>
					<image:ZoomContentView>
						<ffimageloading:CachedImage Source="{Binding FileAttachmentUrl}"
						                            HorizontalOptions="FillAndExpand"
						                            VerticalOptions="FillAndExpand" />
					</image:ZoomContentView>
				</DataTemplate>
			</cv:CarouselViewControl.ItemTemplate>
			<cv:CarouselViewControl.Behaviors>
				<behaviors:CarouselZoomHandlingBehavior />
			</cv:CarouselViewControl.Behaviors>
		</cv:CarouselViewControl>

		<Button Image="close.png"
		        x:Name="CloseButton"
		        AutomationId="CloseButton"
		        Clicked="Button_OnClicked"
		        HorizontalOptions="End"
		        VerticalOptions="Start"
		        HeightRequest="50"
		        WidthRequest="50"
		        Margin="5,25,5,5"
		        BackgroundColor="Transparent" />
	</Grid>`
But, removing ContentView from data template, and placing just the image inside data template, no issues. So looks like something is broken when data template is a content view
Working data template
`<cv:CarouselViewControl.ItemTemplate>
				<DataTemplate>
							<ffimageloading:CachedImage Source="{Binding FileAttachmentUrl}"
						                            HorizontalOptions="FillAndExpand"
						                            VerticalOptions="FillAndExpand" />					
				</DataTemplate>
</cv:CarouselViewControl.ItemTemplate>`

I attached screen shots of an image looks in landscape mode in built out with version 5.0.2 and 5.2.0/5.1.3. The centered image screen shot is how we can to display which works with 5.0.2 but is broken from >5.0.2

![5 0 2](https://user-images.githubusercontent.com/33257210/48081070-33449000-e1bd-11e8-80f3-19352f27f1e7.png)
![5 2 0](https://user-images.githubusercontent.com/33257210/48081071-33449000-e1bd-11e8-9bf5-b52a48005b70.png)

**Comment by ngalicoco** [comment]
We are on Xamarin Forms version: 3.1.0.697729
Android Target SDK version: 28

**Comment by GamesAgeddon** [comment]
Had the same issue already reported https://github.com/alexrainman/CarouselView/issues/310

**Comment by alexrainman** [comment]
Why wrapping the image with ContentView. That's against XF best practices.

**Comment by ngalicoco** [comment]
> Why wrapping the image with ContentView. That's against XF best practices.

It is not just a simple contentview, it is custom content view which has behaviors associated with it for zooming.

**Comment by alexrainman** [comment]
Can you share that ContentView so I can test? Or, can you share a demo reproducing the issue?

**Comment by alexrainman** [comment]
Will try to reproduce this.

**Comment by alexrainman** [comment]
It works for me with or without a ContentView.
