### ISSUE TITLE
[Android] IndicatorsShape did not set to square

### ISSUE THREAD

**Issue by ShahmanTeh** [alexrainman/CarouselView#471]
Hi, I have set the CarouselViewControl IndicatorShape to Square in xaml, but it did not change to square at all.

**Comment by alexrainman** [comment]
Android? iOS?

**Comment by ShahmanTeh** [comment]
Android. tested using your demo build on both Android Device (OnePlus 3T) 8.0 and Genymotion Emulator 8.0

**Comment by alexrainman** [comment]
I don't have a OnePlus but I did test with Genymotion 8.0 and still cannot reproduce this.

**Comment by alexrainman** [comment]
Found the problem. Fix included in next release.
