### ISSUE TITLE
[Android] Unhandled exception 

### ISSUE THREAD

**Issue by liu12010** [alexrainman/CarouselView#475]
Received this exception  when I first run my project on Android 
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(android.content.res.ColorStateList)' on a null object reference

**Comment by alexrainman** [comment]
I am getting close to release date. Please submit a demo reproducing the issue if you want a fix to be included. Thanks

**Comment by liu12010** [comment]
I was failed to copy that issue on another project.
I can't provide the project I'm developing now,It will cause some commercial issue.
I thought maybe it was just somewhere wrong at my project.
I'll post it here If I find it out later.
Thx for your Reply.
