### ISSUE TITLE
[UWP] Datatemplate rendering multiple times per page

### ISSUE THREAD

**Issue by Ruddy2007** [alexrainman/CarouselView#476]
This issue came to my attention after my UWP application has "flashing" issues, looking into it, it looks to be the Carousel View. 

Here is an example: 
```
        // List of pages (create 4 pages)
        var testList = new List<string> { "Test 1", "Test 2", "Test 3", "Test 4" };

        // XAML for carousel view with a binding to the test list 
        <CarouselView:CarouselViewControl ItemsSource="{Binding testList}" ShowIndicators="True" IsSwipeEnabled="True" ShowArrows="True" BackgroundColor="CadetBlue">
            <CarouselView:CarouselViewControl.ItemTemplate>
                <DataTemplate>
                    <Controls:TestView ButtonClickedCommand="{Binding Source={x:Reference conPage}, Path=BindingContext.ButtonHasBeenClickedCommand}"></Controls:TestView>
                </DataTemplate>
            </CarouselView:CarouselViewControl.ItemTemplate>
        </CarouselView:CarouselViewControl>

        // Test view constructor 
        public TestView()
        {
            Debug.WriteLine("Test View Created");
        }
```

The code above creates 4 pages but it renders out 3 times (this seems to random, sometimes it can be 2), we can see this by looking how many times "Test View Created" has been called. Here is the output:

```
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
Test View Created
```

I am trying to look into this and was hoping it may be the way Xamarin.Forms works but I have a feeling it is how and when the control is handing size changes for the view. 

I created a custom renderer for the carousel view and can see that when you do not set a size (height & width) they can and will be changed multiple times for the view, this triggers the property changed events (size changed etc) and the carousel  view redraws. I have tried the same thing using a StackLayout and that seems to handle the size changes without redrawing its children (not sure that is a fair comparison but it may help).

I might be overlooking something here but I am struggling to find a fix for this problem. Let me know your thoughts on this and if I am correct in thinking this is problem. I will upload a test project soon to demo this. Also I have not yet tested on iOS or Android.

**Comment by Ruddy2007** [comment]
Ok just to add onto this quickly, it seems to be when you wrap the view in a StackLayout it then triggers the above behaviour.

**Comment by alexrainman** [comment]
I have been focused on Android and iOS but will work on UWP as soon as i am donde with bugs and brand new funtionality like infinite scrolling, pull to load more, autoplay, indicators position, arrows size and more.

**Comment by Ruddy2007** [comment]
@alexrainman I will try get round to giving more information on this problem soon. Just wanted you to know I am still active on these bugs I have reported just a little busy to invest more time into them at the moment.

**Comment by Ruddy2007** [comment]
@alexrainman Have you used the demo I have in [this issue](https://github.com/alexrainman/CarouselView/issues/469#issuecomment-439876028)?

I have just downloaded and ran it to see the same issue.

**Comment by Ruddy2007** [comment]
Looking into this a bit more, I have hooked in your project and found that  the double rendering is caused by `flipView.SizeChanged += FlipView_SizeChanged;`.

I don't yet fully understand what is going on but the height appears to change 2 times, this catches it second time round and forces the view to re-render. 

Commenting out the size changed then fixes the issue (I only see it render in once but I would guess this would have a huge effect on resizing etc. 

If you could explain what this is doing exactly it would be helpful. 
```

        private void FlipView_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (e.NewSize.Width != ElementWidth || e.NewSize.Height != ElementHeight)
            {
                if (timer != null)
                    timer.Dispose();
                timer = null;

                timer = new Timer(OnTick, e.NewSize, 100, 100);
            }
        }

        private void OnTick(object args)
        {
            timer.Dispose();
            timer = null;

            // Save new dimensions when resize completes
            var size = (Windows.Foundation.Size)args;
            ElementWidth = size.Width;
            ElementHeight = size.Height;

            // Refresh UI
            Xamarin.Forms.Device.BeginInvokeOnMainThread(() =>
            {
                if (Element != null)
                {
                    SetNativeView();
                    Element.SendPositionSelected();
                }
            });
        }
```

**Comment by Ruddy2007** [comment]
Yet another update. 

I think this may not be your plugin causing the issue. With a carousel view in a StackLayout alone you do not see this issue, however if you put a button before it we then see the issue as listed above. 

This appears to be the way Xamarin.Forms StackLayout handles its children with unknown heights (gets the height of the page and then sorts out what child gets what height)?

Please do not close this issue without confirming my results and being 100% sure this is how the plugin should behave.

**Comment by alexrainman** [comment]
If you notice, I don’t advice to place the CarouselView inside StackLayout.

**Comment by Ruddy2007** [comment]
@alexrainman In my main application where I am having this problem it is in a Grid. So I am still looking into this issue. I have a feeling it could be something to do with me binding the grid row heights, that could be causing a similar issue to the StackLayout.

**Comment by Ruddy2007** [comment]
In a odd twist, this appears to mainly happen when on my external monitor and not the laptop screen. I have no idea why that is a thing but it appears to be.

**Comment by morphinapg** [comment]
I think this may be the same or related to the issue I'm having. When resizing the window in UWP, my listview full of data flashes and reloads as if I just loaded the page, even ignoring any changes to the data I've done such as the property I use to expand the listviewitem, which I think is particularly strange. I realized it was the carouselview when I noticed the flashing was happening at the exact same time the carouselview recenters (which has a lag to it). Here's a video:

https://www.youtube.com/watch?v=o5c7GVnbcxs

**Comment by morphinapg** [comment]
I was able to solve my issue by adding a timer to delay any PositionSelected code until at least a second after I finish sizing the window, similar to your timer for delaying SetNativeView. I can see that in your SetNativeView, you basically re-render the ItemsSource every time this is called, and this appears to trigger PositionSelected at least a couple times. First, Position is changed to -1, then to 0, and then back to what it was before SetNativeView was called. I would recommend blocking PositionSelected from firing until after SetNativeView is done doing its thing. 

As for the original topic, I'm fairly certain this is what's causing it:

```
var source = new List<FrameworkElement>();
            if (Element.ItemsSource != null && Element.ItemsSource?.GetCount() > 0)
            {
                for (int j = 0; j <= Element.ItemsSource.GetCount() - 1; j++)
                {
                    source.Add(CreateView(Element.ItemsSource.GetItem(j)));
                }
            }

            Source = new ObservableCollection<FrameworkElement>(source);
            flipView.ItemsSource = Source;
```

You're recreating the view for every page of the carouselview every time the window size is changed. Is it possible to modify the underlying FrameworkElement objects, rather than recreate them every time? I tried messing around with the code but I couldn't figure out a fix for that. The delay and then rerender of the CarouselView is also, I'm guessing, not the cleanest way to handle UI adjustments. Ideally it should be smoother than that. But again, I don't know the solution for that either.

**Comment by alexrainman** [comment]
This will be fixed in the next release.

**Comment by Ruddy2007** [comment]
@alexrainman Can you share your fix for this please? Or release a new version.

**Comment by morphinapg** [comment]
> @morphinapg Did you fix this issue by any chance?

I did not. I was able to solve the issue it was causing in my app as explained above, but I was just working around what the CarouselView was doing. I think most people encountering this issue would not be able to solve it without the official fix coming in the next release. 

That being said, it seems Xamarin.Forms is implementing their own official CarouselView in 4.4.0, expected within the next couple months.

**Comment by Ruddy2007** [comment]
@morphinapg No problem. Its going to take time to move from this plugin to the official one so I need to get these bugs sorted to get us by for now. As the owner appears to have abandoned this plugin :( I will be forking and fixing some issues that are causing us pain. 

Hopefully it will be useful to others. Thanks for your fast reply. :)

**Comment by alexrainman** [comment]
Sorry but have not abandoned the plugin, just yet. It has taken me more time than expected to catch up after one year without releasing a fix. I have this one fixed in the new code. Actually, i have completely refactored how the plugin behaves in UWP.

**Comment by furkick** [comment]
@alexrainman And when will you be releasing these changes? There are many people in dire need of these changes.

**Comment by Ruddy2007** [comment]
@alexrainman Do we have a better way to contact you? Would like a chat if possible to run through some of these issues as I am starting to fix them. I have started with this problem and found UWP is coming back with a 0.4 different in height. Rounding would correct the issue but doesn't seem correct, wondering how you solved this.

**Comment by Ruddy2007** [comment]
@morphinapg I have fixed this and another issue I have been having on my fork of this project. Feel free to use the changes if you need them.

**Comment by morphinapg** [comment]
> Actually, i have completely refactored how the plugin behaves in UWP.

@alexrainman Whenever I compile with .NET native on the current version, my CarouselView control does not display. Will the new version fix that? I was just about ready to publish my app but I realized I couldn't do it without compiling to .NET native which is an issue for me. Strangely, it functions completely fine without .NET native, but windows store certification fails

Please upload these changes. We've been waiting so long. I tried the official XF CarouselView and it simply did not work for my purposes in its current state.

**Comment by alexrainman** [comment]
I am releasing in couple of days.

**Comment by morphinapg** [comment]
Great to hear! 

Update on the .Net Native situation: I found a fix from this article:

https://tomsoderling.github.io/what-every-Xamarin.Froms-developer-needs-to-know-about-UWP/

Based on the solution in that article, I was able to fix my UWP project by changing to this in my App.xaml.cs file in my UWP project:

```
Xamarin.Forms.Forms.Init(e, new[] { typeof(CarouselViewRenderer).GetTypeInfo().Assembly });
```

If you've already fixed this in the new version you're releasing, you can disregard this, but if not, you might want to implement this into your code as well.
