### ISSUE TITLE
Multiple items in horizontal orientation

### ISSUE THREAD

**Issue by miolegbsgh** [alexrainman/CarouselView#478]
Hi,
This is probably just a question, may not necessarily be an issue. 
When in horizontal view only single item is shown and item spacing is disregarded. 
Is it at all capable of showing multiple items as in a list view.

Kind regards

**Comment by alexrainman** [comment]
No. This is a CarouselView, not a ListView. A carousel is intended to fill the entire screen if it is the man component of your page or fill the height request or dimensions your are assigning to it.

**Comment by miolegbsgh** [comment]
Thank you for your answer,
I thought about that and it is a valid consideration.
On other hand I  would like to use presence of partially visible items as indicators, in place of left/right arrows. 
I wonder if you can recommend on how to achieve this, please.
