### ISSUE TITLE
Android  Sliding conflict with the TabbedPage

### ISSUE THREAD

**Issue by MyueX** [alexrainman/CarouselView#48]
when i use the CarouselView in TabbedPage,CarouselView can not slid. and the CarouselView Do not show，when init it must swipe to display (int iOS,Android can not swipe).

**Comment by alexrainman** [comment]
That's an old Android problem. TabbedPage use the same native control that CarouselView use. TabbedPage has a swipe event in the same direction as CarouselView and that goes against Google design guide lines. So, in this case it's not the CarouselView itself. It's container swipe event is overriding the carousel swipe event.

You have two options:

- Disable TabbedPage swipe event or,
- Make CarouselView vertical.

**Comment by alexrainman** [comment]
About not showing when init? Will do some test.

**Comment by MyueX** [comment]
Thank you for your comments。

not showing like this 
![](http://p1.bqimg.com/1949/3a04a827484110a2.png)

**Comment by alexrainman** [comment]
From your screenshot i can see that what is not showing is the content of the page itself. I can see the page indicators, that mean the carousel is showing but not loading its content. Weird.

**Comment by alexrainman** [comment]
I am sorry to tell you that CarouselView inside TabbedPage won't work. The issue is not related to my plugin. TabbedPage somehow Dispose the view when it's not visible and doesn't load it again when swipe. I will try to find why, but you should build a custom tabs with XAML.

**Comment by alexrainman** [comment]
Take a look at issue #45 he is building a custom tab because of this problem.

**Comment by alexrainman** [comment]
Please check at this repo for a solution: https://github.com/alexrainman/TabbedCarouselView

**Comment by MyueX** [comment]
@alexrainman  thanks

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
