### ISSUE TITLE
[Android/iOS] When moving an item that is not the first it throws out of bounds exception

### ISSUE THREAD

**Issue by fedemkr** [alexrainman/CarouselView#483]
**Platform: Android & iOS
Exception: IndexOutofRange**

**What happens**

Having an `ObservableCollection<T>` if we do a `NotifyCollectionChangedAction.Move` of an item that is not the first one it throws an `out of bounds exception`.

```c#
OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Move, myItem, newIndex, oldIndex));
```

I've tracked down the issue and in Android is [here](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs#L142) and in iOS is [here](https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.iOS/CarouselViewImplementation.cs#L129):

```c#
Source.Insert(e.NewStartingIndex, e.OldItems[e.OldStartingIndex]);
```
There what is wrong is that `OldItems` send just the items that were affected by the `Move` action which can be one or more or all. So if you just send one item in the event args but your `OldStartingIndex` is 2 because it was the third item on your `ObservableCollection` then that index won't be found on the `OldItems` array throwing an `out of bounds exception`.

In order to fix that I'd do an insert range in the `Source` with all the `OldItems` in the `NewStartingIndex`:

```c#
Source.InsertRange(e.NewStartingIndex, e.OldItems.Cast<object>());
```

I'm happy to do a PR if you want.

**Comment by alexrainman** [comment]
Will run some test before applying your PR.

**Comment by mmehdidehghani** [comment]
Hi
I have the same issue :( i want to change my observable collection in PositionSelected and it thrown IndexOutofRange.
I'm new in Xamarin.Form.
Could you please help me how can i fix it. 🙏🏻🙏🏻🌹🌹

**Comment by alexrainman** [comment]
I will take a look at this as soon as i can.

**Comment by mmehdidehghani** [comment]
Dear alexrainman
Thank a lot for your reply. 
 I'm waiting for your response. 🙏🏻🙏🏻🌹🌹

**Comment by mmehdidehghani** [comment]
Dear alexrainman
Could you please tell me when you will be able fix the issue? 🙈🙈🙈🙏🏻🙏🏻🌹🌹
Thank you so much
Best Regards

**Comment by fedemkr** [comment]
@mmehdidehghani just in case I did a PR with the Fix, you can download the Fork compile it and reference the dll directly as a temporary workaround.

https://github.com/fedemkr/CarouselView

**Comment by mmehdidehghani** [comment]
Dear fedemkr
Thank you sooooooooo much. I will download it. 🙏🏻🙏🏻🌹🌹🙏🏻🙏🏻🌹🌹🙏🏻🙏🏻🌹🌹
Best Regards

**Comment by alexrainman** [comment]
Merging. It will be out soon.
