### ISSUE TITLE
CarouselView will not be developed?

### ISSUE THREAD

**Issue by Wenfengcheng** [alexrainman/CarouselView#485]
@alexrainman 
I heared that *Xamarin Forms* decided to merge this control into *XF* before, but I can not find any message about **CarouselView implementation**, I aslo find that the collectionview will completely replace the needs of **CarouselView**. [CarouselView will be replaced?](https://github.com/xamarin/Xamarin.Forms/issues/2219#issuecomment-419523457)
So is this control will not be devoloped or supported anymore?

**Comment by alexrainman** [comment]
@Wenfengcheng the answer to your question is YES, the control will continue under development. I am catching up with all the reported issues and preparing a very big release that will include a lot of brand new functionality. Yes, Xamarin is releasing a CollectionView control but, that doesn't make this control not useful and different.

**Comment by Wenfengcheng** [comment]
@alexrainman I am particularly happy to hear that. I have been waiting for a new release all this year. But I am very sorry that I did not see any new features(such as autoSwipe, Infinite scrolling, etc...) being released, and everytime I ask about this features, you said *submit any issues there https://github.com/xamarin/xamarin.forms/tree/feature-carouselview*.
So I can't wait to wait for the next version of the control.

**Comment by alexrainman** [comment]
I made the mistake of almost abandoning this project believing that it will br integrated into Forms. Not making that mistake anymore.

**Comment by Wenfengcheng** [comment]
Yeah, I also think that you have to give up this project. Due to long-term non-maintenance, many people have unstared this project.

**Comment by alexrainman** [comment]
Not giving up. 100k downloads this year. 300 per-day.

**Comment by dfoulk** [comment]
Why would he stop supporting his project because some users withdrew their stars? Could you imagine what great opensource projects we would lose if everyone just gave up because of that? No, sir. That is silly.

**Comment by alexrainman** [comment]
Issue #440 has been fixed but not released yet. I have big plans for this control, including a brand new version in the future that will modern widgets for all platforms.

**Comment by Wenfengcheng** [comment]
@dfoulk @scastria  No one will doubt the greatness of this project, but @alexrainman used to stop updating CarouselView because he misunderstood that Xamarin will maintain and refactor this repo officially. Because he has not updated and fixed issue for a long time, some people who love CarouselView began to give up (such as withdrew their stars).
So stopping supporting this repo is not related to some users withdrew their stars, those who love this project will also wait for his updates. And understand what I want to say.
