### ISSUE TITLE
Capture physical keyboard / remote control scroll 

### ISSUE THREAD

**Issue by hadihashem** [alexrainman/CarouselView#487]
Hello
I'm using CarouselView on an Android TV app
In order to get it certified by Amazon (for Fire TV devices) it is required to allow scrolling using physical keys (keyboard or remote control) 
Would any one be able to help me on this?
I appreciate your feedback
Regards

**Comment by hadihashem** [comment]
![ba9069nnd2r8](https://user-images.githubusercontent.com/34154847/50966327-e63eac00-14d4-11e9-946c-dad7533b62df.jpg)
![wp11j31cau84](https://user-images.githubusercontent.com/34154847/50966332-e8a10600-14d4-11e9-815f-d9fe80553ecd.jpg)

**Comment by alexrainman** [comment]
Do you have an idea to which key_down it is translated?

**Comment by hadihashem** [comment]
no i don't .. sorry
i had to make a custom package for FireTV without CarouselView .. until this enhancement will be released
thank you in advance
