### ISSUE TITLE
Error: System.InvalidCastException: Specified cast is not valid

### ISSUE THREAD

**Issue by willowvil** [alexrainman/CarouselView#49]
Hi,

I´m getting an error "System.InvalidCastException: Specified cast is not valid" with a simple example in Android:

```
var imagesCarousel = new CarouselViewControl();
imagesCarousel.ItemsSource = imagesSource;
imagesCarousel.ItemTemplate = new DataTemplate (typeof(ImageCarouselCell));
imagesCarousel.Position = 0;
imagesCarousel.InterPageSpacing = 10;
imagesCarousel.Orientation = Orientation.Horizontal;

public class ImageCarouselCell : ViewCell
{
	public ImageCarouselCell()
	{
		var image = new Image()
		{
			HorizontalOptions = LayoutOptions.FillAndExpand,
			VerticalOptions = LayoutOptions.FillAndExpand
		};
		image.SetBinding(Image.SourceProperty, "img");
		View = image;
	}
}
```

Thanks!

**Comment by alexrainman** [comment]
ViewCell is not supported in carousel. You have to use View or ContentView.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by joshk6** [comment]
Hi there.  Tried to "help you back" but it says form is private.

FYI, thanks for the carousel.  Its working well now, but I am a newbie and the whole data template thing kind of threw me.  So I was looking at the Xamarin ref on datatemplate here: [https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/templates/data-templates/creating/#type](url) which says among other things:  

> Here, the ListView.ItemTemplate property is set to a DataTemplate that's created from a custom type that defines the cell appearance. The custom type must derive **from type ViewCell,** as shown in the following code example:

So it might be save some time for other of us newbies to document that yours require a View or ContentView and not view cell
