### ISSUE TITLE
Pass Item as Parameter to ViewModel 

### ISSUE THREAD

**Issue by mmehdidehghani** [alexrainman/CarouselView#490]
Hi
I'm new to xamarin development.  I used the Xamarin.Forms.CarouselView and it was sensitive in swiping and changed it to CarouselView.FormsPlugin.AllowViewModels.
I want to pass my item (a model) to my viewModel command, like this:
private void CarouselView_ItemSelected(object sender, SelectedItemChangedEventArgs e)
        {
            var word = e.SelectedItem as LessonWordModel;
            var vm = BindingContext as WordViewModel;
            vm?.BindingExmaples.Execute(word);
        }

I don't know how can i pass parameter in PositionSelectedCommand.
Could you please help me how can i do that?

**Comment by mmehdidehghani** [comment]
Hi again.
I Changed it:
 private void CarouselViewControl_PositionSelected(object sender, CarouselView.FormsPlugin.Abstractions.PositionSelectedEventArgs e)
        {
            var vm = BindingContext as WordViewModel;
            var word = vm?.UserLessonWords[e.NewValue];
            vm?.BindingExmaples.Execute(word);
        }

It passed model to my ViewModel, but i have 2 issues (:
1) zero poistion fired twice!
2) When i change my itemsource in viewModel, i get this error: index out of range!

Could you please help me?

**Comment by alexrainman** [comment]
ViewModels as item source will be supported in the upcoming release. Can you upload a reproduction solution?

**Comment by alexrainman** [comment]
Adding ItemSelectedCommand in the next release.
