### ISSUE TITLE
Auto-slide animation too fast on android

### ISSUE THREAD

**Issue by gueneylib** [alexrainman/CarouselView#494]
Hi @alexrainman ,
first of all, many thanks to you for making this awesome carousel. It was very easy to integrate to my application.
I defined an auto-slide feature on the carousel, and it works fine.
The only problem is that the position-changing animation is too fast on android. It's like lightning-fast and not trackable with human eyes.

Is there any possibility to slow down the animation on android side?

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This will be supported.
