### ISSUE TITLE
Is it possible to show previews of previous/next item?

### ISSUE THREAD

**Issue by Inrego** [alexrainman/CarouselView#495]
Is it possible? I made this illustration to show what I mean:

![image](https://user-images.githubusercontent.com/2242329/53347346-2b019380-3919-11e9-84a8-009ce0f82639.png)

**Comment by Inrego** [comment]
Here's some more info about it being implemented in iOS:
https://stackoverflow.com/questions/41284846/how-to-use-uipageviewcontroller-to-also-display-a-part-of-the-previous-and-next

And this issue seems to indicate it's possible on Android by setting negative InterPageSpacing:
https://github.com/alexrainman/CarouselView/issues/463

**Comment by zwilkin** [comment]
I, too, would love to see this implementation!

**Comment by alexrainman** [comment]
This is not easy as it is no supported by the “under the hood native control” but, i think i can come up with a workaround. It won’t be there for next release.
