### ISSUE TITLE
(Android) Does not re-measure its layout on Height Changed

### ISSUE THREAD

**Issue by JKennedy24** [alexrainman/CarouselView#496]
With the latest release of this and the latest Xamarin.Forms and latest release of carousel

Layout is not re-measured on height changed.

This was a previous bug which was fixed here: https://github.com/alexrainman/CarouselView/issues/184

Same repo still works just needs nugets updating

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This issue will be corrected.

**Comment by alexrainman** [comment]
Can you try the solution mentioned in #406?

**Comment by JKennedy24** [comment]
@alexrainman I tried the solution highlighted. adding:

            this.LoadApplication(App);

            //https://github.com/alexrainman/CarouselView/issues/406
            Xamarin.Forms.Application.Current.On<Xamarin.Forms.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);

But this didn't fix the issue,

if you test a listview inside a carousel, open the app in landscape and then rotate the app to portrait you will see it doesnt remeasure

**Comment by alexrainman** [comment]
Going to try that.

**Comment by alexrainman** [comment]
It works as expected for me even without using the workaround, at least in my latest source code.
