### ISSUE TITLE
SwipeGestureRecognizer with Android

### ISSUE THREAD

**Issue by ahmadkq** [alexrainman/CarouselView#498]
When using GestureRecognizers with SwipeGestureRecognizer to use direction "UP" or "Down" for example, it is not working with Android but it is working in iOS. In Android, the swipe command is not called.

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Can you provide a demo?

**Comment by alexrainman** [comment]
I am adding support for SwipeGestureRecognizer in next release but tapped won't work. You will have to use a Command instead.
