### ISSUE TITLE
Method Init not exist

### ISSUE THREAD

**Issue by ivanteles** [alexrainman/CarouselView#499]
I tried to start the init method call in Ios, but it does not exist in the project.

CarouselViewRenderer.Init();

**Comment by NelsonSantos** [comment]
Hi,

You should put the 
using CarouselView.FormsPlugin.iOS namespace at the header of your .cs file or ...
call CarouselView.FormsPlugin.iOS.CarouselViewRenderer.Init(); directly.

Regards...

**Comment by ivanteles** [comment]
Tanks
