### ISSUE TITLE
Lots of controls don't work correctly

### ISSUE THREAD

**Issue by JoshuaNovak919** [alexrainman/CarouselView#5]
Switches etc do not work properly in a CarouselViewControl.

**Comment by alexrainman** [comment]
Which issues u have with them?

**Comment by alexrainman** [comment]
Are you still having this issue?

**Comment by alexrainman** [comment]
No answer back so, i guess you are not using the control anymore or it's not giving you issues. I will release UWP support soon and i will add customizable Page Indicators. Also, InsertPage now receives an optional parameter for the position where you want to insert the page, if not specified, it will be added to the end. I also added Bounces property that works only for iOS. This will disable swipe on iOS and it's useful if you want to have only one page at a time and move back and fort programmatically. I will put together a demo with this functionality.

**Comment by JoshuaNovak919** [comment]
@alexrainman Sorry, been crazy busy lately. I'm still using it, but I made a work around for now. The official CarouselView plugin is almost out of Prerelease, so by the time I need a carousel view again I can probably just use that. And that one I believe, works the same as all Xamarin.Forms views so I shouldn't have the same issue.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
