### ISSUE TITLE
Touch events swallowed

### ISSUE THREAD

**Issue by jasekiw** [alexrainman/CarouselView#500]
When adding children to the cardview that contains a touch effect, it no longer works. 
If I use the touch effects outside the carousel view it works fine,  inside no event gets raised.

ex.
```
<Grid.Effects>
    <tt:TouchEffect Capture="True" TouchAction="TouchEffect_OnTouchAction"   />
</Grid.Effects>
```

**Comment by jasekiw** [comment]
This also can be reproduced by adding a button inside the carouselview and you will find that the button does not trigger it's click event. I did this test on android. This ruins a lot of use cases for this library.

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Running some tests.

**Comment by alexrainman** [comment]
Related #431, #491, #498, #501

**Comment by alexrainman** [comment]
Done.
