### ISSUE TITLE
TapGesture not working when ItemsSource is set

### ISSUE THREAD

**Issue by ColdThor** [alexrainman/CarouselView#501]
I noticed some people are having troubles with adding TapGestureRecognizer to the carousel. I debuged my own problem to the fact that the TapGestureRecognizer works if the ItemsSource is null / not set.

My XAML:

<StackLayout HorizontalOptions="Center" VerticalOptions="End" Margin="0,0,0,10" x:Name="caro"
                                  BackgroundColor="Black">

                <cv:CarouselViewControl x:Name="carousel"
        
                    ShowArrows="false"
                    ShowIndicators="true"
                    PositionSelected="Handle_PositionSelected"
                    Scrolled="Handle_Scrolled"
                    Orientation="Horizontal">

                    <cv:CarouselViewControl.Behaviors>
                        
                        <behaviors:AutoscrollCarouselBehavior Delay="4000"/>
                    </cv:CarouselViewControl.Behaviors>

                    

                    <cv:CarouselViewControl.GestureRecognizers>
                     <TapGestureRecognizer 
                     Tapped="OnButtonTapped" 
                     NumberOfTapsRequired="1">
                     </TapGestureRecognizer>
                    </cv:CarouselViewControl.GestureRecognizers>

                </cv:CarouselViewControl>
            </StackLayout>

The CS behind the XAML:
             
            InitializeComponent();
            carousel.IsVisible = true;
            carousel.HeightRequest = 150;
            carousel.WidthRequest = 300;
            BindingContext = _vm = new SlideShowViewModel();
            carousel.ItemsSource = _vm.MyItemsSource;  
          

The BindingContext is unchanged from Demo.

Since I am using the Carousel to display banners I need them to be clickable but cant see a way to do so. Read the related threads but nothing worked.

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Running some tests.

**Comment by alexrainman** [comment]
I am adding support for TapGestureRecognizer in next release but tapped won't work. You will have to use a Command instead.
