### ISSUE TITLE
Popping a page back to a carousel view page in landscape causes page reset

### ISSUE THREAD

**Issue by jonasrembratttetrapak** [alexrainman/CarouselView#502]
DESCRIPTION:

On older iPhones (v. 8 or lower) in landscape mode, from a carousel view, when pushing a page to the nav stack in landscape and then popping back to the page again, it gets "reset": The page scrolls to the top and the iPhone status bar suddenly appears (it shouldn't in landscape mode).

Attached a small demo project.
[Lab.StackNavInLandscape.zip](https://github.com/alexrainman/CarouselView/files/2952598/Lab.StackNavInLandscape.zip)

**Comment by jonasrembratttetrapak** [comment]
I could mention that this only happens when user navigates back to carousel view page using a PopAsync(). It does not happen if he/she just navigates "< Back" from the navigation bar.

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Running some tests.

**Comment by alexrainman** [comment]
This is not a bug of the carousel itself but Xamarin. PopAsync changes the height of the navigation bar, causing the element size to change so the Carousel resets. Don't know if i can do anything here.
