### ISSUE TITLE
System.NullRefernceException thrown and preview don't work

### ISSUE THREAD

**Issue by davidra7** [alexrainman/CarouselView#503]
Hi,
I added to MainActivity render init function

base.OnCreate(savedInstanceState);
global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
CarouselViewRenderer.Init();
LoadApplication(new App());

The preview don't work for android but works for iOS , the error is System.NullRefernceException was thrown in onElementChanged
![Screen Shot 2019-03-22 at 16 05 13](https://user-images.githubusercontent.com/5837615/54828295-862a6a00-4cbc-11e9-868b-265d733f0100.png)

my CV xaml is 
<controls:CarouselViewControl x:Name="CV" ShowIndicators="false" PositionSelectedCommand="Handle_PositionSelected" Orientation="Horizontal" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">

Thanks for the help,
David

**Comment by lewcianci** [comment]
Same issue here.  This package was broken first with XF 3.5 and now it has broken again for some other reason :(

**Comment by lewcianci** [comment]
@davidra7 is your CarouselView in another control, like a Frame or something? When I put my CarouselView in a frame I got this error.  Taking the CarouselView out of the frame made it work.

**Comment by davidra7** [comment]
Hi,
My CV is inside StackLayout , what frame did you used?

**Comment by lewcianci** [comment]
Actually, I recreated this exact issue when using Visual="Material" in my XAML.  Are you using that per chance? If you are, remove it and I reckon it will come to life.

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Running some tests.

**Comment by rtolliver** [comment]
Echoing seeing this issue on the latest version on Xamarin.Android. The only workaround I've found to this point is rolling back to an older version.

**Comment by alexrainman** [comment]
Community, i have been working hard to release a new version. I am close to that point.

**Comment by maxbaki** [comment]
> Community, i have been working hard to release a new version. I am close to that point.

Really need help on this. App still crash on IOS and Android 28.

Thank you!

**Comment by alexrainman** [comment]
Cant reproduce the exception. Also, preview doesn't render the carousel and i don't have a clue why.
