### ISSUE TITLE
Arrow Position

### ISSUE THREAD

**Issue by jmtejada** [alexrainman/CarouselView#505]
Hi, this is a great complement. 👍 

Is it possible to modify the arrow template? Or change the position of them? that is, have the option to draw them in the top, middle or bottom of the screen?

thanks!

**Comment by alexrainman** [comment]
Can you provide more details on your need? What do you mean with top middle and bottom?

**Comment by jmtejada** [comment]
It is possible to change the location of the arrows to move them up, to the middle or down. So that it fits my design.

![image](https://user-images.githubusercontent.com/23384279/55120463-2e2ca280-50c4-11e9-98ce-8e352c4156e3.png)

thanks! 👍

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This will be included.

**Comment by alexrainman** [comment]
This will be included in next release.
