### ISSUE TITLE
Chage position programatically

### ISSUE THREAD

**Issue by hectorast** [alexrainman/CarouselView#506]
I want to add and external button to skip a tutorial carousel, I except that when click in this button go to last item in the carousel.

I see that in previous version exists SetCurrentPage, but now is deprecated. Are there any other solution to do that?

Thanks.

**Comment by alexrainman** [comment]
Just set position property to the last page.

**Comment by hectorast** [comment]
I try it but in Carousel nothing happend

**Comment by lewcianci** [comment]
Yeah @hectorast I do this exact thing in my app.  Post some code and I'll take a look at it (and we'll give @alexrainman  a rest!).  Where you have the property for CurrentPage, does that class implement INotifyPropertyChanged? Are you using a framework like Prism or something? Or just code behind?

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Changing the position programmatically or binding it to a property that you change programmatically should fix the problem.
