### ISSUE TITLE
This warnings will disappear when i release the new version that will support XF.3.4.x and latest Android packages.

### ISSUE THREAD

**Issue by Monikaprime** [alexrainman/CarouselView#510]
This warnings will disappear when i release the new version that will support XF.3.4.x and latest Android packages.

_Originally posted by @alexrainman in https://github.com/alexrainman/CarouselView/issues/420#issuecomment-439905615_

**Comment by Monikaprime** [comment]
![image](https://user-images.githubusercontent.com/47033567/55457509-bb618100-5607-11e9-892d-bec22a9021cb.png)

check not solved for XF.3.6 and plugin version 5.2.0

**Comment by dfoulk** [comment]
I've got all these too. We've decided to update to Xamarin.Forms 4.0's CarouselView. Might be worth updating for you too!

[https://msdn.microsoft.com/en-us/magazine/mt833407.aspx](https://msdn.microsoft.com/en-us/magazine/mt833407.aspx)

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This issue will be corrected.

**Comment by alexrainman** [comment]
This will be fixed in the next release.
