### ISSUE TITLE
Indicators position aligning - Start | Middle | End

### ISSUE THREAD

**Issue by LeoJHarris** [alexrainman/CarouselView#512]
Hi there,

Feature request to be able to gain more control of placement of the Indicators.

Proposing properties: VerticalAlign and HorizontalAlign.

With Enumeration values: Start | Middle | End

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. I have been trying to implement this but I am facing some roadblocks. If it is not included in next release then it will be the upcoming one. It is in my roadmap for sure.

**Comment by alexrainman** [comment]
Planned for future roadmap.
