### ISSUE TITLE
[Android] Blocking: When changing main page get error 

### ISSUE THREAD

**Issue by PWaliaDev** [alexrainman/CarouselView#518]
When changing Main page of application from Carousel View to something else get below error

Unable to activate instance of type Com.ViewPagerIndicator.CirclePageIndicator from native handle 0xff91625c (key_handle 0x379aca3). ---> System.MissingMethodException: No constructor found for Com.ViewPagerIndicator.CirclePageIndicator::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.   at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.

Also I tried ways mentioned in this ticket #489 but nothing works 

if I add Xamarin.Android.Support.ViewPager then get below error.

Error XA2002: Can not resolve reference: Xamarin.Android.Support.ViewPager, referenced by Com.ViewPagerIndicator. Please add a NuGet package or assembly reference for Xamarin.Android.Support.ViewPager, or remove the reference to Com.ViewPagerIndicator.

**Comment by Kornelis** [comment]
I had a similar issue. Downgrading the CircleIndicator Nuget Package helped as a Workaround.

**Comment by hamid-shaikh** [comment]
> I had a similar issue. Downgrading the CircleIndicator Nuget Package helped as a Workaround.

There is no such package installed called CircleIndicator - I can only see package installed is CarouselView.FormsPlugin

**Comment by DoctorWaffles** [comment]
> I had a similar issue. Downgrading the CircleIndicator Nuget Package helped as a Workaround.

All version seems to break for me, what version of CircleIndicator and CarouselView were you using?

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. This issue will be corrected.

**Comment by Phenek** [comment]
@alexrainman Hope you will, cause we stuck with Xamarin 3.4 with your very useful lib.

**Comment by tempest360** [comment]
@alexrainman any update on the new release ? It's been more than 3 weeks now.
@Phenek has created a PR for the change. 
Thanks 👍

**Comment by pandaloupe** [comment]
My quick and dirty fix for this is clearing the content and thus all controls from the current page before switching to another main page. While this is surely not an elegant solution and leaves the page blank while initializing the new one at least the error is gone...

```
// clear the contents of the old page
var oldPage = Application.Current.MainPage;
if (oldPage is NavigationPage navPage)
{
   if (navPage.RootPage is ContentPage contentPage)
   {
      contentPage.Content = null;
   }
}

// now switch to your new page
Application.Current.MainPage = [your new page];
```

**Comment by USAMA-app** [comment]
> I am back! Releasing new version in the next 2 weeks. This issue will be corrected.

any update of this issue.

**Comment by alexrainman** [comment]
Updating to latest version of CirclePageIndicator should solve this in the meantime.

**Comment by Phenek** [comment]
#489
I updated CirclePageIndicator to 1.0.3 inside my project

Even if I install ViewPager I got the:

Can not resolve reference: Xamarin.Android.Support.ViewPager, referenced by Com.ViewPagerIndicator.

Unfortunately I think that there is already a CirclePageIndicator.dll in Carousel Lib

Updating the CirclePageIndicator inside the CarouselView nupkg is solving the issue for me.

Regards,

**Comment by alexrainman** [comment]
There's not a CirclePageIndicator.dll in Carousel Lib. You will have to wait for the next release then.

**Comment by pandaloupe** [comment]
> Updating to latest version of CirclePageIndicator should solve this in the meantime.

@alexrainman Tying to do that, I get the same Error as @Phenek 

> Updating the CirclePageIndicator inside the CarouselView nupkg is solved the issue for me.

@Phenek How did you do that?

Nevertheless: Great tool, would always recommend it! 👍

**Comment by Phenek** [comment]
I just created a nuspec file with the updated circlepageIndicator PR
and then nuget pack it to create .nupkg output

**Comment by LeoJHarris** [comment]
@Phenek Im in the process of doing the same, fingers crossed. In the mean time you think you might be able to zip up that precious .nupkg and add it here. 👍

**Comment by banjahman** [comment]
For anybody running into this currently, I worked around it by following this comment from @tunbeo in another thread.

> I updated All Project to Xamarin Forms 4.0
In Android, add Xamarin.Android.CirclePageIndicator 1.0.3 , used Android 9.0, in Android Build checked Enable Multi-Dex. Then delete all bin and obj folders, open Solution again and it works like a charm hehe
https://github.com/alexrainman/CarouselView/issues/489#issuecomment-499863613

**Comment by alexrainman** [comment]
This will be fixed in next release.
