### ISSUE TITLE
Crash on adding an item to carouselView

### ISSUE THREAD

**Issue by pasha-o** [alexrainman/CarouselView#52]
hi @alexrainman 
I used the plugin and created a simple test to see how it looks. I receive a crash as soon as adding an item

this is the message I receive in android using API 23

Java.Lang.IllegalStateException: The application's **PagerAdapter** changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 1 Pager id: []:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class md5fa3be16b83ce3acd3be83265686c14de.CarouselViewRenderer_PageAdapter

am i doing anthing wrong?

here is the sample XAML

`<carousel:CarouselViewControl ItemsSource="{Binding MyImages}" Orientation="Horizontal"
 ShowIndicators="True" PageIndicatorTintColor="White" InterPageSpacing="2" Position="0" CurrentPageIndicatorTintColor="Orange" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" >

        <carousel:CarouselViewControl.ItemTemplate>
          <DataTemplate>
            <Image  Aspect="AspectFill" Source="{Binding}"  />
          </DataTemplate>
        </carousel:CarouselViewControl.ItemTemplate>

</carousel:CarouselViewControl>`

**Comment by alexrainman** [comment]
I dont know how MyImages may look but they maybe a list of string representing the url of the image, dont?

Take a look how you are doing the binding of Image source, it should be something like this:

<Image Source="{Binding .}" />

Also, if you are going to build an image carousel, use FFImageLoading or you will get OutOfMemory crash in Android.

**Comment by alexrainman** [comment]
Image Source="{Binding .}"

**Comment by alexrainman** [comment]
Take a look at this repo as example: https://github.com/alexrainman/TabbedCarouselView

**Comment by pasha-o** [comment]
thanks for the prompt response , 
MyImages is an observableCollection 

 VehicleImages = new ObservableCollection<ImageSource>();

i will have a look - weird part is I got it working for the first time and not anymore :)

**Comment by alexrainman** [comment]
The plugin has been well tested by the community and lot of issues has been fixed and functionality added. The only trick with images is to use it with FFImageLoading.

**Comment by pasha-o** [comment]
in your sample  Source="**{Binding .}**" what is dot for?

**Comment by pasha-o** [comment]
hi @alexrainman

soi tried your suggestion with using the FFImageLoading and it only worked once.  every other try throws the exception i posted before .

 Java.Lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 1 Pager id: io.SensoDrive.ResParkAuto:id/pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class md5fa3be16b83ce3acd3be83265686c14de.CarouselViewRenderer_PageAdapter
01-10 22:13:59.977 I/MonoDroid(25794):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-10 22:13:59.977 I/MonoDroid(25794):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in /Users/builder/data/lanes/3511/501e63ce/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083 
01-10 22:13:59.977 I/MonoDroid(25794):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00022] in /Users/builder/data/lanes/3511/501e63ce/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:41 
01-10 22:13:59.977 I/MonoDroid(25794):   at Android.Views.View.Measure (System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x0002a] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.View.cs:13953 
01-10 22:13:59.977 I/MonoDroid(25794):   at Xamarin.Forms.Platform.Android.ViewRenderer`2[TView,TNativeView].OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00037] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\ViewRenderer.cs:136 
01-10 22:13:59.977 I/MonoDroid(25794):   at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:240 
01-10 22:13:59.977 I/MonoDroid(25794):   at (wrapper dynamic-method) System.Object:88906e53-6f2c-4892-a1bb-b5c7d2b6af4d (intptr,intptr,bool,int,int,int,int)
01-10 22:13:59.977 I/MonoDroid(25794):   --- End of managed Java.Lang.IllegalStateException stack trace ---

**Comment by alexrainman** [comment]
Please share a demo reproducing the issue.

**Comment by alexrainman** [comment]
I don't really know what are you doing. Please share a demo.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
