### ISSUE TITLE
[Android] Images sometimes do not show

### ISSUE THREAD

**Issue by ethanyuxinzhang** [alexrainman/CarouselView#521]
Hi

I am working on a cross-platform project using xamarin forms. I am using carouselview to display captured or picked photos. The strange thing is that sometimes the carouselview does not show the images. It happens every now and then and only on Android device. Is there any potential reason for causing this?

**Comment by alexrainman** [comment]
I am back! Releasing new version in the next 2 weeks. Can you provide a demo reproducing the issue?
