### ISSUE TITLE
iOS crash on swipe + SetCurrentPage(index)

### ISSUE THREAD

**Issue by SickRed** [alexrainman/CarouselView#53]
Hello, first of all thx for this package!

I've developed an android version of my app where CarouselView works like a charm. Now I started testing the iOS version of the app. 

Swiping works for like 10 swipes, then it fails with a crash like this:

> Foundation.MonoTouchException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x7ffb74874f50; frame = (0 0; 320 470); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x608001626c40>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x7ffb74c7f310>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x7ffb74b97730>.
> Native stack trace:
> 	0   CoreFoundation                      0x000000010b12ed4b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x000000010b53021e objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010b1982b5 +[NSException raise:format:] + 197
> 	3   UIKit                               0x00000001091f345b -[UIView(Internal) _setViewDelegate:] + 231
> 	4   UIKit                               0x00000001092dda13 +[UIViewController setViewController:forView:] + 41
> 	5   UIKit                               0x00000001092d5292 -[UIViewController setView:] + 522
> 	6   PpushiOS                            0x0000000104ebdbfc xamarin_dyn_objc_msgSendSuper + 220
> 	7   ???                                 0x000000011e0e9f2c 0x0 + 4799242028
> 	8   ???                                 0x000000012271a4de 0x0 + 4872840414
> 
>   at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:310
>   at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/runtime/Delegates.generated.cs:126
>   at at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
>   at at (wrapper managed-to-native) ObjCRuntime.Messaging:void_objc_msgSendSuper_IntPtr (intptr,intptr,intptr)
>   at UIKit.UIViewController.set_View (UIKit.UIView value) [0x00040] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:2729
>   at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.CreateViewController (System.Int32 index) [0x00110] in <78d737c765134c5bafa5a0691d6978a8>:0
>   at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.<AttachEvents>m__0 (UIKit.UIPageViewController pageViewController, UIKit.UIViewController referenceViewController) [0x00020] in <78d737c765134c5bafa5a0691d6978a8>:0
>   at UIKit.UIPageViewController+_UIPageViewControllerDataSource.GetPreviousViewController (UIKit.UIPageViewController pageViewController, UIKit.UIViewController referenceViewController) [0x0000d] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/src/build/ios/native/UIKit/UIPageViewController.g.cs:587
>   at at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
>   at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/src/UIKit/UIApplication.cs:79
>   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0003`

Same happens (but earlier) when using the SetCurrentPage method instead of swiping. The error is pretty much the same:

> Foundation.MonoTouchException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x7fe43c018e50; frame = (0 0; 320 470); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x61800182e480>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x7fe43cd75950>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x7fe43ca768a0>.
> Native stack trace:
> 	0   CoreFoundation                      0x0000000113e79d4b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00000001144de21e objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000113ee32b5 +[NSException raise:format:] + 197
> 	3   UIKit                               0x00000001114e845b -[UIView(Internal) _setViewDelegate:] + 231
> 	4   UIKit                               0x00000001115d2a13 +[UIViewController setViewController:forView:] + 41
> 	5   UIKit                               0x00000001115ca292 -[UIViewController setView:] + 522
> 	6   PpushiOS                            0x000000010e16bbfc xamarin_dyn_objc_msgSendSuper + 220
> 	7   ???                                 0x0000000127397f2c 0x0 + 4953046828
> 	8   ???                                 0x000000012b8cd01f 0x0 + 5025615903
> 
>   at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:310
>   at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/runtime/Delegates.generated.cs:126
>   at at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
>   at at (wrapper managed-to-native) ObjCRuntime.Messaging:void_objc_msgSendSuper_IntPtr (intptr,intptr,intptr)
>   at UIKit.UIViewController.set_View (UIKit.UIView value) [0x00040] in /Users/builder/data/lanes/3985/4d858103/source/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:2729
>   at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.CreateViewController (System.Int32 index) [0x00110] in <78d737c765134c5bafa5a0691d6978a8>:0
>   at CarouselView.FormsPlugin.iOS.CarouselViewRenderer.SetCurrentController (System.Int32 position) [0x000b6] in <78d737c765134c5bafa5a0691d6978a8>:0
>   at CarouselView.FormsPlugin.Abstractions.CarouselViewControl.SetCurrentPage (System.Int32 position) [0x0000b] in <09d0125b14a645b5ba406d1198523a1c>:
> [...]

The invoking function looks like this
`if (index > -1 && index < Tabs.Count)
            {
                	Carousel.SetCurrentPage(index);
            		Update();			
            }`
Nothing special

Thx in advance for any help

**Comment by alexrainman** [comment]
Lets see if i can reproduce. Thanks

**Comment by alexrainman** [comment]
Fix in next release.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by asmundur** [comment]
@alexrainman this is happening for me as well, only on phone, but not in simulator

**Comment by ashwinishelke** [comment]
@alexrainman I am also getting same issue when quickly trying to swipe carousel page on iOS device. Please let me know the solution
