### ISSUE TITLE
Implementation Ideas

### ISSUE THREAD

**Issue by Abesoddy** [alexrainman/CarouselView#531]
Hello everyone,

I would like to implement this plugin to have a functioning like this gif : http://www.giphy.com/gifs/Zai4isNPoelJHWeUIg

I don't know if this is the right place to ask for this but I think you know what it is possible to do with the plugin so I would like to know if it seems possible to you?

Thank you in advance for your feedback.

**Comment by alexrainman** [comment]
Sadly, this cannot be supported with the underlying native widgets.

**Comment by Abesoddy** [comment]
Oh bad, I tried to implement it with the Handle_Scrolled : 

`public void Handle_Scrolled(object sender, CarouselView.FormsPlugin.Abstractions.ScrolledEventArgs e)
        {
            if (e.Direction == ScrollDirection.Right)
            {
                Wrapper.Items[_currentIndex].FontSize = Wrapper.Items[_currentIndex].FontSize - (e.NewValue / 10);

                if (_currentIndex < Wrapper.Items.Count - 1)
                    Wrapper.Items[_currentIndex + 1].FontSize = Wrapper.Items[_currentIndex + 1].FontSize + (e.NewValue / 10);
            }
            else if (e.Direction == ScrollDirection.Left)
            {
                Wrapper.Items[_currentIndex].FontSize = Wrapper.Items[_currentIndex].FontSize - (e.NewValue / 10);

                if (_currentIndex > 0)
                    Wrapper.Items[_currentIndex - 1].FontSize = Wrapper.Items[_currentIndex - 1].FontSize + (e.NewValue / 10);
            }
        }`

But when the position does not change, the size of the font changes and it will have to come back by default at the end of the swipe.
