### ISSUE TITLE
Android: Arrow images are different for previous and next image

### ISSUE THREAD

**Issue by AdamBowler** [alexrainman/CarouselView#534]
The next arrow and previous arrow on Android have two different images and I can't find a way to replace the images being used.
This is not an issue on iOS.

![image](https://user-images.githubusercontent.com/17048266/61296613-5dc9fc80-a7d2-11e9-83ac-08c6c7713b45.png)

**Comment by alexrainman** [comment]
I don't see how this is possible. That next arrow is not included in the plugin. I bet you have an arrow in your app named Next.png
