### ISSUE TITLE
[Android] CarouselView not showing when inside modal

### ISSUE THREAD

**Issue by LJungmann** [alexrainman/CarouselView#536]
Whenever I use the CarouselView and push the page in a modal, the CarouselView shows nothing on Android. 

I know this issue is known. But there was still no update to the plugin.

I know I can fix it by doing what was done here: #329 

But I don't want to download the code, build the dll and add the reference -> because I might miss future updates when I do so

Is there a chance you might include this in the next update? Doesn't seem like a big effort

**Comment by alexrainman** [comment]
Running some tests.
