### ISSUE TITLE
CarouselViewRenderer.Init() cause DllNotFoundException

### ISSUE THREAD

**Issue by realzhaorong** [alexrainman/CarouselView#537]
> -- OS Windows 10 Pro 1803
> -- Visual Studio Community 2019 16.2
> -- Xamarin.Forms 4.0 sr1

07-26 13:16:19.556 D/Mono    (22771): Loading reference 6 of CarouselView.FormsPlugin.Android.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
07-26 13:16:19.556 D/Mono    (22771): Assembly Ref addref CarouselView.FormsPlugin.Android[0x559883abb0] -> System[0x5598977850]: 7
07-26 13:16:19.626 D/Mono    (22771): DllImport attempting to load: 'libmono-native.so'.
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.626 D/Mono    (22771): DllImport error loading library './libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.626 D/Mono    (22771): DllImport error loading library './libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.626 D/Mono    (22771): DllImport error loading library './libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.626 D/Mono    (22771): DllImport error loading library '/system/lib64/libmono-native.so': '(null)'.
07-26 13:16:19.626 D/Mono    (22771): DllImport error loading library '/system/lib64/libmono-native.so': '(null)'.
07-26 13:16:19.626 D/Mono    (22771): DllImport error loading library '/system/lib64/libmono-native.so': '(null)'.
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.626 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.636 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.636 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.636 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.636 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.636 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.636 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.636 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.636 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.636 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.636 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.636 W/Mono    (22771): DllImport unable to load library 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.646 D/Mono    (22771): DllImport attempting to load: 'libmono-native.so'.
07-26 13:16:19.646 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.646 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.646 D/Mono    (22771): DllImport error loading library './libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.646 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.646 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.646 D/Mono    (22771): DllImport error loading library './libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.646 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.646 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/./libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.646 D/Mono    (22771): DllImport error loading library './libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.646 D/Mono    (22771): DllImport error loading library '/system/lib64/libmono-native.so': '(null)'.
07-26 13:16:19.646 D/Mono    (22771): DllImport error loading library '/system/lib64/libmono-native.so': '(null)'.
07-26 13:16:19.646 D/Mono    (22771): DllImport error loading library '/system/lib64/libmono-native.so': '(null)'.
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.656 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.656 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.656 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6ffffffe arg 0x1e88
07-26 13:16:19.656 W/linker  (22771): /data/app/com.ultuum.wilmar-1/lib/arm64/libmono-native.so: unused DT entry: type 0x6fffffff arg 0x1
07-26 13:16:19.656 D/Mono    (22771): DllImport error loading library 'libmono-native.so': 'dlopen failed: library "libmonosgen-2.0.so" not found'.
07-26 13:16:19.656 W/Mono    (22771): DllImport unable to load library 'dlopen failed: library "libmonosgen-2.0.so" not found'.
**System.DllNotFoundException:** 'libmono-native.so'

**Comment by alexrainman** [comment]
Can't reproduce this.

**Comment by DottorPagliaccius** [comment]
same problem here, only on a Xiaomi Redmi 3, Android 5.1, works fine elsewhere.
