### ISSUE TITLE
Customising arrows in carousel view

### ISSUE THREAD

**Issue by xhashimks** [alexrainman/CarouselView#539]
I need arrows to be placed in a particular position in the carousel view along with my custom arrow.. is it possible in this? Please help me if it is possible

**Comment by alexrainman** [comment]
Where do you want to place the arrows and what kind of customizations do you want to do?

**Comment by xhashimks** [comment]
@alexrainman I need to place the arrows in the same position itself but need to set padding.. also I need to add my own arrow images in the carousel view...

**Comment by alexrainman** [comment]
Padding how?

**Comment by xhashimks** [comment]
like the left arrow I need to move little bit right and right arrow to little bit left

**Comment by alexrainman** [comment]
Well, that’s a margin.

**Comment by xhashimks** [comment]
ok.. but if i set margin, it affects the complete carousel view margin right? I just need the margin for arrows .. also i need to add my own arrow image.. is that possible? can u pls help?

**Comment by xhashimks** [comment]
@alexrainman Any updates?

**Comment by alexrainman** [comment]
@xhashimks it has taken me more than planned to stabilize all the new functionality on Android. I have some cool tweaks to apply yet to allow full customization and styling on arrows and indicators. As soon as i finish that, the new version will be out. I gues by end of August.

**Comment by alexrainman** [comment]
Fully customizable arrows will be provided in next release.
