### ISSUE TITLE
NullReferenceException, when Content = null

### ISSUE THREAD

**Issue by Tak1wa** [alexrainman/CarouselView#54]
If Content = null is done on the OnDisappearing of the Page on which CarouselViewControl is located with ItemsSource set, "System.NullReferenceException: Object reference not set to an instance of an object." Will occur. (Check with Android)

**Comment by alexrainman** [comment]
Android only issue?

**Comment by Tak1wa** [comment]
Yes, its only Android.

**Comment by alexrainman** [comment]
Next release will have a fix.

**Comment by alexrainman** [comment]
What do you mean with Content = null?

**Comment by alexrainman** [comment]
I cannot reproduce this. If you help, i will release a fix today. Thanks

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
