### ISSUE TITLE
Binding IsVisible Property 

### ISSUE THREAD

**Issue by moniquealtero** [alexrainman/CarouselView#540]
I recently need to use IsVisible property binding it to my view model but it not seems to work correctly. Using the property whithout bindig works just fine.

This is fine:
```
<controls:CarouselViewControl 
IsVisible="false"
Orientation="Horizontal"
ItemsSource="{Binding Promocao.Banners}"
HeightRequest="250">
```

This is not fine:
```
<controls:CarouselViewControl 
IsVisible="{Binding HasMoreThanOneBanner}"
Orientation="Horizontal"
ItemsSource="{Binding Promocao.Banners}"
HeightRequest="250">
```
I tested the property binding with other components and it is working.

Is there any tip?

**Comment by alexrainman** [comment]
Running some tests.

**Comment by alexrainman** [comment]
Implemented and out in the next release.
