### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by developer9969** [alexrainman/CarouselView#541]
Hi.
The author made a fantastic control.
Even though we now have the CollectionView still this is a valid control.However it has not been updated for some many months.

Is it dead?

many thanks for this control

**Comment by alexrainman** [comment]
@developer9969 the answer is not. Expect next release pretty soon.

**Comment by developer9969** [comment]
@alexrainman  fantastic!.
Look I am always grateful when people like you gives something like this to the community.
I am about to start a project when a carousel will play a bit part in many pages.
Could you give us an idea when you are planning the release ?

many thanks

**Comment by rossbc** [comment]
Yes, would love to know, as I need to use .NET standard library 2.0+ and this control does not seem to work due to dependencies that are not compatible.

**Comment by Ruddy2007** [comment]
@alexrainman I think we should reopen this. It would be nice to get a real answer as the last release was last updated 17/01/2018. 

We have been hearing of this new release you have for months if not over a year? If you have one please do let us at it. Or at least make a branch visible to us.

If its help you need its help you will get but there isn't much point of us fixing bugs and creating PRs if you have already fixed it. I would be happy to pick some of these issues up if we keep this control going. 

It has got to the point where I need this control updating so I am going to have to make time to fork it and start working through the bugs I need fixed.
