### ISSUE TITLE
issues with carousel view on vs 2019 for mac and xamarin forms 4.x

### ISSUE THREAD

**Issue by nikhilsingh58** [alexrainman/CarouselView#542]
casousel view is crashing in android in vs 2019.any new version provided for the same ?

**Comment by alexrainman** [comment]
This will be fixed in next release. It will be out in a few days.

**Comment by nikhilsingh58** [comment]
still no update on the next version and the issue is closed. May I know why?

**Comment by nikhilsingh58** [comment]
Any update on new release
