### ISSUE TITLE
Button not displayed properly on Android

### ISSUE THREAD

**Issue by awatertrevi** [alexrainman/CarouselView#545]
When placing an button inside a `DataTemplate` on Android it renders as follows (on iOS it works normal):

![image](https://user-images.githubusercontent.com/16825568/64158291-7badf800-ce38-11e9-882f-05b7be2e050a.png)

**Problems:**
- Text is not centered horizontally
- Padding is gone

I tried adding both properties manually, however without any luck.

Only additional styling that was applied was via the App.xaml:

```
<Style TargetType="Button">
    <Setter Property="BackgroundColor" Value="{StaticResource ColorGreen}" />
    <Setter Property="TextColor" Value="{StaticResource ColorWhite}" />
</Style>
```

_I tested this on multiple Android devices._

**Comment by alexrainman** [comment]
Can you provide a demo?
