### ISSUE TITLE
Carousel View not appearing after switching pages (Android)

### ISSUE THREAD

**Issue by becarioWelldex** [alexrainman/CarouselView#553]
Hi i have an issue with Android, when i switch pages the carousel view control dissapear.

Example: Im in Page 1 and carousel view loads perfectly first time and when refreshing values works fine, but when i switch to Page 2 and i go back to Page 1 the carousel view control doesn't load anymore but on iOS works perfectly.

Here is how a switch pages.
![image](https://user-images.githubusercontent.com/55720896/67520725-065be800-f66f-11e9-9c09-57eedd24c544.png)

and here is how i refresh carouser view values.
![image](https://user-images.githubusercontent.com/55720896/67520782-268ba700-f66f-11e9-9c41-2c3c1b6a6515.png)

**Comment by douni327** [comment]
I have same issue. please check it out.

**Comment by aris515** [comment]
I think this worked for me.
In CarouselView/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs
add  **canSetLayout = true;**
`        protected override void OnAttachedToWindow()
        {
            if (Control == null)
           {
               canSetLayout = true;  //Add this line
                Element_SizeChanged(Element, null);
           }
            base.OnAttachedToWindow();
        }`

**Comment by becarioWelldex** [comment]
> I think this worked for me.
> In CarouselView/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs
> add **canSetLayout = true;**
> ` protected override void OnAttachedToWindow() { if (Control == null) { canSetLayout = true; //Add this line Element_SizeChanged(Element, null); } base.OnAttachedToWindow(); }`
Where is that folder located?

**Comment by aris515** [comment]
you have to download the source-code and modify this file 
[https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs](url)

**Comment by becarioWelldex** [comment]
> you have to download the source-code and modify this file
> https://github.com/alexrainman/CarouselView/blob/master/CarouselView/CarouselView.FormsPlugin.Android/CarouselViewImplementation.cs

Edited. now how can i implement the edited nugget into my project?

**Comment by becarioWelldex** [comment]
@alexrainman any solution?

**Comment by becarioWelldex** [comment]
Update: This bug doesn't happen in version 5.0.2, this bug occur after 5.0.2

**Comment by dfoulk** [comment]
@becarioWelldex copy the CarouselView.FormsPlugin projects into your project and create references to them as follows:

Your Xamarin.Forms (.NET Standard) project => CarouselView.FormsPlugin.Abstractions
Your Android project => CarouselView.FormsPlugin.Android
Your iOS project => CarouselView.FormsPlugin.iOS

Trying to re-publish this project as an update NuGet is a headache. It is dated, thus the resulting package doesn't build as you would expect (your changes will not be present).

Trust me, not worth the headache... Just create the project references locally and move on with your life.

**Comment by fashaikh2021** [comment]
Is this issue only happening with Android 9 ? thanks.

**Comment by InquisitorJax** [comment]
same issue. CarouselView hosted in AppShell tabs. When moving to a different tab, and then back to the tab that has the CarouselView, the content is empty until a resize event takes place.

**Comment by alexrainman** [comment]
Expect a fix in the next release.
