### ISSUE TITLE
Could not load file or assembly System 4.0.0.0 on UWP Universal Windows

### ISSUE THREAD

**Issue by davspan** [alexrainman/CarouselView#56]
I'm getting following Exception when trying to use it in a UWP Universal Windows (Windows 10) project:

{"Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"}

Thanks

**Comment by alexrainman** [comment]
Can you download the demo and try to run it?

**Comment by ozzy1873** [comment]
You may have to load the render assembly:

```
var rendererAssemblies = new[]
                {
                typeof(CarouselViewRenderer).GetTypeInfo().Assembly
                };

                Xamarin.Forms.Forms.Init(e, rendererAssemblies);

               CarouselViewRenderer.Init();
```

**Comment by alexrainman** [comment]
Did this solved the issue?

**Comment by davspan** [comment]
Thank you all for the replies. 

It was apparently a strange issue. I tried to run the demo and I had to install the Build 10240. I also had to uninstall Xamarin Forms Nuget Package and reinstall it again. Finally, it did work. 

Thanks and best regards,

David

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
