### ISSUE TITLE
[Bug] Crash if using CarouselView in ScrollView

### ISSUE THREAD

**Issue by SymxnCreator** [alexrainman/CarouselView#560]
Hello,

If I place the CarouselViewControl inside a ScrollView, the application crashes when the page is initialized.
I get the following exception: System.NullReferenceException: Object reference not set to an instance of an object.

Can you fix that?

**Comment by askfarhan** [comment]
I am also having same issue. Any workaround ?

**Comment by Cyrus-Sushiant** [comment]
I am also having same problem.
How can you fix that?

**Comment by alexrainman** [comment]
Is this Android or iOS?

**Comment by alexrainman** [comment]
I was able to fix the crash but, i am facing another issue, kind of the same it happens with StackLayout.

In Android, as ViewPager has its own ScrollView, wrapping the Carousel into a ScrollView stop it from propagating HeightRequest and it shows up blank.

**Comment by alexrainman** [comment]
InstantiateItem is never called.

**Comment by alexrainman** [comment]
Fixed.

**Comment by Cyrus-Sushiant** [comment]
I have same problem in Android.
I want add a CarouselView in ScrollView. You can observe base code in [this link](https://github.com/danielmonettelli/XF_FoodApp/blob/master/XF_FoodApp/XF_FoodApp/Views/Discover.xaml).

**Comment by Cyrus-Sushiant** [comment]
When does it be release?

**Comment by sparkhead95** [comment]
I have the same problem after updating my old app to use the latest Xamarin Forms.. I don't have my carouselView in a scrollview though...
[crash_log.txt](https://github.com/alexrainman/CarouselView/files/4191043/crash_log.txt)

**Comment by dejanbasic** [comment]
I have the same problem only on Android, when I put CarouselView in ScrollView.
I'm waiting for the new release. Thanks :)

**Comment by Mittchel** [comment]
@alexrainman did you release this already? I'm still experiencing the same problem on Android in latest version 5.2.0

**Comment by SymxnCreator** [comment]
Can you fix it now or not...?

**Comment by yalamandarao** [comment]
Same issue facing in Android.

**Comment by daniels7** [comment]
@alexrainman We have the same problem. Please release the fix you mentioned. We would be very thankful

**Comment by AviadKatani** [comment]
I'm facing the same issue here, though I'm not directly using ScrollView but SfPdfViewer (and it's using ScrollView).
Call Stack:
https://gyazo.com/f4410aa97ddae8d72f81fdb16972fd34

Any solution? Actually I am surprised to see people still commenting here as last Nuget update is from 2018. Any way to update to the last version with fixes?

**Comment by ivanowen** [comment]
Having same issue.. only on Android
