### ISSUE TITLE
Array of ContentPage as ItemsSource

### ISSUE THREAD

**Issue by dalton5** [alexrainman/CarouselView#562]
Hi,

I would like to use content page as ItemSource and not content view but it's not working I have an error. 

Is it possible?

My code is:

` <ContentPage.Content>
        <controls:CarouselViewControl Position="1" ShowIndicators="True" IndicatorsShape="Square" Orientation="Horizontal" InterPageSpacing="10" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <controls:CarouselViewControl.ItemsSource>
                <x:Array Type="{x:Type Page}">
                    <profile:ProfilePage/>
                    <rate:SearchPage/>
                </x:Array>
            </controls:CarouselViewControl.ItemsSource>
        </controls:CarouselViewControl>
    </ContentPage.Content>`

And it seems to crash on line 701 of the file CarouselViewImplementation.cs

So is it possible and if yes how can I perform it?

Thanks,

**Comment by alexrainman** [comment]
ContentPage as source is not supported. Please use ContentView.
