### ISSUE TITLE
[Enhancement] Fire PositionSelected event earlier

### ISSUE THREAD

**Issue by SymxnCreator** [alexrainman/CarouselView#567]
Hi there,

It is currently the case that PositionSelected is changed as soon as you swipe back and forth between the items.
But if you let go while swiping, PositionSelected is only changed as soon as the animation has ended.

Can you fire PositionSelected once released and not when the swipe animation has ended?

**Comment by alexrainman** [comment]
It cannot be done because of limitations of the platform specific controls.
