### ISSUE TITLE
Dependency version conflict

### ISSUE THREAD

**Issue by Symorp** [alexrainman/CarouselView#568]
Hi,
thanks for a great plugin.

I tried to update some nuggets and i got this error:
Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 28.0.0.3
Xamarin.Android.Support.Core.Utils 28.0.0.3 -> Xamarin.Android.Support.Compat (= 28.0.0.3) 
CarouselView.FormsPlugin 5.2.0 -> Xamarin.Android.Support.v4 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).

Can you please help me, what to do now? I think problem is the last version of your plugin is built with Xamarin.Android.Support.v4 25.4.0.2 not 28.0.0.3

Many thanks

**Comment by prashantpurmah** [comment]
Hi, I am currently facing the same issue. Could you let us know if there are any plans of upgrading to the latest Android.Support packages?

**Comment by alexrainman** [comment]
Working to update to AndroidX but having some challenges with Vertical ViewPager.

**Comment by alexrainman** [comment]
It will be solved in the next release.
