### ISSUE TITLE
Arrows appear for only one record in iOS

### ISSUE THREAD

**Issue by Druffl3** [alexrainman/CarouselView#571]
I am using the carousel view to display appointments the user is scheduled for, with the option to cancel it. Upon successful cancelation, I am removing that particular appointment from the collection bound to Carousel ItemSource. 
After repeated cancellations, when the user has only one appointment left, the CarouselView displays both the left and right arrows, instead of any as expected.

When there are two appointments I can notice opacity difference, with the more opaque one indicating the direction where more appointments are available. In this case swiping left will reveal the other appointment.
<img width="350" alt="Screenshot 2020-05-12 at 4 33 30 PM" src="https://user-images.githubusercontent.com/28187687/81677264-6af55d80-946e-11ea-8d68-c24d7d244687.png">

When there's only one appointment remaining:
<img width="351" alt="Screenshot 2020-05-12 at 4 32 05 PM" src="https://user-images.githubusercontent.com/28187687/81677281-6fba1180-946e-11ea-88b8-122cf6b4c2d4.png">

Why can't the arrows simply not appear when there's only one item or one record in the collection?
Like this:
<img width="348" alt="Screenshot 2020-05-12 at 4 37 14 PM" src="https://user-images.githubusercontent.com/28187687/81677881-e7883c00-946e-11ea-9fda-6e1236c37aae.png">

**Comment by alexrainman** [comment]
Trying to reproduce this.
