### ISSUE TITLE
IOS: swipe right

### ISSUE THREAD

**Issue by csk1nner** [alexrainman/CarouselView#577]
Hello there!

Great tool.  I'm running into a problem with IOS (xamarin.forms) and a left swipe (move back).  When the back swipe is used sometimes the page navigates back as opposed to the carousel control.  I've solved the problem by using: https://xamarinhelp.com/xamarin-forms-back-navigation-pitfalls/ - Is there a way to prevent the event from bubbling up except on the first page of the carousel?

**Comment by alexrainman** [comment]
It is a Xamarin.Forms issue so, can't help in that case.
