### ISSUE TITLE
Error linking release version 6.0

### ISSUE THREAD

**Issue by dsancho** [alexrainman/CarouselView#588]
In debug mode it compiles fine. In release mode I get the following error:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(366,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void CarouselView.FormsPlugin.Droid.CarouselViewRenderer::SetIndicators()' in assembly: 'CarouselView.FormsPlugin.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Com.ViewPagerIndicator.CirclePageIndicator::SetOrientation(System.Int32)

These are the packages of the project (I have all updated to latest).

Acr.UserDialogs                                       7.1.0.470                         
CardsView                                             2.6.9                             
CarouselView.FormsPlugin                              6.0.0                             
DLToolkit.Forms.Controls.FlowListView                 2.0.11                            
Flurl                                                 3.0.1                             
Flurl.Http                                            3.0.1                             
Microsoft.AppCenter.Analytics                         4.0.0                             
Microsoft.AppCenter.Crashes                           4.0.0                             
Microsoft.Identity.Client                             4.24.0                            
Newtonsoft.Json                                       12.0.3                            
Rg.Plugins.Popup                                      2.0.0.9                           
Xam.Plugin.Media                                      5.0.1                             
Xamarin.Android.Support.Annotations                   28.0.0.3                          
Xamarin.Android.Support.Collections                   28.0.0.3                          
Xamarin.Android.Support.Compat                        28.0.0.3                          
Xamarin.Android.Support.Core.UI                       28.0.0.3                          
Xamarin.Android.Support.Core.Utils                    28.0.0.3                          
Xamarin.Android.Support.Design                        28.0.0.3                          
Xamarin.Android.Support.Fragment                      28.0.0.3                          
Xamarin.Android.Support.Interpolator                  28.0.0.3                          
Xamarin.Android.Support.Media.Compat                  28.0.0.3                          
Xamarin.Android.Support.v7.MediaRouter                28.0.0.3                          
Xamarin.AndroidX.AppCompat.Resources                  1.1.0.1                           
Xamarin.AndroidX.MediaRouter                          1.2.0.1                           
Xamarin.AndroidX.Palette                              1.0.0.6                           
Xamarin.Essentials                                    1.6.0                             
Xamarin.FFImageLoading.Forms                          2.4.11.982                        
Xamarin.FFImageLoading.Transformations                2.4.11.982                        
Xamarin.Firebase.Ads                                  119.6.0                           
Xamarin.Firebase.Messaging                            121.0.1                           
Xamarin.Forms                                         4.8.0.1821                        
Xamarin.Forms.InputKit                                3.4.4                             
Xamarin.Google.Android.DataTransport.TransportRuntime 2.2.5                             
Xamarin.Google.Dagger                                 2.27.0                            
Xamarin.GooglePlayServices.Ads                        119.6.0                           
Xamarin.GooglePlayServices.Ads.Lite                   119.6.0                           
Xamarin.GooglePlayServices.Base                       117.5.0

**Comment by alexanderzuban** [comment]
Physical cleanup of obj and bin folders  fixed it
