### ISSUE TITLE
NullReferenceException on Android tabbed page

### ISSUE THREAD

**Issue by pumpkinvsi** [alexrainman/CarouselView#59]
I have carousel view on the first tab of tabbed page and if I go to the third tab and return back to the first one I'm geting NullReferenceException with next StackTrace:
  at CarouselView.FormsPlugin.Android.CirclePageIndicator.OnDraw (Android.Graphics.Canvas canvas) [0x0001e] in <4de3a42817be4f81ba276587fa20165c>:0 
  at Android.Views.View.n_OnDraw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x00011] in /Users/builder/data/lanes/3819/5a02b032/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.View.cs:14432 
  at (wrapper dynamic-method) System.Object:7d9fdf5e-5746-408f-a7e4-1a256892adbb (intptr,intptr,intptr)

**Comment by pumpkinvsi** [comment]
In addition:
It happens if I set ShowIndicators="True"
If it's "False" carousel view just doesn't render.

**Comment by alexrainman** [comment]
It will be easy to reproduce. Expect a fix soon. Thanks

**Comment by ignusin** [comment]
In CarouselViewImplementation.cs on line 54 (CarouselViewRenderer#OnElementChanged)

replaced
`
indicator = nativeView.FindViewById<CirclePageIndicator>(Resource.Id.indicator);
`

with

`
indicator = nativeView.FindViewById<CirclePageIndicator>(Resource.Id.indicator);
if (viewPager.Adapter == null)
{
    viewPager.Adapter = new PageAdapter(Element, viewPager);
}
`

This is a "quick" fix, I am not 100% sure if this is correct solution, but works for our project.

**Comment by alexrainman** [comment]
Your fix is the right one :)

Expect an update.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
