### ISSUE TITLE
[Bug?] CarouselViewControl FlowDirection property wont set the flowdirection

### ISSUE THREAD

**Issue by rranlevi** [alexrainman/CarouselView#594]
When adding the CarouselViewControl  and setting the flowdirection to RightToLeft,
it wont set in the UI,
this project is epic but please have a look on this bug.
In iOS it does change the layout but not in the android UI.

**Comment by alexrainman** [comment]
There's not FlowDirection property in this control.

**Comment by rranlevi** [comment]
hello Alex, why not?
in its its working fine

**Comment by rranlevi** [comment]
> There's not FlowDirection property in this control.
Is there another way to effect the FlowDirection of the Control?
