### ISSUE TITLE
[Request] Start loading the next & previous view

### ISSUE THREAD

**Issue by yonkahlon** [alexrainman/CarouselView#595]
The contents of each view in the carousel is on our server - some of the carousel projects (including Xamarin's CarouselView) start loading the next few views even while it is hidden.

Is it already possible to do that? I couldn't find any properties for that. If not, could this be a request for a future release?

**Comment by alexrainman** [comment]
In both Android and iOS, the previous and next view are loaded by default, unless they are WebViews, where you will need to handle pre-loading by yourself.
