### ISSUE TITLE
PositionSelected event returns wrong Position value

### ISSUE THREAD

**Issue by kentfonager** [alexrainman/CarouselView#60]
On both iOS and Android, when the event PositionSelected is triggered, an incorrect value of Position is sometimes returned, when fetching the value of the Position member value.

I had the idea that maybe the event could be triggered "before" the correct value was set in Position, so I tried to debug the value of Position twice in my PositionSelected handler, with a delay in between:

			Debug.WriteLine ("--> Page : " + Position);
			await Task.Delay (50);
			Debug.WriteLine ("--> Page : " + Position);

And when the value is incorrect, it will be correct after the delay, as I suspected.

If I enable page indicators, those are correct, event though the value of Position is "wrong" when the PositionSelected handler is triggered.

**Comment by alexrainman** [comment]
Cannot reproduce this.

**Comment by alexrainman** [comment]
I found this problem in iOS and is now fixed.

**Comment by alexrainman** [comment]
Confirming this also in Android. Releasing a fix today.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
