### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by NelsonSantos** [alexrainman/CarouselView#61]
Hi...

I have changed from SetCurrentPage to Position property, but this not change the page on Android.

I have no time to test on iOS.

This is the new default behavior to change the page position, correct?

Best regards

Nelson

**Comment by alexrainman** [comment]
Yes, changing position in code behind changes the pages, and it works. Tested both Android and iOS.

**Comment by NelsonSantos** [comment]
Hi @alexrainman...

There are something wrong in my environment that make it do not work!

I have changed it from binding to manually set the Position property, but this does not make effect.

I have looked at your code and you does not call anything method to change it when your PositionProperty has changes.

Are there some step to do before or after I change Position property to make it work properly?

Regards...

Nelson

**Comment by alexrainman** [comment]
Did you run the demo?

**Comment by alexrainman** [comment]
Position is a binding. If you use a binding and you change the property in your code behind, the carousel will swipe. If you don't use a binding, you can instead change Carousel position in code behind and it will swipe.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
