### ISSUE TITLE
TapGestureRecognizer doesn't work when added to CarouselViewControl (Android)

### ISSUE THREAD

**Issue by AndriiTsok** [alexrainman/CarouselView#66]
I'm trying to handle Click event on carousel.

I've added GR so I can handle tap event. It works for iOS but doesn't on Android.
Would be great to have ItemSelectedCommand or at least to fix the issue with Gesture Recognizer.

**Comment by alexrainman** [comment]
Fix on next release.

**Comment by alexrainman** [comment]
If i add this to the ContentView, it works:

```
var tapGesture = new TapGestureRecognizer((obj) => Debug.WriteLine("Second View tapped"));
GestureRecognizers.Add(tapGesture);
```

Anyway, i will add the ItemTapped event callback in next release.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by abelgs1987** [comment]
I'm facing the same and even if the tapgesturerecognizer is on its parent, the tap event is not fired.
On iOS works well.
