### ISSUE TITLE
NullReference exception. CirclePageIndicator.OnDraw(Canvas canvas)

### ISSUE THREAD

**Issue by AndriiTsok** [alexrainman/CarouselView#67]
When switching between tabs I'm getting this crash.
Android. AppCompat Activity.

> Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
CarouselView.FormsPlugin.Android.CirclePageIndicator.OnDraw(Canvas canvas)<ff273abb3880455da01c63ed01f48435>:0
Android.Views.View.n_OnDraw_Landroid_graphics_Canvas_(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas)<0b29c59a6a2f48e680b347829cbda543>:0
at (wrapper dynamic-method) System.Object:33ac3283-52c3-43a4-ae9c-8042fe0355ed (intptr,intptr,intptr)
md5fa3be16b83ce3acd3be83265686c14de.CirclePageIndicator.n_onDraw(Native Method)
md5fa3be16b83ce3acd3be83265686c14de.CirclePageIndicator.onDraw()CirclePageIndicator.java:52
android.view.View.draw()View.java:16186
android.view.View.updateDisplayListIfDirty()View.java:15109
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.updateDisplayListIfDirty()View.java:15104
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.draw()View.java:16189
android.view.View.updateDisplayListIfDirty()View.java:15109
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.updateDisplayListIfDirty()View.java:15104
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.draw()View.java:16189
android.widget.FrameLayout.draw()FrameLayout.java:592
android.widget.ScrollView.draw()ScrollView.java:2486
md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.n_draw(Native Method)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.draw()ScrollViewRenderer.java:51
android.view.View.updateDisplayListIfDirty()View.java:15109
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.draw()View.java:16189
android.view.View.updateDisplayListIfDirty()View.java:15109
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.updateDisplayListIfDirty()View.java:15104
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.draw()View.java:16189
android.support.v4.view.ViewPager.draw()ViewPager.java:2415
android.view.View.updateDisplayListIfDirty()View.java:15109
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.updateDisplayListIfDirty()View.java:15104
android.view.View.getDisplayList()View.java:15132
android.view.View.draw()View.java:15907
android.view.ViewGroup.drawChild()ViewGroup.java:3703
android.view.ViewGroup.dispatchDraw()ViewGroup.java:3497
android.view.View.draw()View.java:16189
android.widget.FrameLayout.draw()FrameLayout.java:592
com.android.internal.policy.impl.PhoneWindow$DecorView.draw()PhoneWindow.java:2923
android.view.View.updateDisplayListIfDirty()View.java:15109
android.view.View.getDisplayList()View.java:15132
android.view.ThreadedRenderer.updateViewTreeDisplayList()ThreadedRenderer.java:275
android.view.ThreadedRenderer.updateRootDisplayList()ThreadedRenderer.java:281
android.view.ThreadedRenderer.draw()ThreadedRenderer.java:320
android.view.ViewRootImpl.draw()ViewRootImpl.java:2751
android.view.ViewRootImpl.performDraw()ViewRootImpl.java:2584
android.view.ViewRootImpl.performTraversals()ViewRootImpl.java:2176
android.view.ViewRootImpl.doTraversal()ViewRootImpl.java:1191
android.view.ViewRootImpl$TraversalRunnable.run()ViewRootImpl.java:6642
android.view.Choreographer$CallbackRecord.run()Choreographer.java:777
android.view.Choreographer.doCallbacks()Choreographer.java:590
android.view.Choreographer.doFrame()Choreographer.java:560
android.view.Choreographer$FrameDisplayEventReceiver.run()Choreographer.java:763
android.os.Handler.handleCallback()Handler.java:739
android.os.Handler.dispatchMessage()Handler.java:95
android.os.Looper.loop()Looper.java:145
android.app.ActivityThread.main()ActivityThread.java:5938
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke()Method.java:372
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1400
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1195

**Comment by alexrainman** [comment]
Yes, it will be fixed in next release.

**Comment by AndriiTsok** [comment]
That is awesome! Thank you.
When are you going to release it ? Our team has release tomorrow and this issue became critical for us :) 

Maybe I could somehow help you with this one ?

**Comment by alexrainman** [comment]
Later today.

**Comment by AndriiTsok** [comment]
Hello @alexrainman sorry for bothering, but any updates on the fix ?

**Comment by AndriiTsok** [comment]
@alexrainman  I'm going to test our app against the square indicators.
Any updates on the fix ? Also I'm going to find some time tomorrow to review CirclePageIndicator.OnDraw for possible Null reference Exs.

**Comment by alexrainman** [comment]
I know whats the fix for it but havent time to do it. Will try tonight. Thanks

**Comment by AndriiTsok** [comment]
The fix is in #70  :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
