### ISSUE TITLE
Fatal exception ToolbarItems secondary in release mode

### ISSUE THREAD

**Issue by ndesorden** [alexrainman/CarouselView#68]
Hi,
in xamarin forms 2.3.3.180 i've installed your great plugin and carousel view works ok.

But, i've a master detail page with secondary items toolbar. When i click in icon to display secondary menu, app crash only in RELEASE mode. Debug mode is ok.

`Time	Device Name	Type	PID	Tag	Message
02-22 09:29:55.622	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	4350	AndroidRuntime	Shutting down VM
02-22 09:29:57.459	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	854	ActivityManager	Process es.test.myapp (pid 4350) has died
02-22 09:29:57.459	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	854	ActivityManager	Process es.test.myapp (pid 4350) has died
02-22 09:29:57.459	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	ActivityManager	Service crashed 2 times, stopping: ServiceRecord{bda0a73 u0 es.test.myapp/md563bb5d7cd114ceda82ec85fb57ce3637.PushNotificationService}
02-22 09:29:57.453	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	854	WindowState	WIN DEATH: Window{6a2d984 u0 es.test.myapp/md5ff3bebde84a0e0a6dd4318ee9bc2d832.MainActivity}
02-22 09:29:57.453	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	854	GraphicsStats	Buffer count: 3
02-22 09:29:57.453	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	854	WindowState	WIN DEATH: Window{6a2d984 u0 es.test.myapp/md5ff3bebde84a0e0a6dd4318ee9bc2d832.MainActivity}
02-22 09:29:57.453	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	854	GraphicsStats	Buffer count: 3
02-22 09:29:57.451	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	854	JavaBinder	!!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
02-22 09:29:57.451	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	854	JavaBinder	!!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
02-22 09:29:57.451	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	854	JavaBinder	!!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
02-22 09:29:57.451	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	InputMethodManagerService	Got RemoteException sending setActive(false) notification to pid 4350 uid 10081
02-22 09:29:57.451	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	854	JavaBinder	!!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
02-22 09:29:57.451	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	InputMethodManagerService	Got RemoteException sending setActive(false) notification to pid 4350 uid 10081
02-22 09:29:57.448	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	854	OpenGLRenderer	endAllStagingAnimators on 0xda6c2e00 (RippleDrawable) with handle 0xd9abfc60
02-22 09:29:57.448	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	854	OpenGLRenderer	endAllStagingAnimators on 0xda6c2e00 (RippleDrawable) with handle 0xd9abfc60
02-22 09:29:57.443	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	854	Surface	getSlotFromBufferLocked: unknown buffer: 0xf2cf68a0
02-22 09:29:57.443	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	854	Surface	getSlotFromBufferLocked: unknown buffer: 0xf2cf68a0
02-22 09:29:57.418	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	4350	Process	Sending signal. PID: 4350 SIG: 9
02-22 09:29:57.418	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	4350	Process	Sending signal. PID: 4350 SIG: 9
02-22 09:29:56.280	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	1114	EGL_emulation	eglSurfaceAttrib not implemented
02-22 09:29:56.280	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	1114	OpenGLRenderer	Failed to set EGL_SWAP_BEHAVIOR on surface 0xe8e2eec0, error=EGL_SUCCESS
02-22 09:29:56.280	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	1114	OpenGLRenderer	Failed to set EGL_SWAP_BEHAVIOR on surface 0xe8e2eec0, error=EGL_SUCCESS
02-22 09:29:56.280	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	1114	EGL_emulation	eglSurfaceAttrib not implemented
02-22 09:29:56.208	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	ActivityManager	Activity pause timeout for ActivityRecord{163cbc1 u0 es.test.myapp/md5ff3bebde84a0e0a6dd4318ee9bc2d832.MainActivity t1671 f}
02-22 09:29:56.208	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	ActivityManager	Activity pause timeout for ActivityRecord{163cbc1 u0 es.test.myapp/md5ff3bebde84a0e0a6dd4318ee9bc2d832.MainActivity t1671 f}
02-22 09:29:55.765	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	EGL_emulation	eglSurfaceAttrib not implemented
02-22 09:29:55.765	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	OpenGLRenderer	Failed to set EGL_SWAP_BEHAVIOR on surface 0xd7aed180, error=EGL_SUCCESS
02-22 09:29:55.765	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	OpenGLRenderer	Failed to set EGL_SWAP_BEHAVIOR on surface 0xd7aed180, error=EGL_SUCCESS
02-22 09:29:55.765	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	EGL_emulation	eglSurfaceAttrib not implemented
02-22 09:29:55.734	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	854	OpenGLRenderer	Initialized EGL, version 1.4
02-22 09:29:55.734	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Info	854	OpenGLRenderer	Initialized EGL, version 1.4
02-22 09:29:55.649	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	834	EGL_emulation	tid 834: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
02-22 09:29:55.649	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	834	EGL_emulation	tid 834: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
02-22 09:29:55.631	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	854		HostConnection::get() New Host Connection established 0xda4f8010, tid 1223
02-22 09:29:55.631	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	854		HostConnection::get() New Host Connection established 0xda4f8010, tid 1223
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.os.Handler.dispatchMessage(Handler.java:95)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime	Process: es.test.myapp, PID: 4350
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.ListMenuItemView.initialize(ListMenuItemView.java:104)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.MenuPopupHelper$MenuAdapter.getView(MenuPopupHelper.java:381)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.os.Looper.loop(Looper.java:148)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.ListMenuItemView.initialize(ListMenuItemView.java:104)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.MenuPopupHelper.measureContentWidth(MenuPopupHelper.java:223)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:785)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime	Process: es.test.myapp, PID: 4350
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.ListMenuItemView.setTitle(ListMenuItemView.java:117)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.os.Looper.loop(Looper.java:148)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at java.lang.reflect.Method.invoke(Native Method)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.ListMenuItemView.setTitle(ListMenuItemView.java:117)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:785)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:157)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.MenuPopupHelper.measureContentWidth(MenuPopupHelper.java:223)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime	FATAL EXCEPTION: main
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime	java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.os.Handler.handleCallback(Handler.java:739)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.app.ActivityThread.main(ActivityThread.java:5417)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at java.lang.reflect.Method.invoke(Native Method)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.app.ActivityThread.main(ActivityThread.java:5417)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime	FATAL EXCEPTION: main
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime	java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.os.Handler.dispatchMessage(Handler.java:95)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	ActivityManager	  Force finishing activity es.test.myapp/md5ff3bebde84a0e0a6dd4318ee9bc2d832.MainActivity
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.MenuPopupHelper$MenuAdapter.getView(MenuPopupHelper.java:381)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:157)
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Warning	854	ActivityManager	  Force finishing activity es.test.myapp/md5ff3bebde84a0e0a6dd4318ee9bc2d832.MainActivity
02-22 09:29:55.625	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Error	4350	AndroidRuntime		at android.os.Handler.handleCallback(Handler.java:739)
02-22 09:29:55.622	Genymotion Google Nexus 5 - 6.0.0 - API 23 - 1080x1920	Debug	4350	AndroidRuntime	Shutting down VM
`

Only tested in Android

**Comment by alexrainman** [comment]
If you take a look at the stacktrace, there's nothing there related to the plugin.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
