### ISSUE TITLE
Position property is not changing to the respective item view always starts with the first item view

### ISSUE THREAD

**Issue by gsssubramanyam** [alexrainman/CarouselView#69]
I wanted to to change the CarouselView starting item position. I am trying using the below property as mentioned in documentation
(viewObj).Position = 2;
After updating the position also it is starting with the first item only always.

**Comment by alexrainman** [comment]
Are you using Xaml or code? Because this works.

```xml
<controls:CarouselViewControl x:Name="myCarousel"
                                  HorizontalOptions="FillAndExpand"
                                  VerticalOptions="FillAndExpand"
                                  AnimateTransition="true"
                                  IndicatorsShape="Circle"
                                  InterPageSpacing="10"
                                  InterPageSpacingColor="Red"
                                  Orientation="Horizontal"
                                  Position="1"
                                  ShowIndicators="true"/>
```

**Comment by alexrainman** [comment]
Releasing an update with some minor fixes for Position changes.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
