### ISSUE TITLE
UWP: All content is rebuilt when vertical size is changed

### ISSUE THREAD

**Issue by dominik-weber** [alexrainman/CarouselView#7]
When I resize the Demo.UWP app window all pages inside the carousel view are rebuilt. Also the indicators at the bottom are added again and accumulate on every resize.

![image](https://cloud.githubusercontent.com/assets/1771927/16848509/6616330a-49f6-11e6-963e-f820001e37d6.png)

**Comment by alexrainman** [comment]
Ooops let me fix that :)

**Comment by alexrainman** [comment]
I am also working on a fix for the widgets height issue :)

**Comment by dominik-weber** [comment]
Thank you for the quick response! Btw. if I initialize the control with an empty itemssource I get this exception:

Value does not fall within the expected range.

   at Windows.UI.Xaml.Controls.Primitives.Selector.put_SelectedIndex(Int32 value)
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.<OnElementPropertyChanged>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()


If I don't set the ItemsSource property at all I get a Null Reference exception:

   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.<OnElementPropertyChanged>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by alexrainman** [comment]
Well, you suposed to pass something in the ItemsSource or you want a CarouselView with no views?

**Comment by dominik-weber** [comment]
I wanted to start with en empty CarouselView and add pages later on. What I'm trying to create is a hierarchical menu that starts empty and once it is initialized (asynchronously) the first page is added. When the user selects an item the sub menu page is selected and navigated/scrolled to and so on.

**Comment by alexrainman** [comment]
Let my try to add that functionality, the thing is the FlipView need a selected index

**Comment by alexrainman** [comment]
By the way, thanks for using my control :)

**Comment by dominik-weber** [comment]
well, thank you for creating it! ;)

**Comment by alexrainman** [comment]
What about the same functionality on Android and iOS?

**Comment by dominik-weber** [comment]
I have not tested on android and ios yet.

**Comment by alexrainman** [comment]
Cannot debug UWP app. Do you have any advice? I know what to change in the plugin to fix your problem but somehow, debug mode is not working.

**Comment by alexrainman** [comment]
Your fix is almost ready!

**Comment by alexrainman** [comment]
You solution for this is completed. Unfortunately, i have to re-render each page again when screen is resized, but it's transparent for end user. I was able to keep the carousel position and, call rendering when screen resize is completed only.

I have to add one more detail for HeighRequest issue and i will ship version 2 :)

**Comment by dominik-weber** [comment]
works, thanks! :+1:

**Comment by alexrainman** [comment]
Some changes are on the way like observable collection changed event to handle remove/add pages, slide to page changing position, a fix to allow indicators have transparent background. So, the methods to add/remove pages and set position will be gone soon.

**Comment by dominik-weber** [comment]
Sounds great ;) One thing I've noticed is when I resize the window the content now seems to be resized delayed. Is there a reason for this?

**Comment by alexrainman** [comment]
Its because to avoid multiple resizing, i have to put a timer and wait for the last resized event to trigger. I can lower the timer for next release.

**Comment by alexrainman** [comment]
SizeChanged is called multiple times, weird :(

**Comment by dominik-weber** [comment]
Ah, I see. What I'm not quite getting is why you have to rebuild the content every time the size changes. Wouldn't it be enough to apply/layout the new size?

**Comment by alexrainman** [comment]
I tried that but it didnt work. I still trying.

**Comment by alexrainman** [comment]
My experience with UWP is limited to this plugin, so i am doing my best to make it work in the right way. The only thing left is to avoid needing to rebuild the whole thing on resize.

**Comment by alexrainman** [comment]
I am really having hard times making this to work in the right way. SizeChanged is called multiple times and Timer is not working as expected :(

**Comment by alexrainman** [comment]
I am not UWP expert. Actually, this plugin is the very first thing i do, so you are free to clone the repo and try to achieve this:

- Avoid to rebuild multiple times when ResizeChanged is called (maybe resize the each page instead of re-generating them)

- Use UWP TemplateSelector that will return what Xamarin.Forms template selector will return given the position.

If you take a look at my code, i had to generate all the pages and add them to an array of FrameworkElement and use the array as source of FlipView. That's not the case of iOS and Android where only 3 pages are rendered at a time as maximum. I use each platform widget virtualization in those cases.

**Comment by alexrainman** [comment]
I think i found the way of not rendering all the views and use a DataTemplate instead, so it will get better in the next version where i will be releasing vertical swiping/scrolling :)

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
