### ISSUE TITLE
[Android] Invalid cast exception on ItemTemplate instanciation

### ISSUE THREAD

**Issue by sudrahn** [alexrainman/CarouselView#72]
Hi,

I have a simple ItemTemplate like this:
`
public class AItemTemplate: ViewCell
{
  public AItemTemplate()
  {
			var gridLayout = new Grid() {
				RowDefinitions = {
					new RowDefinition() { Height = new GridLength(1, GridUnitType.Star) },
					new RowDefinition() { Height = new GridLength(1, GridUnitType.Star) }
				},
				ColumnDefinitions = {
					new ColumnDefinition() { Width = new GridLength(1, GridUnitType.Star) },
					new ColumnDefinition() { Width = new GridLength(2, GridUnitType.Star) },
				}
			};
			var sequenceLabel = new Label() { };
			sequenceLabel.SetBinding(Label.TextProperty, nameof(AViewModel.StringVal));
			gridLayout.Children.Add(sequenceLabel, 0, 0);
			View = gridLayout;
			[snip]`

**Comment by alexrainman** [comment]
CarouselView doesnt support ViewCell. Use ContentView instead. Thanks

**Comment by sudrahn** [comment]
Sorry, this was my first comment in github, so I had some problems with formatting the code.
Well, seems that I have found a way to get ViewCell going :)
I'll try further. Would you be interested in results?

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
