### ISSUE TITLE
Change position programmatically

### ISSUE THREAD

**Issue by willowvil** [alexrainman/CarouselView#74]
Hi,

I´m not able to change selected view in code behind. Here is the code:

```
var carousel = new CarouselViewControl()
{
Orientation = Orientation.Horizontal,
ItemsSource = myDataSource,
ItemTemplate = new carouselTemplate(),
Position = 0,
InterPageSpacing = 0,
ShowIndicators = true
}

private void myFunction()
{
carousel.Position = 1;
}
```

Thanks!

**Comment by alexrainman** [comment]
Take a look at the demo. Changing position works. You may be missing something.

**Comment by willowvil** [comment]
I copied the code from your example, but as I said, "carousel.Position = 1" does not work. However, I have installed version 2.9.0 and with "carousel.SetCurrentPage(index);" it works correctly.

Thank you.

**Comment by alexrainman** [comment]
This works for me. Please take a look at the demo.

**Comment by alexrainman** [comment]
Releasing an update with some minor fix for Position changes.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by andybeaulieu** [comment]
In my case, I found that if I set the carousel.ItemsSource _first_ and then set Position, then the Indicators would be incorrect and the order of items would be messed up.

But, if I _first_ set Position and then set ItemsSource, then it was OK. 

This is with v.4.2.6.

**Comment by alexrainman** [comment]
Which platform?

**Comment by alexrainman** [comment]
This works for me without any issue.
