### ISSUE TITLE
Dynamically Changing Carousel Doesn't Load Threads

### ISSUE THREAD

**Issue by ahoefling** [alexrainman/CarouselView#75]
**Problem**
I am using the CarouselView as an Image Carousel with a camera integration library that allows the users to take photos and dynamically add it to the Carousel. I have noticed cached threading issues when I call `InsertPage` where it will show duplicate items when all are unique. This error sometimes goes away when I dynamically add n+1 items. See example below for details of problem

**Example Test Case**
1. Add first carousel item (no problems)
2. Add second carousel item (n+1 is a duplicate of n)
3. Add third Carousel item (n, n+1 are correct and n+2 is a duplicate of n+1)
4. Add fourth Carousel item (n, n+1, n+2 are correct and n+3 is a duplicate of n+2)
...
pattern continues for all items added

**Workaround**
A work around to this problem is to re-build the ItemsSource every time I want to add an item `InsertPage` to the ItemsSource. What I will do is remove all items from the CarouselView via `RemovePage` and then re-build the ItemsSrouce using `InsertPage`. This change has appeared to resolve the issue.

**Comment by ahoefling** [comment]
The proposed workaround I mentioned in my original comment did not work as well as I hoped. The simple solution was to just set the `ItemsSource` every time I wanted to do an update. The Concept is still the same but the method I used is different. Below is the code that solved my problem in the code behind `.xaml.cs`:

`CarouselView.ItemsSource = photos;`

**Comment by alexrainman** [comment]
I am sure there's something wrong with your code. InsertPage should work without duplicates.

**Comment by alexrainman** [comment]
Please provide a reproduction demo.

**Comment by ahoefling** [comment]
I don't know if I went into enough detail in my initial posts but `InsertPage` does work fine. The problem is when I call `InsertPage` and there is a background Task doing some work to load the content. While I have the object added to the CarouselView the View is not properly updating after the background Task has completed.

The thing that I found very interesting is even iterating through my List and calling `InsertPage` on each item I still ran into the same concurrency issue. As stated above if I apply the entire list directly to `CarouselView.ItemsSource` it all appeared to work without issue.

Since I can't share the code from my project, I'll put together a demo reproduction project to help us figure out exactly where the problem is and how we can resolve it.

**Comment by alexrainman** [comment]
Please, share demo project. Thanks

**Comment by alexrainman** [comment]
Releasing an update with some minor fixes for Position changes. Once you provide your demo and a fix is found, i will release another update.

**Comment by ahoefling** [comment]
@alexrainman I have a few deadlines I am trying to hit with my current project. I am hoping to get you a demo project by the weekend. I apologize for the delay on this and hope it isn't that big of a deal.

**Comment by ahoefling** [comment]
[CarouselView-DuplicateDemo-2017-03-22_20.44.59.mp4.zip](https://github.com/alexrainman/CarouselView/files/863309/CarouselView-DuplicateDemo-2017-03-22_20.44.59.mp4.zip)
Example video with demo

**Comment by ahoefling** [comment]
@alexrainman I have created the example project as a fork of this repo to make it easy to resolve references, debug and fix. The example repository can be found at https://github.com/surgeforward/CarouselView .

After further investigation the duplicate appears to be more of a caching issue when you call `InsertPage(obj, 0)`. I can confirm in my other project that this is happening when when we call `InsertPage(obj, 1)` where `Position = 1`. 

1. Click `Add Button` - which will add a new slide with a random number from
2. The slide count updates via the circle indicators but the content remains the same
3. Slide the Carousel 1 item to the right or left and back to the original. The content will remain duplicated
4. Slide the Carousel 2 items to the right or left and then back to the original. The content will be updated to it's correct value.

The steps above are documented in the video I added to this issue. 

Thanks!!

**Comment by alexrainman** [comment]
Hi there. Found a fix for your issue. Android ViewPager is tricky and its not designed to work as i made it work :)

Releasing an update after running some tests in UWP.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
