### ISSUE TITLE
Call to DataTemplateSelector.OnSelectTemplate happend multiple times on Android

### ISSUE THREAD

**Issue by rinoandrejohnsen** [alexrainman/CarouselView#78]
When using a CarouselView cross platform the behavior is different. When using it for UWP the expected behavior occurs when on slides programmatically(add Page, Position++, remove previous page). The DataTemplateSelector.OnSelectTemplate is only called once.

On Android this seems to be different. It works as expected up to "add Page, Position++", but when removing a page DataTemplateSelector.OnSelectTemplate is called a second time and then one ends with two Pages in the CarouselView.

**Comment by alexrainman** [comment]
What do you mean you end up with two pages? In Android, SelectTemplate is called multiple times because Android ViewPager renders the current page, the previous one and the next one.

**Comment by rinoandrejohnsen** [comment]
Say you want to show one page at time. When going from the first page to the second page, one adds a new page by calling "CarouselViewControl.InsertPage();". Then one calls "CarouselViewControl.Position++" to change datatemplate and DataTemplateSelector.OnSelectTemplate is called (as one expect). After those to steps one call "CarouselViewControl.RemovePage(0)" to remove the previous page. This is where the behavior is different. For UWP, nothing happens (as one expect), but for Android the DataTemplateSelector.OnSelectTemplate method is called once again when removing the previous page.

**Comment by alexrainman** [comment]
Can you share a demo project?

**Comment by rinoandrejohnsen** [comment]
I can put one to together later this evening where the issue is illustrated.

**Comment by alexrainman** [comment]
I think i know what are you missing.

To move forward:

```
async void OnNext (object sender, TappedEventArgs e) {
	await Carousel.InsertPage(obj); // parameter is the new item to be used as binding context for the second view
	await Carousel.RemovePage(0);
}
```
To move back:

```
async void OnPrevious (object sender, TappedEventArgs e) {
	var pages = new List<int>() { 1, pages[0] }; // inserting one item on position 0 of ItemsSource
	Carousel.Position = 1;
	Carousel.ItemsSource = pages;
	await Task.Delay(100); // YOU MAY BE MISSING THIS
	await Carousel.RemovePage(1);
}
```

**Comment by rinoandrejohnsen** [comment]
Sadly - no. I wish it was that simple, but give me a couple of hours and I will have a demo project for you.

**Comment by alexrainman** [comment]
I figure it out. The plugin has changed over the time and rendering one page at the time doesn't behave the same way.

ItemsSource is a List<int> with 0 as first value:

```
public async void OnPrev(object sender, TappedEventArgs e)
{
	if (_vm.ItemsSource[0] > 0)
	{
		_vm.ItemsSource = new List<int>() { _vm.ItemsSource[0] - 1, _vm.ItemsSource[0] };
		await Task.Delay(100);
		myCarousel.AnimateTransition = false;
		myCarousel.Position = 1;
		myCarousel.AnimateTransition = true;
		await myCarousel.RemovePage(1);
	}
}

public async void OnNext(object sender, TappedEventArgs e)
{
	if (_vm.ItemsSource[0] < 4)
	{
		await myCarousel.InsertPage(_vm.ItemsSource[0] + 1);
		await myCarousel.RemovePage(0);
	}
}
```

Tested in all platforms.

**Comment by rinoandrejohnsen** [comment]
Check this out:
https://github.com/rinoandrejohnsen/CarouselViewControlTestApp2

Please set a breakpoint inside the pageselector class and see that it is called twice on Android, but not on UWP. Have not testet for iOS

**Comment by alexrainman** [comment]
Pls, try the code i just shared. Its the only way to have only one page at the time.

**Comment by rinoandrejohnsen** [comment]
That works, but with no animation between the two.

**Comment by alexrainman** [comment]
No no, it works with Animation. I am releasing an update later that will include a demo here in the repo.

**Comment by alexrainman** [comment]
See that onPrev includes await Task.Delay(100); just for that, to keep animation going back. Going forward works by default.

**Comment by rinoandrejohnsen** [comment]
Download the demo project and see what I am talking about. There is clearly a bug there.

**Comment by alexrainman** [comment]
Definitely you are not looking at the code i just shared. If you change the position programmatically SelectTemplate will be called twice. Do this:

```
public async void OnNext(object sender, TappedEventArgs e)
{
	if (_vm.ItemsSource[0] < 4)
	{
		await myCarousel.InsertPage(_vm.ItemsSource[0] + 1);
		await myCarousel.RemovePage(0);
	}
}
```

Then to move back:

```
public async void OnPrev(object sender, TappedEventArgs e)
{
	if (_vm.ItemsSource[0] > 0)
	{
		_vm.ItemsSource = new List<int>() { _vm.ItemsSource[0] - 1, _vm.ItemsSource[0] };
		await Task.Delay(100);
		myCarousel.AnimateTransition = false;
		myCarousel.Position = 1;
		myCarousel.AnimateTransition = true;
		await myCarousel.RemovePage(1);
	}
}
```

**Comment by rinoandrejohnsen** [comment]
Sir, there is no way around it. On Android it is called twice and not on UWP. The proof is there in the demo. UWP will have one page in the carousel and Android will have two pages. This is not the expected behavior when one ask for one.

**Comment by alexrainman** [comment]
The demo is wrong. You dont need all the code you are adding there to change next page:

```
private async Task NextPage()
        {
            var pageIndex = Convert.ToInt32(this.carouselViewControl.ItemsSource[0]);
            await this.carouselViewControl.InsertPage(pageIndex + 1);
            this.carouselViewControl.Position++;  // NO NEEDED, THIS CAUSE THE PROBLEM
            await Task.Delay(100); // NO NEEDED
            await this.carouselViewControl.RemovePage(0);
        }
```

I just updated the README.

**Comment by alexrainman** [comment]
Android and UWP native widgets behaves completely different. Use what i am providing and it will work. Thanks

**Comment by rinoandrejohnsen** [comment]
var pageIndex = Convert.ToInt32(this.carouselViewControl.ItemsSource[0]);
await this.carouselViewControl.InsertPage(pageIndex + 1);
await this.carouselViewControl.RemovePage(0);

By using that alone, there are no animations between the views.

**Comment by alexrainman** [comment]
I get animations between the views with just those lines. Try keeping await Task.Delay(100);

**Comment by rinoandrejohnsen** [comment]
No animation for me with a Task.Delay of either 100 or 1000 milliseconds. I have the latest version from Nuget

**Comment by alexrainman** [comment]
I have animations in your own demo just commenting this line: this.carouselViewControl.Position++;

**Comment by rinoandrejohnsen** [comment]
iOS maybe? I don't have it on either UWP or Android in my demo when testing

**Comment by alexrainman** [comment]
Android, iOS and UWP. All them. Take a look at this video: https://drive.google.com/file/d/0B6hZDQudMRBUZWJpVC1qbDdFVEU/view?usp=sharing

**Comment by rinoandrejohnsen** [comment]
I only get that with Position++ on Android and UWP. For me right now, there is only a swap in page, seeing one and then another with no moments or transitions what so ever. However, I run it on a device and not an emulator. My device is running on Android 6 with the latest from Xamarin.

**Comment by rinoandrejohnsen** [comment]
Just tested on Android, I get the animation there by just commenting this line: this.carouselViewControl.Position++; in the demo project. This does not work for UWP for me. When testing on Android, this did not fix the issue that on Android the template method is called twice and there is two views there. I can bet that in the video you sent me you will see only one mark for one page, but if you try to grad to the left, the right side will be showing you a similar green page with the same number. I guess there is a callback on the Android implementation that gets called twice.

If you can't fix it would you accept a pull request from me with a fix?

**Comment by alexrainman** [comment]
Actually you are not seeing two pages. What you see is the ViewPager trying to render another page with the same bindingContext and that's actually a problem i fixed before. Swiping should be disabled.

**Comment by rinoandrejohnsen** [comment]
How can one disable swiping?

**Comment by alexrainman** [comment]
Done. Releasing a fix for Android and iOS. UWP works by default.

**Comment by rinoandrejohnsen** [comment]
Thx, looking forward to try it out!

**Comment by savandavande** [comment]
Hi,
I am facing the same issue with latest version (3.1.1) also. For android and iOS ... "OnSelectTemplate" calls multiple times

**Comment by alexrainman** [comment]
Are you rendering one page at the time?

**Comment by savandavande** [comment]
[Xam.CarouselTest.zip](https://github.com/alexrainman/CarouselView/files/914468/Xam.CarouselTest.zip)

Here is my code. I want to bind same ViewModel to all my pages. Which is my baseView Model. So I cant use "object item" of "OnSelectTemplate" to find out the which template I have to return. 

So I really need this fix. Please help

**Comment by alexrainman** [comment]
OnSelectTemplate called multiple times in Android is completely normal unless you only one element in your collection. Android ViewPager adapter renders the element before and the one after the current element visible, so at least you will get 3 OnSelectTemplate calls.

**Comment by savandavande** [comment]
Yes. you are correct. Thanks for replying. I implemented a workaround. 

By the way, nice control....

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
