### ISSUE TITLE
Exception thrown when coming from background (Android)

### ISSUE THREAD

**Issue by bernadevteam** [alexrainman/CarouselView#79]
Hi,

I've implemented the control and it works beautifully. However, when the app comes back from the background this exception is being thrown:

System.InvalidCastException: Specified cast is not valid.
CarouselView.FormsPlugin.Android.CarouselViewRenderer+PageAdapter.RestoreState (IParcelable state, Java.Lang.ClassLoader loader) <0x999b02a8 + 0x0009c> in <filename unknown>:0 
[log.txt](https://github.com/alexrainman/CarouselView/files/862585/log.txt)

**Comment by alexrainman** [comment]
Yeah, i know what its. Releasing an update.

**Comment by bernadevteam** [comment]
Awesome. Thanks!

**Comment by alexrainman** [comment]
By the way, how you handled to call RestoreState?

**Comment by alexrainman** [comment]
I cannot reproduce it.

**Comment by alexrainman** [comment]
I guess you are doing something in MainActivity but, what?

**Comment by bernadevteam** [comment]
You have to open the app, then start using others and wait for sometime. After several minutes, try to access it, and then you'll get the exception.

**Comment by alexrainman** [comment]
OK, lets see if can reproduce it.

**Comment by alexrainman** [comment]
Anyway, i dont if i can fix it. If not, i will remove the RestoreState code.

**Comment by alexrainman** [comment]
I cannot reproduce it :(

**Comment by bernadevteam** [comment]
Then try accessing after an hour or two.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
