### ISSUE TITLE
NullRefException on Android Only

### ISSUE THREAD

**Issue by alexDairay** [alexrainman/CarouselView#8]
Hi,

when I use this control it works perfectly on iOS but on Android i get this : 

`System.NullReferenceException: Object reference not set to an instance of an object.
  at CarouselView.FormsPlugin.Android.CirclePageIndicator.MeasureLong (Int32 measureSpec) [0x00038] in <filename unknown>:0
  at CarouselView.FormsPlugin.Android.CirclePageIndicator.OnMeasure (Int32 widthMeasureSpec, Int32 heightMeasureSpec) [0x0000b] in <filename unknown>:0
  at Android.Views.View.n_OnMeasure_II (IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec) [0x00009] in <filename unknown>:0
  at at (wrapper dynamic-method) System.Object:8bb25a89-3729-4ef0-a3dc-9dc45deab218 (intptr,intptr,int,int)`

Only when i set the PageIndicators property to true.

Thanks.

**Comment by alexrainman** [comment]
I will take a look at it.

**Comment by alexrainman** [comment]
Android version and device?

**Comment by alexDairay** [comment]
Got this issue on Simulator Nexus4 - Marshmallow API 23, also on Simulator Nexus5 - Lollipop API 22 and on real device galaxy S4 Android 5.0.1

**Comment by alexDairay** [comment]
ok I found a bug Fix in the file CirclePageIndicator.cs line 458 : replace : 
`			if ((specMode == MeasureSpecMode.Exactly) || (mViewPager == null)) {`

by `			if ((specMode == MeasureSpecMode.Exactly) || (mViewPager == null) || (mViewPager.Adapter == null)) {`

I can fork and make the pull request for you if you want or i can let you add it :)

**Comment by alexrainman** [comment]
Awesome, thanks for fixing this. Will update soon.

**Comment by alexrainman** [comment]
Package update on the way. Thanks

**Comment by alexrainman** [comment]
Fixed.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
