### ISSUE TITLE
Xamarin.Android.Support version problem

### ISSUE THREAD

**Issue by NelsonSantos** [alexrainman/CarouselView#80]
Hi Alex,

After upgrade to version 3.0.2, we have issues with some Xamarin.Android.Support... dll's.

Xamarin.Forms needs all your Xamarin.Android.Support dll's on version 23.3 and your CarouselViewControl is using some on 24.2.1 version, that cause conflicts on build the project.

There are a need to use these new dlls, since these files did not exist in the previous version?

We're not getting a build with this version mismatch problem.

Thanks...

Nelson

**Comment by alexrainman** [comment]
Latest version requires Xamarin.Android.Support.v4 version 24.2.1 for Android 7 support. Update to that version to get all the packages needed. Also you will need API 24 SDK platform and build tools 24 latest

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
