### ISSUE TITLE
CarouselView with different ContentPages

### ISSUE THREAD

**Issue by CJACQUEL** [alexrainman/CarouselView#81]
Hello, 
I have 4 contentPages, each different. 
How to integrate them in your Carrouselview without MVVM. 
Thank you,

**Comment by alexrainman** [comment]
Easy, convert the ContentPages to ContentViews. They can have their own code behind logic. Use TemplateSelector to return the page you want depending in the position.

**Comment by ashmcleod** [comment]
Hi, sorry for reopening. I´m trying to do what you told, but IOS throws an exception about reassigning a view that has been previously assigned when sliding back and forth. I have 4 slides:

error:
`Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x13bddb5e0; frame = (0 0; 375 573); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x171a381e0>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x13d9035c0>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x13d904470>.
Native stack trace:
	0   CoreFoundation                      0x0000000189e651d0 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018889c55c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000189e65100 <redacted> + 0
	3   UIKit                               0x000000018fd95788 <redacted> + 248
	4   UIKit                               0x000000018fd95680 <redacted> + 48
	5   UIKit                               0x000000018fd95308 <redacted> + 424
	6   libXamarin.iOS.dll.dylib            0x000000010069dc10 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSendSuper_IntPtr_intptr_intptr_intptr + 112
	7   libXamarin.iOS.dll.dylib            0x00000001005fa418 UIKit_UIViewController_set_View_UIKit_UIView + 216
	8   libCarouselView.FormsPlugin.iOS.dll.dylib 0x0000000103077558 CarouselView_FormsPlugin_iOS_CarouselViewRenderer_CreateViewController_int + 2488
	9   libCarouselView.FormsPlugin.iOS.dll.dylib 0x00000001030780f4 CarouselView_FormsPlugin_iOS_CarouselViewRenderer__ConfigurePageControllerm__2_UIKit_UIPageViewController_UIKit_UIViewController + 468
	10  libXamarin.iOS.dll.dylib            0x000000010064807c UIKit_UIPageViewController__UIPageViewControllerDataSource_GetNextViewController_UIKit_UIPageViewController_UIKit_UIViewController + 60
	11  libmscorlib.dll.dylib               0x0000000100b45c44 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	12  libmonosgen-2.0.dylib               0x00000001002bfab4 mono_jit_runtime_invoke + 1776
	13  libmonosgen-2.0.dylib               0x0000000100339b2c do_runtime_invoke + 112
	14  libmonosgen-2.0.dylib               0x0000000100339a88 mono_runtime_invoke + 208
	15  NaizMobile.iOS                      0x00000001000d68a0 _Z31native_to_managed_trampoline_66P11objc_objectP13objc_selectorPP11_MonoMethodP20UIPageViewControllerP16UIViewControllerPKcSB_SB_SB_ + 692
	16  NaizMobile.iOS                      0x00000001000d65e0 -[UIKit_UIPageViewController__UIPageViewControllerDataSource pageViewController:viewControllerAfterViewController:] + 96
	17  UIKit                               0x0000000190523400 <redacted> + 164
	18  UIKit                               0x00000001905290e0 <redacted> + 268
	19  UIKit                               0x000000019052922c <redacted> + 64
	20  UIKit                               0x00000001905f82e8 <redacted> + 164
	21  UIKit                               0x00000001905f89ec <redacted> + 268
	22  UIKit                               0x00000001905f8d8c <redacted> + 364
	23  UIKit                               0x00000001905fb230 <redacted> + 316
	24  UIKit                               0x00000001905f889c <redacted> + 824
	25  UIKit                               0x00000001905fbe7c <redacted> + 1096
	26  UIKit                               0x00000001905f7998 <redacted> + 200
	27  UIKit                               0x000000018fd17a80 <redacted> + 1196
	28  QuartzCore                          0x000000018d1c59d8 <redacted> + 148
	29  QuartzCore                          0x000000018d1ba4cc <redacted> + 292
	30  QuartzCore                          0x000000018d1ba38c <redacted> + 32
	31  QuartzCore                          0x000000018d1373e0 <redacted> + 252
	32  QuartzCore                          0x000000018d15ea68 <redacted> + 512
	33  QuartzCore                          0x000000018d0bae7c <redacted> + 616
	34  IOKit                               0x000000018a0d2094 IODispatchCalloutFromCFMessage + 372
	35  CoreFoundation                      0x0000000189dfae50 <redacted> + 180
	36  CoreFoundation                      0x0000000189e13218 <redacted> + 56
	37  CoreFoundation                      0x0000000189e129cc <redacted> + 436
	38  CoreFoundation                      0x0000000189e104b0 <redacted> + 1840
	39  CoreFoundation                      0x0000000189d3e2b8 CFRunLoopRunSpecific + 444
	40  GraphicsServices                    0x000000018b7f2198 GSEventRunModal + 180
	41  UIKit                               0x000000018fd857fc <redacted> + 684
	42  UIKit                               0x000000018fd80534 UIApplicationMain + 208
	43  libXamarin.iOS.dll.dylib            0x0000000100698004 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 340
	44  libXamarin.iOS.dll.dylib            0x000000010063fa7c UIKit_UIApplication_Main_string___intptr_intptr + 44
	45  libXamarin.iOS.dll.dylib            0x000000010063fa3c UIKit_UIApplication_Main_string___string_string + 172
	46  libNaizMobile.iOS.exe.dylib         0x000000010017f5f0 NaizMobile_iOS_Application_Main_string__ + 160
	47  libmscorlib.dll.dylib               0x0000000100b45c44 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	48  libmonosgen-2.0.dylib               0x00000001002bfab4 mono_jit_runtime_invoke + 1776
	49  libmonosgen-2.0.dylib               0x0000000100339b2c do_runtime_invoke + 112
	50  libmonosgen-2.0.dylib               0x000000010033cec4 do_exec_main_checked + 152
	51  libmonosgen-2.0.dylib               0x00000001002a3770 mono_jit_exec + 260
	52  libxamarin-debug.dylib              0x00000001005a5dec xamarin_main + 2136
	53  NaizMobile.iOS                      0x00000001000ef400 main + 96
	54  libdyld.dylib                       0x0000000188d215b8 <redacted> + 4
`

this is my code:
`using System;
using System.Collections.Generic;
using Xamarin.Forms;
using CarouselView.FormsPlugin.Abstractions;
using NaizMobile.Slides;
namespace NaizMobile
{
  public class CarouselViewMultiPage : CarouselViewControl
    {
      List<View> _children = new List<View> { };
      public List<View> Children {
        get { return _children; }
        set {
          _children = value;
          OnPropertyChanged ();
        }
      }
      public CarouselViewMultiPage ()
      {
        this.ItemTemplate = new CarouselTemplateSelector ();
        this.ItemsSource = Children;
        this.SetBinding (ItemsSourceProperty, "Children");
        BindingContext = this;
      }
    }
    public class CarouselTemplateSelector : DataTemplateSelector
    {
      protected override DataTemplate OnSelectTemplate (object item, BindableObject container)
      {
        View civ = (View)item;
        return new DataTemplate (() => {
          return civ;
        });
      }
    }
}`

**Comment by alexrainman** [comment]
Please, use the demo as example on how to implement the carousel. Thanks

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by micheleissa** [comment]
Hi I'm a novice when it comes to Xamarin Forms so would it be possible to provide more details how to use the control with several ContentPages instead of simple images views. Thank you.
