### ISSUE TITLE
Error Version 3.0.2 for Android

### ISSUE THREAD

**Issue by matteopiccioni** [alexrainman/CarouselView#83]
Hello,
If I update to version 3.0.2 I have the following error (3.0.1 is ok): 

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.Core.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Android.Support.Core.UI.dll'
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x0015d] in <9ca47d05131d4b8c85910dacd818f0c6>:0 
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00001] in <9ca47d05131d4b8c85910dacd818f0c6>:0 
  at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x0018e] in <3f37ea95794e430e91f10accab4cf241>:0 
  at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x001c0] in <3f37ea95794e430e91f10accab4cf241>:0  (ProjectName.Droid)`

Thanks

**Comment by alexrainman** [comment]
Update Xamarin.Android.Support.v4 to version 24.2.1

**Comment by kikolopes90** [comment]
Can not update Xamarin Android recent version because incompatible with Xamarin Forms, right?

**Comment by alexrainman** [comment]
Exactly. I tested up to 24.2.1

Higher than that don't work.

**Comment by priehle** [comment]
I'm also confused by this. I can't install CarouselView because it requires 24.2.1, but I can't upgrade Xamarin.Android.Support.v4 because Xamarin Forms is only compatible with 23.3.0.

**Comment by priehle** [comment]
I understand now. It's necessary to download the Android API 24 platform and build tools 24, as you mentioned in the other bug. Though I'm still getting this error when I try to update:

Could not install package 'Xamarin.Android.Support.Compat 24.2.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I doubt it's related to CarouselView, though.

**Comment by alexrainman** [comment]
Latest version of forms is compatible.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
