### ISSUE TITLE
Exception in UWP project, and problem with binding

### ISSUE THREAD

**Issue by Shkolik** [alexrainman/CarouselView#84]
If you try to change Position (binded to the viewmodel's property) after setting BindingContext of page that  will crash application. 
Test project and screenshoot attached.

In test app you can see Image that has similar binding like in data template for CarouselView item, it's just for reference to show that binding works on simple image and don't work on carousel control.

Click on "Add image" button - Image source of Image control will changed, ItemsSource of Carousel will be updated, but control not.
Click again - app will crash.

Tested on Simulator, Desktop and Phone.

![exception](https://cloud.githubusercontent.com/assets/26121979/24412219/858626d2-13e0-11e7-88d9-d733845e5186.png)
[TestCarousel.zip](https://github.com/alexrainman/CarouselView/files/876104/TestCarousel.zip)

**Comment by alexrainman** [comment]
Will take a look.

**Comment by Shkolik** [comment]
Any news about this issue?

**Comment by alexrainman** [comment]
Is taking me lot of time to understand what are you trying to do :(

**Comment by alexrainman** [comment]
First, CarouselView doesn't support ObservableCollection callback events. To add/remove pages from it you have to use InsertPage and RemovePage.

**Comment by alexrainman** [comment]
You can use ObservableCollection and CollectionChanged for your own logic but inserting an element in the collection wont refresh UI.

**Comment by alexrainman** [comment]
Actually it needs to be done in the other way. You call InsertPage(bindingContext, position) and the element will be added to UI and to the collection, then CollectionChanged will be called and you do your own stuff there.

**Comment by alexrainman** [comment]
I fixed your project: https://drive.google.com/file/d/0B6hZDQudMRBUblJzTXdBNnVXc1k/view?usp=sharing

**Comment by Shkolik** [comment]
Thanks, it works, but what about MVVM pattern? Will be better to have support of CollectionChanged  events.

**Comment by alexrainman** [comment]
Its not possible in Android.

**Comment by alexrainman** [comment]
You can still use an ObservableCollection as source and use CollectionChanged for your own business logic but not to add/remove pages from the carousel.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
