### ISSUE TITLE
Indicator margin/padding?

### ISSUE THREAD

**Issue by Ivan-L** [alexrainman/CarouselView#85]
In horizontal mode, it would be useful if there were a property which allows for the customization of space between the indicators and the bottom edge of the control. I would love to increase the distance of the indicators from the bottom as we have a design where there is an element which overlaps the bottom of the control and it almost overlaps the indicators.

The above property could control the distance of the indicators from the right most edge of the control in horizontal mode as well.

Is there any chance of implementing such a property? I cannot seem to find a different way to do this.

**Comment by alexrainman** [comment]
Yes it could be done, but in your case, why an element overlaps the carousel?

**Comment by Ivan-L** [comment]
I think a picture better explains the scenario.

<img width="374" alt="screen shot 2017-03-29 at 1 50 55 pm" src="https://cloud.githubusercontent.com/assets/16413523/24453135/ef77310c-1486-11e7-9873-7d67f3c1b68b.png">

**Comment by alexrainman** [comment]
Whats that bump for?

**Comment by Ivan-L** [comment]
It's just part of the design that is being implemented for the app being built. The bump overlays the carousel and the images scroll underneath it. It would be great if the carousel indicators can be moved up.

**Comment by alexrainman** [comment]
As i said, it can be done but it doesn't make sense just because of your design, you got my point? A functionality needs to be something the whole community needs.

**Comment by alexrainman** [comment]
There's a lot of things to change just to add that property.

**Comment by Ivan-L** [comment]
Yeah I understand. I saw that it might be a lot of work, so if I am the first person requesting this, then the work involved may not justify the end result. But if it has been requested before, then perhaps it would make sense. The alternative for me is to hide your carousel indicators, still use your carousel view and implement the indicators on my own, positioning them where appropriate.

**Comment by alexrainman** [comment]
This control soon will be officially included in Xamarin.Forms core.

**Comment by Ivan-L** [comment]
That is great news, because this control is better than the Xamarin.Forms.CarouselView control which is still in beta. One of the reasons for opting to use this control is because the carousel indicators are built in.

I understand that you would not want to necessarily implement the positioning of the indicators just because one person asked for it. It makes sense for this to be a larger community requirement before it is considered to be implemented. So if it is the case that such a feature would not widely be used, then I will implement the indicators myself which will overlap the control at the correct position.

**Comment by alexrainman** [comment]
Let me give it a try first.

**Comment by alexrainman** [comment]
Sorry, doing this is way complicated :(

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by tomh4** [comment]
I know this is closed, but it would also be great if the positioning of the Inidicators could be made a bit more flexibel, e.g. at a specified height of the control itself

**Comment by Rikudouensof** [comment]
What I actually did to achieve this was to margin the topside of the indicator to a negative value.
