### ISSUE TITLE
It doesn't show up in release mode UWP

### ISSUE THREAD

**Issue by mariolobar** [alexrainman/CarouselView#87]
If you put in release mode your app and deploy it the carousel view doesn't show up. Also happen in your demo. Any advice on it?

Thank you very much

**Comment by alexrainman** [comment]
Are you calling Init()?

**Comment by mariolobar** [comment]
Yes, of course. You can test it in your own example.

**Comment by johnxy84** [comment]
That's true, having same issue as well, would be glad if it be fixed soon I'm close to a deadline and i really love this control.

**Comment by abdu292** [comment]
Oh, true. The control doesn't seem to be appearing in release mode. I wish this issue is fixed at the earliest. Planning to release the app in a couple of weeks.

**Comment by alexrainman** [comment]
I confirm this issue but don't know how to solve it.

**Comment by BMarinov** [comment]
I cant seem to get it to work either. I added the Init() call to MainActivity.cs (droid project), but im getting an exception:

`04-10 23:28:00.049 I/MonoDroid( 5093): System.InvalidCastException: Specified cast is not valid.
04-10 23:28:00.049 I/MonoDroid( 5093):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer+PageAdapter.InstantiateItem (Android.Views.ViewGroup container, System.Int32 position) [0x000d6] in <6e08348ed7f945e1ae8ab96a74452766>:0 
04-10 23:28:00.049 I/MonoDroid( 5093):   at Android.Support.V4.View.PagerAdapter.n_InstantiateItem_Landroid_view_ViewGroup_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_container, System.Int32 position) [0x00011] in <d0d76ee8ec7644cfa17d1f0e3600d646>:0 
04-10 23:28:00.049 I/MonoDroid( 5093):   at (wrapper dynamic-method) System.Object:8aa87d87-1bde-4289-b974-8e5be8c0eb22 (intptr,intptr,intptr,int)`

**Comment by alexrainman** [comment]
MainActivity.cs? This issue is UWP. The plugin works without issues in other platforms.

**Comment by BMarinov** [comment]
Ah well, my bad, I saw someone having an issue on android and the control not showing (same problem), thought it might be related :)

**Comment by grahampett** [comment]
Replace your call to Forms.Init(e) with:

    List<Assembly> assembliesToInclude = new List<Assembly>();
    assembliesToInclude.Add(typeof(CarouselViewRenderer).GetTypeInfo().Assembly);
    Forms.Init(e, assembliesToInclude);
    DependencyService.Register<CarouselViewRenderer>();

See [https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/#Troubleshooting](https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/#Troubleshooting)

**Comment by alexrainman** [comment]
Let me try that.

**Comment by alexrainman** [comment]
I can confirm this solve the issue :)

```
List<Assembly> assembliesToInclude = new List<Assembly>();
assembliesToInclude.Add(typeof(CarouselViewRenderer).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

**Comment by abdu292** [comment]
Thanks! I was already using something similar for FFImaegLoading, and just included one liner for this library to get it working.

                ```
                var assembliesToInclude = new List<Assembly>()
                {
                    typeof(CachedImage).GetTypeInfo().Assembly,
                    typeof(CachedImageRenderer).GetTypeInfo().Assembly,
                    typeof(CarouselViewRenderer).GetTypeInfo().Assembly
                };

```

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by mattrichnz** [comment]
Alex - I'm thinking it may be worth updating your README.MD to indicate this is a requirement for the plugin to work correctly in Release.

The fix works great, but should really be in the docs if it is a required step.

Thanks for all your great work! Looking forward to seeing this in XF core.
