### ISSUE TITLE
Migrating the control to Xamarin.Forms.Core

### ISSUE THREAD

**Issue by AndriiTsok** [alexrainman/CarouselView#88]
I see that you are merging this control to Xamarin.Forms repo. 
I would be happy to assist or to help. Just let me know, assign issues.
Cheers :)

**Comment by alexrainman** [comment]
No issues so far. Implementing all the binding properties changes. I already added support for ObservableCollections :)

Will let you know if i need help.

Thanks a lot for the support!

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
