### ISSUE TITLE
Controls on Page loses state

### ISSUE THREAD

**Issue by oridotaoyebode** [alexrainman/CarouselView#89]
I have a datatemplateSelector (customcontrols) for the ItemTemplate. However, every time I swipe left or right, the custom controls on the previous page loses its states.

is this the default behaviour or am I missing something?

**Comment by alexrainman** [comment]
Default behavior (for now). Advice? Use ViewModels to save the values/states of your controls so you can restore them with bindings.

**Comment by oridotaoyebode** [comment]
Okay cool. Sorry for the late reply.  

I took a look at the source code and I understand why you built the control the way it is.  Especially with how bad Android is with memory management.

My advice would be to maybe have a property in the control to flag SaveState.... I wouldn't worry too much about this though as I think I am the only one having this problem


Thanks for the support.

Regards

**Comment by alexrainman** [comment]
This is something i will engineer after the control has passed Xamarin.Forms.Core PR.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
