### ISSUE TITLE
iOS null exception, pushed as Modal page

### ISSUE THREAD

**Issue by shnaz** [alexrainman/CarouselView#9]
Hey, I have a simple image gallery page that is modally pushed in a navigation page. 
It works fine until I pop it, then I get a null exception. 

I have tried to recreate the issue in source code and it seems that pageController is null when it is tried accessed. See screenshot. Note: Control is not null here, so pageController is never initialized.

EDIT: After further testing, it doesnt matter if it is pushed modally or not, the null exception occurs anyways when tried popped
.
![image](https://cloud.githubusercontent.com/assets/6933856/17061506/21dfc860-502f-11e6-8d61-d53cb0bd4499.png)

**Comment by alexrainman** [comment]
Fix this and other issues and will update later today. Thanks

**Comment by shnaz** [comment]
Wow that was quick. I look forward to it. Really appreciate your work. I went from using Xamarin.Forms.CarouselView(too buggy and basic) to this. Thumbs up!

**Comment by alexrainman** [comment]
Thanks for cheering. I want to make it better and more stable. There's only one bug i cannot find a way to solve and that its HeightRequest requirement :(

**Comment by alexrainman** [comment]
I cannot reproduce your issue :(

**Comment by alexrainman** [comment]
Fixex.

**Comment by shnaz** [comment]
Great. 👍🏼👍🏼

**Comment by shnaz** [comment]
When is it going to be released, you think?

**Comment by alexrainman** [comment]
Already released :)

**Comment by shnaz** [comment]
Superb. Im gonna update right away then.

**Comment by shnaz** [comment]
It works perfectly! Thank you @alexrainman.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

**Comment by alexrainman** [comment]
This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (xamarin/Xamarin.Forms#853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
