### ISSUE TITLE
Auto Advance with User Interaction

### ISSUE THREAD

**Issue by cklenk** [alexrainman/CarouselView#90]
Hi there,

I have my carousel view control set up on a repeating timer to advance through the item source. I was wondering if there is an event or method that could "pause" the timer when the user swipes. It appears a tap gesture does not work.

Thanks

**Comment by alexrainman** [comment]
There's not such a method but maybe it can be added.

**Comment by Hasanajouz** [comment]
want the same here.
so i can create auto swipe

**Comment by alexrainman** [comment]
SO guys, you want to detect touch event to stop auto swipe no?

**Comment by Hasanajouz** [comment]
or maybe position changed event

**Comment by alexrainman** [comment]
There's PositionSelected event already.

**Comment by cklenk** [comment]
@alexrainman Yes I would like that very much.

I also have found that if I have three items in my carousel view and if I'm on index 1 or 2 and I just ever so slightly move the control but not enough to advance to the next view it raises the PositionSelected event. However if I'm on index 0 and do the same thing the event does not get raised. Any thoughts?

Thanks

**Comment by tonholis** [comment]
Hi @cklenk ! 
Did you solve this? I have the same scenario here: a background task advancing the slides after x seconds. But I would like to apply a better control when a user swipes to the next/prev slide like stopping the timer. I tried putting a gesture recognizer on carousel but doesn't work.

**Comment by Hasanajouz** [comment]
@cklenk 
"I also have found that if I have three items in my carousel view and if I'm on index 1 or 2 and I just ever so slightly move the control but not enough to advance to the next view it raises the PositionSelected event. However if I'm on index 0 and do the same thing the event does not get raised. Any thoughts?"

this happens to me just in iOs
