### ISSUE TITLE
View associted with at most view controller

### ISSUE THREAD

**Issue by Nuada26** [alexrainman/CarouselView#93]
Hi,

 i have problem with iOS project, i have populate carousel view with this list view :

`listview = new List<View>();
            listview.Add(new ModuleView());
            listview.Add(new MusersView());
            listview.Add(new AccountView());
            listview.Add(new SettingsView());
`

but when i'm come back second time on view, for exemple i go to the second and i come back on the first view i have this error:

`Foundation.MonoTouchException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x151884c80; frame = (0 0; 320 454); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x14ddf8810>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x14ffc3380>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x1518916e0>.`

i don't understand what's the problem, and i don't add view .

**Comment by alexrainman** [comment]
I don't know what are you doing here. You don't add views directly to the carousel. You have to create a template and attach it to ItemTemplate property. Create a list of objects, that will be the binding context of each page of the carousel, and attach to ItemsSource property.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
