### ISSUE TITLE
Color Transparent

### ISSUE THREAD

**Issue by Nuada26** [alexrainman/CarouselView#94]
Hi one more time,

  I have a bug on Android, i have put my background color in transparent on iOS it's works but not Android color stay in white .
 Any idea ?

Thanks in advance

**Comment by alexrainman** [comment]
Which part you want transparent? Each view background or the space between them?

**Comment by Nuada26** [comment]
Each view background.

**Comment by Nuada26** [comment]
I have resolve that, i add this line :

carousel.InterPageSpacingColor = Color.Transparent;

and my background color is transparent too.

**Comment by alexrainman** [comment]
Yes

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
