### ISSUE TITLE
Many bug

### ISSUE THREAD

**Issue by Nuada26** [alexrainman/CarouselView#95]
Hi one last time,

 this is my code xaml :

`  <cv:CarouselViewControl Orientation="Horizontal" InterPageSpacing="10"  x:Name="carousel" BackgroundColor="Transparent" Position="{Binding Position}">
        </cv:CarouselViewControl>`

and this is my code :

`public partial class MainPage : ContentPage
    {
        private ObservableCollection<View> listview;
        private const int VIEW_SETTINGS = 3;
        private const int VIEW_MODULES = 0;
        private const int VIEW_MUSERS = 1;
        private const int VIEW_ACCOUNT = 2;

        public MainPage()
        {
            InitializeComponent();

            listview = new ObservableCollection<View>();
            listview.Add( new ModuleView());
            listview.Add(new MusersView());
            listview.Add(new AccountView());
            listview.Add(new SettingsView());
            
            carousel.InterPageSpacingColor = Color.Transparent;
            carousel.ItemsSource = listview;
            carousel.IsSwipingEnabled = false;
            carousel.ItemTemplate = GetDataTemplate();
            carousel.PositionSelected += Carousel_PositionSelected;
            Carousel_PositionSelected(this, new EventArgs());
        }
        //*********************************************************
        private void Carousel_PositionSelected(object sender, EventArgs e)
        {
            switch (carousel.Position)
            {
                case VIEW_ACCOUNT:
                    Title = ResourceStrings.Account;
                    break;
                case VIEW_MUSERS:
                    Title = ResourceStrings.Community;
                    break;
                case VIEW_MODULES:
                    Title = ResourceStrings.Modules;
                    break;
                case VIEW_SETTINGS:
                    Title = ResourceStrings.Settings;
                    break;
            }
        }
        //*********************************************************
        private DataTemplate GetDataTemplate()
        {
            return new DataTemplate(() =>
            {
                View v = listview[carousel.Position];
                return v;
            });
        }
        //*********************************************************
        private void OnCarouselIndicatorTapped(object sender, EventArgs e)
        {
            if (sender == accountbox)
            {
                
                carousel.Position = 2;//Error appears here
            }
            else if (sender == musersbox)
            {
                carousel.Position = 1;//Error appears here
            }
            else if (sender == parambox)
            {
                carousel.Position = 3;//Error appears here
            }
            else if (sender == modulebox)
            {
                carousel.Position = 0; //Error appears here
            }
        } 
    }`

So first bug it's on Android carousel isn't in the same order of the listview, and i don't know why.
But on iOS it's in order so do u have an idea?

The second bug is on Android and iOS. I explain, when i switch position on carousel, i go 1 and i go 2 and i go 1 for exemple, i have this error appears at the places of the code that I marked, exact places depends the 4th box i have tapped : 

on iOS:

`Foundation.MonoTouchException: Objective-C exception thrown.  Name: UIViewControllerHierarchyInconsistency Reason: A view can only be associated with at most one view controller at a time! View <Xamarin_Forms_Platform_iOS_Platform_DefaultRenderer: 0x10d467b90; frame = (0 0; 320 454); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x172031fa0>> is associated with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x10499b4e0>. Clear this association before associating this view with <CarouselView_FormsPlugin_iOS_ViewContainer: 0x11307e6c0>.`

on Android:

'Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.'

i don't understand why i have this bug, i hope u can understand why.

Thanks in advance.

**Comment by alexrainman** [comment]
As i said, dont add Views directly to the list you will use as ItemsSource. ItemsSource is a list of objects you will use as binding context for each page in the carousel. View is not supported as ItemsSource. Then attach a DataTemplate to carousel ItemTemplate property.

**Comment by Nuada26** [comment]
So i just have to do that :

`carousel.ItemsSource = new List<DataTemplate>()
{
	new DataTemplate(() => { return new ModuleView(); }),
	new DataTemplate(() => { return new MusersView(); }),
	new DataTemplate(() => { return new AccountView(); })
	new DataTemplate(() => { return new SettingsView(); })
};`

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
