### ISSUE TITLE
Content not getting rendered in iOS because ElementWidth is 0 (+ fix)

### ISSUE THREAD

**Issue by JoshaMunnik** [alexrainman/CarouselView#96]
I've the following setup (it's a bit complex because of the design I've to follow):

ContentPage
1. StackLayout with child that is a 
2. AbsoluteLayout with child that is a
3. StackLayout with child that is a
4. CarouselView (ShowIndicators="True") with DataTemplate containing
   - StackLayout (vertical) containing children
     - StackLayout (horizontal) for header
     - ListView 

On Android everything works correctly and the header and ListView with the items are shown correctly and I can swipe to the next and previous lists. On iOS however nothing is shown.

I'm also using the CarouselViewController in another page (using a much less complex layout) and there it is working correctly both in iOS and Android.

I installed the source and discovered that (for whatever reason) the "Width" property of CarouselViewController never changes, resulting in the ElementWidth being not set in CarouselViewImplementation.cs and thus stays 0 (it's initially value) resulting the content not being visible.

I changed the OnElementPropertyChanged method and added also an assignment to ElementWidth when the "Height" property has changed:

	case "Height":
          ElementWidth = rect.Width;
          ElementHeight = rect.Height;
          // etc...

Not sure if this is a correct fix and I've no idea why the Width property is not changed (could maybe be a bug in Xamarin.Forms itself).

**Comment by alexrainman** [comment]
Does this fix your problem?

**Comment by JoshaMunnik** [comment]
Yes, the above fixes it.

I was curious and checked also the Android implementation. That one ignores the Width property (there is no ElementWidth variable).

**Comment by alexrainman** [comment]
Not needed in Android. This is just iOS problem. Will apply your fix. Thanks

**Comment by JoshaMunnik** [comment]
Thank you for the quick response and for this nice control (very useful).

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
