### ISSUE TITLE
Xamarin.Forms 2.3.4 - different views for the same data XAML throws XAMLC error

### ISSUE THREAD

**Issue by djcparker** [alexrainman/CarouselView#97]
I've been using this awesome control with different views for the same data with now problems.
The definition was declared like

```
      <carousel:CarouselViewControl.ItemsSource>
            <x:Array Type="{x:Type DataTemplate}">

                <DataTemplate>
                ......

```
And it works fine.
I tried updating to Forms 2.3.4 and the XamlC compiler started throwing an error saying 

```
  Resource: UI.Views.Configure.ConfigurePage.xaml... 
       Creating empty ConfigurePage.__InitComponentRuntime ...done.
2>     Copying body of InitializeComponent to __InitComponentRuntime ...done.
2>     Parsing Xaml... done.
2>     Replacing ConfigurePage.InitializeComponent ()... failed.
2>D:\Source\UI\Views\Configure\ConfigurePage.xaml : error : Value cannot be null.
2>D:\Source\\Views\Configure\ConfigurePage.xaml : error : Parameter name: fieldType
```

I tracked it down to the x:Array definition...
I notice in your latest readme you've changed it to a code behind example.

Do you know why this error occurs?
Is it still possible to define the data templates in Xaml?

(mainly for my own knowledge, thanks!)

**Comment by alexrainman** [comment]
ItemsSource has been changed to IEnumerable so its not possible to declare from xaml using array. Use code behind please. Thanks

**Comment by alexrainman** [comment]
If you figure it out how to do it from xaml let me know :)

**Comment by djcparker** [comment]
Ahhhh... That makes sense - thanks for the reply.....
interestingly, it threw the exception before I updated your control to the latest version.  

thanks again!

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by djcparker** [comment]
Hey Alex, sure, happy to support you.  Didn't know there was a form for that :)  Thanks for the control, really pleased it is being pulled into the core offering...

Dave

**Comment by alexrainman** [comment]
Thanks in advance!
