### ISSUE TITLE
Error: Unable to find a version of 'Xamarin.Android.Support.Design'

### ISSUE THREAD

**Issue by biapar** [alexrainman/CarouselView#98]
With latest nuget, I've this error: Unable to find a version of 'Xamarin.Android.Support.Design' that is compatible with 'Xamarin.Forms 2.3.4.231 constraint: Xamarin.Android.Support.Design (= 23.3.0)'.

**Comment by alexrainman** [comment]
Thats a constraints of Forms 2.3.4 and not the carousel.

**Comment by thankee** [comment]
I've same error message, and I use Forms 2.3.3.193. Thie error message appears only when trying to add CarouselView.FormsPlugin 4.1.0 to android project.

Step1. Make new Xamarin.Forms Project(PCL) with Visual Studio 2017.
Step2. Open nuget package manager, and try to add CarouselView.FormsPlugin 4.1.0 to android project.
Step3. You can see this error message.
Unable to find a version of 'Xamarin.Android.Support.Design' that is compatible with 'Xamarin.Forms 2.3.4.231 constraint: Xamarin.Android.Support.Design (= 23.3.0)'.

**Comment by biapar** [comment]
How solve?

Saluti
ing. Biagio Paruolo

**Comment by alexrainman** [comment]
This what i have in the plugin with Xamarin.Forms 2.3.3.193

<img width="444" alt="screen shot 2017-04-16 at 10 50 32 am" src="https://cloud.githubusercontent.com/assets/3793554/25072393/99ba64b8-2292-11e7-9644-4b9b3adc1962.png">

**Comment by alexrainman** [comment]
And i just updated to latest forms with all Xamarin packages matching 24.2.1 version

<img width="411" alt="screen shot 2017-04-16 at 10 52 35 am" src="https://cloud.githubusercontent.com/assets/3793554/25072408/e6f95c98-2292-11e7-8344-ec2a1f1831da.png">

**Comment by alexrainman** [comment]
Update Xamarin.Android.Support.v4 to 24.2.1

**Comment by kosta59** [comment]
Hello, im also facing this problem. im currently using xamarin forms 2.3.4.231 and Support.v4 is 23.3.0 . im for some reason when i try to update the support.v4 i get this error message.

Unable to resolve dependencies. 'Xamarin.Android.Support.v4 25.1.1' is not compatible with 'Xamarin.Forms 2.3.4.231 constraint: Xamarin.Android.Support.v4 (= 23.3.0)'. 

im guessing that xamarin has not updated the support.v4 with forms yet??

**Comment by alexrainman** [comment]
You have to update but not to latest version. Use 24.2.1

**Comment by biapar** [comment]
Under Visual Studio, I've this error with nuget.

![image](https://cloud.githubusercontent.com/assets/661517/25097165/a708ef88-23a3-11e7-8a62-f9a530e9d389.png)

**Comment by alexrainman** [comment]
As i said: don't use Xamarin.Android.Support.v4 25.1.1 as its not compatible with Forms. Use version 24.2.1 which will provide you Android 7 support.

**Comment by biapar** [comment]
I think that it's not possible to install Xamarin.Android Support 24.2.1 because the constraint Xamarin.Forms 2.3.4.231 constraint: Xamarin.Android.Support.Design (= 23.3.0) block it.

**Comment by alexrainman** [comment]
I dont have that constraint

**Comment by alexrainman** [comment]
Maybe Visual Studio issue? I use Xamarin Studio on a Mac.

**Comment by alexrainman** [comment]
I confirm that, if i create a new project, which comes with forms 2.3.4.224, i can update to Xamarin.Android.Support.v4

After that i can update to Xamarin.Forms 2.3.4.231 without issues.

**Comment by alexrainman** [comment]
<img width="435" alt="screen shot 2017-04-17 at 6 39 50 pm" src="https://cloud.githubusercontent.com/assets/3793554/25108686/56141a40-239d-11e7-8d6b-572784fcff3b.png">

<img width="453" alt="screen shot 2017-04-17 at 6 40 08 pm" src="https://cloud.githubusercontent.com/assets/3793554/25108689/5e6ac86a-239d-11e7-86ab-4daef9611f71.png">

<img width="882" alt="screen shot 2017-04-17 at 6 40 18 pm" src="https://cloud.githubusercontent.com/assets/3793554/25108693/625a4798-239d-11e7-84fe-273be26cf86b.png">

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.

**Comment by biapar** [comment]
I'm not had solved the problem until now...at moment I've used a scrollview ( sigh )

**Comment by alexrainman** [comment]
I solved that in latest releases.

**Comment by biapar** [comment]
Yes! I installed it without the error. Which was the problem?

**Comment by alexrainman** [comment]
Xamarin.Forms depends on Xamarin.Android.Support.v4 23.3.0, i was using 24.2.1 :)

**Comment by biapar** [comment]
So, Did you used a newer lib version? But then you pay attention when Xamarin will release the next version.

**Comment by alexrainman** [comment]
This control will be included in Xamarin.Forms core very soon, so you wont need to worry about it anymore and i wont need to deal with neither :)
