### ISSUE TITLE
Update ItemSource during runtime and refresh control

### ISSUE THREAD

**Issue by johnxy84** [alexrainman/CarouselView#99]
I have a carousel control feeding from an item source using Binding, but when I update the item source, and I know it's been updated during debugging,  the layout is not refreshed. It still shows using the previous ItemSource,  was wondering if it's not possible or am I doing something wrong?

**Comment by alexrainman** [comment]
Thats implemented in latest release.

**Comment by johnxy84** [comment]
Oh cool, let me check it out. Can you give give a brief snippet or example just in case??

**Comment by alexrainman** [comment]
It's simple. If you use a binding or simply assign the ItemsSource property, the carousel will refresh. Also, ItemTemplate can be changed and UI will refresh.

**Comment by johnxy84** [comment]
Hello, I still faced the same error,do I need to raise property change in the model of the observable collection which is the carousel Itemsource? ? If you could give an example it would wild be nice

**Comment by alexrainman** [comment]
Of course you need to raise property changed. How the the control will now? Only add/remove from the observable collection will raise automatically but to change the whole itemssource the property in the VM needs to implement PropertyChanged. I use Fody for that myself.

**Comment by alexrainman** [comment]
If my work is helping you, please help me back: https://xamarinhq.wufoo.com/forms/nominate-a-xamarin-mvp/

This is what i have done that is community visible:

- Alex has been pretty active sharing his knowledge and answering questions in StackOverflow, GitHub and Xamarin Forums.
- Alex has been open sourcing Xamarin components and plugin with the community, with more of 10 repositories being maintained on GitHub.
- One of Alex's Xamarin.Forms plugin, the CarouselView, is currently being pulled into the Xamarin.Forms core (https://github.com/xamarin/Xamarin.Forms/pull/853). As an stable widget, this control has become the standard for Xamarin.Forms carousel screens with more that 16K downloads in NuGet and more than 100 solved and not open issues.
- Another Alex's plugin, the SegmentedControl (https://github.com/alexrainman/SegmentedControl), is a big candidate to be also pulled into Xamarin.Forms core.
- Plus Xamarin.Forms UI related plugins, Alex shares plugins to set app icon Badge, Google Analytics and KeyChain access.
- Alex shares his knowledge about cutting edge technologies like Couchbase NoSQL and MobileIron integration with Xamarin Apps.
